-- EPT Module: Equipment Performance Tracking
CREATE TABLE EST_EQUIPMENT_ALARM (
    ALARM_ID            NVARCHAR(50)    NOT NULL,
    EQUIPMENT_ID        NVARCHAR(50)    NOT NULL,
    ALARM_CODE          NVARCHAR(50)    NOT NULL,
    ALARM_NAME          NVARCHAR(200)   NOT NULL,
    ALARM_LEVEL         NVARCHAR(20)    NOT NULL,
    OCCURRED_AT         DATETIME2       NOT NULL,
    CLEARED_AT          DATETIME2       NULL,
    ELAPSED_SECONDS     BIGINT          NULL,
    CREATED_BY          NVARCHAR(50)    NOT NULL,
    CREATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY          NVARCHAR(50)    NOT NULL,
    UPDATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_EPT_EQUIPMENT_ALARM PRIMARY KEY (ALARM_ID),
    CONSTRAINT FK_EPT_ALARM_EQUIPMENT FOREIGN KEY (EQUIPMENT_ID)
        REFERENCES MDM_EQUIPMENT (EQUIPMENT_ID)
);

CREATE INDEX IX_EPT_ALARM_EQUIPMENT ON EST_EQUIPMENT_ALARM (EQUIPMENT_ID, OCCURRED_AT DESC);
CREATE INDEX IX_EPT_ALARM_LEVEL     ON EST_EQUIPMENT_ALARM (ALARM_LEVEL, CLEARED_AT);
