-- QMS Module: Quality Management System
CREATE TABLE QMS_DEFECT (
    DEFECT_ID       NVARCHAR(50)    NOT NULL,
    LOT_ID          NVARCHAR(50)    NOT NULL,
    EQUIPMENT_ID    NVARCHAR(50)    NOT NULL,
    DEFECT_CLASS_ID NVARCHAR(50)    NOT NULL,
    DEFECT_COUNT    INT             NOT NULL DEFAULT 0,
    DEFECT_RATE     DECIMAL(10,4)   NOT NULL DEFAULT 0,
    INSPECTED_AT    DATETIME2       NOT NULL,
    INSPECTOR_ID    NVARCHAR(50)    NOT NULL,
    REMARK          NVARCHAR(500)   NULL,
    IS_CONFIRMED    BIT             NOT NULL DEFAULT 0,
    CONFIRMED_AT    DATETIME2       NULL,
    CREATED_BY      NVARCHAR(50)    NOT NULL,
    CREATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY      NVARCHAR(50)    NOT NULL,
    UPDATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_QMS_DEFECT PRIMARY KEY (DEFECT_ID),
    CONSTRAINT FK_QMS_DEFECT_EQUIPMENT FOREIGN KEY (EQUIPMENT_ID)
        REFERENCES MDM_EQUIPMENT (EQUIPMENT_ID),
    CONSTRAINT FK_QMS_DEFECT_INSPECTOR FOREIGN KEY (INSPECTOR_ID)
        REFERENCES SYS_USER (USER_ID)
);

CREATE INDEX IX_QMS_DEFECT_LOT      ON QMS_DEFECT (LOT_ID, INSPECTED_AT DESC);
CREATE INDEX IX_QMS_DEFECT_EQUIP    ON QMS_DEFECT (EQUIPMENT_ID, INSPECTED_AT DESC);
CREATE INDEX IX_QMS_DEFECT_CONFIRM  ON QMS_DEFECT (IS_CONFIRMED, CONFIRMED_AT);
