-- PPM Module: Production Plan Management
CREATE TABLE POM_PRODUCTION_PLAN (
    PLAN_ID             NVARCHAR(50)    NOT NULL,
    PLAN_NAME           NVARCHAR(200)   NOT NULL,
    PLANT_ID            NVARCHAR(50)    NOT NULL,
    PRODUCT_ID          NVARCHAR(50)    NOT NULL,
    PLANNED_QTY         DECIMAL(18,4)   NOT NULL,
    PLANNED_START_DATE  DATETIME2       NOT NULL,
    PLANNED_END_DATE    DATETIME2       NOT NULL,
    STATUS              NVARCHAR(20)    NOT NULL DEFAULT 'Draft',
    REMARK              NVARCHAR(500)   NULL,
    CREATED_BY          NVARCHAR(50)    NOT NULL,
    CREATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY          NVARCHAR(50)    NOT NULL,
    UPDATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_POM_PRODUCTION_PLAN PRIMARY KEY (PLAN_ID)
);

CREATE INDEX IX_POM_PLAN_PLANT   ON POM_PRODUCTION_PLAN (PLANT_ID, STATUS);
CREATE INDEX IX_POM_PLAN_PRODUCT ON POM_PRODUCTION_PLAN (PRODUCT_ID, PLANNED_START_DATE);
