-- EMS Module: Equipment Management System
CREATE TABLE CMMS_WORK_ORDER (
    WO_ID           NVARCHAR(50)    NOT NULL,
    PLAN_ID         NVARCHAR(50)    NULL,
    EQUIPMENT_ID    NVARCHAR(50)    NOT NULL,
    WO_TYPE         NVARCHAR(50)    NOT NULL,
    DESCRIPTION     NVARCHAR(500)   NULL,
    ASSIGNEE_ID     NVARCHAR(50)    NOT NULL,
    ISSUED_AT       DATETIME2       NOT NULL,
    STARTED_AT      DATETIME2       NULL,
    COMPLETED_AT    DATETIME2       NULL,
    STATUS          NVARCHAR(20)    NOT NULL DEFAULT 'Issued',
    FAILURE_CODE_ID NVARCHAR(50)    NULL,
    REMARK          NVARCHAR(500)   NULL,
    CREATED_BY      NVARCHAR(50)    NOT NULL,
    CREATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY      NVARCHAR(50)    NOT NULL,
    UPDATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_CMMS_WORK_ORDER PRIMARY KEY (WO_ID),
    CONSTRAINT FK_CMMS_WO_PLAN      FOREIGN KEY (PLAN_ID)      REFERENCES POM_PRODUCTION_PLAN (PLAN_ID),
    CONSTRAINT FK_CMMS_WO_EQUIPMENT FOREIGN KEY (EQUIPMENT_ID) REFERENCES MDM_EQUIPMENT (EQUIPMENT_ID),
    CONSTRAINT FK_CMMS_WO_ASSIGNEE  FOREIGN KEY (ASSIGNEE_ID)  REFERENCES SYS_USER (USER_ID)
);

CREATE INDEX IX_CMMS_WO_EQUIPMENT ON CMMS_WORK_ORDER (EQUIPMENT_ID, STATUS);
CREATE INDEX IX_CMMS_WO_ASSIGNEE  ON CMMS_WORK_ORDER (ASSIGNEE_ID, ISSUED_AT DESC);
CREATE INDEX IX_CMMS_WO_PLAN      ON CMMS_WORK_ORDER (PLAN_ID) WHERE PLAN_ID IS NOT NULL;
