-- DLV Module: Delivery Management
CREATE TABLE SHP_DELIVERY_ORDER (
    ORDER_ID        NVARCHAR(50)    NOT NULL,
    CUSTOMER_NAME   NVARCHAR(200)   NOT NULL,
    PLANT_ID        NVARCHAR(50)    NOT NULL,
    REQUESTED_DATE  DATETIME2       NOT NULL,
    SHIPPED_DATE    DATETIME2       NULL,
    STATUS          NVARCHAR(20)    NOT NULL DEFAULT 'Draft',
    REMARK          NVARCHAR(500)   NULL,
    CREATED_BY      NVARCHAR(50)    NOT NULL,
    CREATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY      NVARCHAR(50)    NOT NULL,
    UPDATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_DLV_DELIVERY_ORDER PRIMARY KEY (ORDER_ID)
);

CREATE INDEX IX_DLV_ORDER_PLANT    ON SHP_DELIVERY_ORDER (PLANT_ID, STATUS);
CREATE INDEX IX_DLV_ORDER_CUSTOMER ON SHP_DELIVERY_ORDER (CUSTOMER_NAME, REQUESTED_DATE DESC);
