-- FDC Module: alarm occurrence/clear history (design 10.4.1)
-- 알람 발생 시 1행 기록(OCCURRED_AT). 정상 복귀 시 CLEARED_AT/IS_CLEARED 갱신.
CREATE TABLE FDC_ALARM_HISTORY (
    ALARM_ID         NVARCHAR(50)    NOT NULL,
    ALARM_CONFIG_ID  NVARCHAR(50)    NOT NULL,
    EQUIPMENT_ID     NVARCHAR(50)    NOT NULL,
    PARAMETER_ID     NVARCHAR(50)    NOT NULL,
    ALARM_LEVEL      NVARCHAR(20)    NOT NULL,
    TRIGGER_VALUE    DECIMAL(18,6)   NOT NULL,
    MESSAGE          NVARCHAR(500)   NOT NULL,
    OCCURRED_AT      DATETIME2       NOT NULL,
    CLEARED_AT       DATETIME2       NULL,
    IS_CLEARED       BIT             NOT NULL DEFAULT 0,
    CREATED_BY       NVARCHAR(50)    NOT NULL,
    CREATED_AT       DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY       NVARCHAR(50)    NOT NULL,
    UPDATED_AT       DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_FDC_ALARM_HISTORY PRIMARY KEY (ALARM_ID),
    CONSTRAINT FK_FDC_ALARM_HIST_CONFIG FOREIGN KEY (ALARM_CONFIG_ID)
        REFERENCES FDC_ALARM_CONFIG (ALARM_CONFIG_ID)
);

CREATE INDEX IX_FDC_ALARM_HIST_EQUIP ON FDC_ALARM_HISTORY (EQUIPMENT_ID, OCCURRED_AT DESC);
CREATE INDEX IX_FDC_ALARM_HIST_OPEN  ON FDC_ALARM_HISTORY (IS_CLEARED, OCCURRED_AT DESC);
