-- FDC Module: parameter grouping master (design 10.4.1)
-- FDC 파라미터(FDC_PARAMETER.GROUP_ID)를 묶는 그룹 마스터. 설비별 파라미터를 화면에서 그룹 단위로 관리한다.
CREATE TABLE FDC_PARAMETER_GROUP (
    GROUP_ID       NVARCHAR(50)    NOT NULL,
    GROUP_NAME     NVARCHAR(200)   NOT NULL,
    EQUIPMENT_ID   NVARCHAR(50)    NOT NULL,
    DESCRIPTION    NVARCHAR(500)   NULL,
    DISPLAY_ORDER  INT             NOT NULL DEFAULT 0,
    IS_ACTIVE      BIT             NOT NULL DEFAULT 1,
    CREATED_BY     NVARCHAR(50)    NOT NULL,
    CREATED_AT     DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY     NVARCHAR(50)    NOT NULL,
    UPDATED_AT     DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_FDC_PARAMETER_GROUP PRIMARY KEY (GROUP_ID),
    CONSTRAINT FK_FDC_PARAM_GROUP_EQUIPMENT FOREIGN KEY (EQUIPMENT_ID)
        REFERENCES MDM_EQUIPMENT (EQUIPMENT_ID)
);

CREATE INDEX IX_FDC_PARAM_GROUP_EQUIPMENT ON FDC_PARAMETER_GROUP (EQUIPMENT_ID, IS_ACTIVE, DISPLAY_ORDER);
