-- CMMS Module: Maintenance Plan & Spare Part (정비 계획 / 예비품 재고)
-- 기존 갭 보강 — V008은 CMMS_WORK_ORDER만 생성했고, 정비계획/예비품 2개 테이블이 누락되어
-- MaintenancePlanRepository / SparePartRepository 가 MSSQL/SQLite 양쪽에서 'no such column/table'로
-- 실패했다(maintenance-plans / spare-parts 엔드포인트가 신규 DB에서 동작 불가).
-- 컬럼/타입/널 허용은 리포지토리 쿼리(SELECT */INSERT/UPDATE)와 1:1 정합.
-- 감사 컬럼(CREATED_BY 등)은 두 리포지토리 모두 ServiceObjectProcessor.InsertAsync/UpdateAsync 를
-- 사용해 CreatedBy/CreatedAt/UpdatedBy/UpdatedAt 파라미터가 주입되므로 V008 컨벤션대로 포함한다.

-- 정비 계획 — INSERT(PLAN_ID, PLAN_NAME, EQUIPMENT_ID, PLAN_TYPE, CYCLE_TYPE, SCHEDULED_DATE,
--   ESTIMATED_DURATION_HOURS, ASSIGNEE_ID, STATUS, +감사) / WHERE PLAN_ID(PK) / GetByEquipment·GetByStatus.
CREATE TABLE CMMS_MAINTENANCE_PLAN (
    PLAN_ID                  NVARCHAR(50)    NOT NULL,
    PLAN_NAME                NVARCHAR(200)   NOT NULL,
    EQUIPMENT_ID             NVARCHAR(50)    NOT NULL,
    PLAN_TYPE                NVARCHAR(50)    NOT NULL,
    CYCLE_TYPE               NVARCHAR(50)    NOT NULL,
    SCHEDULED_DATE           DATETIME2       NOT NULL,
    ESTIMATED_DURATION_HOURS DECIMAL(18,4)   NOT NULL,
    ASSIGNEE_ID              NVARCHAR(50)    NOT NULL,
    STATUS                   NVARCHAR(20)    NOT NULL DEFAULT 'Planned',
    CREATED_BY               NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT               DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY               NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT               DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_CMMS_MAINTENANCE_PLAN PRIMARY KEY (PLAN_ID),
    CONSTRAINT FK_CMMS_PLAN_EQUIPMENT FOREIGN KEY (EQUIPMENT_ID) REFERENCES MDM_EQUIPMENT (EQUIPMENT_ID),
    CONSTRAINT FK_CMMS_PLAN_ASSIGNEE  FOREIGN KEY (ASSIGNEE_ID)  REFERENCES SYS_USER (USER_ID)
);

-- GetByEquipmentAsync: WHERE EQUIPMENT_ID = @ ORDER BY SCHEDULED_DATE
CREATE INDEX IX_CMMS_PLAN_EQUIPMENT ON CMMS_MAINTENANCE_PLAN (EQUIPMENT_ID, SCHEDULED_DATE);
-- GetByStatusAsync: WHERE STATUS = @ ORDER BY SCHEDULED_DATE
CREATE INDEX IX_CMMS_PLAN_STATUS    ON CMMS_MAINTENANCE_PLAN (STATUS, SCHEDULED_DATE);

-- 예비품 — INSERT(PART_ID, PART_NAME, PART_NUMBER, DESCRIPTION, UNIT_OF_MEASURE, CURRENT_STOCK,
--   MIN_STOCK, MAX_STOCK, LOCATION, EQUIPMENT_CLASS_ID, +감사) / WHERE PART_ID(PK) /
--   GetAll ORDER BY PART_NAME / GetLowStock WHERE CURRENT_STOCK <= MIN_STOCK.
-- EQUIPMENT_CLASS_ID 는 C# string? 라 NULL 허용. 부모 테이블(MDM_EQUIPMENT_CLASS)이 어느 마이그레이션에도
-- 존재하지 않으므로 FK는 두지 않는다(가공의 테이블을 만들지 않는다).
CREATE TABLE CMMS_SPARE_PART (
    PART_ID            NVARCHAR(50)    NOT NULL,
    PART_NAME          NVARCHAR(200)   NOT NULL,
    PART_NUMBER        NVARCHAR(100)   NOT NULL,
    DESCRIPTION        NVARCHAR(500)   NULL,
    UNIT_OF_MEASURE    NVARCHAR(50)    NOT NULL,
    CURRENT_STOCK      DECIMAL(18,4)   NOT NULL,
    MIN_STOCK          DECIMAL(18,4)   NOT NULL,
    MAX_STOCK          DECIMAL(18,4)   NOT NULL,
    LOCATION           NVARCHAR(200)   NOT NULL,
    EQUIPMENT_CLASS_ID NVARCHAR(50)    NULL,
    CREATED_BY         NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT         DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY         NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT         DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_CMMS_SPARE_PART PRIMARY KEY (PART_ID)
);

-- GetAllAsync / GetLowStockAsync 모두 ORDER BY PART_NAME
CREATE INDEX IX_CMMS_SPARE_PART_NAME ON CMMS_SPARE_PART (PART_NAME);
