-- POM Module: Production Order Management
-- 기존 갭 보강 — POM_PRODUCTION_PLAN(V007)만 존재했고 생산지시(ProductionOrder) 테이블이 누락되어
-- /api/v1/pom/orders 계열 기능(ProductionOrderService/ProductionOrderRepository)이 MSSQL/SQLite 양쪽에서
-- 'no such table' 로 실패했다. 컬럼/타입/널 허용은 ProductionOrderRepository 의 SELECT/INSERT/UPDATE SQL과 1:1 정합.
-- 감사 컬럼(CREATED_BY 등)은 리포지토리가 _processor.InsertAsync/UpdateAsync(InjectAudit) 경로를 쓰므로 포함한다.

CREATE TABLE POM_PRODUCTION_ORDER (
    ORDER_ID            NVARCHAR(50)    NOT NULL,
    PLAN_ID             NVARCHAR(50)    NOT NULL,
    EQUIPMENT_ID        NVARCHAR(50)    NOT NULL,
    PRODUCT_ID          NVARCHAR(50)    NOT NULL,
    ORDER_QTY           DECIMAL(18,4)   NOT NULL,
    ACTUAL_QTY          DECIMAL(18,4)   NULL,
    SCHEDULED_START     DATETIME2       NOT NULL,
    SCHEDULED_END       DATETIME2       NOT NULL,
    ACTUAL_START        DATETIME2       NULL,
    ACTUAL_END          DATETIME2       NULL,
    STATUS              NVARCHAR(20)    NOT NULL DEFAULT 'Issued',
    CREATED_BY          NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY          NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_POM_PRODUCTION_ORDER PRIMARY KEY (ORDER_ID),
    CONSTRAINT FK_POM_ORDER_PLAN FOREIGN KEY (PLAN_ID)
        REFERENCES POM_PRODUCTION_PLAN (PLAN_ID),
    CONSTRAINT FK_POM_ORDER_EQUIPMENT FOREIGN KEY (EQUIPMENT_ID)
        REFERENCES MDM_EQUIPMENT (EQUIPMENT_ID)
);

CREATE INDEX IX_POM_ORDER_PLAN      ON POM_PRODUCTION_ORDER (PLAN_ID, SCHEDULED_START);
CREATE INDEX IX_POM_ORDER_EQUIPMENT ON POM_PRODUCTION_ORDER (EQUIPMENT_ID, STATUS);
