-- SHP Module: Delivery Items & Shipment History (배송 품목 / 출하 이력)
-- 기존 갭 보강 — V009는 SHP_DELIVERY_ORDER만 생성했고, 배송 품목/출하 이력 2개 테이블이 누락되어
-- 해당 기능(DeliveryItemRepository / ShipmentHistoryRepository)이 MSSQL/SQLite 양쪽에서 동작하지 못했다.
-- 컬럼/타입/널 허용은 리포지토리 SQL(SELECT */INSERT/UPDATE)과 1:1 정합한다.
-- 두 리포지토리 모두 ServiceObjectProcessor.InsertAsync/UpdateAsync 를 사용하므로 감사 컬럼(CREATED_BY 등)을 둔다.
-- 부모 테이블 SHP_DELIVERY_ORDER(ORDER_ID, V009)는 이미 존재하므로 DELIVERY_ORDER_ID에 FK를 건다.

-- 배송 품목 — DeliveryItemRepository: SELECT * WHERE ITEM_ID / DELIVERY_ORDER_ID,
-- INSERT(ITEM_ID, DELIVERY_ORDER_ID, PRODUCT_ID, PLANNED_QTY, ACTUAL_QTY, LOT_ID + 감사),
-- UPDATE(ACTUAL_QTY) WHERE ITEM_ID. PK = ITEM_ID(upsert 키).
CREATE TABLE SHP_DELIVERY_ITEM (
    ITEM_ID             NVARCHAR(50)    NOT NULL,
    DELIVERY_ORDER_ID   NVARCHAR(50)    NOT NULL,
    PRODUCT_ID          NVARCHAR(50)    NOT NULL,
    PLANNED_QTY         DECIMAL(18,4)   NOT NULL,
    ACTUAL_QTY          DECIMAL(18,4)   NULL,
    LOT_ID              NVARCHAR(50)    NULL,
    CREATED_BY          NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY          NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_DLV_DELIVERY_ITEM PRIMARY KEY (ITEM_ID),
    CONSTRAINT FK_DLV_ITEM_ORDER FOREIGN KEY (DELIVERY_ORDER_ID)
        REFERENCES SHP_DELIVERY_ORDER (ORDER_ID)
);

CREATE INDEX IX_DLV_ITEM_ORDER ON SHP_DELIVERY_ITEM (DELIVERY_ORDER_ID, CREATED_AT);

-- 출하 이력 — ShipmentHistoryRepository: SELECT * WHERE DELIVERY_ORDER_ID ORDER BY SHIPPED_AT DESC,
-- INSERT(HISTORY_ID, DELIVERY_ORDER_ID, SHIPPED_AT, SHIPPED_QTY, SHIPPED_BY, CARRIER, TRACKING_NO + 감사).
-- PK = HISTORY_ID. CARRIER / TRACKING_NO는 string? 이라 NULL 허용.
CREATE TABLE SHP_SHIPMENT_HISTORY (
    HISTORY_ID          NVARCHAR(50)    NOT NULL,
    DELIVERY_ORDER_ID   NVARCHAR(50)    NOT NULL,
    SHIPPED_AT          DATETIME2       NOT NULL,
    SHIPPED_QTY         DECIMAL(18,4)   NOT NULL,
    SHIPPED_BY          NVARCHAR(50)    NOT NULL,
    CARRIER             NVARCHAR(200)   NULL,
    TRACKING_NO         NVARCHAR(200)   NULL,
    CREATED_BY          NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY          NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_DLV_SHIPMENT_HISTORY PRIMARY KEY (HISTORY_ID),
    CONSTRAINT FK_DLV_HIST_ORDER FOREIGN KEY (DELIVERY_ORDER_ID)
        REFERENCES SHP_DELIVERY_ORDER (ORDER_ID)
);

CREATE INDEX IX_DLV_HIST_ORDER ON SHP_SHIPMENT_HISTORY (DELIVERY_ORDER_ID, SHIPPED_AT DESC);
