-- QMS Module: Quality Management master/result tables (마이그레이션 누락 보강)
-- V006은 QMS_DEFECT 한 테이블만 생성했고, 결함분류/검사규격/검사결과/SPC파라미터 4개 테이블이
-- 누락되어 해당 기능(DefectClass/InspectionSpec/InspectionResult/SpcParam Repository)이
-- 신규 DB에서 "no such table"로 동작하지 못했다.
-- 컬럼/타입/널 허용은 각 리포지토리의 SELECT/INSERT/UPDATE SQL 및 Row 클래스와 1:1 정합.
-- 감사 컬럼(CREATED_BY 등)은 ServiceObjectProcessor.InsertAsync/UpdateAsync가 주입하므로 DEFAULT와 함께 둔다.

-- 결함 분류(DefectClassRepository) — SELECT *, INSERT/UPDATE 컬럼 집합 기준.
-- IS_DELETED/DELETED_AT는 UPDATE(소프트삭제) 및 Row.ToDomain/FromDomain에서 사용한다.
-- SEVERITY는 도메인에서 Critical/Major/Minor로 제약되어 NVARCHAR(20)로 둔다.
CREATE TABLE QMS_DEFECT_CLASS (
    DEFECT_CLASS_ID     NVARCHAR(50)    NOT NULL,
    DEFECT_CLASS_NAME   NVARCHAR(200)   NOT NULL,
    DESCRIPTION         NVARCHAR(500)   NULL,
    SEVERITY            NVARCHAR(20)     NOT NULL,
    IS_ACTIVE           BIT             NOT NULL DEFAULT 1,
    IS_DELETED          BIT             NOT NULL DEFAULT 0,
    DELETED_AT          DATETIME2       NULL,
    CREATED_BY          NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY          NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_QMS_DEFECT_CLASS PRIMARY KEY (DEFECT_CLASS_ID)
);

CREATE INDEX IX_QMS_DEFECT_CLASS_NAME   ON QMS_DEFECT_CLASS (DEFECT_CLASS_NAME);
CREATE INDEX IX_QMS_DEFECT_CLASS_ACTIVE ON QMS_DEFECT_CLASS (IS_DELETED, IS_ACTIVE);

-- 검사 규격(InspectionSpecRepository) — SELECT *, INSERT 컬럼 기준.
-- NOMINAL_VALUE/TOLERANCE_PLUS/TOLERANCE_MINUS는 decimal?라 NULL 허용.
-- PROCESS_ID는 참조할 공정 마스터 테이블이 db/migrations에 없으므로 FK 생략(부모 미존재).
CREATE TABLE QMS_INSPECTION_SPEC (
    SPEC_ID             NVARCHAR(50)    NOT NULL,
    SPEC_NAME           NVARCHAR(200)   NOT NULL,
    PROCESS_ID          NVARCHAR(50)    NOT NULL,
    ITEM_NAME           NVARCHAR(200)   NOT NULL,
    MEASURE_TYPE        NVARCHAR(50)    NOT NULL,
    NOMINAL_VALUE       DECIMAL(18,4)   NULL,
    TOLERANCE_PLUS      DECIMAL(18,4)   NULL,
    TOLERANCE_MINUS     DECIMAL(18,4)   NULL,
    IS_ACTIVE           BIT             NOT NULL DEFAULT 1,
    CREATED_BY          NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY          NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_QMS_INSPECTION_SPEC PRIMARY KEY (SPEC_ID)
);

CREATE INDEX IX_QMS_INSPECTION_SPEC_PROCESS ON QMS_INSPECTION_SPEC (PROCESS_ID, IS_ACTIVE);

-- 검사 결과(InspectionResultRepository) — SELECT *, INSERT 컬럼 기준.
-- MEASURED_VALUE/ATTRIBUTE_RESULT/REMARK는 nullable. FK: 설비/검사자/검사규격(상위에서 선생성).
CREATE TABLE QMS_INSPECTION_RESULT (
    RESULT_ID           NVARCHAR(50)    NOT NULL,
    SPEC_ID             NVARCHAR(50)    NOT NULL,
    LOT_ID              NVARCHAR(50)    NOT NULL,
    EQUIPMENT_ID        NVARCHAR(50)    NOT NULL,
    MEASURED_VALUE      DECIMAL(18,4)   NULL,
    ATTRIBUTE_RESULT    NVARCHAR(50)    NULL,
    INSPECTED_AT        DATETIME2       NOT NULL,
    INSPECTOR_ID        NVARCHAR(50)    NOT NULL,
    IS_PASS             BIT             NOT NULL DEFAULT 0,
    REMARK              NVARCHAR(500)   NULL,
    CREATED_BY          NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY          NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_QMS_INSPECTION_RESULT PRIMARY KEY (RESULT_ID),
    CONSTRAINT FK_QMS_INSP_RESULT_SPEC FOREIGN KEY (SPEC_ID)
        REFERENCES QMS_INSPECTION_SPEC (SPEC_ID),
    CONSTRAINT FK_QMS_INSP_RESULT_EQUIPMENT FOREIGN KEY (EQUIPMENT_ID)
        REFERENCES MDM_EQUIPMENT (EQUIPMENT_ID),
    CONSTRAINT FK_QMS_INSP_RESULT_INSPECTOR FOREIGN KEY (INSPECTOR_ID)
        REFERENCES SYS_USER (USER_ID)
);

CREATE INDEX IX_QMS_INSP_RESULT_LOT  ON QMS_INSPECTION_RESULT (LOT_ID, INSPECTED_AT DESC);
CREATE INDEX IX_QMS_INSP_RESULT_SPEC ON QMS_INSPECTION_RESULT (SPEC_ID, INSPECTED_AT DESC);

-- SPC 파라미터(SpcParamRepository) — SELECT *, INSERT/UPDATE 컬럼 기준.
-- MEAN/UCL/LCL/SAMPLE_SIZE는 NOT NULL(decimal/int), USL/LSL은 decimal?라 NULL 허용.
-- FK: 설비(MDM_EQUIPMENT). PROCESS_ID는 공정 마스터 미존재로 FK 생략.
CREATE TABLE QMS_SPC_PARAM (
    PARAM_ID            NVARCHAR(50)    NOT NULL,
    PARAM_NAME          NVARCHAR(200)   NOT NULL,
    EQUIPMENT_ID        NVARCHAR(50)    NOT NULL,
    PROCESS_ID          NVARCHAR(50)    NOT NULL,
    MEAN                DECIMAL(18,4)   NOT NULL DEFAULT 0,
    UCL                 DECIMAL(18,4)   NOT NULL DEFAULT 0,
    LCL                 DECIMAL(18,4)   NOT NULL DEFAULT 0,
    USL                 DECIMAL(18,4)   NULL,
    LSL                 DECIMAL(18,4)   NULL,
    SAMPLE_SIZE         INT             NOT NULL DEFAULT 0,
    IS_ACTIVE           BIT             NOT NULL DEFAULT 1,
    CREATED_BY          NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY          NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_QMS_SPC_PARAM PRIMARY KEY (PARAM_ID),
    CONSTRAINT FK_QMS_SPC_PARAM_EQUIPMENT FOREIGN KEY (EQUIPMENT_ID)
        REFERENCES MDM_EQUIPMENT (EQUIPMENT_ID)
);

CREATE INDEX IX_QMS_SPC_PARAM_EQUIP ON QMS_SPC_PARAM (EQUIPMENT_ID, IS_ACTIVE);
