-- CMMS Module: 설비 점검 항목 마스터(점검 항목 그룹/항목/설비별 항목).
-- SmartUX EMS 메뉴의 점검 항목 업무화면 3종(설비 점검 항목 그룹/항목/설비별 항목 관리)이 새 시스템에서
-- "no such table"로 막혀 있어, 화면 점등의 백엔드로 3개 마스터 테이블을 신설한다. 컬럼/감사/제약은
-- V027__CMMS_PLAN_SPAREPART · V035__MDM_MASTER_EXT 스타일과 정합(NVARCHAR/DATETIME2/감사 4컬럼 + PK/FK).
-- SQLite는 SqliteSchemaInitializer가 방언 변환(NVARCHAR→TEXT 등)·FK 비강제. 부모→자식 순서로 생성.

-- 점검 항목 그룹.
CREATE TABLE CMMS_MAINT_ITEM_CLASS (
    ITEM_CLASS_ID     NVARCHAR(50)    NOT NULL,
    ITEM_CLASS_NAME   NVARCHAR(200)   NOT NULL,
    DESCRIPTION       NVARCHAR(500)   NULL,
    CREATED_BY        NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT        DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY        NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT        DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_CMMS_MAINT_ITEM_CLASS PRIMARY KEY (ITEM_CLASS_ID)
);
CREATE INDEX IX_CMMS_MAINT_ITEM_CLASS_NAME ON CMMS_MAINT_ITEM_CLASS (ITEM_CLASS_NAME);

-- 점검 항목 — 그룹(CMMS_MAINT_ITEM_CLASS) 참조(nullable), 점검 방법/단위.
CREATE TABLE CMMS_MAINT_ITEM (
    ITEM_ID            NVARCHAR(50)    NOT NULL,
    ITEM_NAME          NVARCHAR(200)   NOT NULL,
    ITEM_CLASS_ID      NVARCHAR(50)    NULL,
    INSPECTION_METHOD  NVARCHAR(200)   NULL,
    UNIT               NVARCHAR(50)    NULL,
    DESCRIPTION        NVARCHAR(500)   NULL,
    IS_ACTIVE          BIT             NOT NULL DEFAULT 1,
    CREATED_BY         NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT         DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY         NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT         DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_CMMS_MAINT_ITEM PRIMARY KEY (ITEM_ID),
    CONSTRAINT FK_CMMS_MAINT_ITEM_CLASS FOREIGN KEY (ITEM_CLASS_ID)
        REFERENCES CMMS_MAINT_ITEM_CLASS (ITEM_CLASS_ID)
);
CREATE INDEX IX_CMMS_MAINT_ITEM_CLASS_REF ON CMMS_MAINT_ITEM (ITEM_CLASS_ID, ITEM_NAME);

-- 설비별 점검 항목(매핑) — 설비(MDM_EQUIPMENT)·점검항목(CMMS_MAINT_ITEM) 연결 + 점검 주기.
CREATE TABLE CMMS_EQP_MAINT_ITEM (
    EQP_ITEM_ID        NVARCHAR(50)    NOT NULL,
    EQUIPMENT_ID       NVARCHAR(50)    NOT NULL,
    ITEM_ID            NVARCHAR(50)    NOT NULL,
    CYCLE_TYPE         NVARCHAR(50)    NULL,
    CYCLE_VALUE        INT             NULL,
    IS_ACTIVE          BIT             NOT NULL DEFAULT 1,
    CREATED_BY         NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT         DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY         NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT         DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_CMMS_EQP_MAINT_ITEM PRIMARY KEY (EQP_ITEM_ID),
    CONSTRAINT FK_CMMS_EQP_MAINT_ITEM_EQUIP FOREIGN KEY (EQUIPMENT_ID)
        REFERENCES MDM_EQUIPMENT (EQUIPMENT_ID),
    CONSTRAINT FK_CMMS_EQP_MAINT_ITEM_ITEM FOREIGN KEY (ITEM_ID)
        REFERENCES CMMS_MAINT_ITEM (ITEM_ID)
);
CREATE INDEX IX_CMMS_EQP_MAINT_ITEM_EQUIP ON CMMS_EQP_MAINT_ITEM (EQUIPMENT_ID, ITEM_ID);
