-- QMS Module: 검사 실행 기록(수입/공정/출하). SmartUX QMS 검사 관리 메뉴(수입/공정/출하 검사 등록·이력·현황)가
-- "no such table"로 막혀 있어 화면 점등 백엔드로 단일 검사 실행 테이블을 신설한다. INSPECTION_TYPE으로
-- 수입(Incoming)/공정(Process)/출하(Shipping)를 구분한다. 컬럼/감사는 V030 QMS_INSPECTION_RESULT 스타일과 정합.
-- LOT/PRODUCT/SPEC/설비는 소프트 참조(FK 생략). SQLite는 방언 변환·FK 비강제.
CREATE TABLE QMS_INSPECTION (
    INSPECTION_ID    NVARCHAR(50)    NOT NULL,
    INSPECTION_TYPE  NVARCHAR(50)    NOT NULL,
    LOT_ID           NVARCHAR(50)    NULL,
    PRODUCT_ID       NVARCHAR(50)    NULL,
    EQUIPMENT_ID     NVARCHAR(50)    NULL,
    SPEC_ID          NVARCHAR(50)    NULL,
    INSPECTED_AT     DATETIME2       NOT NULL,
    INSPECTOR_ID     NVARCHAR(50)    NULL,
    RESULT           NVARCHAR(20)    NULL,
    SAMPLE_QTY       INT             NULL,
    DEFECT_QTY       INT             NULL,
    IS_CONFIRMED     BIT             NOT NULL DEFAULT 0,
    REMARK           NVARCHAR(500)   NULL,
    CREATED_BY       NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT       DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY       NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT       DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_QMS_INSPECTION PRIMARY KEY (INSPECTION_ID)
);
CREATE INDEX IX_QMS_INSPECTION_TYPE ON QMS_INSPECTION (INSPECTION_TYPE, INSPECTED_AT DESC);
CREATE INDEX IX_QMS_INSPECTION_LOT  ON QMS_INSPECTION (LOT_ID, INSPECTED_AT DESC);
