-- QMS Module: 장기재고 검사(자재/제품). SmartUX QMS 장기재고검사 메뉴(자재/제품 의뢰·결과·이력)가
-- "no such table"로 막혀 있어 화면 점등 백엔드로 단일 장기재고 검사 테이블을 신설한다. TARGET_TYPE으로
-- 자재(Material)/제품(Product)을 구분한다. 컬럼/감사는 V030/V040 QMS 스타일과 정합. 소프트 참조 FK 생략.
CREATE TABLE QMS_LONGTERM_INSPECTION (
    LT_INSP_ID       NVARCHAR(50)    NOT NULL,
    TARGET_TYPE      NVARCHAR(50)    NOT NULL,
    PRODUCT_ID       NVARCHAR(50)    NULL,
    LOT_ID           NVARCHAR(50)    NULL,
    WAREHOUSE        NVARCHAR(100)   NULL,
    REQUEST_DATE     DATETIME2       NULL,
    REQUESTED_BY     NVARCHAR(50)    NULL,
    INSPECTED_AT     DATETIME2       NULL,
    INSPECTOR_ID     NVARCHAR(50)    NULL,
    RESULT           NVARCHAR(20)    NULL,
    STATUS           NVARCHAR(20)    NOT NULL DEFAULT 'Requested',
    REMARK           NVARCHAR(500)   NULL,
    CREATED_BY       NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT       DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY       NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT       DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_QMS_LONGTERM_INSPECTION PRIMARY KEY (LT_INSP_ID)
);
CREATE INDEX IX_QMS_LT_INSP_TARGET ON QMS_LONGTERM_INSPECTION (TARGET_TYPE, REQUEST_DATE DESC);
