-- QMS Module: 고객 클레임. SmartUX QMS 클레임 메뉴(접수/처리결과/현황/발생현황/처리현황)의 백엔드로 단일 클레임
-- 테이블을 신설한다. 컬럼/감사는 V030/V040 QMS 스타일과 정합. 품목/LOT는 소프트 참조(FK 생략).
CREATE TABLE QMS_CLAIM (
    CLAIM_ID        NVARCHAR(50)    NOT NULL,
    CLAIM_NO        NVARCHAR(50)    NULL,
    CUSTOMER_NAME   NVARCHAR(200)   NOT NULL,
    PRODUCT_ID      NVARCHAR(50)    NULL,
    LOT_ID          NVARCHAR(50)    NULL,
    CLAIM_TYPE      NVARCHAR(50)    NULL,
    OCCURRED_DATE   DATETIME2       NULL,
    RECEIVED_DATE   DATETIME2       NULL,
    SEVERITY        NVARCHAR(20)    NULL,
    DESCRIPTION     NVARCHAR(1000)  NULL,
    STATUS          NVARCHAR(20)    NOT NULL DEFAULT 'Received',
    ACTION_DESC     NVARCHAR(1000)  NULL,
    COMPLETED_AT    DATETIME2       NULL,
    ASSIGNEE_ID     NVARCHAR(50)    NULL,
    CREATED_BY      NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY      NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_QMS_CLAIM PRIMARY KEY (CLAIM_ID)
);
CREATE INDEX IX_QMS_CLAIM_STATUS ON QMS_CLAIM (STATUS, OCCURRED_DATE DESC);
