-- QMS Module: 품질보증(QCA) — 부적합(NCR) + Hold/Release(Risk Range).
-- SmartUX QMS QCA 메뉴(NCR 관리/현황, Hold/Release 등록/현황)의 백엔드로 2개 테이블을 신설한다.
-- 컬럼/감사는 V030/V040 QMS 스타일과 정합. LOT/품목/설비/결함분류는 소프트 참조(FK 생략).

-- 부적합 보고서(NCR).
CREATE TABLE QMS_NCR (
    NCR_ID          NVARCHAR(50)    NOT NULL,
    NCR_NO          NVARCHAR(50)    NULL,
    SOURCE_TYPE     NVARCHAR(50)    NULL,
    LOT_ID          NVARCHAR(50)    NULL,
    PRODUCT_ID      NVARCHAR(50)    NULL,
    EQUIPMENT_ID    NVARCHAR(50)    NULL,
    DEFECT_CLASS_ID NVARCHAR(50)    NULL,
    ISSUED_DATE     DATETIME2       NOT NULL,
    ISSUED_BY       NVARCHAR(50)    NULL,
    DESCRIPTION     NVARCHAR(1000)  NULL,
    DISPOSITION     NVARCHAR(100)   NULL,
    STATUS          NVARCHAR(20)    NOT NULL DEFAULT 'Open',
    CLOSED_AT       DATETIME2       NULL,
    CREATED_BY      NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY      NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_QMS_NCR PRIMARY KEY (NCR_ID)
);
CREATE INDEX IX_QMS_NCR_STATUS ON QMS_NCR (STATUS, ISSUED_DATE DESC);

-- Hold/Release(Risk Range) 처리.
CREATE TABLE QMS_HOLD_RELEASE (
    HOLD_ID         NVARCHAR(50)    NOT NULL,
    LOT_ID          NVARCHAR(50)    NULL,
    PRODUCT_ID      NVARCHAR(50)    NULL,
    HOLD_TYPE       NVARCHAR(20)    NOT NULL,
    RISK_RANGE      NVARCHAR(100)   NULL,
    REASON          NVARCHAR(1000)  NULL,
    REQUESTED_BY    NVARCHAR(50)    NULL,
    REQUESTED_AT    DATETIME2       NOT NULL,
    STATUS          NVARCHAR(20)    NOT NULL DEFAULT 'Hold',
    RELEASED_BY     NVARCHAR(50)    NULL,
    RELEASED_AT     DATETIME2       NULL,
    CREATED_BY      NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY      NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_QMS_HOLD_RELEASE PRIMARY KEY (HOLD_ID)
);
CREATE INDEX IX_QMS_HOLD_RELEASE_STATUS ON QMS_HOLD_RELEASE (STATUS, REQUESTED_AT DESC);
