-- QMS Module: 4M 변경 관리. SmartUX QMS 4M 변경 이력/변경점 발생 현황 화면의 백엔드로 단일 변경 테이블을
-- 신설한다. CHANGE_TYPE으로 Man/Machine/Material/Method 구분. 컬럼/감사는 V030/V040 QMS 스타일과 정합. 소프트 참조 FK 생략.
CREATE TABLE QMS_4M_CHANGE (
    CHANGE_ID       NVARCHAR(50)    NOT NULL,
    CHANGE_NO       NVARCHAR(50)    NULL,
    CHANGE_TYPE     NVARCHAR(50)    NULL,
    EQUIPMENT_ID    NVARCHAR(50)    NULL,
    PRODUCT_ID      NVARCHAR(50)    NULL,
    CHANGE_DATE     DATETIME2       NULL,
    DESCRIPTION     NVARCHAR(1000)  NULL,
    REQUESTED_BY    NVARCHAR(50)    NULL,
    APPROVAL_STATUS NVARCHAR(20)    NOT NULL DEFAULT 'Pending',
    APPROVED_BY     NVARCHAR(50)    NULL,
    APPROVED_AT     DATETIME2       NULL,
    CREATED_BY      NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY      NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_QMS_4M_CHANGE PRIMARY KEY (CHANGE_ID)
);
CREATE INDEX IX_QMS_4M_CHANGE_TYPE ON QMS_4M_CHANGE (CHANGE_TYPE, CHANGE_DATE DESC);
