-- SYS/시스템관리 보강: 공지사항·메시지(그룹)·다국어(그룹)·Rule. SmartUX SYSTEM_2 메뉴의 공지/메시지/다국어/Rule
-- 업무화면 백엔드로 6개 마스터를 신설한다. 컬럼/감사/제약은 V031 SYS_MASTER 스타일과 정합. 부모(그룹)→자식 순서.
-- SQLite는 SqliteSchemaInitializer가 방언 변환·FK 비강제.

-- 공지사항.
CREATE TABLE SYS_NOTICE (
    NOTICE_ID     NVARCHAR(50)    NOT NULL,
    TITLE         NVARCHAR(300)   NOT NULL,
    CONTENT       NVARCHAR(2000)  NULL,
    NOTICE_TYPE   NVARCHAR(50)    NULL,
    POSTED_BY     NVARCHAR(50)    NULL,
    POSTED_AT     DATETIME2       NULL,
    IS_ACTIVE     BIT             NOT NULL DEFAULT 1,
    CREATED_BY    NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT    DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY    NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT    DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_SYS_NOTICE PRIMARY KEY (NOTICE_ID)
);
CREATE INDEX IX_SYS_NOTICE_POSTED ON SYS_NOTICE (POSTED_AT DESC);

-- 메시지 그룹.
CREATE TABLE SYS_MESSAGE_CLASS (
    MSG_CLASS_ID   NVARCHAR(50)   NOT NULL,
    MSG_CLASS_NAME NVARCHAR(200)  NOT NULL,
    DESCRIPTION    NVARCHAR(500)  NULL,
    CREATED_BY     NVARCHAR(50)   NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT     DATETIME2      NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY     NVARCHAR(50)   NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT     DATETIME2      NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_SYS_MESSAGE_CLASS PRIMARY KEY (MSG_CLASS_ID)
);

-- 메시지.
CREATE TABLE SYS_MESSAGE (
    MSG_ID         NVARCHAR(50)   NOT NULL,
    MSG_CLASS_ID   NVARCHAR(50)   NULL,
    MSG_CODE       NVARCHAR(100)  NULL,
    MSG_TEXT       NVARCHAR(1000) NULL,
    LANGUAGE       NVARCHAR(20)   NULL,
    DESCRIPTION    NVARCHAR(500)  NULL,
    CREATED_BY     NVARCHAR(50)   NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT     DATETIME2      NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY     NVARCHAR(50)   NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT     DATETIME2      NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_SYS_MESSAGE PRIMARY KEY (MSG_ID),
    CONSTRAINT FK_SYS_MESSAGE_CLASS FOREIGN KEY (MSG_CLASS_ID) REFERENCES SYS_MESSAGE_CLASS (MSG_CLASS_ID)
);
CREATE INDEX IX_SYS_MESSAGE_CLASS_REF ON SYS_MESSAGE (MSG_CLASS_ID, MSG_CODE);

-- 다국어 그룹.
CREATE TABLE SYS_LANGUAGE_CLASS (
    LANG_CLASS_ID   NVARCHAR(50)  NOT NULL,
    LANG_CLASS_NAME NVARCHAR(200) NOT NULL,
    DESCRIPTION     NVARCHAR(500) NULL,
    CREATED_BY      NVARCHAR(50)  NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT      DATETIME2     NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY      NVARCHAR(50)  NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT      DATETIME2     NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_SYS_LANGUAGE_CLASS PRIMARY KEY (LANG_CLASS_ID)
);

-- 다국어(번역 항목).
CREATE TABLE SYS_I18N (
    I18N_ID        NVARCHAR(50)   NOT NULL,
    LANG_CLASS_ID  NVARCHAR(50)   NULL,
    MESSAGE_KEY    NVARCHAR(200)  NOT NULL,
    LANGUAGE       NVARCHAR(20)   NOT NULL,
    TRANSLATION    NVARCHAR(1000) NULL,
    CREATED_BY     NVARCHAR(50)   NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT     DATETIME2      NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY     NVARCHAR(50)   NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT     DATETIME2      NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_SYS_I18N PRIMARY KEY (I18N_ID)
);
CREATE INDEX IX_SYS_I18N_KEY ON SYS_I18N (MESSAGE_KEY, LANGUAGE);

-- Rule.
CREATE TABLE SYS_RULE (
    RULE_ID         NVARCHAR(50)   NOT NULL,
    RULE_NAME       NVARCHAR(200)  NOT NULL,
    RULE_TYPE       NVARCHAR(50)   NULL,
    RULE_EXPRESSION NVARCHAR(2000) NULL,
    IS_ACTIVE       BIT            NOT NULL DEFAULT 1,
    DESCRIPTION     NVARCHAR(500)  NULL,
    CREATED_BY      NVARCHAR(50)   NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT      DATETIME2      NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY      NVARCHAR(50)   NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT      DATETIME2      NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_SYS_RULE PRIMARY KEY (RULE_ID)
);
CREATE INDEX IX_SYS_RULE_NAME ON SYS_RULE (RULE_NAME);
