-- IVT(자재/재고): 자재 LOT/재고 + 입출고 트랜잭션(입고/이동/불출). SmartUX FACTORY_IVT(창고) 메뉴의
-- 자재/입고/재고/불출/이동 업무화면 백엔드로 2개 테이블을 신설한다. MATERIAL_ID는 MDM_PRODUCT 소프트 참조(FK 생략),
-- TX_TYPE으로 입고(Incoming)/이동(Move)/불출(Dispensing) 구분. 컬럼/감사는 V027/V045 스타일과 정합. SQLite 방언 변환·FK 비강제.

-- 자재 LOT / 재고.
CREATE TABLE IVT_MATERIAL_LOT (
    LOT_ID        NVARCHAR(50)    NOT NULL,
    MATERIAL_ID   NVARCHAR(50)    NULL,
    LOT_NO        NVARCHAR(100)   NULL,
    WAREHOUSE     NVARCHAR(100)   NULL,
    CURRENT_QTY   DECIMAL(18,2)   NULL,
    UNIT          NVARCHAR(50)    NULL,
    STATUS        NVARCHAR(20)    NOT NULL DEFAULT 'InStock',
    RECEIVED_AT   DATETIME2       NULL,
    EXPIRY_AT     DATETIME2       NULL,
    CREATED_BY    NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT    DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY    NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT    DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_IVT_MATERIAL_LOT PRIMARY KEY (LOT_ID)
);
CREATE INDEX IX_IVT_MATERIAL_LOT_MAT ON IVT_MATERIAL_LOT (MATERIAL_ID, WAREHOUSE);

-- 자재 입출고 트랜잭션.
CREATE TABLE IVT_MATERIAL_TX (
    TX_ID          NVARCHAR(50)    NOT NULL,
    LOT_ID         NVARCHAR(50)    NULL,
    MATERIAL_ID    NVARCHAR(50)    NULL,
    TX_TYPE        NVARCHAR(20)    NOT NULL,
    QTY            DECIMAL(18,2)   NULL,
    FROM_WAREHOUSE NVARCHAR(100)   NULL,
    TO_WAREHOUSE   NVARCHAR(100)   NULL,
    TX_AT          DATETIME2       NOT NULL,
    PROCESSED_BY   NVARCHAR(50)    NULL,
    STATUS         NVARCHAR(20)    NULL,
    REMARK         NVARCHAR(500)   NULL,
    CREATED_BY     NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT     DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY     NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT     DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_IVT_MATERIAL_TX PRIMARY KEY (TX_ID)
);
CREATE INDEX IX_IVT_MATERIAL_TX_TYPE ON IVT_MATERIAL_TX (TX_TYPE, TX_AT DESC);
