-- COM(공통): 알람(그룹/정의) + 상태(모델/코드) + 라벨 + ID 채번. SmartUX FACTORY_COM 공통 메뉴의 알람/상태/라벨/채번
-- 업무화면 백엔드로 6개 마스터를 신설한다. 컬럼/감사/제약은 V031/V046 스타일과 정합. 부모(그룹/모델)→자식 순서. SQLite 방언 변환·FK 비강제.

-- 알람 그룹.
CREATE TABLE COM_ALARM_CLASS (
    ALARM_CLASS_ID   NVARCHAR(50)   NOT NULL,
    ALARM_CLASS_NAME NVARCHAR(200)  NOT NULL,
    DESCRIPTION      NVARCHAR(500)  NULL,
    IS_ACTIVE        BIT            NOT NULL DEFAULT 1,
    CREATED_BY       NVARCHAR(50)   NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT       DATETIME2      NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY       NVARCHAR(50)   NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT       DATETIME2      NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_COM_ALARM_CLASS PRIMARY KEY (ALARM_CLASS_ID)
);

-- 알람 정의.
CREATE TABLE COM_ALARM (
    ALARM_ID         NVARCHAR(50)   NOT NULL,
    ALARM_NAME       NVARCHAR(200)  NOT NULL,
    ALARM_CLASS_ID   NVARCHAR(50)   NULL,
    SEVERITY         NVARCHAR(20)   NULL,
    MESSAGE          NVARCHAR(500)  NULL,
    IS_ACTIVE        BIT            NOT NULL DEFAULT 1,
    CREATED_BY       NVARCHAR(50)   NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT       DATETIME2      NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY       NVARCHAR(50)   NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT       DATETIME2      NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_COM_ALARM PRIMARY KEY (ALARM_ID),
    CONSTRAINT FK_COM_ALARM_CLASS FOREIGN KEY (ALARM_CLASS_ID) REFERENCES COM_ALARM_CLASS (ALARM_CLASS_ID)
);
CREATE INDEX IX_COM_ALARM_CLASS_REF ON COM_ALARM (ALARM_CLASS_ID, ALARM_NAME);

-- 상태 모델.
CREATE TABLE COM_STATE_MODEL (
    MODEL_ID         NVARCHAR(50)   NOT NULL,
    MODEL_NAME       NVARCHAR(200)  NOT NULL,
    TARGET_ENTITY    NVARCHAR(100)  NULL,
    DESCRIPTION      NVARCHAR(500)  NULL,
    CREATED_BY       NVARCHAR(50)   NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT       DATETIME2      NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY       NVARCHAR(50)   NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT       DATETIME2      NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_COM_STATE_MODEL PRIMARY KEY (MODEL_ID)
);

-- 상태 코드(모델별 상태 + 전이 이벤트).
CREATE TABLE COM_STATE (
    STATE_ID         NVARCHAR(50)   NOT NULL,
    MODEL_ID         NVARCHAR(50)   NULL,
    STATE_NAME       NVARCHAR(200)  NOT NULL,
    STATE_CODE       NVARCHAR(50)   NULL,
    SORT_ORDER       INT            NULL,
    IS_INITIAL       BIT            NOT NULL DEFAULT 0,
    CREATED_BY       NVARCHAR(50)   NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT       DATETIME2      NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY       NVARCHAR(50)   NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT       DATETIME2      NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_COM_STATE PRIMARY KEY (STATE_ID),
    CONSTRAINT FK_COM_STATE_MODEL FOREIGN KEY (MODEL_ID) REFERENCES COM_STATE_MODEL (MODEL_ID)
);
CREATE INDEX IX_COM_STATE_MODEL_REF ON COM_STATE (MODEL_ID, SORT_ORDER);

-- 라벨.
CREATE TABLE COM_LABEL (
    LABEL_ID         NVARCHAR(50)   NOT NULL,
    LABEL_NAME       NVARCHAR(200)  NOT NULL,
    LABEL_TYPE       NVARCHAR(50)   NULL,
    TEMPLATE         NVARCHAR(2000) NULL,
    IS_ACTIVE        BIT            NOT NULL DEFAULT 1,
    CREATED_BY       NVARCHAR(50)   NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT       DATETIME2      NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY       NVARCHAR(50)   NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT       DATETIME2      NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_COM_LABEL PRIMARY KEY (LABEL_ID)
);

-- ID 채번 규칙.
CREATE TABLE COM_ID_RULE (
    RULE_ID          NVARCHAR(50)   NOT NULL,
    RULE_NAME        NVARCHAR(200)  NOT NULL,
    PREFIX           NVARCHAR(50)   NULL,
    SEQ_LENGTH       INT            NULL,
    CURRENT_SEQ      INT            NULL,
    RESET_CYCLE      NVARCHAR(20)   NULL,
    DESCRIPTION      NVARCHAR(500)  NULL,
    CREATED_BY       NVARCHAR(50)   NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT       DATETIME2      NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY       NVARCHAR(50)   NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT       DATETIME2      NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_COM_ID_RULE PRIMARY KEY (RULE_ID)
);
