using System.Data.Common;
using NexaOne.Infrastructure.Persistence;

namespace NexaOne.CRM.Infrastructure;

internal sealed class CrmSqliteSchemaContribution : ISqliteSchemaContribution
{
    public string Id => "CRM.CustomerEnrollment.V193";

    public void Apply(DbConnection connection, DbTransaction transaction)
    {
        ArgumentNullException.ThrowIfNull(connection);
        ArgumentNullException.ThrowIfNull(transaction);
        using var command = connection.CreateCommand();
        command.Transaction = transaction;
        command.CommandText = """
            CREATE TABLE IF NOT EXISTS CRM_PIPELINE (
                TENANT_ID TEXT NOT NULL, ORGANIZATION_ID TEXT NOT NULL, PIPELINE_ID TEXT NOT NULL,
                VERSION TEXT NOT NULL, NAME TEXT NOT NULL, DESCRIPTION TEXT NULL,
                CONSTRAINT PK_CRM_PIPELINE PRIMARY KEY (TENANT_ID,ORGANIZATION_ID,PIPELINE_ID));
            CREATE INDEX IF NOT EXISTS IX_CRM_PIPELINE_PAGE ON CRM_PIPELINE
                (TENANT_ID,ORGANIZATION_ID,NAME,PIPELINE_ID);

            CREATE TABLE IF NOT EXISTS CRM_PIPELINE_STAGE (
                TENANT_ID TEXT NOT NULL, ORGANIZATION_ID TEXT NOT NULL, STAGE_ID TEXT NOT NULL,
                PIPELINE_ID TEXT NOT NULL, NAME TEXT NOT NULL, DESCRIPTION TEXT NULL, STAGE_INDEX INTEGER NOT NULL,
                CONSTRAINT PK_CRM_PIPELINE_STAGE PRIMARY KEY (TENANT_ID,ORGANIZATION_ID,STAGE_ID),
                CONSTRAINT UQ_CRM_PIPELINE_STAGE_INDEX UNIQUE (TENANT_ID,ORGANIZATION_ID,PIPELINE_ID,STAGE_INDEX),
                CONSTRAINT FK_CRM_PIPELINE_STAGE_PIPELINE FOREIGN KEY (TENANT_ID,ORGANIZATION_ID,PIPELINE_ID)
                    REFERENCES CRM_PIPELINE (TENANT_ID,ORGANIZATION_ID,PIPELINE_ID),
                CONSTRAINT CK_CRM_PIPELINE_STAGE_INDEX CHECK (STAGE_INDEX>0));

            CREATE TABLE IF NOT EXISTS CRM_DEAL (
                TENANT_ID TEXT NOT NULL, ORGANIZATION_ID TEXT NOT NULL, DEAL_ID TEXT NOT NULL,
                VERSION TEXT NOT NULL, STAGE_ID TEXT NOT NULL, TITLE TEXT NOT NULL,
                PROBABILITY INTEGER NOT NULL, CLIENT_ID TEXT NULL, CREATED_BY TEXT NULL,
                CONSTRAINT PK_CRM_DEAL PRIMARY KEY (TENANT_ID,ORGANIZATION_ID,DEAL_ID),
                CONSTRAINT FK_CRM_DEAL_STAGE FOREIGN KEY (TENANT_ID,ORGANIZATION_ID,STAGE_ID)
                    REFERENCES CRM_PIPELINE_STAGE (TENANT_ID,ORGANIZATION_ID,STAGE_ID),
                CONSTRAINT CK_CRM_DEAL_PROBABILITY CHECK (PROBABILITY BETWEEN 0 AND 5));
            CREATE INDEX IF NOT EXISTS IX_CRM_DEAL_PAGE ON CRM_DEAL
                (TENANT_ID,ORGANIZATION_ID,STAGE_ID,DEAL_ID);
            CREATE INDEX IF NOT EXISTS IX_CRM_DEAL_CREATED ON CRM_DEAL
                (TENANT_ID,ORGANIZATION_ID,CREATED_BY,STAGE_ID,DEAL_ID);
            CREATE UNIQUE INDEX IF NOT EXISTS UQ_CRM_DEAL_CLIENT ON CRM_DEAL
                (TENANT_ID,ORGANIZATION_ID,CLIENT_ID) WHERE CLIENT_ID IS NOT NULL;

            CREATE TABLE IF NOT EXISTS CRM_DEAL_ASSIGNEE (
                TENANT_ID TEXT NOT NULL, ORGANIZATION_ID TEXT NOT NULL, DEAL_ID TEXT NOT NULL,
                EMPLOYEE_ID TEXT NOT NULL,
                CONSTRAINT PK_CRM_DEAL_ASSIGNEE PRIMARY KEY (TENANT_ID,ORGANIZATION_ID,DEAL_ID,EMPLOYEE_ID),
                CONSTRAINT FK_CRM_DEAL_ASSIGNEE_DEAL FOREIGN KEY (TENANT_ID,ORGANIZATION_ID,DEAL_ID)
                    REFERENCES CRM_DEAL (TENANT_ID,ORGANIZATION_ID,DEAL_ID));
            CREATE INDEX IF NOT EXISTS IX_CRM_DEAL_ASSIGNEE_EMPLOYEE ON CRM_DEAL_ASSIGNEE
                (TENANT_ID,ORGANIZATION_ID,EMPLOYEE_ID,DEAL_ID);

            CREATE TABLE IF NOT EXISTS CRM_AUDIT (
                TENANT_ID TEXT NOT NULL, ORGANIZATION_ID TEXT NOT NULL, CHANGE_ID TEXT NOT NULL,
                ACTOR_USER_ID TEXT NOT NULL, OPERATION TEXT NOT NULL, ENTITY_ID TEXT NOT NULL,
                PREVIOUS_VERSION TEXT NULL, VERSION TEXT NULL, RECORDED_AT_TICKS INTEGER NOT NULL,
                CONSTRAINT PK_CRM_AUDIT PRIMARY KEY (TENANT_ID,ORGANIZATION_ID,CHANGE_ID));
            CREATE INDEX IF NOT EXISTS IX_CRM_AUDIT_ENTITY ON CRM_AUDIT
                (TENANT_ID,ORGANIZATION_ID,ENTITY_ID,RECORDED_AT_TICKS,CHANGE_ID);

            CREATE TABLE IF NOT EXISTS CRM_TEAM (
                TENANT_ID TEXT NOT NULL, ORGANIZATION_ID TEXT NOT NULL, TEAM_ID TEXT NOT NULL,
                VERSION TEXT NOT NULL, CREATED_BY TEXT NOT NULL, NAME TEXT NOT NULL, TEAM_PREFIX TEXT NULL,
                IS_PUBLIC INTEGER NOT NULL, SHARE_PROFILE_VIEW INTEGER NOT NULL, REQUIRE_PLAN_TO_TRACK INTEGER NOT NULL,
                CONSTRAINT PK_CRM_TEAM PRIMARY KEY (TENANT_ID,ORGANIZATION_ID,TEAM_ID));
            CREATE INDEX IF NOT EXISTS IX_CRM_TEAM_PAGE ON CRM_TEAM
                (TENANT_ID,ORGANIZATION_ID,NAME,TEAM_ID);

            CREATE TABLE IF NOT EXISTS CRM_TEAM_MEMBER (
                TENANT_ID TEXT NOT NULL, ORGANIZATION_ID TEXT NOT NULL, TEAM_ID TEXT NOT NULL,
                EMPLOYEE_ID TEXT NOT NULL, IS_MANAGER INTEGER NOT NULL,
                CONSTRAINT PK_CRM_TEAM_MEMBER PRIMARY KEY (TENANT_ID,ORGANIZATION_ID,TEAM_ID,EMPLOYEE_ID),
                CONSTRAINT FK_CRM_TEAM_MEMBER_TEAM FOREIGN KEY (TENANT_ID,ORGANIZATION_ID,TEAM_ID)
                    REFERENCES CRM_TEAM (TENANT_ID,ORGANIZATION_ID,TEAM_ID));
            CREATE INDEX IF NOT EXISTS IX_CRM_TEAM_MEMBER_EMPLOYEE ON CRM_TEAM_MEMBER
                (TENANT_ID,ORGANIZATION_ID,EMPLOYEE_ID,TEAM_ID);

            CREATE TABLE IF NOT EXISTS CRM_PROJECT (
                TENANT_ID TEXT NOT NULL, ORGANIZATION_ID TEXT NOT NULL, PROJECT_ID TEXT NOT NULL,
                VERSION TEXT NOT NULL, CREATED_BY TEXT NOT NULL, NAME TEXT NOT NULL,
                DESCRIPTION TEXT NULL, CODE TEXT NULL, PROJECT_STATUS TEXT NOT NULL,
                START_AT_TICKS INTEGER NULL, END_AT_TICKS INTEGER NULL, IS_BILLABLE INTEGER NOT NULL,
                IS_PUBLIC INTEGER NOT NULL, BUDGET NUMERIC NULL, BUDGET_TYPE TEXT NOT NULL, CUSTOMER_ID TEXT NULL,
                CONSTRAINT PK_CRM_PROJECT PRIMARY KEY (TENANT_ID,ORGANIZATION_ID,PROJECT_ID));
            CREATE INDEX IF NOT EXISTS IX_CRM_PROJECT_PAGE ON CRM_PROJECT
                (TENANT_ID,ORGANIZATION_ID,NAME,PROJECT_ID);
            CREATE INDEX IF NOT EXISTS IX_CRM_PROJECT_CREATED ON CRM_PROJECT
                (TENANT_ID,ORGANIZATION_ID,CREATED_BY,NAME,PROJECT_ID);

            CREATE TABLE IF NOT EXISTS CRM_PROJECT_MEMBER (
                TENANT_ID TEXT NOT NULL, ORGANIZATION_ID TEXT NOT NULL, PROJECT_ID TEXT NOT NULL,
                EMPLOYEE_ID TEXT NOT NULL, IS_MANAGER INTEGER NOT NULL,
                CONSTRAINT PK_CRM_PROJECT_MEMBER PRIMARY KEY (TENANT_ID,ORGANIZATION_ID,PROJECT_ID,EMPLOYEE_ID),
                CONSTRAINT FK_CRM_PROJECT_MEMBER_PROJECT FOREIGN KEY (TENANT_ID,ORGANIZATION_ID,PROJECT_ID)
                    REFERENCES CRM_PROJECT (TENANT_ID,ORGANIZATION_ID,PROJECT_ID));
            CREATE INDEX IF NOT EXISTS IX_CRM_PROJECT_MEMBER_EMPLOYEE ON CRM_PROJECT_MEMBER
                (TENANT_ID,ORGANIZATION_ID,EMPLOYEE_ID,PROJECT_ID);

            CREATE TABLE IF NOT EXISTS CRM_PROJECT_TEAM (
                TENANT_ID TEXT NOT NULL, ORGANIZATION_ID TEXT NOT NULL, PROJECT_ID TEXT NOT NULL, TEAM_ID TEXT NOT NULL,
                CONSTRAINT PK_CRM_PROJECT_TEAM PRIMARY KEY (TENANT_ID,ORGANIZATION_ID,PROJECT_ID,TEAM_ID),
                CONSTRAINT FK_CRM_PROJECT_TEAM_PROJECT FOREIGN KEY (TENANT_ID,ORGANIZATION_ID,PROJECT_ID)
                    REFERENCES CRM_PROJECT (TENANT_ID,ORGANIZATION_ID,PROJECT_ID),
                CONSTRAINT FK_CRM_PROJECT_TEAM_TEAM FOREIGN KEY (TENANT_ID,ORGANIZATION_ID,TEAM_ID)
                    REFERENCES CRM_TEAM (TENANT_ID,ORGANIZATION_ID,TEAM_ID));
            CREATE INDEX IF NOT EXISTS IX_CRM_PROJECT_TEAM_TEAM ON CRM_PROJECT_TEAM
                (TENANT_ID,ORGANIZATION_ID,TEAM_ID,PROJECT_ID);

            CREATE TABLE IF NOT EXISTS CRM_CUSTOMER_ENROLLMENT (
                TENANT_ID TEXT NOT NULL, ORGANIZATION_ID TEXT NOT NULL, CONTACT_ID TEXT NOT NULL,
                VERSION TEXT NOT NULL, MDM_CUSTOMER_ID TEXT NOT NULL, CUSTOMER_NAME TEXT NOT NULL,
                ENROLLED_BY TEXT NOT NULL, ENROLLED_AT_TICKS INTEGER NOT NULL,
                CONSTRAINT PK_CRM_CUSTOMER_ENROLLMENT PRIMARY KEY (TENANT_ID,ORGANIZATION_ID,CONTACT_ID),
                CONSTRAINT UQ_CRM_CUSTOMER_ENROLLMENT_MDM UNIQUE (TENANT_ID,ORGANIZATION_ID,MDM_CUSTOMER_ID));
            CREATE INDEX IF NOT EXISTS IX_CRM_CUSTOMER_ENROLLMENT_PAGE ON CRM_CUSTOMER_ENROLLMENT
                (TENANT_ID,ORGANIZATION_ID,MDM_CUSTOMER_ID,CONTACT_ID);
            """;
        command.ExecuteNonQuery();
    }
}
