using System.Globalization;
using NexaFramework.Service.Erp;
using NexaOne.ServiceContracts.Erp;
using SkiaSharp;

namespace NexaOne.Server.Gateway;

internal static class BillingPdfRenderer
{
    private const float PageWidth = 595;
    private const float PageHeight = 842;
    private const float Margin = 42;

    internal static byte[] Render(BillingDocumentView view, string fontPath)
    {
        ArgumentNullException.ThrowIfNull(view);
        if (string.IsNullOrWhiteSpace(fontPath) || !File.Exists(fontPath))
            throw new InvalidOperationException("The billing PDF font is unavailable.");
        using var typeface = SKTypeface.FromFile(fontPath)
            ?? throw new InvalidOperationException("The billing PDF font cannot be loaded.");
        using var regular = new SKFont(typeface, 10);
        using var small = new SKFont(typeface, 8);
        using var heading = new SKFont(typeface, 22);
        using var bold = new SKFont(typeface, 10) { Embolden = true };
        using var ink = new SKPaint { Color = SKColors.Black, IsAntialias = true };
        using var muted = new SKPaint { Color = new SKColor(80, 88, 100), IsAntialias = true };
        using var rule = new SKPaint { Color = new SKColor(211, 216, 224), StrokeWidth = 1 };
        using var stream = new MemoryStream();
        using var pdf = SKDocument.CreatePdf(stream);

        var pageNumber = 0;
        SKCanvas? canvas = null;
        float y = 0;
        void EndPage()
        {
            if (canvas is null) return;
            Draw(canvas, $"Generated by NexaOne · Page {pageNumber}", Margin, PageHeight - 24, small, muted);
            pdf.EndPage();
            canvas = null;
        }
        void BeginPage()
        {
            EndPage();
            canvas = pdf.BeginPage(PageWidth, PageHeight);
            pageNumber++;
            y = Margin;
            Draw(canvas, DocumentTitle(view.Document.Kind), Margin, y + 20, heading, ink);
            Draw(canvas, $"No. {view.Document.Number}", PageWidth - Margin - 105, y + 18, bold, ink);
            y += 48;
            Draw(canvas, $"Customer  {view.Contact.Name}", Margin, y, bold, ink);
            y += 18;
            Draw(canvas, $"Document date  {view.Document.Input.DocumentDate:yyyy-MM-dd}", Margin, y, regular, muted);
            Draw(canvas, $"Due date  {view.Document.Input.DueDate:yyyy-MM-dd}", 300, y, regular, muted);
            y += 20;
            canvas.DrawLine(Margin, y, PageWidth - Margin, y, rule);
            y += 24;
            Draw(canvas, "Description", Margin, y, bold, ink);
            DrawRight(canvas, "Quantity", 370, y, bold, ink);
            DrawRight(canvas, "Unit price", 468, y, bold, ink);
            DrawRight(canvas, "Amount", PageWidth - Margin, y, bold, ink);
            y += 12;
            canvas.DrawLine(Margin, y, PageWidth - Margin, y, rule);
            y += 18;
        }

        BeginPage();
        foreach (var line in view.Document.Input.Lines)
        {
            var wrapped = Wrap(line.Description, regular, 255);
            var rowHeight = Math.Max(22, wrapped.Count * 14 + 8);
            if (y + rowHeight > PageHeight - 150) BeginPage();
            for (var index = 0; index < wrapped.Count; index++)
                Draw(canvas!, wrapped[index], Margin, y + index * 14, regular, ink);
            DrawRight(canvas!, Amount(line.Quantity), 370, y, regular, ink);
            DrawRight(canvas!, Amount(line.UnitPrice), 468, y, regular, ink);
            DrawRight(canvas!, Amount(line.LineTotal), PageWidth - Margin, y, regular, ink);
            y += rowHeight;
            canvas!.DrawLine(Margin, y - 8, PageWidth - Margin, y - 8, rule);
        }

        if (y + 145 > PageHeight - Margin) BeginPage();
        y += 4;
        TotalRow(canvas!, "Subtotal", view.Document.Totals.Subtotal, ref y, regular, ink);
        if (view.Document.Totals.DiscountAmount != 0)
            TotalRow(canvas!, "Discount", -view.Document.Totals.DiscountAmount, ref y, regular, ink);
        if (view.Document.Totals.TaxAmount != 0)
            TotalRow(canvas!, "Tax", view.Document.Totals.TaxAmount, ref y, regular, ink);
        TotalRow(canvas!, $"Total ({view.Document.Input.Currency})", view.Document.Totals.Total,
            ref y, bold, ink);
        TotalRow(canvas!, "Paid", view.Document.Paid, ref y, regular, ink);
        if (view.Document.Credited != 0)
            TotalRow(canvas!, "Credited", view.Document.Credited, ref y, regular, ink);
        TotalRow(canvas!, "Balance due", view.Document.Due, ref y, bold, ink);
        if (!string.IsNullOrWhiteSpace(view.Document.Input.Terms))
        {
            y += 16; Draw(canvas!, "Terms", Margin, y, bold, ink); y += 16;
            foreach (var text in Wrap(view.Document.Input.Terms!, small, PageWidth - Margin * 2))
            { Draw(canvas!, text, Margin, y, small, muted); y += 12; }
        }
        if (!string.IsNullOrWhiteSpace(view.Document.Input.Note))
        {
            y += 10; Draw(canvas!, "Note", Margin, y, bold, ink); y += 16;
            foreach (var text in Wrap(view.Document.Input.Note!, small, PageWidth - Margin * 2))
            { Draw(canvas!, text, Margin, y, small, muted); y += 12; }
        }
        EndPage();
        pdf.Close();
        return stream.ToArray();
    }

    private static string DocumentTitle(BillingKind kind) => kind switch
    {
        BillingKind.Estimate => "ESTIMATE",
        BillingKind.Invoice => "INVOICE",
        BillingKind.CreditNote => "CREDIT NOTE",
        _ => throw new InvalidDataException("Unsupported billing document kind.")
    };

    private static string Amount(decimal value) => value.ToString("#,##0.00######", CultureInfo.InvariantCulture);

    private static void TotalRow(SKCanvas canvas, string label, decimal amount, ref float y,
        SKFont font, SKPaint paint)
    {
        Draw(canvas, label, 330, y, font, paint);
        DrawRight(canvas, Amount(amount), PageWidth - Margin, y, font, paint);
        y += 18;
    }

    private static IReadOnlyList<string> Wrap(string text, SKFont font, float width)
    {
        var result = new List<string>();
        var current = "";
        foreach (var element in StringInfo.GetTextElementEnumerator(text).AsEnumerable())
        {
            var candidate = current + element;
            if (current.Length > 0 && font.MeasureText(candidate) > width)
            { result.Add(current); current = element; }
            else current = candidate;
        }
        if (current.Length > 0) result.Add(current);
        return result.Count == 0 ? [""] : result;
    }

    private static void Draw(SKCanvas canvas, string text, float x, float y, SKFont font, SKPaint paint)
        => canvas.DrawText(text, x, y, SKTextAlign.Left, font, paint);

    private static void DrawRight(SKCanvas canvas, string text, float x, float y, SKFont font, SKPaint paint)
        => canvas.DrawText(text, x, y, SKTextAlign.Right, font, paint);

    private static IEnumerable<string> AsEnumerable(this TextElementEnumerator enumerator)
    {
        while (enumerator.MoveNext()) yield return enumerator.GetTextElement();
    }
}
