-- SYS Module: User Management
CREATE TABLE SYS_USER (
    USER_ID         NVARCHAR(50)    NOT NULL,
    USER_NAME       NVARCHAR(100)   NOT NULL,
    PASSWORD_HASH   NVARCHAR(64)    NOT NULL,
    EMAIL           NVARCHAR(200)   NOT NULL,
    ROLE_ID         NVARCHAR(50)    NOT NULL,
    LANGUAGE        NVARCHAR(10)    NOT NULL DEFAULT 'KoKr',
    IS_ACTIVE       BIT             NOT NULL DEFAULT 1,
    IS_DELETED      BIT             NOT NULL DEFAULT 0,
    DELETED_AT      DATETIME2       NULL,
    LAST_LOGIN_AT   DATETIME2       NULL,
    CREATED_BY      NVARCHAR(50)    NOT NULL,
    CREATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY      NVARCHAR(50)    NOT NULL,
    UPDATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_SYS_USER PRIMARY KEY (USER_ID)
);

-- Default admin user (password: admin, SHA-256 lowercase hex)
INSERT INTO SYS_USER
    (USER_ID, USER_NAME, PASSWORD_HASH, EMAIL, ROLE_ID, LANGUAGE, IS_ACTIVE, IS_DELETED,
     CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT)
VALUES
    ('admin', 'Administrator',
     '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918',
     'admin@nexaone.local', 'ADMIN', 'KoKr', 1, 0,
     'SYSTEM', GETUTCDATE(), 'SYSTEM', GETUTCDATE());
