-- MDM Module: Master Data Management
CREATE TABLE MDM_EQUIPMENT (
    EQUIPMENT_ID            NVARCHAR(50)    NOT NULL,
    EQUIPMENT_NAME          NVARCHAR(200)   NOT NULL,
    DESCRIPTION             NVARCHAR(500)   NULL,
    PLANT_ID                NVARCHAR(50)    NOT NULL,
    AREA_ID                 NVARCHAR(50)    NOT NULL,
    EQUIPMENT_TYPE          NVARCHAR(50)    NOT NULL,
    PARENT_EQUIPMENT_ID     NVARCHAR(50)    NULL,
    VENDOR                  NVARCHAR(100)   NULL,
    MODEL                   NVARCHAR(100)   NULL,
    EQUIPMENT_CLASS_ID      NVARCHAR(50)    NOT NULL,
    VALID_STATE             NVARCHAR(20)    NOT NULL DEFAULT 'Active',
    CREATED_BY              NVARCHAR(50)    NOT NULL,
    CREATED_AT              DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY              NVARCHAR(50)    NOT NULL,
    UPDATED_AT              DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_MDM_EQUIPMENT PRIMARY KEY (EQUIPMENT_ID),
    CONSTRAINT FK_MDM_EQUIPMENT_PARENT FOREIGN KEY (PARENT_EQUIPMENT_ID)
        REFERENCES MDM_EQUIPMENT (EQUIPMENT_ID)
);

CREATE INDEX IX_MDM_EQUIPMENT_PLANT ON MDM_EQUIPMENT (PLANT_ID, VALID_STATE);
CREATE INDEX IX_MDM_EQUIPMENT_CLASS ON MDM_EQUIPMENT (EQUIPMENT_CLASS_ID);
