-- FDC Module: Fault Detection and Classification
CREATE TABLE FDC_INTERLOCK_RULE (
    RULE_ID         NVARCHAR(50)    NOT NULL,
    RULE_NAME       NVARCHAR(200)   NOT NULL,
    EQUIPMENT_ID    NVARCHAR(50)    NOT NULL,
    PARAMETER_ID    NVARCHAR(50)    NOT NULL,
    OPERATOR        NVARCHAR(10)    NOT NULL,
    THRESHOLD_VALUE DECIMAL(18,6)   NOT NULL,
    ACTION          NVARCHAR(200)   NOT NULL,
    PRIORITY        INT             NOT NULL DEFAULT 0,
    IS_ACTIVE       BIT             NOT NULL DEFAULT 1,
    CREATED_BY      NVARCHAR(50)    NOT NULL,
    CREATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY      NVARCHAR(50)    NOT NULL,
    UPDATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_FDC_INTERLOCK_RULE PRIMARY KEY (RULE_ID),
    CONSTRAINT FK_FDC_RULE_EQUIPMENT FOREIGN KEY (EQUIPMENT_ID)
        REFERENCES MDM_EQUIPMENT (EQUIPMENT_ID)
);

CREATE INDEX IX_FDC_RULE_EQUIPMENT ON FDC_INTERLOCK_RULE (EQUIPMENT_ID, IS_ACTIVE);
CREATE INDEX IX_FDC_RULE_PRIORITY  ON FDC_INTERLOCK_RULE (PRIORITY DESC, IS_ACTIVE);
