-- RMS Module: Recipe Management System
CREATE TABLE RMS_RECIPE (
    RECIPE_ID           NVARCHAR(50)    NOT NULL,
    RECIPE_NAME         NVARCHAR(200)   NOT NULL,
    DESCRIPTION         NVARCHAR(500)   NULL,
    EQUIPMENT_CLASS_ID  NVARCHAR(50)    NOT NULL,
    VERSION             INT             NOT NULL DEFAULT 1,
    APPROVAL_STATE      NVARCHAR(20)    NOT NULL DEFAULT 'Draft',
    FIRST_APPROVER_ID   NVARCHAR(50)    NULL,
    SECOND_APPROVER_ID  NVARCHAR(50)    NULL,
    RELEASED_AT         DATETIME2       NULL,
    CREATED_BY          NVARCHAR(50)    NOT NULL,
    CREATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY          NVARCHAR(50)    NOT NULL,
    UPDATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_RMS_RECIPE PRIMARY KEY (RECIPE_ID),
    CONSTRAINT FK_RMS_RECIPE_FIRST_APPROVER  FOREIGN KEY (FIRST_APPROVER_ID)  REFERENCES SYS_USER (USER_ID),
    CONSTRAINT FK_RMS_RECIPE_SECOND_APPROVER FOREIGN KEY (SECOND_APPROVER_ID) REFERENCES SYS_USER (USER_ID)
);

CREATE INDEX IX_RMS_RECIPE_CLASS ON RMS_RECIPE (EQUIPMENT_CLASS_ID, APPROVAL_STATE);
