-- PPM Module: Lot TrackIn/TrackOut 생산 추적 (설계서 19.4)
-- 설계 표준명 STD_TB_LOT_HISTORY/STD_TB_LOT_MIXING_RELATION은
-- 기존 마이그레이션의 모듈 접두사 규칙(POM_*)에 맞춰 POM_LOT_HISTORY/POM_LOT_MIXING_RELATION으로 적응.
CREATE TABLE POM_LOT (
    LOT_ID              NVARCHAR(50)    NOT NULL,
    PLANT_ID            NVARCHAR(50)    NOT NULL,
    WORK_ORDER_ID       NVARCHAR(50)    NULL,           -- POM_WORK_ORDER.WORK_ORDER_ID (Mixing output may be NULL)
    PRODUCT_ID          NVARCHAR(50)    NOT NULL,
    QTY                 DECIMAL(18,4)   NOT NULL,
    DEFECT_QTY          DECIMAL(18,4)   NOT NULL DEFAULT 0,
    LOT_STATE           NVARCHAR(20)    NOT NULL DEFAULT 'Created',  -- Created/Queued/Processing/Completed/Consumed
    PROCESS_STATE       NVARCHAR(20)    NOT NULL DEFAULT 'Idle',     -- Idle/Run
    ROUTE_STEPS         NVARCHAR(500)   NOT NULL,       -- '>' 구분 공정 순서 (현행 ProcessPathStack 적응)
    CURRENT_STEP        INT             NOT NULL DEFAULT 0,
    EQUIPMENT_ID        NVARCHAR(50)    NULL,           -- TrackIn 중에만 점유, TrackOut 시 반납(NULL)
    RECIPE_DEF_ID       NVARCHAR(50)    NULL,
    RECIPE_DEF_VERSION  INT             NULL,
    CARRIER_ID          NVARCHAR(50)    NULL,
    IS_HOLD             CHAR(1)         NOT NULL DEFAULT 'N',
    TRACK_IN_USER       NVARCHAR(50)    NULL,
    TRACK_IN_TIME       DATETIME2       NULL,
    TRACK_OUT_USER      NVARCHAR(50)    NULL,
    TRACK_OUT_TIME      DATETIME2       NULL,
    CREATED_BY          NVARCHAR(50)    NOT NULL,
    CREATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY          NVARCHAR(50)    NULL,
    UPDATED_AT          DATETIME2       NULL,
    CONSTRAINT PK_POM_LOT PRIMARY KEY (LOT_ID)
);

CREATE INDEX IX_POM_LOT_PLANT ON POM_LOT (PLANT_ID, LOT_STATE);
CREATE INDEX IX_POM_LOT_WO    ON POM_LOT (WORK_ORDER_ID) WHERE WORK_ORDER_ID IS NOT NULL;

CREATE TABLE POM_LOT_HISTORY (
    LOT_HISTORY_ID      BIGINT IDENTITY(1,1) NOT NULL,
    PLANT_ID            NVARCHAR(50)    NOT NULL,
    LOT_ID              NVARCHAR(50)    NOT NULL,
    EQUIPMENT_ID        NVARCHAR(50)    NULL,
    PROCESS_ID          NVARCHAR(50)    NOT NULL,
    RECIPE_DEF_ID       NVARCHAR(50)    NULL,
    RECIPE_DEF_VERSION  INT             NULL,
    TRACK_IN_TIME       DATETIME2       NULL,
    TRACK_OUT_TIME      DATETIME2       NULL,
    EXECUTION_ID        NVARCHAR(20)    NOT NULL,       -- TrackIn/TrackOut/Finish/Consume
    EXECUTION_USER      NVARCHAR(50)    NOT NULL,
    QTY                 DECIMAL(18,4)   NOT NULL,
    DEFECT_QTY          DECIMAL(18,4)   NOT NULL DEFAULT 0,
    LOT_STATE           NVARCHAR(20)    NOT NULL,       -- 처리 후 Lot 상태
    PROCESS_STATE       NVARCHAR(20)    NOT NULL,       -- 처리 후 Process 상태
    CREATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_POM_LOT_HISTORY PRIMARY KEY (LOT_HISTORY_ID)
);

-- 설계 19.4.6 조회 인덱스 3종
CREATE INDEX IX_POM_LOT_HISTORY_LOT  ON POM_LOT_HISTORY (PLANT_ID, LOT_ID, TRACK_IN_TIME);
CREATE INDEX IX_POM_LOT_HISTORY_EQP  ON POM_LOT_HISTORY (PLANT_ID, EQUIPMENT_ID, TRACK_IN_TIME, TRACK_OUT_TIME);
CREATE INDEX IX_POM_LOT_HISTORY_PROC ON POM_LOT_HISTORY (PLANT_ID, PROCESS_ID, TRACK_IN_TIME);

CREATE TABLE POM_LOT_MIXING_RELATION (
    PLANT_ID            NVARCHAR(50)    NOT NULL,
    OUTPUT_LOT_ID       NVARCHAR(50)    NOT NULL,
    INPUT_LOT_ID        NVARCHAR(50)    NOT NULL,
    INPUT_QTY           DECIMAL(18,4)   NOT NULL,
    MIXING_RATE         DECIMAL(9,4)    NULL,           -- 출력 수량 대비 투입 비율
    CONSUMED_AT         DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSUMED_BY         NVARCHAR(50)    NOT NULL,
    CONSTRAINT PK_POM_LOT_MIXING_RELATION PRIMARY KEY (PLANT_ID, OUTPUT_LOT_ID, INPUT_LOT_ID)
);

CREATE INDEX IX_POM_LOT_MIXING_INPUT ON POM_LOT_MIXING_RELATION (PLANT_ID, INPUT_LOT_ID);
