-- FDC Module: collection parameter master (design 10.4.1)
-- 컬럼은 FdcParameterRepository / FdcParameter 도메인과 1:1 정합. 기존 리포지토리가
-- FDC_PARAMETER를 참조하나 마이그레이션이 누락되어 있던 갭을 보완한다.
CREATE TABLE FDC_PARAMETER (
    PARAMETER_ID          NVARCHAR(50)    NOT NULL,
    PARAMETER_NAME        NVARCHAR(200)   NOT NULL,
    EQUIPMENT_ID          NVARCHAR(50)    NOT NULL,
    GROUP_ID              NVARCHAR(50)    NULL,
    UNIT                  NVARCHAR(50)    NOT NULL,
    LOWER_LIMIT           DECIMAL(18,6)   NOT NULL,
    UPPER_LIMIT           DECIMAL(18,6)   NOT NULL,
    LOWER_CONTROL_LIMIT   DECIMAL(18,6)   NULL,
    UPPER_CONTROL_LIMIT   DECIMAL(18,6)   NULL,
    SAMPLING_INTERVAL_MS  INT             NOT NULL DEFAULT 1000,
    IS_ACTIVE             BIT             NOT NULL DEFAULT 1,
    CREATED_BY            NVARCHAR(50)    NOT NULL,
    CREATED_AT            DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY            NVARCHAR(50)    NOT NULL,
    UPDATED_AT            DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_FDC_PARAMETER PRIMARY KEY (PARAMETER_ID),
    CONSTRAINT FK_FDC_PARAM_EQUIPMENT FOREIGN KEY (EQUIPMENT_ID)
        REFERENCES MDM_EQUIPMENT (EQUIPMENT_ID)
);

CREATE INDEX IX_FDC_PARAM_EQUIPMENT ON FDC_PARAMETER (EQUIPMENT_ID, IS_ACTIVE);
