-- FDC Module: collected time-series data (design 10.4.1)
-- 컬럼은 FdcCollectDataRepository / FdcCollectData 도메인과 1:1 정합. 수집 데이터는
-- 트랜잭션 시계열이므로 감사 필드 없이 수집 시점(COLLECTED_AT)만 둔다.
CREATE TABLE FDC_COLLECT_DATA (
    COLLECT_ID    NVARCHAR(50)    NOT NULL,
    EQUIPMENT_ID  NVARCHAR(50)    NOT NULL,
    PARAMETER_ID  NVARCHAR(50)    NOT NULL,
    VALUE         DECIMAL(18,6)   NOT NULL,
    COLLECTED_AT  DATETIME2       NOT NULL,
    QUALITY       NVARCHAR(20)    NOT NULL DEFAULT 'Good',
    LOWER_LIMIT   DECIMAL(18,6)   NOT NULL,
    UPPER_LIMIT   DECIMAL(18,6)   NOT NULL,
    CONSTRAINT PK_FDC_COLLECT_DATA PRIMARY KEY (COLLECT_ID),
    CONSTRAINT FK_FDC_DATA_PARAMETER FOREIGN KEY (PARAMETER_ID)
        REFERENCES FDC_PARAMETER (PARAMETER_ID)
);

CREATE INDEX IX_FDC_DATA_PARAM_TIME ON FDC_COLLECT_DATA (PARAMETER_ID, COLLECTED_AT DESC);
CREATE INDEX IX_FDC_DATA_EQUIP_TIME ON FDC_COLLECT_DATA (EQUIPMENT_ID, COLLECTED_AT DESC);
