-- FDC Module: interlock trigger/resolve history (design 10.4.1 / 10.4.2)
-- 인터락 규칙 발동 시 1행 기록(TRIGGERED_AT). 해제 시 RESOLVED_AT/IS_RESOLVED 갱신.
CREATE TABLE FDC_INTERLOCK_HISTORY (
    HISTORY_ID     NVARCHAR(50)    NOT NULL,
    RULE_ID        NVARCHAR(50)    NOT NULL,
    EQUIPMENT_ID   NVARCHAR(50)    NOT NULL,
    PARAMETER_ID   NVARCHAR(50)    NOT NULL,
    TRIGGER_VALUE  DECIMAL(18,6)   NOT NULL,
    ACTION         NVARCHAR(200)   NOT NULL,
    MESSAGE        NVARCHAR(500)   NOT NULL,
    TRIGGERED_AT   DATETIME2       NOT NULL,
    RESOLVED_AT    DATETIME2       NULL,
    IS_RESOLVED    BIT             NOT NULL DEFAULT 0,
    CREATED_BY     NVARCHAR(50)    NOT NULL,
    CREATED_AT     DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY     NVARCHAR(50)    NOT NULL,
    UPDATED_AT     DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_FDC_INTERLOCK_HISTORY PRIMARY KEY (HISTORY_ID),
    CONSTRAINT FK_FDC_HIST_RULE FOREIGN KEY (RULE_ID)
        REFERENCES FDC_INTERLOCK_RULE (RULE_ID)
);

CREATE INDEX IX_FDC_HIST_EQUIP_TIME ON FDC_INTERLOCK_HISTORY (EQUIPMENT_ID, TRIGGERED_AT DESC);
CREATE INDEX IX_FDC_HIST_UNRESOLVED ON FDC_INTERLOCK_HISTORY (IS_RESOLVED, TRIGGERED_AT DESC);
