-- FDC Module: equipment-to-protocol-endpoint mapping (design 10.4.2)
-- 설비를 NexusLogic 설비 프로토콜 엔드포인트(OPC-UA 등)에 매핑한다. 통신 관심사는
-- 마스터(MDM_EQUIPMENT)와 분리하여 FDC bounded context가 소유한다. 한 설비에 복수 엔드포인트 가능.
CREATE TABLE FDC_EQUIPMENT_ENDPOINT (
    ENDPOINT_ID           NVARCHAR(50)    NOT NULL,
    EQUIPMENT_ID          NVARCHAR(50)    NOT NULL,
    PROTOCOL              NVARCHAR(20)    NOT NULL,   -- OpcUa / ModbusTcp / SiemensS7 / MitsubishiMc / EtherNetIp / OmronFins
    ENDPOINT_URL          NVARCHAR(500)   NOT NULL,   -- 예: opc.tcp://host:4840
    SAMPLING_INTERVAL_MS  INT             NOT NULL DEFAULT 1000,
    IS_ACTIVE             BIT             NOT NULL DEFAULT 1,
    CREATED_BY            NVARCHAR(50)    NOT NULL,
    CREATED_AT            DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY            NVARCHAR(50)    NOT NULL,
    UPDATED_AT            DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_FDC_EQUIPMENT_ENDPOINT PRIMARY KEY (ENDPOINT_ID),
    CONSTRAINT FK_FDC_ENDPOINT_EQUIPMENT FOREIGN KEY (EQUIPMENT_ID)
        REFERENCES MDM_EQUIPMENT (EQUIPMENT_ID)
);

CREATE INDEX IX_FDC_ENDPOINT_EQUIPMENT ON FDC_EQUIPMENT_ENDPOINT (EQUIPMENT_ID, IS_ACTIVE);
CREATE INDEX IX_FDC_ENDPOINT_ACTIVE    ON FDC_EQUIPMENT_ENDPOINT (IS_ACTIVE);
