-- FDC Module: threshold-based alarm configuration (design 10.4.1)
-- 인터락(안전 제어/정지)과 별개로, 파라미터별 임계치 경고(Warning/Critical)를 설정한다.
-- 알람은 정지하지 않고 알림만 발생시킨다.
CREATE TABLE FDC_ALARM_CONFIG (
    ALARM_CONFIG_ID  NVARCHAR(50)    NOT NULL,
    EQUIPMENT_ID     NVARCHAR(50)    NOT NULL,
    PARAMETER_ID     NVARCHAR(50)    NOT NULL,
    ALARM_LEVEL      NVARCHAR(20)    NOT NULL,   -- Warning / Critical
    OPERATOR         NVARCHAR(10)    NOT NULL,   -- GT / LT / GTE / LTE / EQ
    THRESHOLD_VALUE  DECIMAL(18,6)   NOT NULL,
    IS_ACTIVE        BIT             NOT NULL DEFAULT 1,
    CREATED_BY       NVARCHAR(50)    NOT NULL,
    CREATED_AT       DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY       NVARCHAR(50)    NOT NULL,
    UPDATED_AT       DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_FDC_ALARM_CONFIG PRIMARY KEY (ALARM_CONFIG_ID),
    CONSTRAINT FK_FDC_ALARM_CFG_EQUIPMENT FOREIGN KEY (EQUIPMENT_ID)
        REFERENCES MDM_EQUIPMENT (EQUIPMENT_ID)
);

CREATE INDEX IX_FDC_ALARM_CFG_PARAM ON FDC_ALARM_CONFIG (EQUIPMENT_ID, PARAMETER_ID, IS_ACTIVE);
