-- EST Module: Equipment State Tracking (현재 상태 / 상태 변경 이력 / 상태 전이 매트릭스)
-- 기존 갭 보강 — V003은 EST_EQUIPMENT_ALARM만 생성했고 설비 상태 추적 3개 테이블이 누락되어
-- 설비상태 기능(EquipmentStateService/Repository)이 MSSQL/SQLite 양쪽에서 동작하지 못했다.
-- 컬럼/타입/널 허용은 리포지토리 쿼리(EquipmentStateRepository/EquipmentStateMatrixRepository)와 1:1 정합.
-- 감사 컬럼(CREATED_BY 등)은 이 세 테이블의 리포지토리 SQL이 참조하지 않으므로 두지 않는다.

-- 설비 현재 상태 — UpsertAsync(ON CONFLICT/MERGE)가 EQUIPMENT_ID(PK) 기준으로 5개 컬럼을 갱신한다.
CREATE TABLE EST_EQUIPMENT_STATE (
    EQUIPMENT_ID        NVARCHAR(50)    NOT NULL,
    PLANT_ID            NVARCHAR(50)    NOT NULL,
    CURRENT_STATE_ID    NVARCHAR(50)    NOT NULL,
    STATE_CHANGED_AT    DATETIME2       NOT NULL,
    STATE_VERSION       INT             NOT NULL DEFAULT 1,
    CONSTRAINT PK_EST_EQUIPMENT_STATE PRIMARY KEY (EQUIPMENT_ID),
    CONSTRAINT FK_EST_STATE_EQUIPMENT FOREIGN KEY (EQUIPMENT_ID)
        REFERENCES MDM_EQUIPMENT (EQUIPMENT_ID)
);

CREATE INDEX IX_EST_STATE_PLANT ON EST_EQUIPMENT_STATE (PLANT_ID, EQUIPMENT_ID);

-- 상태 변경 이력 — 상태 변경과 동일 트랜잭션으로 1행 기록(ChangeStateWithHistoryAsync, 원자성).
-- HIST_ID = "{equipmentId}_{yyyyMMddHHmmssfff}" 형식이라 EQUIPMENT_ID(<=50) + 구분자 + 17자리를 수용해 100으로 둔다.
CREATE TABLE EST_EQUIPMENT_STATE_HISTORY (
    HIST_ID         NVARCHAR(100)   NOT NULL,
    EQUIPMENT_ID    NVARCHAR(50)    NOT NULL,
    FROM_STATE      NVARCHAR(50)    NOT NULL,
    TO_STATE        NVARCHAR(50)    NOT NULL,
    SET_STATE       NVARCHAR(50)    NOT NULL,
    CHANGED_AT      DATETIME2       NOT NULL,
    CHANGED_BY      NVARCHAR(50)    NOT NULL,
    REASON          NVARCHAR(500)   NULL,
    SOURCE_TYPE     NVARCHAR(20)    NOT NULL,
    TXN_HIST_KEY    NVARCHAR(100)   NULL,
    CONSTRAINT PK_EST_EQUIPMENT_STATE_HISTORY PRIMARY KEY (HIST_ID),
    CONSTRAINT FK_EST_HIST_EQUIPMENT FOREIGN KEY (EQUIPMENT_ID)
        REFERENCES MDM_EQUIPMENT (EQUIPMENT_ID)
);

CREATE INDEX IX_EST_STATE_HIST_EQUIPMENT ON EST_EQUIPMENT_STATE_HISTORY (EQUIPMENT_ID, CHANGED_AT DESC);

-- 상태 전이 매트릭스(플랜트별 전이 허용/조건) — PLANT_ID+FROM+TO 복합 PK.
-- ALLOW_FLAG/REQUIRE_REASON는 'Y'/'N', VALID_STATE는 'Valid'/'Invalid' 문자열로 저장한다(리포지토리 비교 기준).
CREATE TABLE EST_STATE_MATRIX (
    PLANT_ID        NVARCHAR(50)    NOT NULL,
    FROM_STATE_ID   NVARCHAR(50)    NOT NULL,
    TO_STATE_ID     NVARCHAR(50)    NOT NULL,
    ALLOW_FLAG      NVARCHAR(1)     NOT NULL DEFAULT 'N',
    SET_STATE_ID    NVARCHAR(50)    NULL,
    REQUIRE_REASON  NVARCHAR(1)     NOT NULL DEFAULT 'N',
    VALID_STATE     NVARCHAR(20)    NOT NULL DEFAULT 'Valid',
    CONSTRAINT PK_EST_STATE_MATRIX PRIMARY KEY (PLANT_ID, FROM_STATE_ID, TO_STATE_ID)
);
