-- MDM Module: Master Data (공장/구역/제품/코드클래스/코드)
-- 기존 갭 보강 — V002는 MDM_EQUIPMENT만 생성했고, MdmMasterService가 사용하는
-- 공장(Plant)/구역(Area)/제품(Product)/코드클래스(CodeClass)/코드(Code) 5개 마스터 테이블이
-- db/migrations에 누락되어 신규 DB에서 plants/areas/products/code-classes/codes 기능이 동작하지 못했다.
-- 컬럼/타입/널 허용은 리포지토리 SQL(PlantRepository/AreaRepository/ProductRepository/CodeRepository)과 1:1 정합.
-- 모든 리포지토리가 ServiceObjectProcessor.InsertAsync/UpdateAsync를 사용하므로 감사 컬럼
-- (CREATED_BY/CREATED_AT/UPDATED_BY/UPDATED_AT)을 V002 컨벤션대로 포함한다.
-- 부모-자식 순서: MDM_PLANT → MDM_AREA(FK PLANT_ID), MDM_CODE_CLASS → MDM_CODE(FK CODE_CLASS_ID).

-- 공장 — PlantRepository: SELECT * WHERE PLANT_ID, INSERT(PLANT_ID, PLANT_NAME, DESCRIPTION, COUNTRY, TIME_ZONE).
CREATE TABLE MDM_PLANT (
    PLANT_ID                NVARCHAR(50)    NOT NULL,
    PLANT_NAME              NVARCHAR(200)   NOT NULL,
    DESCRIPTION             NVARCHAR(500)   NULL,
    COUNTRY                 NVARCHAR(100)   NULL,
    TIME_ZONE               NVARCHAR(100)   NULL,
    CREATED_BY              NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT              DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY              NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT              DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_MDM_PLANT PRIMARY KEY (PLANT_ID)
);

CREATE INDEX IX_MDM_PLANT_NAME ON MDM_PLANT (PLANT_NAME);

-- 구역 — AreaRepository: SELECT * WHERE AREA_ID / WHERE PLANT_ID, INSERT(AREA_ID, AREA_NAME, DESCRIPTION, PLANT_ID).
CREATE TABLE MDM_AREA (
    AREA_ID                 NVARCHAR(50)    NOT NULL,
    AREA_NAME               NVARCHAR(200)   NOT NULL,
    DESCRIPTION             NVARCHAR(500)   NULL,
    PLANT_ID                NVARCHAR(50)    NOT NULL,
    CREATED_BY              NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT              DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY              NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT              DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_MDM_AREA PRIMARY KEY (AREA_ID),
    CONSTRAINT FK_MDM_AREA_PLANT FOREIGN KEY (PLANT_ID)
        REFERENCES MDM_PLANT (PLANT_ID)
);

CREATE INDEX IX_MDM_AREA_PLANT ON MDM_AREA (PLANT_ID, AREA_NAME);

-- 제품 — ProductRepository: SELECT * WHERE PRODUCT_ID / WHERE VALID_STATE = 'Valid',
--        INSERT(PRODUCT_ID, PRODUCT_NAME, DESCRIPTION, PRODUCT_TYPE, UNIT, VALID_STATE).
CREATE TABLE MDM_PRODUCT (
    PRODUCT_ID              NVARCHAR(50)    NOT NULL,
    PRODUCT_NAME            NVARCHAR(200)   NOT NULL,
    DESCRIPTION             NVARCHAR(500)   NULL,
    PRODUCT_TYPE            NVARCHAR(50)    NOT NULL,
    UNIT                    NVARCHAR(50)    NOT NULL,
    VALID_STATE             NVARCHAR(20)    NOT NULL DEFAULT 'Valid',
    CREATED_BY              NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT              DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY              NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT              DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_MDM_PRODUCT PRIMARY KEY (PRODUCT_ID)
);

CREATE INDEX IX_MDM_PRODUCT_VALID ON MDM_PRODUCT (VALID_STATE, PRODUCT_NAME);

-- 코드 클래스 — CodeRepository: SELECT * WHERE CODE_CLASS_ID / ORDER BY CODE_CLASS_NAME,
--               INSERT(CODE_CLASS_ID, CODE_CLASS_NAME, DESCRIPTION).
CREATE TABLE MDM_CODE_CLASS (
    CODE_CLASS_ID           NVARCHAR(50)    NOT NULL,
    CODE_CLASS_NAME         NVARCHAR(200)   NOT NULL,
    DESCRIPTION             NVARCHAR(500)   NULL,
    CREATED_BY              NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT              DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY              NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT              DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_MDM_CODE_CLASS PRIMARY KEY (CODE_CLASS_ID)
);

CREATE INDEX IX_MDM_CODE_CLASS_NAME ON MDM_CODE_CLASS (CODE_CLASS_NAME);

-- 코드 — CodeRepository: SELECT * WHERE CODE_CLASS_ID AND VALID_STATE = 'Valid' ORDER BY SORT_ORDER, CODE_NAME,
--        INSERT(CODE_ID, CODE_CLASS_ID, CODE_NAME, SORT_ORDER, VALID_STATE).
CREATE TABLE MDM_CODE (
    CODE_ID                 NVARCHAR(50)    NOT NULL,
    CODE_CLASS_ID           NVARCHAR(50)    NOT NULL,
    CODE_NAME               NVARCHAR(200)   NOT NULL,
    SORT_ORDER              INT             NOT NULL DEFAULT 0,
    VALID_STATE             NVARCHAR(20)    NOT NULL DEFAULT 'Valid',
    CREATED_BY              NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT              DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY              NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT              DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_MDM_CODE PRIMARY KEY (CODE_ID),
    CONSTRAINT FK_MDM_CODE_CLASS FOREIGN KEY (CODE_CLASS_ID)
        REFERENCES MDM_CODE_CLASS (CODE_CLASS_ID)
);

CREATE INDEX IX_MDM_CODE_CLASS ON MDM_CODE (CODE_CLASS_ID, VALID_STATE, SORT_ORDER);
