-- 통합 호스트 Phase 3b — 리프레시 토큰 영속(게이트웨이식 인증) + PASSWORD_HASH 폭 확장.
-- SYS_REFRESH_TOKEN: 평문 토큰을 저장하지 않고 SHA-256 해시(TOKEN_HASH)만 저장한다.
CREATE TABLE SYS_REFRESH_TOKEN (
    TOKEN_ID    NVARCHAR(50)    NOT NULL,
    USER_ID     NVARCHAR(50)    NOT NULL,
    TOKEN_HASH  NVARCHAR(100)   NOT NULL,
    EXPIRES_AT  DATETIME2       NOT NULL,
    REVOKED_AT  DATETIME2       NULL,
    CREATED_AT  DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_SYS_REFRESH_TOKEN PRIMARY KEY (TOKEN_ID)
);

CREATE INDEX IX_SYS_REFRESH_TOKEN_LOOKUP ON SYS_REFRESH_TOKEN (USER_ID, TOKEN_HASH);

-- PBKDF2 강화 해시 문자열(약 83자)이 기존 NVARCHAR(64)를 초과해 MSSQL에서 rehash 쓰기가 throw하므로
-- rehash-on-login 활성 전 선행 확장한다(SQLite는 길이 무개념이라 가려진 MSSQL 실버그).
ALTER TABLE SYS_USER ALTER COLUMN PASSWORD_HASH NVARCHAR(255) NOT NULL;
