-- MDM Module: 마스터 데이터 보강(분류/공정/프로세스/라우팅/BOM/Qtime).
-- SmartUX MDM 메뉴의 잔여 업무화면(설비 그룹·품목 그룹·캐리어(그룹)·공정(그룹)·프로세스(그룹)·
-- 라우팅·BOM·Qtime(액션))이 새 시스템에서 "no such table"로 막혀 있어, 화면 점등의 백엔드로 12개
-- 마스터 테이블을 신설한다. 컬럼/감사/제약은 V026__MDM_MASTER 스타일과 정합(NVARCHAR/ DATETIME2/
-- 감사 4컬럼 + PK/FK). SQLite는 SqliteSchemaInitializer가 방언 변환(NVARCHAR→TEXT 등)·FK 비강제.
-- 부모→자식 순서로 생성: *_CLASS → 본체, MDM_PRODUCT(V026)·MDM_SEGMENT 참조는 선생성 후 참조.

-- 설비 그룹(MDM_EQUIPMENT.EQUIPMENT_CLASS_ID가 가리키는 분류 마스터 — 기존 컬럼과 디커플, FK는 신규측만).
CREATE TABLE MDM_EQUIPMENT_CLASS (
    EQUIPMENT_CLASS_ID      NVARCHAR(50)    NOT NULL,
    EQUIPMENT_CLASS_NAME    NVARCHAR(200)   NOT NULL,
    DESCRIPTION             NVARCHAR(500)   NULL,
    CREATED_BY              NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT              DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY              NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT              DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_MDM_EQUIPMENT_CLASS PRIMARY KEY (EQUIPMENT_CLASS_ID)
);
CREATE INDEX IX_MDM_EQUIPMENT_CLASS_NAME ON MDM_EQUIPMENT_CLASS (EQUIPMENT_CLASS_NAME);

-- 품목(제품) 그룹.
CREATE TABLE MDM_ITEM_CLASS (
    ITEM_CLASS_ID           NVARCHAR(50)    NOT NULL,
    ITEM_CLASS_NAME         NVARCHAR(200)   NOT NULL,
    DESCRIPTION             NVARCHAR(500)   NULL,
    CREATED_BY              NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT              DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY              NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT              DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_MDM_ITEM_CLASS PRIMARY KEY (ITEM_CLASS_ID)
);
CREATE INDEX IX_MDM_ITEM_CLASS_NAME ON MDM_ITEM_CLASS (ITEM_CLASS_NAME);

-- 캐리어 그룹.
CREATE TABLE MDM_CARRIER_CLASS (
    CARRIER_CLASS_ID        NVARCHAR(50)    NOT NULL,
    CARRIER_CLASS_NAME      NVARCHAR(200)   NOT NULL,
    DESCRIPTION             NVARCHAR(500)   NULL,
    CREATED_BY              NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT              DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY              NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT              DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_MDM_CARRIER_CLASS PRIMARY KEY (CARRIER_CLASS_ID)
);
CREATE INDEX IX_MDM_CARRIER_CLASS_NAME ON MDM_CARRIER_CLASS (CARRIER_CLASS_NAME);

-- 캐리어 — 그룹(MDM_CARRIER_CLASS) 참조(nullable).
CREATE TABLE MDM_CARRIER (
    CARRIER_ID              NVARCHAR(50)    NOT NULL,
    CARRIER_NAME            NVARCHAR(200)   NOT NULL,
    CARRIER_CLASS_ID        NVARCHAR(50)    NULL,
    DESCRIPTION             NVARCHAR(500)   NULL,
    CREATED_BY              NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT              DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY              NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT              DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_MDM_CARRIER PRIMARY KEY (CARRIER_ID),
    CONSTRAINT FK_MDM_CARRIER_CLASS FOREIGN KEY (CARRIER_CLASS_ID)
        REFERENCES MDM_CARRIER_CLASS (CARRIER_CLASS_ID)
);
CREATE INDEX IX_MDM_CARRIER_CLASS_REF ON MDM_CARRIER (CARRIER_CLASS_ID, CARRIER_NAME);

-- 공정(세그먼트) 그룹.
CREATE TABLE MDM_SEGMENT_CLASS (
    SEGMENT_CLASS_ID        NVARCHAR(50)    NOT NULL,
    SEGMENT_CLASS_NAME      NVARCHAR(200)   NOT NULL,
    DESCRIPTION             NVARCHAR(500)   NULL,
    CREATED_BY              NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT              DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY              NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT              DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_MDM_SEGMENT_CLASS PRIMARY KEY (SEGMENT_CLASS_ID)
);
CREATE INDEX IX_MDM_SEGMENT_CLASS_NAME ON MDM_SEGMENT_CLASS (SEGMENT_CLASS_NAME);

-- 공정(세그먼트) — 그룹(MDM_SEGMENT_CLASS) 참조(nullable).
CREATE TABLE MDM_SEGMENT (
    SEGMENT_ID              NVARCHAR(50)    NOT NULL,
    SEGMENT_NAME            NVARCHAR(200)   NOT NULL,
    SEGMENT_CLASS_ID        NVARCHAR(50)    NULL,
    DESCRIPTION             NVARCHAR(500)   NULL,
    CREATED_BY              NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT              DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY              NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT              DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_MDM_SEGMENT PRIMARY KEY (SEGMENT_ID),
    CONSTRAINT FK_MDM_SEGMENT_CLASS FOREIGN KEY (SEGMENT_CLASS_ID)
        REFERENCES MDM_SEGMENT_CLASS (SEGMENT_CLASS_ID)
);
CREATE INDEX IX_MDM_SEGMENT_CLASS_REF ON MDM_SEGMENT (SEGMENT_CLASS_ID, SEGMENT_NAME);

-- 프로세스 그룹.
CREATE TABLE MDM_PROCESS_CLASS (
    PROCESS_CLASS_ID        NVARCHAR(50)    NOT NULL,
    PROCESS_CLASS_NAME      NVARCHAR(200)   NOT NULL,
    DESCRIPTION             NVARCHAR(500)   NULL,
    CREATED_BY              NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT              DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY              NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT              DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_MDM_PROCESS_CLASS PRIMARY KEY (PROCESS_CLASS_ID)
);
CREATE INDEX IX_MDM_PROCESS_CLASS_NAME ON MDM_PROCESS_CLASS (PROCESS_CLASS_NAME);

-- 프로세스 — 그룹(MDM_PROCESS_CLASS) 참조(nullable).
CREATE TABLE MDM_PROCESS (
    PROCESS_ID              NVARCHAR(50)    NOT NULL,
    PROCESS_NAME            NVARCHAR(200)   NOT NULL,
    PROCESS_CLASS_ID        NVARCHAR(50)    NULL,
    DESCRIPTION             NVARCHAR(500)   NULL,
    CREATED_BY              NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT              DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY              NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT              DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_MDM_PROCESS PRIMARY KEY (PROCESS_ID),
    CONSTRAINT FK_MDM_PROCESS_CLASS FOREIGN KEY (PROCESS_CLASS_ID)
        REFERENCES MDM_PROCESS_CLASS (PROCESS_CLASS_ID)
);
CREATE INDEX IX_MDM_PROCESS_CLASS_REF ON MDM_PROCESS (PROCESS_CLASS_ID, PROCESS_NAME);

-- 라우팅(제품 단위 공정 경로 헤더) — 제품(MDM_PRODUCT, V026) 참조.
CREATE TABLE MDM_ROUTING (
    ROUTING_ID              NVARCHAR(50)    NOT NULL,
    ROUTING_NAME            NVARCHAR(200)   NOT NULL,
    PRODUCT_ID              NVARCHAR(50)    NOT NULL,
    DESCRIPTION             NVARCHAR(500)   NULL,
    CREATED_BY              NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT              DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY              NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT              DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_MDM_ROUTING PRIMARY KEY (ROUTING_ID),
    CONSTRAINT FK_MDM_ROUTING_PRODUCT FOREIGN KEY (PRODUCT_ID)
        REFERENCES MDM_PRODUCT (PRODUCT_ID)
);
CREATE INDEX IX_MDM_ROUTING_PRODUCT ON MDM_ROUTING (PRODUCT_ID, ROUTING_NAME);

-- BOM(제품 부품 구성) — 제품/부품 모두 MDM_PRODUCT 참조.
CREATE TABLE MDM_BOM (
    BOM_ID                  NVARCHAR(50)    NOT NULL,
    PRODUCT_ID              NVARCHAR(50)    NOT NULL,
    COMPONENT_ID            NVARCHAR(50)    NOT NULL,
    QUANTITY                DECIMAL(18,4)   NOT NULL DEFAULT 0,
    DESCRIPTION             NVARCHAR(500)   NULL,
    CREATED_BY              NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT              DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY              NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT              DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_MDM_BOM PRIMARY KEY (BOM_ID),
    CONSTRAINT FK_MDM_BOM_PRODUCT FOREIGN KEY (PRODUCT_ID)
        REFERENCES MDM_PRODUCT (PRODUCT_ID),
    CONSTRAINT FK_MDM_BOM_COMPONENT FOREIGN KEY (COMPONENT_ID)
        REFERENCES MDM_PRODUCT (PRODUCT_ID)
);
CREATE INDEX IX_MDM_BOM_PRODUCT ON MDM_BOM (PRODUCT_ID);

-- Qtime(공정별 표준작업시간) — 공정(MDM_SEGMENT) 참조(nullable).
CREATE TABLE MDM_QTIME (
    QTIME_ID                NVARCHAR(50)    NOT NULL,
    SEGMENT_ID              NVARCHAR(50)    NULL,
    STANDARD_TIME           DECIMAL(18,4)   NOT NULL DEFAULT 0,
    UNIT                    NVARCHAR(50)    NULL,
    DESCRIPTION             NVARCHAR(500)   NULL,
    CREATED_BY              NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT              DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY              NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT              DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_MDM_QTIME PRIMARY KEY (QTIME_ID),
    CONSTRAINT FK_MDM_QTIME_SEGMENT FOREIGN KEY (SEGMENT_ID)
        REFERENCES MDM_SEGMENT (SEGMENT_ID)
);
CREATE INDEX IX_MDM_QTIME_SEGMENT ON MDM_QTIME (SEGMENT_ID);

-- Qtime 액션 — Qtime(MDM_QTIME) 참조(nullable).
CREATE TABLE MDM_QTIME_ACTION (
    ACTION_ID               NVARCHAR(50)    NOT NULL,
    QTIME_ID                NVARCHAR(50)    NULL,
    ACTION_CODE             NVARCHAR(50)    NOT NULL,
    DESCRIPTION             NVARCHAR(500)   NULL,
    CREATED_BY              NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT              DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY              NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT              DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_MDM_QTIME_ACTION PRIMARY KEY (ACTION_ID),
    CONSTRAINT FK_MDM_QTIME_ACTION_QTIME FOREIGN KEY (QTIME_ID)
        REFERENCES MDM_QTIME (QTIME_ID)
);
CREATE INDEX IX_MDM_QTIME_ACTION_QTIME ON MDM_QTIME_ACTION (QTIME_ID);
