-- QMS Module: 기준정보(검사항목/검사정의/수입검사방법) 마스터.
-- SmartUX QMS 기준정보 메뉴의 검사항목 관리·검사 관리·수입검사 방법 설정 화면이 "no such table"로 막혀 있어
-- 화면 점등 백엔드로 3개 마스터 테이블을 신설한다. 컬럼/감사/제약은 V030__QMS_MASTER 스타일과 정합
-- (NVARCHAR/DATETIME2/IS_ACTIVE/감사 4컬럼 + PK). 소프트 참조(PROCESS_ID/PRODUCT_ID)는 V030 InspectionSpec과
-- 동일하게 FK 생략(부모 미존재 가능성). SQLite는 SqliteSchemaInitializer가 방언 변환·FK 비강제.

-- 검사항목 마스터.
CREATE TABLE QMS_INSPECTION_ITEM (
    ITEM_ID           NVARCHAR(50)    NOT NULL,
    ITEM_NAME         NVARCHAR(200)   NOT NULL,
    INSPECTION_TYPE   NVARCHAR(50)    NULL,
    MEASURE_TYPE      NVARCHAR(50)    NULL,
    UNIT              NVARCHAR(50)    NULL,
    DESCRIPTION       NVARCHAR(500)   NULL,
    IS_ACTIVE         BIT             NOT NULL DEFAULT 1,
    CREATED_BY        NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT        DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY        NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT        DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_QMS_INSPECTION_ITEM PRIMARY KEY (ITEM_ID)
);
CREATE INDEX IX_QMS_INSPECTION_ITEM_NAME ON QMS_INSPECTION_ITEM (ITEM_NAME);

-- 검사 정의(검사 관리) — 공정/품목 단위 검사 계획 헤더.
CREATE TABLE QMS_INSPECTION_DEF (
    INSP_DEF_ID       NVARCHAR(50)    NOT NULL,
    INSP_DEF_NAME     NVARCHAR(200)   NOT NULL,
    PROCESS_ID        NVARCHAR(50)    NULL,
    PRODUCT_ID        NVARCHAR(50)    NULL,
    INSPECTION_TYPE   NVARCHAR(50)    NULL,
    DESCRIPTION       NVARCHAR(500)   NULL,
    IS_ACTIVE         BIT             NOT NULL DEFAULT 1,
    CREATED_BY        NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT        DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY        NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT        DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_QMS_INSPECTION_DEF PRIMARY KEY (INSP_DEF_ID)
);
CREATE INDEX IX_QMS_INSPECTION_DEF_PROCESS ON QMS_INSPECTION_DEF (PROCESS_ID, IS_ACTIVE);

-- 수입검사 방법 설정 — 품목별 수입검사 샘플링 방법.
CREATE TABLE QMS_INCOMING_INSP_METHOD (
    METHOD_ID         NVARCHAR(50)    NOT NULL,
    METHOD_NAME       NVARCHAR(200)   NOT NULL,
    PRODUCT_ID        NVARCHAR(50)    NULL,
    SAMPLING_TYPE     NVARCHAR(50)    NULL,
    AQL_LEVEL         NVARCHAR(50)    NULL,
    DESCRIPTION       NVARCHAR(500)   NULL,
    IS_ACTIVE         BIT             NOT NULL DEFAULT 1,
    CREATED_BY        NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT        DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY        NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT        DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_QMS_INCOMING_INSP_METHOD PRIMARY KEY (METHOD_ID)
);
CREATE INDEX IX_QMS_INCOMING_INSP_METHOD_PRODUCT ON QMS_INCOMING_INSP_METHOD (PRODUCT_ID, IS_ACTIVE);
