-- QMS Module: 계측기(Gauge) 관리 — 계측기 마스터 + 검교정 계획/내역 + RNR 계획/평가 + 수리 내역.
-- SmartUX QMS 계측기 관리 메뉴의 6개 업무화면이 "no such table"로 막혀 있어 화면 점등 백엔드로 6개 테이블을
-- 신설한다. 컬럼/감사/제약은 V030__QMS_MASTER · V037__QMS_STD_MASTER 스타일과 정합. 부모(QMS_GAUGE)→자식 순서로
-- 생성하며 자식은 GAUGE_ID FK 보유. EQUIPMENT_ID는 소프트 참조라 FK 생략(V030 패턴). SQLite는 방언 변환·FK 비강제.

-- 계측기 마스터.
CREATE TABLE QMS_GAUGE (
    GAUGE_ID               NVARCHAR(50)    NOT NULL,
    GAUGE_NAME             NVARCHAR(200)   NOT NULL,
    GAUGE_TYPE             NVARCHAR(50)    NULL,
    MODEL                  NVARCHAR(100)   NULL,
    SERIAL_NO              NVARCHAR(100)   NULL,
    LOCATION               NVARCHAR(200)   NULL,
    EQUIPMENT_ID           NVARCHAR(50)    NULL,
    CALIBRATION_CYCLE_DAYS INT            NULL,
    LAST_CALIBRATED_AT     DATETIME2       NULL,
    NEXT_CALIBRATION_AT    DATETIME2       NULL,
    IS_ACTIVE              BIT             NOT NULL DEFAULT 1,
    CREATED_BY             NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT             DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY             NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT             DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_QMS_GAUGE PRIMARY KEY (GAUGE_ID)
);
CREATE INDEX IX_QMS_GAUGE_NAME ON QMS_GAUGE (GAUGE_NAME);
CREATE INDEX IX_QMS_GAUGE_NEXT_CAL ON QMS_GAUGE (NEXT_CALIBRATION_AT);

-- 검교정 계획.
CREATE TABLE QMS_GAUGE_CALIBRATION_PLAN (
    PLAN_ID         NVARCHAR(50)    NOT NULL,
    GAUGE_ID        NVARCHAR(50)    NOT NULL,
    PLAN_NAME       NVARCHAR(200)   NULL,
    SCHEDULED_DATE  DATETIME2       NULL,
    CYCLE_TYPE      NVARCHAR(50)    NULL,
    ASSIGNEE_ID     NVARCHAR(50)    NULL,
    STATUS          NVARCHAR(20)    NOT NULL DEFAULT 'Planned',
    CREATED_BY      NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY      NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_QMS_GAUGE_CAL_PLAN PRIMARY KEY (PLAN_ID),
    CONSTRAINT FK_QMS_GAUGE_CAL_PLAN_GAUGE FOREIGN KEY (GAUGE_ID) REFERENCES QMS_GAUGE (GAUGE_ID)
);
CREATE INDEX IX_QMS_GAUGE_CAL_PLAN_GAUGE ON QMS_GAUGE_CALIBRATION_PLAN (GAUGE_ID, SCHEDULED_DATE);

-- 검교정 내역(결과).
CREATE TABLE QMS_GAUGE_CALIBRATION_RESULT (
    RESULT_ID       NVARCHAR(50)    NOT NULL,
    GAUGE_ID        NVARCHAR(50)    NOT NULL,
    PLAN_ID         NVARCHAR(50)    NULL,
    CALIBRATED_AT   DATETIME2       NOT NULL,
    CALIBRATED_BY   NVARCHAR(50)    NULL,
    RESULT          NVARCHAR(20)    NULL,
    CERTIFICATE_NO  NVARCHAR(100)   NULL,
    NEXT_DUE_AT     DATETIME2       NULL,
    REMARK          NVARCHAR(500)   NULL,
    CREATED_BY      NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY      NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_QMS_GAUGE_CAL_RESULT PRIMARY KEY (RESULT_ID),
    CONSTRAINT FK_QMS_GAUGE_CAL_RESULT_GAUGE FOREIGN KEY (GAUGE_ID) REFERENCES QMS_GAUGE (GAUGE_ID)
);
CREATE INDEX IX_QMS_GAUGE_CAL_RESULT_GAUGE ON QMS_GAUGE_CALIBRATION_RESULT (GAUGE_ID, CALIBRATED_AT DESC);

-- RNR(Gage R&R) 계획.
CREATE TABLE QMS_GAUGE_RNR_PLAN (
    RNR_PLAN_ID     NVARCHAR(50)    NOT NULL,
    GAUGE_ID        NVARCHAR(50)    NOT NULL,
    PLAN_NAME       NVARCHAR(200)   NULL,
    SCHEDULED_DATE  DATETIME2       NULL,
    OPERATOR_COUNT  INT             NULL,
    TRIAL_COUNT     INT             NULL,
    PART_COUNT      INT             NULL,
    STATUS          NVARCHAR(20)    NOT NULL DEFAULT 'Planned',
    CREATED_BY      NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY      NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_QMS_GAUGE_RNR_PLAN PRIMARY KEY (RNR_PLAN_ID),
    CONSTRAINT FK_QMS_GAUGE_RNR_PLAN_GAUGE FOREIGN KEY (GAUGE_ID) REFERENCES QMS_GAUGE (GAUGE_ID)
);
CREATE INDEX IX_QMS_GAUGE_RNR_PLAN_GAUGE ON QMS_GAUGE_RNR_PLAN (GAUGE_ID, SCHEDULED_DATE);

-- RNR 평가(결과).
CREATE TABLE QMS_GAUGE_RNR_RESULT (
    RNR_RESULT_ID   NVARCHAR(50)    NOT NULL,
    RNR_PLAN_ID     NVARCHAR(50)    NULL,
    GAUGE_ID        NVARCHAR(50)    NOT NULL,
    EVALUATED_AT    DATETIME2       NOT NULL,
    EVALUATED_BY    NVARCHAR(50)    NULL,
    GAGE_RR_PERCENT DECIMAL(18,4)   NULL,
    NDC             INT             NULL,
    JUDGEMENT       NVARCHAR(20)    NULL,
    REMARK          NVARCHAR(500)   NULL,
    CREATED_BY      NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY      NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_QMS_GAUGE_RNR_RESULT PRIMARY KEY (RNR_RESULT_ID),
    CONSTRAINT FK_QMS_GAUGE_RNR_RESULT_GAUGE FOREIGN KEY (GAUGE_ID) REFERENCES QMS_GAUGE (GAUGE_ID)
);
CREATE INDEX IX_QMS_GAUGE_RNR_RESULT_GAUGE ON QMS_GAUGE_RNR_RESULT (GAUGE_ID, EVALUATED_AT DESC);

-- 수리 내역.
CREATE TABLE QMS_GAUGE_REPAIR_RESULT (
    REPAIR_ID       NVARCHAR(50)    NOT NULL,
    GAUGE_ID        NVARCHAR(50)    NOT NULL,
    REPAIRED_AT     DATETIME2       NOT NULL,
    REPAIRED_BY     NVARCHAR(50)    NULL,
    FAILURE_DESC    NVARCHAR(500)   NULL,
    REPAIR_DESC     NVARCHAR(500)   NULL,
    COST            DECIMAL(18,2)   NULL,
    CREATED_BY      NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY      NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_QMS_GAUGE_REPAIR PRIMARY KEY (REPAIR_ID),
    CONSTRAINT FK_QMS_GAUGE_REPAIR_GAUGE FOREIGN KEY (GAUGE_ID) REFERENCES QMS_GAUGE (GAUGE_ID)
);
CREATE INDEX IX_QMS_GAUGE_REPAIR_GAUGE ON QMS_GAUGE_REPAIR_RESULT (GAUGE_ID, REPAIRED_AT DESC);
