-- EMS Module: 예비품 그룹 + 예비품 입출고(입고/이동/폐기). SmartUX EMS 예비품 메뉴(그룹 관리·입고·이동·폐기·
-- 입출고 이력)의 백엔드로 2개 테이블을 신설한다. TRANSACTION_TYPE으로 입고(Incoming)/이동(Move)/폐기(Scrap) 구분.
-- 컬럼/감사는 V027 EMS_SPARE_PART · V036 EMS 스타일과 정합. PART_ID는 EMS_SPARE_PART 소프트 참조(FK 생략).

-- 예비품 그룹 마스터.
CREATE TABLE EMS_SPARE_PART_CLASS (
    PART_CLASS_ID    NVARCHAR(50)    NOT NULL,
    PART_CLASS_NAME  NVARCHAR(200)   NOT NULL,
    DESCRIPTION      NVARCHAR(500)   NULL,
    IS_ACTIVE        BIT             NOT NULL DEFAULT 1,
    CREATED_BY       NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT       DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY       NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT       DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_EMS_SPARE_PART_CLASS PRIMARY KEY (PART_CLASS_ID)
);
CREATE INDEX IX_EMS_SPARE_PART_CLASS_NAME ON EMS_SPARE_PART_CLASS (PART_CLASS_NAME);

-- 예비품 입출고 트랜잭션.
CREATE TABLE EMS_SPARE_PART_INOUT (
    INOUT_ID         NVARCHAR(50)    NOT NULL,
    PART_ID          NVARCHAR(50)    NOT NULL,
    TRANSACTION_TYPE NVARCHAR(20)    NOT NULL,
    QUANTITY         DECIMAL(18,2)   NULL,
    FROM_LOCATION    NVARCHAR(200)   NULL,
    TO_LOCATION      NVARCHAR(200)   NULL,
    TRANSACTION_AT   DATETIME2       NOT NULL,
    PROCESSED_BY     NVARCHAR(50)    NULL,
    REMARK           NVARCHAR(500)   NULL,
    CREATED_BY       NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT       DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY       NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT       DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_EMS_SPARE_PART_INOUT PRIMARY KEY (INOUT_ID)
);
CREATE INDEX IX_EMS_SPARE_PART_INOUT_TYPE ON EMS_SPARE_PART_INOUT (TRANSACTION_TYPE, TRANSACTION_AT DESC);
CREATE INDEX IX_EMS_SPARE_PART_INOUT_PART ON EMS_SPARE_PART_INOUT (PART_ID, TRANSACTION_AT DESC);
