-- MDM/기준정보 보강: 작업자(그룹)·작업조·작업달력·거래처·납품처 품목. SmartUX FACTORY_STD 기준정보 메뉴의
-- 작업자/작업조/달력/거래처 업무화면 백엔드로 6개 마스터를 신설한다. 컬럼/감사/제약은 V026/V035 MDM 스타일과 정합.
-- 부모(그룹/거래처)→자식 순서. 소프트 참조(PLANT_ID/PRODUCT_ID)는 FK 생략. SQLite는 방언 변환·FK 비강제.

-- 작업자 그룹.
CREATE TABLE MDM_WORKER_CLASS (
    WORKER_CLASS_ID   NVARCHAR(50)    NOT NULL,
    WORKER_CLASS_NAME NVARCHAR(200)   NOT NULL,
    DESCRIPTION       NVARCHAR(500)   NULL,
    IS_ACTIVE         BIT             NOT NULL DEFAULT 1,
    CREATED_BY        NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT        DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY        NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT        DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_MDM_WORKER_CLASS PRIMARY KEY (WORKER_CLASS_ID)
);
CREATE INDEX IX_MDM_WORKER_CLASS_NAME ON MDM_WORKER_CLASS (WORKER_CLASS_NAME);

-- 작업자.
CREATE TABLE MDM_WORKER (
    WORKER_ID         NVARCHAR(50)    NOT NULL,
    WORKER_NAME       NVARCHAR(200)   NOT NULL,
    WORKER_CLASS_ID   NVARCHAR(50)    NULL,
    EMPLOYEE_NO       NVARCHAR(50)    NULL,
    DEPARTMENT        NVARCHAR(200)   NULL,
    PLANT_ID          NVARCHAR(50)    NULL,
    IS_ACTIVE         BIT             NOT NULL DEFAULT 1,
    CREATED_BY        NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT        DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY        NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT        DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_MDM_WORKER PRIMARY KEY (WORKER_ID),
    CONSTRAINT FK_MDM_WORKER_CLASS FOREIGN KEY (WORKER_CLASS_ID) REFERENCES MDM_WORKER_CLASS (WORKER_CLASS_ID)
);
CREATE INDEX IX_MDM_WORKER_CLASS_REF ON MDM_WORKER (WORKER_CLASS_ID, WORKER_NAME);

-- 작업조(교대).
CREATE TABLE MDM_SHIFT (
    SHIFT_ID          NVARCHAR(50)    NOT NULL,
    SHIFT_NAME        NVARCHAR(200)   NOT NULL,
    START_TIME        NVARCHAR(10)    NULL,
    END_TIME          NVARCHAR(10)    NULL,
    DESCRIPTION       NVARCHAR(500)   NULL,
    IS_ACTIVE         BIT             NOT NULL DEFAULT 1,
    CREATED_BY        NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT        DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY        NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT        DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_MDM_SHIFT PRIMARY KEY (SHIFT_ID)
);

-- 작업 달력.
CREATE TABLE MDM_WORK_CALENDAR (
    CALENDAR_ID       NVARCHAR(50)    NOT NULL,
    CALENDAR_DATE     DATETIME2       NOT NULL,
    DAY_TYPE          NVARCHAR(20)    NULL,
    SHIFT_ID          NVARCHAR(50)    NULL,
    PLANT_ID          NVARCHAR(50)    NULL,
    DESCRIPTION       NVARCHAR(500)   NULL,
    CREATED_BY        NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT        DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY        NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT        DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_MDM_WORK_CALENDAR PRIMARY KEY (CALENDAR_ID)
);
CREATE INDEX IX_MDM_WORK_CALENDAR_DATE ON MDM_WORK_CALENDAR (CALENDAR_DATE);

-- 거래처.
CREATE TABLE MDM_CUSTOMER (
    CUSTOMER_ID       NVARCHAR(50)    NOT NULL,
    CUSTOMER_NAME     NVARCHAR(200)   NOT NULL,
    CUSTOMER_TYPE     NVARCHAR(50)    NULL,
    CONTACT_NAME      NVARCHAR(100)   NULL,
    PHONE             NVARCHAR(50)    NULL,
    ADDRESS           NVARCHAR(500)   NULL,
    IS_ACTIVE         BIT             NOT NULL DEFAULT 1,
    CREATED_BY        NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT        DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY        NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT        DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_MDM_CUSTOMER PRIMARY KEY (CUSTOMER_ID)
);
CREATE INDEX IX_MDM_CUSTOMER_NAME ON MDM_CUSTOMER (CUSTOMER_NAME);

-- 납품처 품목(거래처↔품목 매핑).
CREATE TABLE MDM_DELIVERY_ITEM (
    DELIVERY_ITEM_ID  NVARCHAR(50)    NOT NULL,
    CUSTOMER_ID       NVARCHAR(50)    NOT NULL,
    PRODUCT_ID        NVARCHAR(50)    NOT NULL,
    DELIVERY_CODE     NVARCHAR(100)   NULL,
    UNIT_PRICE        DECIMAL(18,2)   NULL,
    IS_ACTIVE         BIT             NOT NULL DEFAULT 1,
    CREATED_BY        NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT        DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY        NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT        DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_MDM_DELIVERY_ITEM PRIMARY KEY (DELIVERY_ITEM_ID),
    CONSTRAINT FK_MDM_DELIVERY_ITEM_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES MDM_CUSTOMER (CUSTOMER_ID)
);
CREATE INDEX IX_MDM_DELIVERY_ITEM_CUST ON MDM_DELIVERY_ITEM (CUSTOMER_ID, PRODUCT_ID);
