-- EST Module: OEE(설비종합효율) 마트 + 유실(Loss) 상세 + EPT 관심지표 마스터/값.
-- SmartUX EPT(설비성능관리) 화면 점등(Phase 4)용 신설. OEE = 가용성(Availability) × 성능(Performance) × 품질(Quality).
-- 표준 MES 방식대로 설비×일자×작업조 단위로 사전집계한 마트 테이블을 두고, 대시보드는 이를 read한다
-- (원자료 POM_LOT/EST_EQUIPMENT_STATE_HISTORY → 마트 집계는 배치/워커 소관, 후속). SHIFT_ID는 선택 차원이라
-- 느슨 참조(FK 없음, MDM_SHIFT 문자열 키). 손실코드(LOSS_CODE)도 상태코드 관례(문자열)를 따라 느슨 참조한다.
-- 감사/PK/인덱스 관례는 V046/V047과 1:1 정합.

-- 설비종합효율(OEE) 요약 마트 — 설비×일자×작업조 1행. 가용성/성능/품질/OEE는 분율(0~1)로 저장(표시층에서 ×100).
CREATE TABLE EST_OEE_SUMMARY (
    OEE_ID                NVARCHAR(50)    NOT NULL,
    PLANT_ID              NVARCHAR(50)    NOT NULL,
    EQUIPMENT_ID          NVARCHAR(50)    NOT NULL,
    OEE_DATE              DATETIME2       NOT NULL,
    SHIFT_ID              NVARCHAR(50)    NULL,
    PLANNED_MINUTES       DECIMAL(18,4)   NOT NULL DEFAULT 0,   -- 계획 생산 시간(분)
    DOWNTIME_MINUTES      DECIMAL(18,4)   NOT NULL DEFAULT 0,   -- 비가동 시간(분)
    OPERATING_MINUTES     DECIMAL(18,4)   NOT NULL DEFAULT 0,   -- 가동 시간(분) = 계획 - 비가동
    IDEAL_CYCLE_TIME_SEC  DECIMAL(18,4)   NOT NULL DEFAULT 0,   -- 이상 사이클타임(초/개)
    TOTAL_COUNT           DECIMAL(18,4)   NOT NULL DEFAULT 0,   -- 총 생산수
    GOOD_COUNT            DECIMAL(18,4)   NOT NULL DEFAULT 0,   -- 양품수
    DEFECT_COUNT          DECIMAL(18,4)   NOT NULL DEFAULT 0,   -- 불량수
    AVAILABILITY          DECIMAL(10,4)   NOT NULL DEFAULT 0,   -- 가용성 = 가동/계획
    PERFORMANCE           DECIMAL(10,4)   NOT NULL DEFAULT 0,   -- 성능 = (이상사이클×총생산)/가동
    QUALITY               DECIMAL(10,4)   NOT NULL DEFAULT 0,   -- 품질 = 양품/총생산
    OEE                   DECIMAL(10,4)   NOT NULL DEFAULT 0,   -- OEE = 가용성×성능×품질
    CREATED_BY            NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT            DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY            NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT            DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_EST_OEE_SUMMARY PRIMARY KEY (OEE_ID),
    CONSTRAINT FK_EST_OEE_EQUIPMENT FOREIGN KEY (EQUIPMENT_ID)
        REFERENCES MDM_EQUIPMENT (EQUIPMENT_ID)
);

CREATE INDEX IX_EST_OEE_PLANT_DATE     ON EST_OEE_SUMMARY (PLANT_ID, OEE_DATE DESC);
CREATE INDEX IX_EST_OEE_EQUIPMENT_DATE ON EST_OEE_SUMMARY (EQUIPMENT_ID, OEE_DATE DESC);

-- 유실(Loss) 상세 — 설비별 손실 발생 1행(6대 손실 카테고리 + 상세 손실코드). 유실 분석/WORST5 유실의 집계 원천.
CREATE TABLE EST_OEE_LOSS (
    LOSS_ID          NVARCHAR(50)    NOT NULL,
    PLANT_ID         NVARCHAR(50)    NOT NULL,
    EQUIPMENT_ID     NVARCHAR(50)    NOT NULL,
    OEE_DATE         DATETIME2       NOT NULL,
    SHIFT_ID         NVARCHAR(50)    NULL,
    LOSS_CATEGORY    NVARCHAR(30)    NOT NULL,   -- 6대 손실: Breakdown/Setup/MinorStop/SpeedLoss/Defect/Startup
    LOSS_CODE        NVARCHAR(50)    NULL,       -- 상세 손실/사유 코드(느슨 참조)
    LOSS_NAME        NVARCHAR(200)   NULL,
    LOSS_MINUTES     DECIMAL(18,4)   NOT NULL DEFAULT 0,
    OCCURRED_AT      DATETIME2       NOT NULL,
    REASON           NVARCHAR(500)   NULL,
    CREATED_BY       NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT       DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY       NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT       DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_EST_OEE_LOSS PRIMARY KEY (LOSS_ID),
    CONSTRAINT FK_EST_OEE_LOSS_EQUIPMENT FOREIGN KEY (EQUIPMENT_ID)
        REFERENCES MDM_EQUIPMENT (EQUIPMENT_ID)
);

CREATE INDEX IX_EST_OEE_LOSS_EQUIPMENT ON EST_OEE_LOSS (EQUIPMENT_ID, OEE_DATE DESC);
CREATE INDEX IX_EST_OEE_LOSS_CATEGORY  ON EST_OEE_LOSS (LOSS_CATEGORY);

-- EPT 관심지표 마스터 — 사용자가 등록/관리하는 KPI 지표 정의(지표 관리 / 관심 지표 등록 화면).
CREATE TABLE EST_EPT_INDEX (
    INDEX_ID         NVARCHAR(50)    NOT NULL,
    INDEX_NAME       NVARCHAR(200)   NOT NULL,
    INDEX_CATEGORY   NVARCHAR(50)    NULL,
    UNIT             NVARCHAR(20)    NULL,
    DESCRIPTION      NVARCHAR(500)   NULL,
    IS_ACTIVE        BIT             NOT NULL DEFAULT 1,
    CREATED_BY       NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT       DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY       NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT       DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_EST_EPT_INDEX PRIMARY KEY (INDEX_ID)
);

CREATE INDEX IX_EST_EPT_INDEX_NAME ON EST_EPT_INDEX (INDEX_NAME);

-- EPT 관심지표 값 — 지표×설비×일자 측정값(관심 지표 조회 화면).
CREATE TABLE EST_EPT_INDEX_VALUE (
    VALUE_ID         NVARCHAR(50)    NOT NULL,
    INDEX_ID         NVARCHAR(50)    NOT NULL,
    EQUIPMENT_ID     NVARCHAR(50)    NULL,
    PLANT_ID         NVARCHAR(50)    NULL,
    OEE_DATE         DATETIME2       NOT NULL,
    SHIFT_ID         NVARCHAR(50)    NULL,
    INDEX_VALUE      DECIMAL(18,4)   NOT NULL DEFAULT 0,
    CREATED_BY       NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT       DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY       NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT       DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_EST_EPT_INDEX_VALUE PRIMARY KEY (VALUE_ID),
    CONSTRAINT FK_EST_INDEX_VALUE_INDEX FOREIGN KEY (INDEX_ID)
        REFERENCES EST_EPT_INDEX (INDEX_ID)
);

CREATE INDEX IX_EST_INDEX_VALUE_IDX ON EST_EPT_INDEX_VALUE (INDEX_ID, OEE_DATE DESC);
