-- PRC Module: 구매 발주(Purchase Order) 헤더. 레거시 PRC_TB_PURCHASE_ORDER를 현행 관례로 단순 포팅
-- (다국어명/TXN_HIST/ENTERPRISE 등 잡음 컬럼 제거, 감사 4컬럼 DEFAULT). SmartUX FACTORY_PRC 구매오더 관리/현황 점등용.
-- 발주 상세(PRC_PURCHASE_ITEM)·이동오더는 후속(이동오더는 IVT 이동 트랜잭션 모델 선결).
CREATE TABLE PRC_PURCHASE_ORDER (
    PURCHASE_ORDER_ID    NVARCHAR(50)    NOT NULL,
    PLANT_ID             NVARCHAR(50)    NOT NULL,
    PURCHASE_ORDER_NAME  NVARCHAR(200)   NULL,
    VENDOR_ID            NVARCHAR(50)    NULL,
    ORDER_DATE           DATETIME2       NULL,
    INCOMING_DATE        DATETIME2       NULL,
    ORDER_QTY            DECIMAL(18,4)   NOT NULL DEFAULT 0,
    OWNER_ID             NVARCHAR(50)    NULL,
    STATUS               NVARCHAR(20)    NOT NULL DEFAULT 'Draft',   -- Draft/Ordered/Incoming/Closed
    IS_HOLD              CHAR(1)         NOT NULL DEFAULT 'N',
    DESCRIPTION          NVARCHAR(500)   NULL,
    CREATED_BY           NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT           DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY           NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT           DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_PRC_PURCHASE_ORDER PRIMARY KEY (PURCHASE_ORDER_ID)
);

CREATE INDEX IX_PRC_PURCHASE_ORDER_PLANT  ON PRC_PURCHASE_ORDER (PLANT_ID, ORDER_DATE DESC);
CREATE INDEX IX_PRC_PURCHASE_ORDER_VENDOR ON PRC_PURCHASE_ORDER (VENDOR_ID);
