-- SLS Module: 판매 오더(Sales Order) / 판매 요청(Sales Request). 레거시 SLS_TB_SALES_ORDER / SLS_TB_SALES_REQUEST를
-- 현행 관례로 단순 포팅(다국어명/TXN_HIST/ENTERPRISE/중복 REQUEST_* 잡음 제거, 감사 4컬럼 DEFAULT).
-- SmartUX FACTORY_SLS 판매오더 관리·판매 요청 점등용. 납품 현황은 기존 SHP.ShipmentHistoryList 재사용.
CREATE TABLE SLS_SALES_ORDER (
    SALES_ORDER_ID    NVARCHAR(50)    NOT NULL,
    PLANT_ID          NVARCHAR(50)    NOT NULL,
    SALES_ORDER_NAME  NVARCHAR(200)   NULL,
    CUSTOMER_ID       NVARCHAR(50)    NULL,
    PRODUCT_ID        NVARCHAR(50)    NULL,
    PLAN_START_DATE   DATETIME2       NULL,
    PLAN_END_DATE     DATETIME2       NULL,
    PLAN_QTY          DECIMAL(18,4)   NOT NULL DEFAULT 0,
    DELIVERED_QTY     DECIMAL(18,4)   NOT NULL DEFAULT 0,
    OWNER_ID          NVARCHAR(50)    NULL,
    STATUS            NVARCHAR(20)     NOT NULL DEFAULT 'Draft',   -- Draft/Confirmed/Producing/Delivered/Closed
    IS_HOLD           CHAR(1)         NOT NULL DEFAULT 'N',
    DESCRIPTION       NVARCHAR(500)   NULL,
    CREATED_BY        NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT        DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY        NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT        DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_SLS_SALES_ORDER PRIMARY KEY (SALES_ORDER_ID)
);

CREATE INDEX IX_SLS_SALES_ORDER_PLANT    ON SLS_SALES_ORDER (PLANT_ID, PLAN_START_DATE DESC);
CREATE INDEX IX_SLS_SALES_ORDER_CUSTOMER ON SLS_SALES_ORDER (CUSTOMER_ID);

CREATE TABLE SLS_SALES_REQUEST (
    SALES_REQUEST_ID    NVARCHAR(50)    NOT NULL,
    SALES_REQUEST_NAME  NVARCHAR(200)   NULL,
    SALES_ORDER_ID      NVARCHAR(50)    NULL,
    CUSTOMER_ID         NVARCHAR(50)    NULL,
    PRODUCT_ID          NVARCHAR(50)    NULL,
    REQUEST_DATE        DATETIME2       NULL,
    REQUEST_QTY         DECIMAL(18,4)   NOT NULL DEFAULT 0,
    STATUS              NVARCHAR(20)    NOT NULL DEFAULT 'Draft',
    DESCRIPTION         NVARCHAR(500)   NULL,
    CREATED_BY          NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY          NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_SLS_SALES_REQUEST PRIMARY KEY (SALES_REQUEST_ID)
);

CREATE INDEX IX_SLS_SALES_REQUEST_ORDER ON SLS_SALES_REQUEST (SALES_ORDER_ID);
