-- MDM(기준정보) Module: 라벨 마스터 / 발행 이력 / 매핑. 레거시 STD_TB_LABEL / STD_TB_LABEL_ISSUE_LIST /
-- STD_TB_LABEL_MAPPING를 현행 관례로 단순 포팅(다국어/TXN_HIST/템플릿 blob 제거, VALID_STATE→IS_ACTIVE,
-- SEGMENT→PROCESS·ITEM_DEF→ITEM 정규화, 감사 4컬럼 DEFAULT). SmartUX FACTORY_STD 라벨 마스터/발행이력/매핑 점등용.
-- FACTORY_STD가 기존 기준정보 마스터(MDM_*, V046)와 동일 도메인이라 MDM_ 접두사 사용. BOR(자원명세)은 레거시 테이블 부재로 보류.
CREATE TABLE MDM_LABEL (
    LABEL_ID       NVARCHAR(50)    NOT NULL,
    PLANT_ID       NVARCHAR(50)    NOT NULL,
    LABEL_NAME     NVARCHAR(200)   NOT NULL,
    DESCRIPTION    NVARCHAR(500)   NULL,
    IS_ACTIVE      BIT             NOT NULL DEFAULT 1,
    CREATED_BY     NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT     DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY     NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT     DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_MDM_LABEL PRIMARY KEY (LABEL_ID)
);

CREATE INDEX IX_MDM_LABEL_PLANT ON MDM_LABEL (PLANT_ID, LABEL_NAME);

CREATE TABLE MDM_LABEL_ISSUE (
    ISSUE_ID       NVARCHAR(50)    NOT NULL,
    PLANT_ID       NVARCHAR(50)    NOT NULL,
    LABEL_ID       NVARCHAR(50)    NOT NULL,
    ITEM_ID        NVARCHAR(50)    NULL,
    LOT_ID         NVARCHAR(50)    NULL,
    SERIAL_NUM     NVARCHAR(50)    NULL,
    PRINT_CNT      INT             NOT NULL DEFAULT 0,
    ISSUED_AT      DATETIME2       NULL,
    DESCRIPTION    NVARCHAR(500)   NULL,
    CREATED_BY     NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT     DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY     NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT     DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_MDM_LABEL_ISSUE PRIMARY KEY (ISSUE_ID),
    CONSTRAINT FK_MDM_LABEL_ISSUE_LABEL FOREIGN KEY (LABEL_ID) REFERENCES MDM_LABEL (LABEL_ID)
);

CREATE INDEX IX_MDM_LABEL_ISSUE_LABEL ON MDM_LABEL_ISSUE (LABEL_ID, ISSUED_AT DESC);

CREATE TABLE MDM_LABEL_MAPPING (
    MAPPING_ID       NVARCHAR(50)    NOT NULL,
    PLANT_ID         NVARCHAR(50)    NOT NULL,
    PROCESS_ID       NVARCHAR(50)    NULL,
    ITEM_ID          NVARCHAR(50)    NULL,
    LABEL_ID         NVARCHAR(50)    NOT NULL,
    PRINT_LIMIT_CNT  INT             NULL,
    PRINT_LIMIT_YN   CHAR(1)         NOT NULL DEFAULT 'N',
    DESCRIPTION      NVARCHAR(500)   NULL,
    CREATED_BY       NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT       DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY       NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT       DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_MDM_LABEL_MAPPING PRIMARY KEY (MAPPING_ID),
    CONSTRAINT FK_MDM_LABEL_MAPPING_LABEL FOREIGN KEY (LABEL_ID) REFERENCES MDM_LABEL (LABEL_ID)
);

CREATE INDEX IX_MDM_LABEL_MAPPING_LABEL ON MDM_LABEL_MAPPING (LABEL_ID);
