-- EST Module: EPT(설비성능) 레이아웃 마스터 / 설비 EPT 속성. 레거시 EPT_TB_LAYOUT / EPT_TB_EQUIPMENT_EPT_PROPERTY를
-- 현행 관례로 단순 포팅(다국어명/IMAGE blob/LAYOUT_DATA/TXN_HIST 제거, VALID_STATE→IS_ACTIVE, 감사 4컬럼 DEFAULT).
-- SmartUX EPT_STD 레이아웃 관리/구성·설비 EPT 속성 관리 점등용. EPT=설비성능=EST 도메인이라 EST_EPT_ 접두사(EST_EPT_INDEX와 동일).
CREATE TABLE EST_EPT_LAYOUT (
    LAYOUT_ID      NVARCHAR(50)    NOT NULL,
    PLANT_ID       NVARCHAR(50)    NOT NULL,
    LAYOUT_NAME    NVARCHAR(200)   NOT NULL,
    AREA_ID        NVARCHAR(50)    NULL,
    WIDTH          INT             NOT NULL DEFAULT 0,
    HEIGHT         INT             NOT NULL DEFAULT 0,
    IMAGE_URL      NVARCHAR(200)   NULL,
    IS_ACTIVE      BIT             NOT NULL DEFAULT 1,
    CREATED_BY     NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT     DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY     NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT     DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_EST_EPT_LAYOUT PRIMARY KEY (LAYOUT_ID)
);

CREATE INDEX IX_EST_EPT_LAYOUT_PLANT ON EST_EPT_LAYOUT (PLANT_ID, LAYOUT_NAME);

CREATE TABLE EST_EPT_EQUIPMENT_PROPERTY (
    EQUIPMENT_ID        NVARCHAR(50)    NOT NULL,
    PLANT_ID            NVARCHAR(50)    NOT NULL,
    DESCRIPTION         NVARCHAR(500)   NULL,
    CYCLE_TIME          DECIMAL(18,4)   NULL,
    DO_ALARM_INTERLOCK  NVARCHAR(50)    NULL,
    DO_MCC              NVARCHAR(50)    NULL,
    DO_SUMMARY          NVARCHAR(50)    NULL,
    DO_TACT_TIME        NVARCHAR(50)    NULL,
    IS_ACTIVE           BIT             NOT NULL DEFAULT 1,
    CREATED_BY          NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY          NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_EST_EPT_EQUIPMENT_PROPERTY PRIMARY KEY (EQUIPMENT_ID),
    CONSTRAINT FK_EST_EPT_PROPERTY_EQUIPMENT FOREIGN KEY (EQUIPMENT_ID)
        REFERENCES MDM_EQUIPMENT (EQUIPMENT_ID)
);

CREATE INDEX IX_EST_EPT_PROPERTY_PLANT ON EST_EPT_EQUIPMENT_PROPERTY (PLANT_ID);
