-- EST Module: 설비 이벤트 + 상태 매핑(알람↔상태, 이벤트↔상태). MICUBE(설비상태 표준설정) 백엔드를 EST로 이관(사용자 결정).
-- 레거시 STD_TB_EQUIPMENT_STATE_ALARM_MAP / STD_TB_EQUIPMENT_STATE_EVENT_MAP를 현행 관례로 단순 포팅(복합PK→대리키,
-- VALID_STATE→IS_ACTIVE, 감사 DEFAULT) + 설비 이벤트 마스터(레거시 전용 테이블 부재, STATE_EVENT_MAP.EVENT_ID 근거 신설).
-- 설비 상태 정보/매트릭스는 기존 EST_EQUIPMENT_STATE/EST_STATE_MATRIX(V025) 재사용. MICUBE 접두사 미사용(EST_ 접두사).
CREATE TABLE EST_EQUIPMENT_EVENT (
    EVENT_ID       NVARCHAR(50)    NOT NULL,
    PLANT_ID       NVARCHAR(50)    NOT NULL,
    EVENT_NAME     NVARCHAR(200)   NOT NULL,
    EQUIPMENT_ID   NVARCHAR(50)    NULL,
    EVENT_TYPE     NVARCHAR(50)    NULL,
    DESCRIPTION    NVARCHAR(500)   NULL,
    IS_ACTIVE      BIT             NOT NULL DEFAULT 1,
    CREATED_BY     NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT     DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY     NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT     DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_EST_EQUIPMENT_EVENT PRIMARY KEY (EVENT_ID)
);

CREATE INDEX IX_EST_EQUIPMENT_EVENT_PLANT ON EST_EQUIPMENT_EVENT (PLANT_ID, EVENT_NAME);

CREATE TABLE EST_STATE_ALARM_MAP (
    MAP_ID         NVARCHAR(50)    NOT NULL,
    PLANT_ID       NVARCHAR(50)    NOT NULL,
    EQUIPMENT_ID   NVARCHAR(50)    NOT NULL,
    ALARM_DEF_ID   NVARCHAR(50)    NOT NULL,
    SET_STATE      NVARCHAR(50)    NULL,
    DESCRIPTION    NVARCHAR(500)   NULL,
    IS_ACTIVE      BIT             NOT NULL DEFAULT 1,
    CREATED_BY     NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT     DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY     NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT     DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_EST_STATE_ALARM_MAP PRIMARY KEY (MAP_ID)
);

CREATE INDEX IX_EST_STATE_ALARM_MAP_EQUIP ON EST_STATE_ALARM_MAP (EQUIPMENT_ID);

CREATE TABLE EST_STATE_EVENT_MAP (
    MAP_ID         NVARCHAR(50)    NOT NULL,
    PLANT_ID       NVARCHAR(50)    NOT NULL,
    EQUIPMENT_ID   NVARCHAR(50)    NOT NULL,
    EVENT_ID       NVARCHAR(50)    NOT NULL,
    SET_STATE      NVARCHAR(50)    NULL,
    DESCRIPTION    NVARCHAR(500)   NULL,
    IS_ACTIVE      BIT             NOT NULL DEFAULT 1,
    CREATED_BY     NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT     DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY     NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT     DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_EST_STATE_EVENT_MAP PRIMARY KEY (MAP_ID)
);

CREATE INDEX IX_EST_STATE_EVENT_MAP_EQUIP ON EST_STATE_EVENT_MAP (EQUIPMENT_ID);
