-- COM Module: 메일 서버 / 메일 수신자 매핑 / 서비스. MICUBE(설비 알람메일 알림) 백엔드를 COM으로 이관(사용자 결정).
-- 레거시 COM_TB_MAIL_SERVER / STD_TB_USER_EQUIPMENT_*MAIL* / COM_TB_ACTION를 현행 관례로 단순 포팅(복합PK→대리키,
-- 다국어/TXN_HIST 제거, 감사 DEFAULT). MICUBE 접두사 미사용(COM_ 접두사). 알람메일/일반메일은 MAIL_TYPE로 구분.
CREATE TABLE COM_MAIL_SERVER (
    SERVER_ID      NVARCHAR(50)    NOT NULL,
    SERVER_NAME    NVARCHAR(200)   NOT NULL,
    HOST           NVARCHAR(200)   NULL,
    PORT           INT             NULL,
    SENDER_ADDRESS NVARCHAR(200)   NULL,
    USE_SSL        CHAR(1)         NOT NULL DEFAULT 'N',
    IS_ACTIVE      BIT             NOT NULL DEFAULT 1,
    CREATED_BY     NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT     DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY     NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT     DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_COM_MAIL_SERVER PRIMARY KEY (SERVER_ID)
);

CREATE TABLE COM_MAIL_RECIPIENT (
    RECIPIENT_ID   NVARCHAR(50)    NOT NULL,
    PLANT_ID       NVARCHAR(50)    NOT NULL,
    USER_ID        NVARCHAR(50)    NOT NULL,
    EQUIPMENT_ID   NVARCHAR(50)    NULL,
    MAIL_ADDRESS   NVARCHAR(200)   NULL,
    MAIL_TYPE      NVARCHAR(20)    NOT NULL DEFAULT 'Mail',   -- Mail(일반)/Alarm(알람)
    IS_ACTIVE      BIT             NOT NULL DEFAULT 1,
    CREATED_BY     NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT     DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY     NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT     DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_COM_MAIL_RECIPIENT PRIMARY KEY (RECIPIENT_ID)
);

CREATE INDEX IX_COM_MAIL_RECIPIENT_TYPE ON COM_MAIL_RECIPIENT (MAIL_TYPE, EQUIPMENT_ID);

CREATE TABLE COM_SERVICE (
    SERVICE_ID     NVARCHAR(50)    NOT NULL,
    SERVICE_NAME   NVARCHAR(200)   NOT NULL,
    SERVICE_TYPE   NVARCHAR(50)    NULL,
    STATUS         NVARCHAR(20)    NOT NULL DEFAULT 'Stopped',   -- Running/Stopped
    DESCRIPTION    NVARCHAR(500)   NULL,
    IS_ACTIVE      BIT             NOT NULL DEFAULT 1,
    CREATED_BY     NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT     DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY     NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT     DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_COM_SERVICE PRIMARY KEY (SERVICE_ID)
);
