-- MDM(기준정보) Module: BOR(Bill of Resources, 자원명세) 헤더 + 자원 상세. 레거시 전용 테이블 부재로 도메인 개념 기반 신설
-- (BOM=자재명세와 대비되는 자원명세: 공정/품목에 필요한 설비·공구·자원). SmartUX FACTORY_STD BOR 관리(조건/자원 기준) 점등용.
-- FACTORY_STD=기존 기준정보 도메인이라 MDM_ 접두사(MDM_BOM과 대응).
CREATE TABLE MDM_BOR (
    BOR_ID         NVARCHAR(50)    NOT NULL,
    PLANT_ID       NVARCHAR(50)    NOT NULL,
    BOR_NAME       NVARCHAR(200)   NOT NULL,
    PROCESS_ID     NVARCHAR(50)    NULL,
    PRODUCT_ID     NVARCHAR(50)    NULL,
    BOR_TYPE       NVARCHAR(20)    NOT NULL DEFAULT 'Condition',   -- Condition(조건 기준)/Resource(자원 기준)
    DESCRIPTION    NVARCHAR(500)   NULL,
    IS_ACTIVE      BIT             NOT NULL DEFAULT 1,
    CREATED_BY     NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT     DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY     NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT     DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_MDM_BOR PRIMARY KEY (BOR_ID)
);

CREATE INDEX IX_MDM_BOR_PLANT ON MDM_BOR (PLANT_ID, BOR_NAME);

CREATE TABLE MDM_BOR_RESOURCE (
    RESOURCE_ID     NVARCHAR(50)    NOT NULL,
    BOR_ID          NVARCHAR(50)    NOT NULL,
    RESOURCE_TYPE   NVARCHAR(30)    NULL,       -- Equipment/Tool/Material/Worker
    RESOURCE_REF_ID NVARCHAR(50)    NULL,       -- 참조 설비/공구/자재 ID
    RESOURCE_NAME   NVARCHAR(200)   NULL,
    REQUIRED_QTY    DECIMAL(18,4)   NOT NULL DEFAULT 0,
    CONDITION_VALUE NVARCHAR(200)   NULL,        -- 조건 기준 BOR의 조건 값
    IS_ACTIVE       BIT             NOT NULL DEFAULT 1,
    CREATED_BY      NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY      NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_MDM_BOR_RESOURCE PRIMARY KEY (RESOURCE_ID),
    CONSTRAINT FK_MDM_BOR_RESOURCE_BOR FOREIGN KEY (BOR_ID) REFERENCES MDM_BOR (BOR_ID)
);

CREATE INDEX IX_MDM_BOR_RESOURCE_BOR ON MDM_BOR_RESOURCE (BOR_ID);
