-- MDM(기준정보) Module: 벤더(공급사) 마스터 / 벤더 품목. 레거시 MDM_TB_VENDOR / MDM_TB_VENDOR_ITEM를 현행 관례로
-- 단순 포팅(ENTERPRISE/다국어 제거, VALID_STATE→IS_ACTIVE, ITEM_DEF→PRODUCT 정규화, 복합PK→대리키, 감사 DEFAULT).
-- SmartUX MES_MDM_COM 벤더 관리/벤더 품목 관리 점등용. 거래처(MDM_CUSTOMER, V046 판매처)와 구분되는 구매처 마스터.
CREATE TABLE MDM_VENDOR (
    VENDOR_ID       NVARCHAR(50)    NOT NULL,
    VENDOR_NAME     NVARCHAR(200)   NOT NULL,
    VENDOR_TYPE     NVARCHAR(50)    NULL,
    CORPORATION_NO  NVARCHAR(50)    NULL,
    OWNER_NAME      NVARCHAR(100)   NULL,
    PHONE           NVARCHAR(50)    NULL,
    EMAIL           NVARCHAR(200)   NULL,
    ADDRESS         NVARCHAR(300)   NULL,
    DESCRIPTION     NVARCHAR(500)   NULL,
    IS_ACTIVE       BIT             NOT NULL DEFAULT 1,
    CREATED_BY      NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY      NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_MDM_VENDOR PRIMARY KEY (VENDOR_ID)
);

CREATE INDEX IX_MDM_VENDOR_NAME ON MDM_VENDOR (VENDOR_NAME);

CREATE TABLE MDM_VENDOR_ITEM (
    VENDOR_ITEM_ID  NVARCHAR(50)    NOT NULL,
    VENDOR_ID       NVARCHAR(50)    NOT NULL,
    PRODUCT_ID      NVARCHAR(50)    NOT NULL,
    LEAD_TIME_DAYS  DECIMAL(18,4)   NULL,
    MOQ             DECIMAL(18,4)   NULL,
    BASE_PRICE      DECIMAL(18,4)   NULL,
    DESCRIPTION     NVARCHAR(500)   NULL,
    IS_ACTIVE       BIT             NOT NULL DEFAULT 1,
    CREATED_BY      NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY      NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_MDM_VENDOR_ITEM PRIMARY KEY (VENDOR_ITEM_ID),
    CONSTRAINT FK_MDM_VENDOR_ITEM_VENDOR FOREIGN KEY (VENDOR_ID) REFERENCES MDM_VENDOR (VENDOR_ID)
);

CREATE INDEX IX_MDM_VENDOR_ITEM_VENDOR ON MDM_VENDOR_ITEM (VENDOR_ID);
