-- POM Module: 작업지시(Work Order). 레거시 PPM_TB_WORK_ORDER를 현행 관례로 단순 포팅(ENTERPRISE/다국어 제거,
-- ITEM_DEF→PRODUCT 정규화, 복합PK→단일PK, VALID_STATE→감사 DEFAULT). 기존 보류 해소 — POM_LOT.WORK_ORDER_ID(V014)가
-- 이미 이 테이블을 가리키는 FK 컬럼이었으나 본체 테이블이 없었다. SmartUX FACTORY_PPM W/O 관리/작업지시 현황 점등용.
CREATE TABLE POM_WORK_ORDER (
    WORK_ORDER_ID       NVARCHAR(50)    NOT NULL,
    PLANT_ID            NVARCHAR(50)    NOT NULL,
    WORK_ORDER_NAME     NVARCHAR(200)   NULL,
    PRODUCTION_ORDER_ID NVARCHAR(50)    NOT NULL,
    SALES_ORDER_ID      NVARCHAR(50)    NULL,
    AREA_ID             NVARCHAR(50)    NULL,
    EQUIPMENT_ID        NVARCHAR(50)    NULL,
    WORK_ORDER_TYPE     NVARCHAR(50)    NULL,
    PRODUCT_ID          NVARCHAR(50)    NOT NULL,
    PLAN_START_DATE     DATETIME2       NULL,
    PLAN_END_DATE       DATETIME2       NULL,
    PLAN_QTY            DECIMAL(18,4)   NOT NULL DEFAULT 0,
    START_QTY           DECIMAL(18,4)   NOT NULL DEFAULT 0,
    COMPLETE_QTY        DECIMAL(18,4)   NOT NULL DEFAULT 0,
    SCRAP_QTY           DECIMAL(18,4)   NOT NULL DEFAULT 0,
    OWNER_ID            NVARCHAR(50)    NULL,
    STATUS              NVARCHAR(20)    NOT NULL DEFAULT 'Created',   -- Created/Released/Started/Completed/Cancelled
    IS_HOLD             CHAR(1)         NOT NULL DEFAULT 'N',
    STARTED_AT          DATETIME2       NULL,
    COMPLETED_AT        DATETIME2       NULL,
    DESCRIPTION         NVARCHAR(500)   NULL,
    CREATED_BY          NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY          NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_POM_WORK_ORDER PRIMARY KEY (WORK_ORDER_ID)
);

CREATE INDEX IX_POM_WORK_ORDER_PLANT  ON POM_WORK_ORDER (PLANT_ID, PLAN_START_DATE DESC);
CREATE INDEX IX_POM_WORK_ORDER_STATUS ON POM_WORK_ORDER (STATUS);
