-- COM Module: 액션 정의 / 알람별 액션 매핑. 레거시 COM_TB_ACTION / COM_TB_ALARM_ACTION를 현행 관례로 단순 포팅
-- (ENTERPRISE/TXN 제거, 복합PK→대리키, VALID_STATE→IS_ACTIVE, 감사 DEFAULT). 알람 발생 시 수행할 조치(홀드/메일/SMS/
-- 프로시저)를 정의하고 알람에 순서대로 연결한다. SmartUX FACTORY_COM 알람 액션 관리/알람별 액션 관리 점등용.
CREATE TABLE COM_ACTION (
    ACTION_ID       NVARCHAR(50)    NOT NULL,
    ACTION_NAME     NVARCHAR(200)   NOT NULL,
    ACTION_TYPE     NVARCHAR(50)    NULL,        -- Hold/Email/Sms/Procedure
    HOLD_CODE       NVARCHAR(50)    NULL,
    EMAIL_TITLE     NVARCHAR(200)   NULL,
    SMS_TITLE       NVARCHAR(200)   NULL,
    PROCEDURE_NAME  NVARCHAR(200)   NULL,
    DESCRIPTION     NVARCHAR(500)   NULL,
    IS_ACTIVE       BIT             NOT NULL DEFAULT 1,
    CREATED_BY      NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY      NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_COM_ACTION PRIMARY KEY (ACTION_ID)
);

CREATE TABLE COM_ALARM_ACTION (
    ALARM_ACTION_ID  NVARCHAR(50)    NOT NULL,
    ALARM_ID         NVARCHAR(50)    NOT NULL,
    ACTION_ID        NVARCHAR(50)    NOT NULL,
    ACTION_SEQUENCE  INT             NOT NULL DEFAULT 1,
    DESCRIPTION      NVARCHAR(500)   NULL,
    IS_ACTIVE        BIT             NOT NULL DEFAULT 1,
    CREATED_BY       NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT       DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY       NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT       DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_COM_ALARM_ACTION PRIMARY KEY (ALARM_ACTION_ID),
    CONSTRAINT FK_COM_ALARM_ACTION_ACTION FOREIGN KEY (ACTION_ID) REFERENCES COM_ACTION (ACTION_ID)
);

CREATE INDEX IX_COM_ALARM_ACTION_ALARM ON COM_ALARM_ACTION (ALARM_ID, ACTION_SEQUENCE);
