-- FDC Module: 가상 이벤트 정의(SmartUX FDC>이벤트 관리>VIRTUAL EVENT 관리). 레거시
-- FDC_TB_VIRTUAL_EVENT_PARAMETER를 현행 관례로 포팅(다국어 EVENT_NAME_* 5종→단일 EVENT_NAME,
-- 감사 DEFAULT). EES_FDC_VIRTUAL_EVENT_MANAGEMENT 점등용.
-- 평가 엔진 구현됨: FDC VirtualEventFormula(재귀 하강 파서)+VirtualEventEvaluationWorker, 이력은 V069.
-- 1차 범위 = 정의 관리(CRUD)까지 — 평가 엔진(CONDITION_FORMULA를 수집 데이터에 적용해 EVENT_ON/OFF 판정,
-- 레거시 FDC_TB_VIRTUAL_EVENT_DATA_COLLECTION 기록)은 FDC 워커 후속 슬라이스.
CREATE TABLE FDC_VIRTUAL_EVENT (
    PLANT_ID            NVARCHAR(50)    NOT NULL,
    EQUIPMENT_ID        NVARCHAR(50)    NOT NULL,
    EVENT_ID            NVARCHAR(50)    NOT NULL,
    EVENT_NAME          NVARCHAR(200)   NOT NULL,
    EVENT_ON            NVARCHAR(200)   NULL,           -- ON 판정 값/식(레거시 형식 보존)
    EVENT_OFF           NVARCHAR(200)   NULL,           -- OFF 판정 값/식
    CONDITION_FORMULA   NVARCHAR(1000)  NULL,           -- 파라미터 조합 수식(평가 엔진 후속)
    DESCRIPTION         NVARCHAR(500)   NULL,
    VALID_STATE         NVARCHAR(20)    NOT NULL DEFAULT 'Valid',
    CREATED_BY          NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY          NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_FDC_VIRTUAL_EVENT PRIMARY KEY (EQUIPMENT_ID, EVENT_ID)
);

CREATE INDEX IX_FDC_VIRTUAL_EVENT_PLANT ON FDC_VIRTUAL_EVENT (PLANT_ID, VALID_STATE);
