-- 메뉴 ID 표준화(2026-07-09 메뉴 정보구조 감사) — 오타성 레거시 ID 5건 정정.
-- 원본 SmartUX ID는 PROGRAM_ID(미사용 여유 컬럼)에 보존해 이관 추적성을 유지하고,
-- 화면 정의는 구 ID 별칭(InMemoryScreenDefinitionProvider.RegisterAlias)으로 계속 열린다.
-- ⚠ SQLite 증분 경로는 UPDATE를 적용하지 않는다 — dev SQLite는 재생성으로 반영(런북 관례).
--    운영 MSSQL은 본 마이그레이션이 기존 행(i18n·메뉴·권한·개인화)을 일괄 리매핑한다.
--   EFFECIVENESS→EFFECTIVENESS · MONITERING→MONITORING · MOVE_ODER→MOVE_ORDER ·
--   QMS_REP_ITEM_STATUS.js→(확장자 제거) · ITOOLC{GUID}→SYSTEM2_COMMON(폴더)

-- ── i18n 리소스 키(V071 시드분) — menu.{MENU_ID} / screen.{UI_ID}.title ──────────
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET RESOURCE_KEY = 'menu.EES_EPT_OVERALL_EQUIPMENT_EFFECTIVENESS'   WHERE RESOURCE_KEY = 'menu.EES_EPT_OVERALL_EQUIPMENT_EFFECIVENESS';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET RESOURCE_KEY = 'screen.EES_EPT_OVERALL_EQUIPMENT_EFFECTIVENESS.title' WHERE RESOURCE_KEY = 'screen.EES_EPT_OVERALL_EQUIPMENT_EFFECIVENESS.title';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET RESOURCE_KEY = 'menu.EES_POPUP_MONITORING_DASHBOARD'            WHERE RESOURCE_KEY = 'menu.EES_POPUP_MONITERING_DASHBOARD';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET RESOURCE_KEY = 'screen.EES_POPUP_MONITORING_DASHBOARD.title'    WHERE RESOURCE_KEY = 'screen.EES_POPUP_MONITERING_DASHBOARD.title';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET RESOURCE_KEY = 'menu.FACTORY_IVT_MOVE_ORDER'                    WHERE RESOURCE_KEY = 'menu.FACTORY_IVT_MOVE_ODER';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET RESOURCE_KEY = 'screen.FACTORY_IVT_MOVE_ORDER.title'            WHERE RESOURCE_KEY = 'screen.FACTORY_IVT_MOVE_ODER.title';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET RESOURCE_KEY = 'menu.QMS_REP_ITEM_STATUS'                       WHERE RESOURCE_KEY = 'menu.QMS_REP_ITEM_STATUS.js';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET RESOURCE_KEY = 'screen.QMS_REP_ITEM_STATUS.title'               WHERE RESOURCE_KEY = 'screen.QMS_REP_ITEM_STATUS.js.title';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET RESOURCE_KEY = 'menu.SYSTEM2_COMMON'                            WHERE RESOURCE_KEY = 'menu.ITOOLC4390041D17C4B26DE5D5C9B729B7498';

-- ── 메뉴 본체 — 새 ID + PROGRAM_ID=구 ID 보존 (신규 DB는 빈 테이블이라 무해 no-op) ──
UPDATE SYS_MENU SET MENU_ID = 'EES_EPT_OVERALL_EQUIPMENT_EFFECTIVENESS', UI_ID = 'EES_EPT_OVERALL_EQUIPMENT_EFFECTIVENESS', PROGRAM_ID = 'EES_EPT_OVERALL_EQUIPMENT_EFFECIVENESS' WHERE MENU_ID = 'EES_EPT_OVERALL_EQUIPMENT_EFFECIVENESS';
UPDATE SYS_MENU SET MENU_ID = 'EES_POPUP_MONITORING_DASHBOARD', UI_ID = 'EES_POPUP_MONITORING_DASHBOARD', PROGRAM_ID = 'EES_POPUP_MONITERING_DASHBOARD' WHERE MENU_ID = 'EES_POPUP_MONITERING_DASHBOARD';
UPDATE SYS_MENU SET MENU_ID = 'FACTORY_IVT_MOVE_ORDER', UI_ID = 'FACTORY_IVT_MOVE_ORDER', PROGRAM_ID = 'FACTORY_IVT_MOVE_ODER' WHERE MENU_ID = 'FACTORY_IVT_MOVE_ODER';
UPDATE SYS_MENU SET MENU_ID = 'QMS_REP_ITEM_STATUS', UI_ID = 'QMS_REP_ITEM_STATUS', PROGRAM_ID = 'QMS_REP_ITEM_STATUS.js' WHERE MENU_ID = 'QMS_REP_ITEM_STATUS.js';
UPDATE SYS_MENU SET MENU_ID = 'SYSTEM2_COMMON', PROGRAM_ID = 'ITOOLC4390041D17C4B26DE5D5C9B729B7498' WHERE MENU_ID = 'ITOOLC4390041D17C4B26DE5D5C9B729B7498';
UPDATE SYS_MENU SET PARENT_MENU_ID = 'SYSTEM2_COMMON' WHERE PARENT_MENU_ID = 'ITOOLC4390041D17C4B26DE5D5C9B729B7498';

-- ── 참조 테이블 리매핑 — 권한(SYS_MENU_ROLE)·개인화(즐겨찾기/최근, V013 FK 없음) ──
UPDATE SYS_MENU_ROLE SET MENU_ID = 'EES_EPT_OVERALL_EQUIPMENT_EFFECTIVENESS' WHERE MENU_ID = 'EES_EPT_OVERALL_EQUIPMENT_EFFECIVENESS';
UPDATE SYS_MENU_ROLE SET MENU_ID = 'EES_POPUP_MONITORING_DASHBOARD' WHERE MENU_ID = 'EES_POPUP_MONITERING_DASHBOARD';
UPDATE SYS_MENU_ROLE SET MENU_ID = 'FACTORY_IVT_MOVE_ORDER' WHERE MENU_ID = 'FACTORY_IVT_MOVE_ODER';
UPDATE SYS_MENU_ROLE SET MENU_ID = 'QMS_REP_ITEM_STATUS' WHERE MENU_ID = 'QMS_REP_ITEM_STATUS.js';
UPDATE SYS_MENU_ROLE SET MENU_ID = 'SYSTEM2_COMMON' WHERE MENU_ID = 'ITOOLC4390041D17C4B26DE5D5C9B729B7498';
UPDATE SYS_FAVORITE_MENU SET MENU_ID = 'EES_EPT_OVERALL_EQUIPMENT_EFFECTIVENESS' WHERE MENU_ID = 'EES_EPT_OVERALL_EQUIPMENT_EFFECIVENESS';
UPDATE SYS_FAVORITE_MENU SET MENU_ID = 'EES_POPUP_MONITORING_DASHBOARD' WHERE MENU_ID = 'EES_POPUP_MONITERING_DASHBOARD';
UPDATE SYS_FAVORITE_MENU SET MENU_ID = 'FACTORY_IVT_MOVE_ORDER' WHERE MENU_ID = 'FACTORY_IVT_MOVE_ODER';
UPDATE SYS_FAVORITE_MENU SET MENU_ID = 'QMS_REP_ITEM_STATUS' WHERE MENU_ID = 'QMS_REP_ITEM_STATUS.js';
UPDATE SYS_RECENT_MENU SET MENU_ID = 'EES_EPT_OVERALL_EQUIPMENT_EFFECTIVENESS' WHERE MENU_ID = 'EES_EPT_OVERALL_EQUIPMENT_EFFECIVENESS';
UPDATE SYS_RECENT_MENU SET MENU_ID = 'EES_POPUP_MONITORING_DASHBOARD' WHERE MENU_ID = 'EES_POPUP_MONITERING_DASHBOARD';
UPDATE SYS_RECENT_MENU SET MENU_ID = 'FACTORY_IVT_MOVE_ORDER' WHERE MENU_ID = 'FACTORY_IVT_MOVE_ODER';
UPDATE SYS_RECENT_MENU SET MENU_ID = 'QMS_REP_ITEM_STATUS' WHERE MENU_ID = 'QMS_REP_ITEM_STATUS.js';
