-- 메뉴 ID 약어 정리(2026-07-10) — MGNT→MANAGEMENT(3)·REGIST→REGISTRATION(5)·_HI→_HISTORY(1).
-- V081 규약 동일: 원본은 PROGRAM_ID 보존·프로바이더 별칭으로 구 URL 유지·기존 행(i18n/메뉴/권한/개인화) 일괄 리매핑.
-- _GRIDTYPE 6건은 유지 — 접미 제거 시 기존 형제 ID와 충돌(레거시 쌍둥이 화면 구분자, 단순 약어 아님).
-- ⚠ SQLite 증분 경로는 UPDATE 미적용 — dev는 재생성, 운영 MSSQL은 본 마이그레이션이 처리.

UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET RESOURCE_KEY = 'menu.EPT_STD_INDEX_MANAGEMENT' WHERE RESOURCE_KEY = 'menu.EPT_STD_INDEX_MGNT';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET RESOURCE_KEY = 'screen.EPT_STD_INDEX_MANAGEMENT.title' WHERE RESOURCE_KEY = 'screen.EPT_STD_INDEX_MGNT.title';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET RESOURCE_KEY = 'menu.EPT_STD_LAYOUT_MANAGEMENT' WHERE RESOURCE_KEY = 'menu.EPT_STD_LAYOUT_MGNT';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET RESOURCE_KEY = 'screen.EPT_STD_LAYOUT_MANAGEMENT.title' WHERE RESOURCE_KEY = 'screen.EPT_STD_LAYOUT_MGNT.title';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET RESOURCE_KEY = 'menu.QMS_GAUGE_MEASURE_EQUIPMENT_MANAGEMENT' WHERE RESOURCE_KEY = 'menu.QMS_GAUGE_MEASURE_EQUIPMENT_MGNT';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET RESOURCE_KEY = 'screen.QMS_GAUGE_MEASURE_EQUIPMENT_MANAGEMENT.title' WHERE RESOURCE_KEY = 'screen.QMS_GAUGE_MEASURE_EQUIPMENT_MGNT.title';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET RESOURCE_KEY = 'menu.QMS_CLM_CLAIM_REGISTRATION' WHERE RESOURCE_KEY = 'menu.QMS_CLM_CLAIM_REGIST';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET RESOURCE_KEY = 'screen.QMS_CLM_CLAIM_REGISTRATION.title' WHERE RESOURCE_KEY = 'screen.QMS_CLM_CLAIM_REGIST.title';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET RESOURCE_KEY = 'menu.QMS_INSP_IMPORT_REGISTRATION_HIST' WHERE RESOURCE_KEY = 'menu.QMS_INSP_IMPORT_REGIST_HIST';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET RESOURCE_KEY = 'screen.QMS_INSP_IMPORT_REGISTRATION_HIST.title' WHERE RESOURCE_KEY = 'screen.QMS_INSP_IMPORT_REGIST_HIST.title';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET RESOURCE_KEY = 'menu.QMS_INSP_PROCESS_REGISTRATION_HIST' WHERE RESOURCE_KEY = 'menu.QMS_INSP_PROCESS_REGIST_HIST';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET RESOURCE_KEY = 'screen.QMS_INSP_PROCESS_REGISTRATION_HIST.title' WHERE RESOURCE_KEY = 'screen.QMS_INSP_PROCESS_REGIST_HIST.title';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET RESOURCE_KEY = 'menu.QMS_INSP_SHIPPING_REGISTRATION_HIST' WHERE RESOURCE_KEY = 'menu.QMS_INSP_SHIPPING_REGIST_HIST';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET RESOURCE_KEY = 'screen.QMS_INSP_SHIPPING_REGISTRATION_HIST.title' WHERE RESOURCE_KEY = 'screen.QMS_INSP_SHIPPING_REGIST_HIST.title';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET RESOURCE_KEY = 'menu.QMS_SPM_ADMIN_ACTION_RESULT_REGISTRATION' WHERE RESOURCE_KEY = 'menu.QMS_SPM_ADMIN_ACTION_RESULT_REGIST';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET RESOURCE_KEY = 'screen.QMS_SPM_ADMIN_ACTION_RESULT_REGISTRATION.title' WHERE RESOURCE_KEY = 'screen.QMS_SPM_ADMIN_ACTION_RESULT_REGIST.title';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET RESOURCE_KEY = 'menu.EES_FDC_VIRTUAL_EVENT_HISTORY' WHERE RESOURCE_KEY = 'menu.EES_FDC_VIRTUAL_EVENT_HI';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET RESOURCE_KEY = 'screen.EES_FDC_VIRTUAL_EVENT_HISTORY.title' WHERE RESOURCE_KEY = 'screen.EES_FDC_VIRTUAL_EVENT_HI.title';

UPDATE SYS_MENU SET MENU_ID = 'EPT_STD_INDEX_MANAGEMENT', UI_ID = 'EPT_STD_INDEX_MANAGEMENT', PROGRAM_ID = 'EPT_STD_INDEX_MGNT' WHERE MENU_ID = 'EPT_STD_INDEX_MGNT';
UPDATE SYS_MENU SET MENU_ID = 'EPT_STD_LAYOUT_MANAGEMENT', UI_ID = 'EPT_STD_LAYOUT_MANAGEMENT', PROGRAM_ID = 'EPT_STD_LAYOUT_MGNT' WHERE MENU_ID = 'EPT_STD_LAYOUT_MGNT';
UPDATE SYS_MENU SET MENU_ID = 'QMS_GAUGE_MEASURE_EQUIPMENT_MANAGEMENT', UI_ID = 'QMS_GAUGE_MEASURE_EQUIPMENT_MANAGEMENT', PROGRAM_ID = 'QMS_GAUGE_MEASURE_EQUIPMENT_MGNT' WHERE MENU_ID = 'QMS_GAUGE_MEASURE_EQUIPMENT_MGNT';
UPDATE SYS_MENU SET MENU_ID = 'QMS_CLM_CLAIM_REGISTRATION', UI_ID = 'QMS_CLM_CLAIM_REGISTRATION', PROGRAM_ID = 'QMS_CLM_CLAIM_REGIST' WHERE MENU_ID = 'QMS_CLM_CLAIM_REGIST';
UPDATE SYS_MENU SET MENU_ID = 'QMS_INSP_IMPORT_REGISTRATION_HIST', UI_ID = 'QMS_INSP_IMPORT_REGISTRATION_HIST', PROGRAM_ID = 'QMS_INSP_IMPORT_REGIST_HIST' WHERE MENU_ID = 'QMS_INSP_IMPORT_REGIST_HIST';
UPDATE SYS_MENU SET MENU_ID = 'QMS_INSP_PROCESS_REGISTRATION_HIST', UI_ID = 'QMS_INSP_PROCESS_REGISTRATION_HIST', PROGRAM_ID = 'QMS_INSP_PROCESS_REGIST_HIST' WHERE MENU_ID = 'QMS_INSP_PROCESS_REGIST_HIST';
UPDATE SYS_MENU SET MENU_ID = 'QMS_INSP_SHIPPING_REGISTRATION_HIST', UI_ID = 'QMS_INSP_SHIPPING_REGISTRATION_HIST', PROGRAM_ID = 'QMS_INSP_SHIPPING_REGIST_HIST' WHERE MENU_ID = 'QMS_INSP_SHIPPING_REGIST_HIST';
UPDATE SYS_MENU SET MENU_ID = 'QMS_SPM_ADMIN_ACTION_RESULT_REGISTRATION', UI_ID = 'QMS_SPM_ADMIN_ACTION_RESULT_REGISTRATION', PROGRAM_ID = 'QMS_SPM_ADMIN_ACTION_RESULT_REGIST' WHERE MENU_ID = 'QMS_SPM_ADMIN_ACTION_RESULT_REGIST';
UPDATE SYS_MENU SET MENU_ID = 'EES_FDC_VIRTUAL_EVENT_HISTORY', UI_ID = 'EES_FDC_VIRTUAL_EVENT_HISTORY', PROGRAM_ID = 'EES_FDC_VIRTUAL_EVENT_HI' WHERE MENU_ID = 'EES_FDC_VIRTUAL_EVENT_HI';

UPDATE SYS_MENU_ROLE SET MENU_ID = 'EPT_STD_INDEX_MANAGEMENT' WHERE MENU_ID = 'EPT_STD_INDEX_MGNT';
UPDATE SYS_MENU_ROLE SET MENU_ID = 'EPT_STD_LAYOUT_MANAGEMENT' WHERE MENU_ID = 'EPT_STD_LAYOUT_MGNT';
UPDATE SYS_MENU_ROLE SET MENU_ID = 'QMS_GAUGE_MEASURE_EQUIPMENT_MANAGEMENT' WHERE MENU_ID = 'QMS_GAUGE_MEASURE_EQUIPMENT_MGNT';
UPDATE SYS_MENU_ROLE SET MENU_ID = 'QMS_CLM_CLAIM_REGISTRATION' WHERE MENU_ID = 'QMS_CLM_CLAIM_REGIST';
UPDATE SYS_MENU_ROLE SET MENU_ID = 'QMS_INSP_IMPORT_REGISTRATION_HIST' WHERE MENU_ID = 'QMS_INSP_IMPORT_REGIST_HIST';
UPDATE SYS_MENU_ROLE SET MENU_ID = 'QMS_INSP_PROCESS_REGISTRATION_HIST' WHERE MENU_ID = 'QMS_INSP_PROCESS_REGIST_HIST';
UPDATE SYS_MENU_ROLE SET MENU_ID = 'QMS_INSP_SHIPPING_REGISTRATION_HIST' WHERE MENU_ID = 'QMS_INSP_SHIPPING_REGIST_HIST';
UPDATE SYS_MENU_ROLE SET MENU_ID = 'QMS_SPM_ADMIN_ACTION_RESULT_REGISTRATION' WHERE MENU_ID = 'QMS_SPM_ADMIN_ACTION_RESULT_REGIST';
UPDATE SYS_MENU_ROLE SET MENU_ID = 'EES_FDC_VIRTUAL_EVENT_HISTORY' WHERE MENU_ID = 'EES_FDC_VIRTUAL_EVENT_HI';
UPDATE SYS_FAVORITE_MENU SET MENU_ID = 'EPT_STD_INDEX_MANAGEMENT' WHERE MENU_ID = 'EPT_STD_INDEX_MGNT';
UPDATE SYS_FAVORITE_MENU SET MENU_ID = 'EPT_STD_LAYOUT_MANAGEMENT' WHERE MENU_ID = 'EPT_STD_LAYOUT_MGNT';
UPDATE SYS_FAVORITE_MENU SET MENU_ID = 'QMS_GAUGE_MEASURE_EQUIPMENT_MANAGEMENT' WHERE MENU_ID = 'QMS_GAUGE_MEASURE_EQUIPMENT_MGNT';
UPDATE SYS_FAVORITE_MENU SET MENU_ID = 'QMS_CLM_CLAIM_REGISTRATION' WHERE MENU_ID = 'QMS_CLM_CLAIM_REGIST';
UPDATE SYS_FAVORITE_MENU SET MENU_ID = 'QMS_INSP_IMPORT_REGISTRATION_HIST' WHERE MENU_ID = 'QMS_INSP_IMPORT_REGIST_HIST';
UPDATE SYS_FAVORITE_MENU SET MENU_ID = 'QMS_INSP_PROCESS_REGISTRATION_HIST' WHERE MENU_ID = 'QMS_INSP_PROCESS_REGIST_HIST';
UPDATE SYS_FAVORITE_MENU SET MENU_ID = 'QMS_INSP_SHIPPING_REGISTRATION_HIST' WHERE MENU_ID = 'QMS_INSP_SHIPPING_REGIST_HIST';
UPDATE SYS_FAVORITE_MENU SET MENU_ID = 'QMS_SPM_ADMIN_ACTION_RESULT_REGISTRATION' WHERE MENU_ID = 'QMS_SPM_ADMIN_ACTION_RESULT_REGIST';
UPDATE SYS_FAVORITE_MENU SET MENU_ID = 'EES_FDC_VIRTUAL_EVENT_HISTORY' WHERE MENU_ID = 'EES_FDC_VIRTUAL_EVENT_HI';
UPDATE SYS_RECENT_MENU SET MENU_ID = 'EPT_STD_INDEX_MANAGEMENT' WHERE MENU_ID = 'EPT_STD_INDEX_MGNT';
UPDATE SYS_RECENT_MENU SET MENU_ID = 'EPT_STD_LAYOUT_MANAGEMENT' WHERE MENU_ID = 'EPT_STD_LAYOUT_MGNT';
UPDATE SYS_RECENT_MENU SET MENU_ID = 'QMS_GAUGE_MEASURE_EQUIPMENT_MANAGEMENT' WHERE MENU_ID = 'QMS_GAUGE_MEASURE_EQUIPMENT_MGNT';
UPDATE SYS_RECENT_MENU SET MENU_ID = 'QMS_CLM_CLAIM_REGISTRATION' WHERE MENU_ID = 'QMS_CLM_CLAIM_REGIST';
UPDATE SYS_RECENT_MENU SET MENU_ID = 'QMS_INSP_IMPORT_REGISTRATION_HIST' WHERE MENU_ID = 'QMS_INSP_IMPORT_REGIST_HIST';
UPDATE SYS_RECENT_MENU SET MENU_ID = 'QMS_INSP_PROCESS_REGISTRATION_HIST' WHERE MENU_ID = 'QMS_INSP_PROCESS_REGIST_HIST';
UPDATE SYS_RECENT_MENU SET MENU_ID = 'QMS_INSP_SHIPPING_REGISTRATION_HIST' WHERE MENU_ID = 'QMS_INSP_SHIPPING_REGIST_HIST';
UPDATE SYS_RECENT_MENU SET MENU_ID = 'QMS_SPM_ADMIN_ACTION_RESULT_REGISTRATION' WHERE MENU_ID = 'QMS_SPM_ADMIN_ACTION_RESULT_REGIST';
UPDATE SYS_RECENT_MENU SET MENU_ID = 'EES_FDC_VIRTUAL_EVENT_HISTORY' WHERE MENU_ID = 'EES_FDC_VIRTUAL_EVENT_HI';
