-- CRP v1 마스터(2026-07-10) — 워크센터·라우팅 스텝. 스펙: 볼트 2026-07-09-mrp-v1-design.md 'v2 4단' 절.
-- 부하 산식은 명명 쿼리(POM.CrpWorkCenterLoad)가 소유 — 계산기/워커 불요(총량 SQL 집계 v1).
-- 신규 테이블 — SQLite 증분 경로 자동 생성(ALTER 아님). 기존 MDM_ROUTING(헤더)을 재사용한다.
CREATE TABLE MDM_WORK_CENTER (
    WORK_CENTER_ID      NVARCHAR(50)    NOT NULL,
    WORK_CENTER_NAME    NVARCHAR(200)   NOT NULL,
    PLANT_ID            NVARCHAR(50)    NULL,
    DAILY_CAPACITY_MIN  DECIMAL(18,2)   NOT NULL DEFAULT 480,   -- 분/일(1교대 480 기본)
    IS_ACTIVE           CHAR(1)         NOT NULL DEFAULT 'Y',
    DESCRIPTION         NVARCHAR(500)   NULL,
    CREATED_BY          NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY          NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_MDM_WORK_CENTER PRIMARY KEY (WORK_CENTER_ID)
);

CREATE TABLE MDM_ROUTING_STEP (
    ROUTING_ID          NVARCHAR(50)    NOT NULL,
    STEP_NO             INT             NOT NULL,
    STEP_NAME           NVARCHAR(200)   NULL,
    WORK_CENTER_ID      NVARCHAR(50)    NOT NULL,
    STD_TIME_MIN        DECIMAL(18,4)   NOT NULL DEFAULT 0,     -- 개당 표준시간(분)
    CREATED_BY          NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY          NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_MDM_ROUTING_STEP PRIMARY KEY (ROUTING_ID, STEP_NO)
);

CREATE INDEX IX_MDM_ROUTING_STEP_WC ON MDM_ROUTING_STEP (WORK_CENTER_ID);
