-- 화면 진입 채널/경로 메타데이터(2026-07-10).
-- SYS_SCREEN_DEFINITION은 렌더링 JSON을 소유하고, 본 1:1 확장 테이블은 MES/Mobile/POP 라우팅만 소유한다.
-- 신규 테이블 방식이라 기존 SQLite DB도 CreateMissingTables 증분 경로로 재생성 없이 반영된다.
CREATE TABLE SYS_SCREEN_TARGET (
    UI_ID           NVARCHAR(100)   NOT NULL,
    TARGET_CHANNEL  NVARCHAR(20)    NOT NULL DEFAULT 'MES',
    ENTRY_PATH      NVARCHAR(220)   NOT NULL,
    CREATED_BY      NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY      NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_SYS_SCREEN_TARGET PRIMARY KEY (UI_ID),
    CONSTRAINT FK_SYS_SCREEN_TARGET_DEFINITION FOREIGN KEY (UI_ID)
        REFERENCES SYS_SCREEN_DEFINITION (UI_ID) ON DELETE CASCADE,
    CONSTRAINT CK_SYS_SCREEN_TARGET_CHANNEL
        CHECK (TARGET_CHANNEL IN ('MES', 'MOBILE', 'POP')),
    CONSTRAINT CK_SYS_SCREEN_TARGET_ENTRY_PATH
        CHECK (
            (TARGET_CHANNEL = 'MES'    AND ENTRY_PATH LIKE '/meta/%') OR
            (TARGET_CHANNEL = 'MOBILE' AND ENTRY_PATH LIKE '/Mobile/%') OR
            (TARGET_CHANNEL = 'POP'    AND ENTRY_PATH LIKE '/POP/%')
        )
);

CREATE UNIQUE INDEX UX_SYS_SCREEN_TARGET_ENTRY_PATH
    ON SYS_SCREEN_TARGET (ENTRY_PATH);

CREATE INDEX IX_SYS_SCREEN_TARGET_CHANNEL
    ON SYS_SCREEN_TARGET (TARGET_CHANNEL, UI_ID);
