-- POM production-order/work-order boundary.
-- Existing MSSQL data must be mapped before this migration when orphan work orders exist;
-- the NOT NULL/FK changes intentionally fail instead of inventing a parent.
ALTER TABLE POM_WORK_ORDER ADD
    ROUTING_ID       NVARCHAR(50) NULL,
    ROUTING_STEP_NO  INT          NULL,
    PROCESS_ID       NVARCHAR(50) NULL,
    WORK_CENTER_ID   NVARCHAR(50) NULL;

UPDATE POM_WORK_ORDER
SET PRODUCT_ID = (
    SELECT O.PRODUCT_ID
    FROM POM_PRODUCTION_ORDER O
    WHERE O.ORDER_ID = POM_WORK_ORDER.PRODUCTION_ORDER_ID
)
WHERE (PRODUCT_ID IS NULL OR LTRIM(RTRIM(PRODUCT_ID)) = '')
  AND EXISTS (
      SELECT 1 FROM POM_PRODUCTION_ORDER O
      WHERE O.ORDER_ID = POM_WORK_ORDER.PRODUCTION_ORDER_ID
  );

ALTER TABLE POM_WORK_ORDER
    ALTER COLUMN PRODUCT_ID NVARCHAR(50) NOT NULL;

ALTER TABLE POM_WORK_ORDER
    ALTER COLUMN PRODUCTION_ORDER_ID NVARCHAR(50) NOT NULL;

ALTER TABLE POM_WORK_ORDER ADD VERSION_NO INT NOT NULL DEFAULT 1;

ALTER TABLE POM_WORK_ORDER ADD CONSTRAINT FK_POM_WORK_ORDER_PRODUCTION_ORDER
    FOREIGN KEY (PRODUCTION_ORDER_ID) REFERENCES POM_PRODUCTION_ORDER (ORDER_ID);

ALTER TABLE POM_LOT ADD CONSTRAINT FK_POM_LOT_WORK_ORDER
    FOREIGN KEY (WORK_ORDER_ID) REFERENCES POM_WORK_ORDER (WORK_ORDER_ID);

ALTER TABLE POM_WORK_ORDER ADD CONSTRAINT CK_POM_WORK_ORDER_STATUS
    CHECK (STATUS IN ('Created', 'Released', 'Started', 'Completed', 'Cancelled'));

ALTER TABLE POM_WORK_ORDER ADD CONSTRAINT CK_POM_WORK_ORDER_HOLD
    CHECK (IS_HOLD IN ('Y', 'N'));

ALTER TABLE POM_WORK_ORDER ADD CONSTRAINT CK_POM_WORK_ORDER_QTY
    CHECK (
        PLAN_QTY > 0 AND START_QTY >= 0 AND COMPLETE_QTY >= 0 AND SCRAP_QTY >= 0
        AND VERSION_NO >= 1
        AND START_QTY <= PLAN_QTY
        AND COMPLETE_QTY + SCRAP_QTY <= CASE WHEN START_QTY > 0 THEN START_QTY ELSE PLAN_QTY END
    );

CREATE INDEX IX_POM_WORK_ORDER_PARENT
    ON POM_WORK_ORDER (PRODUCTION_ORDER_ID, ROUTING_STEP_NO, STATUS);

CREATE INDEX IX_POM_WORK_ORDER_OPERATOR
    ON POM_WORK_ORDER (PLANT_ID, PROCESS_ID, EQUIPMENT_ID, STATUS);

CREATE INDEX IX_POM_WORK_ORDER_OWNER
    ON POM_WORK_ORDER (OWNER_ID, STATUS);
