-- Append-only work execution audit and client retry protection for MES/Mobile/POP.
CREATE TABLE POM_WORK_ORDER_EXECUTION (
    EXECUTION_ID       NVARCHAR(50)    NOT NULL,
    WORK_ORDER_ID      NVARCHAR(50)    NOT NULL,
    IDEMPOTENCY_KEY    NVARCHAR(100)   NOT NULL,
    ACTION             NVARCHAR(30)    NOT NULL,
    FROM_STATUS        NVARCHAR(20)    NOT NULL,
    TO_STATUS          NVARCHAR(20)    NOT NULL,
    GOOD_QTY           DECIMAL(18,4)   NULL,
    DEFECT_QTY         DECIMAL(18,4)   NULL,
    USER_ID            NVARCHAR(50)    NOT NULL,
    EQUIPMENT_ID       NVARCHAR(50)    NULL,
    CLIENT_CHANNEL     NVARCHAR(20)    NOT NULL,
    DEVICE_ID          NVARCHAR(100)   NULL,
    OCCURRED_AT        DATETIME2       NOT NULL,
    REMARK             NVARCHAR(500)   NULL,
    CREATED_BY         NVARCHAR(50)    NOT NULL,
    CREATED_AT         DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_POM_WORK_ORDER_EXECUTION PRIMARY KEY (EXECUTION_ID),
    CONSTRAINT UQ_POM_WORK_ORDER_EXECUTION_KEY UNIQUE (IDEMPOTENCY_KEY),
    CONSTRAINT FK_POM_WORK_ORDER_EXECUTION_WO FOREIGN KEY (WORK_ORDER_ID)
        REFERENCES POM_WORK_ORDER (WORK_ORDER_ID),
    CONSTRAINT CK_POM_WORK_ORDER_EXECUTION_CHANNEL
        CHECK (CLIENT_CHANNEL IN ('MES', 'MOBILE', 'POP')),
    CONSTRAINT CK_POM_WORK_ORDER_EXECUTION_ACTION
        CHECK (ACTION IN ('Release', 'Start', 'Report', 'Hold', 'ReleaseHold', 'Complete', 'Cancel'))
);

CREATE INDEX IX_POM_WORK_ORDER_EXECUTION_WO
    ON POM_WORK_ORDER_EXECUTION (WORK_ORDER_ID, OCCURRED_AT DESC);

CREATE INDEX IX_POM_WORK_ORDER_EXECUTION_USER
    ON POM_WORK_ORDER_EXECUTION (USER_ID, OCCURRED_AT DESC);
