-- Lot optimistic concurrency, idempotent shop-floor execution, and traceability integrity.
ALTER TABLE POM_LOT ADD VERSION_NO INT NOT NULL DEFAULT 1;
ALTER TABLE POM_LOT_HISTORY ADD REASON NVARCHAR(500) NULL;
ALTER TABLE POM_LOT_HISTORY ADD IDEMPOTENCY_KEY NVARCHAR(100) NULL;

CREATE TABLE POM_LOT_EXECUTION (
    EXECUTION_ID        NVARCHAR(50)  NOT NULL,
    LOT_ID              NVARCHAR(50)  NOT NULL,
    ACTION              NVARCHAR(30)  NOT NULL,
    IDEMPOTENCY_KEY     NVARCHAR(100) NOT NULL,
    REQUEST_HASH        NVARCHAR(64)  NOT NULL,
    EXPECTED_VERSION    INT           NOT NULL,
    RESULT_VERSION      INT           NOT NULL,
    CREATED_BY          NVARCHAR(50)  NOT NULL,
    CREATED_AT          DATETIME2     NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_POM_LOT_EXECUTION PRIMARY KEY (EXECUTION_ID),
    CONSTRAINT UQ_POM_LOT_EXECUTION_KEY UNIQUE (IDEMPOTENCY_KEY),
    CONSTRAINT FK_POM_LOT_EXECUTION_LOT FOREIGN KEY (LOT_ID) REFERENCES POM_LOT (LOT_ID),
    CONSTRAINT CK_POM_LOT_EXECUTION_VERSION CHECK (EXPECTED_VERSION >= 1 AND RESULT_VERSION = EXPECTED_VERSION + 1)
);

CREATE UNIQUE INDEX UX_POM_WORK_ORDER_LOT_BOUNDARY
    ON POM_WORK_ORDER (WORK_ORDER_ID, PLANT_ID, PRODUCT_ID);
CREATE UNIQUE INDEX UX_POM_LOT_PLANT_BOUNDARY
    ON POM_LOT (LOT_ID, PLANT_ID);

ALTER TABLE POM_LOT ADD CONSTRAINT FK_POM_LOT_WORK_ORDER_BOUNDARY
    FOREIGN KEY (WORK_ORDER_ID, PLANT_ID, PRODUCT_ID)
    REFERENCES POM_WORK_ORDER (WORK_ORDER_ID, PLANT_ID, PRODUCT_ID);
ALTER TABLE POM_LOT ADD CONSTRAINT CK_POM_LOT_EXECUTION_STATE CHECK (
    QTY > 0 AND DEFECT_QTY >= 0 AND DEFECT_QTY <= QTY AND VERSION_NO >= 1
    AND LOT_STATE IN ('Created', 'Queued', 'Processing', 'Completed', 'Consumed')
    AND PROCESS_STATE IN ('Idle', 'Run') AND IS_HOLD IN ('Y', 'N')
);

ALTER TABLE POM_LOT_HISTORY ADD CONSTRAINT FK_POM_LOT_HISTORY_LOT
    FOREIGN KEY (LOT_ID, PLANT_ID) REFERENCES POM_LOT (LOT_ID, PLANT_ID);
ALTER TABLE POM_LOT_HISTORY ADD CONSTRAINT CK_POM_LOT_HISTORY_QTY
    CHECK (QTY > 0 AND DEFECT_QTY >= 0 AND DEFECT_QTY <= QTY);
CREATE UNIQUE INDEX UX_POM_LOT_HISTORY_IDEMPOTENCY
    ON POM_LOT_HISTORY (IDEMPOTENCY_KEY) WHERE IDEMPOTENCY_KEY IS NOT NULL;

ALTER TABLE POM_LOT_MIXING_RELATION ADD CONSTRAINT FK_POM_LOT_MIX_OUTPUT
    FOREIGN KEY (OUTPUT_LOT_ID, PLANT_ID) REFERENCES POM_LOT (LOT_ID, PLANT_ID);
ALTER TABLE POM_LOT_MIXING_RELATION ADD CONSTRAINT FK_POM_LOT_MIX_INPUT
    FOREIGN KEY (INPUT_LOT_ID, PLANT_ID) REFERENCES POM_LOT (LOT_ID, PLANT_ID);
ALTER TABLE POM_LOT_MIXING_RELATION ADD CONSTRAINT CK_POM_LOT_MIX_QTY
    CHECK (INPUT_QTY > 0 AND (MIXING_RATE IS NULL OR (MIXING_RATE > 0 AND MIXING_RATE <= 1)));

CREATE INDEX IX_POM_LOT_EXECUTION_LOT
    ON POM_LOT_EXECUTION (LOT_ID, CREATED_AT);
