-- Link the execution header and measured item result. Existing result identifiers are used as
-- deterministic one-to-one inspection identifiers so legacy rows remain traceable.
ALTER TABLE QMS_INSPECTION_RESULT ADD
    INSPECTION_ID NVARCHAR(50) NULL;

UPDATE QMS_INSPECTION_RESULT
SET INSPECTION_ID = RESULT_ID
WHERE INSPECTION_ID IS NULL;

UPDATE QMS_INSPECTION_SPEC
SET MEASURE_TYPE = 'Variable'
WHERE MEASURE_TYPE = 'Numeric';

INSERT INTO QMS_INSPECTION
    (INSPECTION_ID, INSPECTION_TYPE, LOT_ID, EQUIPMENT_ID, SPEC_ID,
     INSPECTED_AT, INSPECTOR_ID, RESULT, SAMPLE_QTY, DEFECT_QTY, IS_CONFIRMED,
     REMARK, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT)
SELECT R.RESULT_ID, 'Process', R.LOT_ID, R.EQUIPMENT_ID, R.SPEC_ID,
       R.INSPECTED_AT, R.INSPECTOR_ID,
       CASE WHEN R.IS_PASS = 1 THEN 'Pass' ELSE 'Fail' END,
       1, CASE WHEN R.IS_PASS = 1 THEN 0 ELSE 1 END, 1,
       R.REMARK, R.CREATED_BY, R.CREATED_AT, R.UPDATED_BY, R.UPDATED_AT
FROM QMS_INSPECTION_RESULT R
WHERE NOT EXISTS (
    SELECT 1 FROM QMS_INSPECTION I WHERE I.INSPECTION_ID = R.RESULT_ID
);

ALTER TABLE QMS_INSPECTION_RESULT ALTER COLUMN INSPECTION_ID NVARCHAR(50) NOT NULL;

ALTER TABLE QMS_INSPECTION_RESULT ADD CONSTRAINT FK_QMS_RESULT_INSPECTION
    FOREIGN KEY (INSPECTION_ID) REFERENCES QMS_INSPECTION (INSPECTION_ID);
ALTER TABLE QMS_INSPECTION_RESULT ADD CONSTRAINT UQ_QMS_RESULT_INSPECTION
    UNIQUE (INSPECTION_ID);

ALTER TABLE QMS_INSPECTION ADD CONSTRAINT CK_QMS_INSPECTION_QUANTITY
    CHECK ((SAMPLE_QTY IS NULL AND DEFECT_QTY IS NULL) OR
        (SAMPLE_QTY IS NOT NULL AND DEFECT_QTY IS NOT NULL AND
         SAMPLE_QTY >= 0 AND DEFECT_QTY >= 0 AND DEFECT_QTY <= SAMPLE_QTY));
ALTER TABLE QMS_INSPECTION_RESULT ADD CONSTRAINT CK_QMS_RESULT_VERDICT
    CHECK (IS_PASS IN (0, 1));
ALTER TABLE QMS_INSPECTION_SPEC ADD CONSTRAINT CK_QMS_SPEC_MEASURE_TYPE
    CHECK (MEASURE_TYPE IN ('Variable', 'Numeric', 'Attribute'));
ALTER TABLE QMS_INSPECTION_SPEC ADD CONSTRAINT CK_QMS_SPEC_TOLERANCE
    CHECK ((TOLERANCE_PLUS IS NULL OR TOLERANCE_PLUS >= 0) AND
           (TOLERANCE_MINUS IS NULL OR TOLERANCE_MINUS >= 0));
ALTER TABLE QMS_DEFECT ADD CONSTRAINT CK_QMS_DEFECT_QUANTITY
    CHECK (DEFECT_COUNT >= 0 AND DEFECT_RATE >= 0 AND DEFECT_RATE <= 1);
ALTER TABLE QMS_SPC_PARAM ADD CONSTRAINT CK_QMS_SPC_LIMITS
    CHECK (SAMPLE_SIZE > 0 AND UCL > LCL AND MEAN >= LCL AND MEAN <= UCL AND
           (USL IS NULL OR LSL IS NULL OR USL > LSL));
