-- EST takt/cycle KPI model.
-- Target takt = net available seconds / required quantity.
-- Ideal cycle is an engineering capability target, while actual cycle is measured from TrackOut history.
-- Availability is never recalculated here: EST_TAKT_SUMMARY.AVAILABILITY_RATIO is copied from EST_OEE_SUMMARY.

CREATE TABLE EST_TAKT_TARGET (
    TAKT_TARGET_ID                  NVARCHAR(50)    NOT NULL,
    PLANT_ID                        NVARCHAR(50)    NOT NULL,
    PRODUCT_ID                      NVARCHAR(50)    NOT NULL,
    PROCESS_ID                      NVARCHAR(50)    NOT NULL,
    EQUIPMENT_ID                    NVARCHAR(50)    NOT NULL,
    SHIFT_ID                        NVARCHAR(50)    NULL,
    EFFECTIVE_FROM                  DATETIME2       NOT NULL,
    EFFECTIVE_TO                    DATETIME2       NULL,
    REQUIRED_QTY                    DECIMAL(18,4)   NOT NULL,
    NET_AVAILABLE_SECONDS           DECIMAL(18,4)   NOT NULL,
    IDEAL_CYCLE_SECONDS_PER_UNIT    DECIMAL(18,4)   NOT NULL,
    QUANTITY_UOM                    NVARCHAR(20)    NOT NULL,
    TIME_UOM                        NVARCHAR(20)    NOT NULL DEFAULT 's/unit',
    DESCRIPTION                     NVARCHAR(500)   NULL,
    IS_ACTIVE                       BIT             NOT NULL DEFAULT 1,
    CREATED_BY                      NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT                      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY                      NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT                      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_EST_TAKT_TARGET PRIMARY KEY (TAKT_TARGET_ID),
    CONSTRAINT FK_EST_TAKT_TARGET_EQUIPMENT FOREIGN KEY (EQUIPMENT_ID)
        REFERENCES MDM_EQUIPMENT (EQUIPMENT_ID),
    CONSTRAINT CK_EST_TAKT_TARGET_QTY CHECK (REQUIRED_QTY > 0),
    CONSTRAINT CK_EST_TAKT_TARGET_TIME CHECK (NET_AVAILABLE_SECONDS > 0),
    CONSTRAINT CK_EST_TAKT_TARGET_IDEAL CHECK (IDEAL_CYCLE_SECONDS_PER_UNIT > 0),
    CONSTRAINT CK_EST_TAKT_TARGET_EFFECTIVE CHECK (EFFECTIVE_TO IS NULL OR EFFECTIVE_TO >= EFFECTIVE_FROM)
);

CREATE INDEX IX_EST_TAKT_TARGET_SCOPE
    ON EST_TAKT_TARGET (PLANT_ID, EQUIPMENT_ID, PRODUCT_ID, PROCESS_ID, SHIFT_ID, EFFECTIVE_FROM);

CREATE TABLE EST_TAKT_SUMMARY (
    TAKT_SUMMARY_ID                 NVARCHAR(50)    NOT NULL,
    TAKT_TARGET_ID                  NVARCHAR(50)    NOT NULL,
    TAKT_DATE                       DATETIME2       NOT NULL,
    WINDOW_START_UTC                DATETIME2       NOT NULL,
    WINDOW_END_UTC                  DATETIME2       NOT NULL,
    PLANT_ID                        NVARCHAR(50)    NOT NULL,
    PRODUCT_ID                      NVARCHAR(50)    NOT NULL,
    PROCESS_ID                      NVARCHAR(50)    NOT NULL,
    EQUIPMENT_ID                    NVARCHAR(50)    NOT NULL,
    SHIFT_ID                        NVARCHAR(50)    NULL,
    REQUIRED_QTY                    DECIMAL(18,4)   NOT NULL,
    ACTUAL_QTY                      DECIMAL(18,4)   NOT NULL DEFAULT 0,
    MEASURED_QTY                    DECIMAL(18,4)   NOT NULL DEFAULT 0,
    NET_AVAILABLE_SECONDS           DECIMAL(18,4)   NOT NULL,
    ACTUAL_RUN_SECONDS              DECIMAL(18,4)   NOT NULL DEFAULT 0,
    TARGET_TAKT_SECONDS_PER_UNIT    DECIMAL(18,4)   NOT NULL,
    IDEAL_CYCLE_SECONDS_PER_UNIT    DECIMAL(18,4)   NOT NULL,
    ACTUAL_CYCLE_SECONDS_PER_UNIT   DECIMAL(18,4)   NULL,
    DEVIATION_SECONDS_PER_UNIT      DECIMAL(18,4)   NULL,
    DEVIATION_RATIO                 DECIMAL(18,6)   NULL,
    AVAILABILITY_RATIO              DECIMAL(10,6)   NOT NULL,
    QUANTITY_UOM                    NVARCHAR(20)    NOT NULL,
    TIME_UOM                        NVARCHAR(20)    NOT NULL,
    CREATED_BY                      NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT                      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY                      NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT                      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_EST_TAKT_SUMMARY PRIMARY KEY (TAKT_SUMMARY_ID),
    CONSTRAINT FK_EST_TAKT_SUMMARY_TARGET FOREIGN KEY (TAKT_TARGET_ID)
        REFERENCES EST_TAKT_TARGET (TAKT_TARGET_ID),
    CONSTRAINT CK_EST_TAKT_SUMMARY_AVAILABILITY CHECK (AVAILABILITY_RATIO >= 0 AND AVAILABILITY_RATIO <= 1)
);

CREATE INDEX IX_EST_TAKT_SUMMARY_SCOPE
    ON EST_TAKT_SUMMARY (PLANT_ID, TAKT_DATE DESC, EQUIPMENT_ID, PRODUCT_ID, PROCESS_ID, SHIFT_ID);
