-- QMS P1: append-only SPC evidence, sampling-plan revisions, and AI inspection audit.
CREATE TABLE QMS_SPC_LIMIT_REVISION (
    LIMIT_REVISION_ID NVARCHAR(50) NOT NULL,
    PARAM_ID NVARCHAR(50) NOT NULL,
    REVISION_NO INT NOT NULL,
    CHART_TYPE NVARCHAR(40) NOT NULL,
    CENTER_LINE DECIMAL(18,6) NOT NULL,
    UCL DECIMAL(18,6) NOT NULL,
    LCL DECIMAL(18,6) NOT NULL,
    EFFECTIVE_FROM DATETIME2 NOT NULL,
    REASON NVARCHAR(500) NULL,
    CREATED_BY NVARCHAR(50) NOT NULL,
    CREATED_AT DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_QMS_SPC_LIMIT_REV PRIMARY KEY (LIMIT_REVISION_ID),
    CONSTRAINT UQ_QMS_SPC_LIMIT_REV UNIQUE (PARAM_ID, REVISION_NO),
    CONSTRAINT FK_QMS_SPC_LIMIT_PARAM FOREIGN KEY (PARAM_ID) REFERENCES QMS_SPC_PARAM (PARAM_ID),
    CONSTRAINT CK_QMS_SPC_LIMIT_ORDER CHECK (REVISION_NO > 0 AND UCL > CENTER_LINE AND CENTER_LINE > LCL)
);
CREATE INDEX IX_QMS_SPC_LIMIT_EFFECTIVE ON QMS_SPC_LIMIT_REVISION (PARAM_ID, EFFECTIVE_FROM DESC);

CREATE TABLE QMS_SPC_SUBGROUP (
    SUBGROUP_ID NVARCHAR(50) NOT NULL,
    PARAM_ID NVARCHAR(50) NOT NULL,
    LIMIT_REVISION_ID NVARCHAR(50) NOT NULL,
    IDEMPOTENCY_KEY NVARCHAR(150) NOT NULL,
    REQUEST_HASH CHAR(64) NOT NULL,
    CHART_TYPE NVARCHAR(40) NOT NULL,
    OBSERVED_AT DATETIME2 NOT NULL,
    SAMPLE_COUNT INT NOT NULL,
    SUBGROUP_MEAN DECIMAL(18,6) NOT NULL,
    SUBGROUP_RANGE DECIMAL(18,6) NOT NULL,
    CREATED_BY NVARCHAR(50) NOT NULL,
    CREATED_AT DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_QMS_SPC_SUBGROUP PRIMARY KEY (SUBGROUP_ID),
    CONSTRAINT UQ_QMS_SPC_SUBGROUP_KEY UNIQUE (IDEMPOTENCY_KEY),
    CONSTRAINT FK_QMS_SPC_SUBGROUP_PARAM FOREIGN KEY (PARAM_ID) REFERENCES QMS_SPC_PARAM (PARAM_ID),
    CONSTRAINT FK_QMS_SPC_SUBGROUP_LIMIT FOREIGN KEY (LIMIT_REVISION_ID) REFERENCES QMS_SPC_LIMIT_REVISION (LIMIT_REVISION_ID),
    CONSTRAINT CK_QMS_SPC_SUBGROUP_COUNT CHECK (SAMPLE_COUNT > 0 AND SUBGROUP_RANGE >= 0)
);
CREATE INDEX IX_QMS_SPC_SUBGROUP_TIME ON QMS_SPC_SUBGROUP (PARAM_ID, OBSERVED_AT DESC);

CREATE TABLE QMS_SPC_OBSERVATION (
    OBSERVATION_ID NVARCHAR(80) NOT NULL,
    PARAM_ID NVARCHAR(50) NOT NULL,
    LIMIT_REVISION_ID NVARCHAR(50) NOT NULL,
    SUBGROUP_ID NVARCHAR(50) NOT NULL,
    SAMPLE_INDEX INT NOT NULL,
    OBSERVED_VALUE DECIMAL(18,6) NOT NULL,
    OBSERVED_AT DATETIME2 NOT NULL,
    SOURCE_TYPE NVARCHAR(40) NOT NULL,
    IDEMPOTENCY_KEY NVARCHAR(170) NOT NULL,
    CREATED_BY NVARCHAR(50) NOT NULL,
    CREATED_AT DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_QMS_SPC_OBSERVATION PRIMARY KEY (OBSERVATION_ID),
    CONSTRAINT UQ_QMS_SPC_OBSERVATION_KEY UNIQUE (IDEMPOTENCY_KEY),
    CONSTRAINT UQ_QMS_SPC_OBSERVATION_ORDER UNIQUE (SUBGROUP_ID, SAMPLE_INDEX),
    CONSTRAINT FK_QMS_SPC_OBS_PARAM FOREIGN KEY (PARAM_ID) REFERENCES QMS_SPC_PARAM (PARAM_ID),
    CONSTRAINT FK_QMS_SPC_OBS_LIMIT FOREIGN KEY (LIMIT_REVISION_ID) REFERENCES QMS_SPC_LIMIT_REVISION (LIMIT_REVISION_ID),
    CONSTRAINT FK_QMS_SPC_OBS_SUBGROUP FOREIGN KEY (SUBGROUP_ID) REFERENCES QMS_SPC_SUBGROUP (SUBGROUP_ID),
    CONSTRAINT CK_QMS_SPC_OBS_INDEX CHECK (SAMPLE_INDEX > 0)
);
CREATE INDEX IX_QMS_SPC_OBSERVATION_TIME ON QMS_SPC_OBSERVATION (PARAM_ID, OBSERVED_AT DESC);

CREATE TABLE QMS_SPC_RULE_VIOLATION (
    VIOLATION_ID NVARCHAR(180) NOT NULL,
    PARAM_ID NVARCHAR(50) NOT NULL,
    LIMIT_REVISION_ID NVARCHAR(50) NOT NULL,
    OBSERVATION_ID NVARCHAR(80) NOT NULL,
    RULE_CODE NVARCHAR(50) NOT NULL,
    DETECTED_AT DATETIME2 NOT NULL,
    EVIDENCE NVARCHAR(1000) NOT NULL,
    CREATED_BY NVARCHAR(50) NOT NULL,
    CREATED_AT DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_QMS_SPC_RULE_VIOLATION PRIMARY KEY (VIOLATION_ID),
    CONSTRAINT UQ_QMS_SPC_RULE_SIGNAL UNIQUE (LIMIT_REVISION_ID, OBSERVATION_ID, RULE_CODE),
    CONSTRAINT FK_QMS_SPC_RULE_PARAM FOREIGN KEY (PARAM_ID) REFERENCES QMS_SPC_PARAM (PARAM_ID),
    CONSTRAINT FK_QMS_SPC_RULE_LIMIT FOREIGN KEY (LIMIT_REVISION_ID) REFERENCES QMS_SPC_LIMIT_REVISION (LIMIT_REVISION_ID),
    CONSTRAINT FK_QMS_SPC_RULE_OBS FOREIGN KEY (OBSERVATION_ID) REFERENCES QMS_SPC_OBSERVATION (OBSERVATION_ID)
);
CREATE INDEX IX_QMS_SPC_RULE_TIME ON QMS_SPC_RULE_VIOLATION (PARAM_ID, DETECTED_AT DESC);

CREATE TABLE QMS_SAMPLING_PLAN_REVISION (
    PLAN_REVISION_ID NVARCHAR(50) NOT NULL,
    PLAN_ID NVARCHAR(50) NOT NULL,
    REVISION_NO INT NOT NULL,
    INSPECTION_MODE NVARCHAR(20) NOT NULL,
    LOT_SIZE_MIN INT NOT NULL,
    LOT_SIZE_MAX INT NULL,
    SAMPLE_SIZE INT NULL,
    ACCEPTANCE_NO INT NOT NULL,
    REJECTION_NO INT NOT NULL,
    AQL DECIMAL(9,4) NOT NULL,
    STANDARD_NAME NVARCHAR(100) NOT NULL,
    STANDARD_VERSION NVARCHAR(50) NOT NULL,
    EFFECTIVE_FROM DATETIME2 NOT NULL,
    CREATED_BY NVARCHAR(50) NOT NULL,
    CREATED_AT DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_QMS_SAMPLING_PLAN_REV PRIMARY KEY (PLAN_REVISION_ID),
    CONSTRAINT UQ_QMS_SAMPLING_PLAN_REV UNIQUE (PLAN_ID, REVISION_NO),
    CONSTRAINT CK_QMS_SAMPLING_PLAN_MODE CHECK (INSPECTION_MODE IN ('Full', 'Sampling')),
    CONSTRAINT CK_QMS_SAMPLING_PLAN_RANGE CHECK (REVISION_NO > 0 AND LOT_SIZE_MIN > 0 AND
        (LOT_SIZE_MAX IS NULL OR LOT_SIZE_MAX >= LOT_SIZE_MIN) AND
        ((INSPECTION_MODE = 'Full' AND SAMPLE_SIZE IS NULL) OR
         (INSPECTION_MODE = 'Sampling' AND SAMPLE_SIZE > 0)) AND
        ACCEPTANCE_NO >= 0 AND REJECTION_NO = ACCEPTANCE_NO + 1 AND AQL >= 0 AND AQL <= 100)
);
CREATE INDEX IX_QMS_SAMPLING_PLAN_EFFECTIVE ON QMS_SAMPLING_PLAN_REVISION (PLAN_ID, EFFECTIVE_FROM DESC);

CREATE TABLE QMS_AI_MODEL_VERSION (
    MODEL_VERSION_ID NVARCHAR(50) NOT NULL,
    MODEL_ID NVARCHAR(50) NOT NULL,
    VERSION_NO INT NOT NULL,
    ARTIFACT_URI NVARCHAR(1000) NOT NULL,
    ARTIFACT_SHA256 CHAR(64) NOT NULL,
    CONFIDENCE_THRESHOLD DECIMAL(9,6) NOT NULL,
    EFFECTIVE_FROM DATETIME2 NOT NULL,
    CREATED_BY NVARCHAR(50) NOT NULL,
    CREATED_AT DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_QMS_AI_MODEL_VERSION PRIMARY KEY (MODEL_VERSION_ID),
    CONSTRAINT UQ_QMS_AI_MODEL_VERSION UNIQUE (MODEL_ID, VERSION_NO),
    CONSTRAINT CK_QMS_AI_MODEL CHECK (VERSION_NO > 0 AND CONFIDENCE_THRESHOLD >= 0 AND CONFIDENCE_THRESHOLD <= 1)
);

CREATE TABLE QMS_AI_INFERENCE (
    INFERENCE_ID NVARCHAR(80) NOT NULL,
    IDEMPOTENCY_KEY NVARCHAR(100) NOT NULL,
    MODEL_VERSION_ID NVARCHAR(50) NOT NULL,
    INSPECTION_ID NVARCHAR(50) NOT NULL,
    IMAGE_URI NVARCHAR(1000) NOT NULL,
    IMAGE_SHA256 CHAR(64) NOT NULL,
    RAW_VERDICT NVARCHAR(20) NOT NULL,
    CONFIDENCE DECIMAL(9,6) NOT NULL,
    THRESHOLD DECIMAL(9,6) NOT NULL,
    INFERRED_AT DATETIME2 NOT NULL,
    REQUEST_HASH CHAR(64) NOT NULL,
    CREATED_BY NVARCHAR(50) NOT NULL,
    CREATED_AT DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_QMS_AI_INFERENCE PRIMARY KEY (INFERENCE_ID),
    CONSTRAINT UQ_QMS_AI_INFERENCE_KEY UNIQUE (IDEMPOTENCY_KEY),
    CONSTRAINT FK_QMS_AI_INFERENCE_MODEL FOREIGN KEY (MODEL_VERSION_ID) REFERENCES QMS_AI_MODEL_VERSION (MODEL_VERSION_ID),
    CONSTRAINT FK_QMS_AI_INFERENCE_INSPECTION FOREIGN KEY (INSPECTION_ID) REFERENCES QMS_INSPECTION (INSPECTION_ID),
    CONSTRAINT CK_QMS_AI_INFERENCE CHECK (RAW_VERDICT IN ('Pass', 'Fail', 'Unknown') AND
        CONFIDENCE >= 0 AND CONFIDENCE <= 1 AND THRESHOLD >= 0 AND THRESHOLD <= 1)
);
CREATE INDEX IX_QMS_AI_INFERENCE_INSPECTION ON QMS_AI_INFERENCE (INSPECTION_ID, INFERRED_AT DESC);

CREATE TABLE QMS_AI_REVIEW (
    REVIEW_ID NVARCHAR(80) NOT NULL,
    INFERENCE_ID NVARCHAR(80) NOT NULL,
    REVIEW_SEQUENCE INT NOT NULL,
    REVIEWER_ID NVARCHAR(50) NOT NULL,
    REVIEW_VERDICT NVARCHAR(20) NOT NULL,
    REASON NVARCHAR(1000) NOT NULL,
    REVIEWED_AT DATETIME2 NOT NULL,
    CREATED_BY NVARCHAR(50) NOT NULL,
    CREATED_AT DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_QMS_AI_REVIEW PRIMARY KEY (REVIEW_ID),
    CONSTRAINT UQ_QMS_AI_REVIEW_SEQUENCE UNIQUE (INFERENCE_ID, REVIEW_SEQUENCE),
    CONSTRAINT FK_QMS_AI_REVIEW_INFERENCE FOREIGN KEY (INFERENCE_ID) REFERENCES QMS_AI_INFERENCE (INFERENCE_ID),
    CONSTRAINT FK_QMS_AI_REVIEW_USER FOREIGN KEY (REVIEWER_ID) REFERENCES SYS_USER (USER_ID),
    CONSTRAINT CK_QMS_AI_REVIEW CHECK (REVIEW_SEQUENCE > 0 AND REVIEW_VERDICT IN ('Pass', 'Fail'))
);
CREATE INDEX IX_QMS_AI_REVIEW_INFERENCE ON QMS_AI_REVIEW (INFERENCE_ID, REVIEW_SEQUENCE);
