-- QMS inspection execution v2: immutable multi-item result, idempotency, sampling snapshot,
-- and append-only cancellation/correction/reinspection history.
ALTER TABLE QMS_INSPECTION ADD
    LOT_QTY INT NULL,
    IDEMPOTENCY_KEY NVARCHAR(150) NULL,
    REQUEST_HASH CHAR(64) NULL,
    SAMPLING_PLAN_REVISION_ID NVARCHAR(50) NULL,
    SAMPLING_SNAPSHOT_JSON NVARCHAR(MAX) NULL,
    RELATION_TYPE NVARCHAR(20) NULL,
    PARENT_INSPECTION_ID NVARCHAR(50) NULL,
    ROOT_INSPECTION_ID NVARCHAR(50) NULL;

ALTER TABLE QMS_INSPECTION_RESULT ADD
    ITEM_SEQUENCE INT NULL,
    SAMPLE_QTY INT NULL,
    DEFECT_QTY INT NULL;

-- V093 enforced a legacy one-header/one-result relation. v2 uses one header with many items.
ALTER TABLE QMS_INSPECTION_RESULT DROP CONSTRAINT UQ_QMS_RESULT_INSPECTION;

CREATE UNIQUE INDEX UX_QMS_INSPECTION_IDEMPOTENCY
    ON QMS_INSPECTION (IDEMPOTENCY_KEY)
    WHERE IDEMPOTENCY_KEY IS NOT NULL;
CREATE UNIQUE INDEX UX_QMS_INSPECTION_RESULT_SEQUENCE
    ON QMS_INSPECTION_RESULT (INSPECTION_ID, ITEM_SEQUENCE)
    WHERE ITEM_SEQUENCE IS NOT NULL;
CREATE UNIQUE INDEX UX_QMS_INSPECTION_RESULT_SPEC
    ON QMS_INSPECTION_RESULT (INSPECTION_ID, SPEC_ID)
    WHERE ITEM_SEQUENCE IS NOT NULL;

ALTER TABLE QMS_INSPECTION ADD CONSTRAINT FK_QMS_INSPECTION_SAMPLING_REV
    FOREIGN KEY (SAMPLING_PLAN_REVISION_ID)
    REFERENCES QMS_SAMPLING_PLAN_REVISION (PLAN_REVISION_ID);
ALTER TABLE QMS_INSPECTION ADD CONSTRAINT FK_QMS_INSPECTION_PARENT
    FOREIGN KEY (PARENT_INSPECTION_ID) REFERENCES QMS_INSPECTION (INSPECTION_ID);
ALTER TABLE QMS_INSPECTION ADD CONSTRAINT FK_QMS_INSPECTION_ROOT
    FOREIGN KEY (ROOT_INSPECTION_ID) REFERENCES QMS_INSPECTION (INSPECTION_ID);
ALTER TABLE QMS_INSPECTION ADD CONSTRAINT CK_QMS_INSPECTION_V2
    CHECK (IDEMPOTENCY_KEY IS NULL OR
        (LEN(IDEMPOTENCY_KEY) > 0 AND REQUEST_HASH IS NOT NULL AND
         LEN(REQUEST_HASH) = 64 AND
         REQUEST_HASH COLLATE Latin1_General_100_BIN2 NOT LIKE '%[^0-9A-Fa-f]%' AND
         LOT_ID IS NOT NULL AND EQUIPMENT_ID IS NOT NULL AND INSPECTOR_ID IS NOT NULL AND
         INSPECTION_TYPE IN ('Incoming', 'Process', 'Shipping') AND
         LOT_QTY IS NOT NULL AND LOT_QTY > 0 AND
         SAMPLE_QTY IS NOT NULL AND SAMPLE_QTY > 0 AND SAMPLE_QTY <= LOT_QTY AND
         DEFECT_QTY IS NOT NULL AND DEFECT_QTY >= 0 AND DEFECT_QTY <= SAMPLE_QTY AND
         RELATION_TYPE IN ('Original', 'Correction', 'Reinspection') AND
         ROOT_INSPECTION_ID IS NOT NULL AND
         ((RELATION_TYPE = 'Original' AND PARENT_INSPECTION_ID IS NULL) OR
          (RELATION_TYPE IN ('Correction', 'Reinspection') AND PARENT_INSPECTION_ID IS NOT NULL))));
ALTER TABLE QMS_INSPECTION_RESULT ADD CONSTRAINT CK_QMS_INSPECTION_RESULT_V2_QTY
    CHECK (ITEM_SEQUENCE IS NULL OR
        (ITEM_SEQUENCE > 0 AND SAMPLE_QTY IS NOT NULL AND SAMPLE_QTY > 0 AND
         DEFECT_QTY IS NOT NULL AND DEFECT_QTY >= 0 AND DEFECT_QTY <= SAMPLE_QTY));

CREATE TABLE QMS_INSPECTION_EVENT (
    EVENT_ID NVARCHAR(50) NOT NULL,
    INSPECTION_ID NVARCHAR(50) NOT NULL,
    EVENT_TYPE NVARCHAR(20) NOT NULL,
    RELATED_INSPECTION_ID NVARCHAR(50) NULL,
    PARENT_INSPECTION_ID NVARCHAR(50) NULL,
    ROOT_INSPECTION_ID NVARCHAR(50) NOT NULL,
    IDEMPOTENCY_KEY NVARCHAR(150) NOT NULL,
    REQUEST_HASH CHAR(64) NOT NULL,
    ACTOR_ID NVARCHAR(50) NOT NULL,
    REASON NVARCHAR(1000) NULL,
    OCCURRED_AT DATETIME2 NOT NULL,
    CREATED_BY NVARCHAR(50) NOT NULL,
    CREATED_AT DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_QMS_INSPECTION_EVENT PRIMARY KEY (EVENT_ID),
    CONSTRAINT UQ_QMS_INSPECTION_EVENT_KEY UNIQUE (INSPECTION_ID, IDEMPOTENCY_KEY),
    CONSTRAINT FK_QMS_INSPECTION_EVENT_EXEC FOREIGN KEY (INSPECTION_ID)
        REFERENCES QMS_INSPECTION (INSPECTION_ID),
    CONSTRAINT FK_QMS_INSPECTION_EVENT_RELATED FOREIGN KEY (RELATED_INSPECTION_ID)
        REFERENCES QMS_INSPECTION (INSPECTION_ID),
    CONSTRAINT FK_QMS_INSPECTION_EVENT_PARENT FOREIGN KEY (PARENT_INSPECTION_ID)
        REFERENCES QMS_INSPECTION (INSPECTION_ID),
    CONSTRAINT FK_QMS_INSPECTION_EVENT_ROOT FOREIGN KEY (ROOT_INSPECTION_ID)
        REFERENCES QMS_INSPECTION (INSPECTION_ID),
    CONSTRAINT FK_QMS_INSPECTION_EVENT_ACTOR FOREIGN KEY (ACTOR_ID)
        REFERENCES SYS_USER (USER_ID),
    CONSTRAINT CK_QMS_INSPECTION_EVENT_TYPE
        CHECK (EVENT_TYPE IN ('Confirmed', 'Cancelled', 'Corrected', 'Reinspected')),
    CONSTRAINT CK_QMS_INSPECTION_EVENT_HASH CHECK (LEN(REQUEST_HASH) = 64)
);
CREATE INDEX IX_QMS_INSPECTION_EVENT_TIME
    ON QMS_INSPECTION_EVENT (INSPECTION_ID, OCCURRED_AT, EVENT_ID);
CREATE UNIQUE INDEX UX_QMS_INSPECTION_EVENT_CANCELLED
    ON QMS_INSPECTION_EVENT (INSPECTION_ID)
    WHERE EVENT_TYPE = 'Cancelled';
CREATE INDEX IX_QMS_INSPECTION_ROOT
    ON QMS_INSPECTION (ROOT_INSPECTION_ID, INSPECTED_AT)
    WHERE ROOT_INSPECTION_ID IS NOT NULL;

-- SQL Server production guard. SQLite receives equivalent triggers from SqliteSchemaInitializer.
-- SQLITE-OMIT-BEGIN
EXEC(N'CREATE TRIGGER TR_QMS_V2_INSPECTION_IMMUTABLE
ON QMS_INSPECTION AFTER UPDATE, DELETE AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted WHERE IDEMPOTENCY_KEY IS NOT NULL)
        THROW 51001, ''Confirmed QMS v2 inspection headers are immutable.'', 1;
END');
EXEC(N'CREATE TRIGGER TR_QMS_V2_INSPECTION_LINEAGE
ON QMS_INSPECTION AFTER INSERT AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (
        SELECT 1 FROM inserted I
        WHERE I.IDEMPOTENCY_KEY IS NOT NULL
          AND I.RELATION_TYPE = ''Original''
          AND I.ROOT_INSPECTION_ID <> I.INSPECTION_ID)
        THROW 51004, ''Original QMS v2 inspections must be their own root.'', 1;

    IF EXISTS (
        SELECT 1
        FROM inserted I
        LEFT JOIN QMS_INSPECTION P ON P.INSPECTION_ID = I.PARENT_INSPECTION_ID
        WHERE I.IDEMPOTENCY_KEY IS NOT NULL
          AND I.RELATION_TYPE IN (''Correction'', ''Reinspection'')
          AND (P.INSPECTION_ID IS NULL OR P.IDEMPOTENCY_KEY IS NULL
               OR P.ROOT_INSPECTION_ID <> I.ROOT_INSPECTION_ID
               OR P.INSPECTION_TYPE <> I.INSPECTION_TYPE
               OR P.LOT_ID <> I.LOT_ID))
        THROW 51005, ''QMS v2 child inspection lineage does not match its parent.'', 1;

    IF EXISTS (
        SELECT 1 FROM inserted I
        JOIN QMS_SAMPLING_PLAN_REVISION S
          ON S.PLAN_REVISION_ID = I.SAMPLING_PLAN_REVISION_ID
        WHERE I.IDEMPOTENCY_KEY IS NOT NULL
          AND S.EFFECTIVE_FROM > I.INSPECTED_AT)
        THROW 51006, ''QMS sampling-plan revision is not effective at inspection time.'', 1;
END');
EXEC(N'CREATE TRIGGER TR_QMS_V2_RESULT_IMMUTABLE
ON QMS_INSPECTION_RESULT AFTER INSERT, UPDATE, DELETE AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (
        SELECT 1 FROM inserted N
        LEFT JOIN deleted D ON D.RESULT_ID = N.RESULT_ID
        JOIN QMS_INSPECTION_EVENT E ON E.INSPECTION_ID = N.INSPECTION_ID
        WHERE D.RESULT_ID IS NULL AND E.EVENT_TYPE = ''Confirmed'')
        THROW 51007, ''Confirmed QMS v2 inspections cannot accept additional result rows.'', 1;
    IF EXISTS (
        SELECT 1 FROM deleted D
        JOIN QMS_INSPECTION I ON I.INSPECTION_ID = D.INSPECTION_ID
        WHERE I.IDEMPOTENCY_KEY IS NOT NULL)
        THROW 51002, ''Confirmed QMS v2 inspection results are immutable.'', 1;
END');
EXEC(N'CREATE TRIGGER TR_QMS_V2_RESULT_INTEGRITY
ON QMS_INSPECTION_RESULT AFTER INSERT, UPDATE AS
BEGIN
    SET NOCOUNT ON;

    -- ITEM_SEQUENCE is the persisted v2 discriminator.  Validate the whole inserted
    -- set so bulk writes cannot bypass aggregate ownership or reference boundaries.
    IF EXISTS (
        SELECT 1
        FROM inserted R
        LEFT JOIN QMS_INSPECTION I ON I.INSPECTION_ID = R.INSPECTION_ID
        WHERE (R.ITEM_SEQUENCE IS NOT NULL OR I.IDEMPOTENCY_KEY IS NOT NULL)
          AND (I.INSPECTION_ID IS NULL OR I.IDEMPOTENCY_KEY IS NULL
               OR R.ITEM_SEQUENCE IS NULL
               OR I.LOT_ID IS NULL OR I.LOT_ID <> R.LOT_ID
               OR I.EQUIPMENT_ID IS NULL OR I.EQUIPMENT_ID <> R.EQUIPMENT_ID
               OR I.INSPECTION_TYPE NOT IN (''Incoming'', ''Process'', ''Shipping'')
               OR (NOT EXISTS (SELECT 1 FROM POM_LOT L WHERE L.LOT_ID = R.LOT_ID)
                   AND NOT EXISTS (SELECT 1 FROM IVT_MATERIAL_LOT L WHERE L.LOT_ID = R.LOT_ID))))
        THROW 51017, ''QMS v2 result requires a matching v2 header, lot, equipment, and inspection type.'', 1;

    IF EXISTS (
        SELECT 1
        FROM inserted R
        JOIN QMS_INSPECTION I ON I.INSPECTION_ID = R.INSPECTION_ID
        LEFT JOIN MDM_EQUIPMENT E
          ON E.EQUIPMENT_ID = R.EQUIPMENT_ID AND E.VALID_STATE = ''Active''
        -- QMS_INSPECTION_SPEC has no temporal effective interval; IS_ACTIVE is the
        -- strongest schema-level eligibility signal available at inspection time.
        LEFT JOIN QMS_INSPECTION_SPEC S
          ON S.SPEC_ID = R.SPEC_ID AND S.IS_ACTIVE = 1
        WHERE I.IDEMPOTENCY_KEY IS NOT NULL
          AND (E.EQUIPMENT_ID IS NULL OR S.SPEC_ID IS NULL))
        THROW 51018, ''QMS v2 result requires active equipment and an active inspection specification.'', 1;

    IF EXISTS (
        SELECT 1
        FROM inserted R
        JOIN QMS_INSPECTION I ON I.INSPECTION_ID = R.INSPECTION_ID
        WHERE I.IDEMPOTENCY_KEY IS NOT NULL
          AND (R.SAMPLE_QTY IS NULL OR R.SAMPLE_QTY <= 0
               OR R.DEFECT_QTY IS NULL OR R.DEFECT_QTY < 0
               OR R.DEFECT_QTY > R.SAMPLE_QTY
               OR I.SAMPLE_QTY IS NULL OR R.SAMPLE_QTY > I.SAMPLE_QTY
               OR I.DEFECT_QTY IS NULL OR R.DEFECT_QTY > I.DEFECT_QTY))
        THROW 51019, ''QMS v2 result quantities must be positive/bounded and cannot exceed header quantities.'', 1;

    IF EXISTS (
        SELECT 1
        FROM inserted R
        JOIN QMS_INSPECTION I ON I.INSPECTION_ID = R.INSPECTION_ID
        JOIN QMS_INSPECTION_SPEC S ON S.SPEC_ID = R.SPEC_ID
        WHERE I.IDEMPOTENCY_KEY IS NOT NULL
          AND (
              (S.MEASURE_TYPE IN (''Variable'', ''Numeric'') AND
                 (R.MEASURED_VALUE IS NULL OR S.NOMINAL_VALUE IS NULL OR
                  R.IS_PASS <> CASE WHEN
                      (R.MEASURED_VALUE <= S.NOMINAL_VALUE OR S.TOLERANCE_PLUS IS NULL
                       OR R.MEASURED_VALUE - S.NOMINAL_VALUE <= S.TOLERANCE_PLUS)
                      AND
                      (R.MEASURED_VALUE >= S.NOMINAL_VALUE OR S.TOLERANCE_MINUS IS NULL
                       OR S.NOMINAL_VALUE - R.MEASURED_VALUE <= S.TOLERANCE_MINUS)
                      THEN 1 ELSE 0 END))
              OR
              (S.MEASURE_TYPE = ''Attribute'' AND
                 (R.MEASURED_VALUE IS NOT NULL
                  OR R.ATTRIBUTE_RESULT IS NULL
                  OR R.ATTRIBUTE_RESULT NOT IN (''Pass'', ''Fail'')
                  OR R.IS_PASS <> CASE WHEN R.ATTRIBUTE_RESULT = ''Pass'' THEN 1 ELSE 0 END))
              OR S.MEASURE_TYPE NOT IN (''Variable'', ''Numeric'', ''Attribute'')))
        THROW 51020, ''QMS v2 result value/verdict does not match its inspection specification type.'', 1;

    -- The domain permits every item to reuse the aggregate sample quantity; quantities
    -- are per specification, not values to be summed.  Only duplicate specifications fail.
    IF EXISTS (
        SELECT 1
        FROM inserted R
        JOIN QMS_INSPECTION I ON I.INSPECTION_ID = R.INSPECTION_ID
        JOIN QMS_INSPECTION_RESULT X
          ON X.INSPECTION_ID = R.INSPECTION_ID
         AND X.RESULT_ID <> R.RESULT_ID
         AND X.SPEC_ID COLLATE Latin1_General_100_CI_AS =
             R.SPEC_ID COLLATE Latin1_General_100_CI_AS
        WHERE I.IDEMPOTENCY_KEY IS NOT NULL)
        THROW 51021, ''A QMS v2 inspection specification can appear only once per execution.'', 1;
END');
EXEC(N'CREATE TRIGGER TR_QMS_V2_EVENT_LINEAGE
ON QMS_INSPECTION_EVENT AFTER INSERT AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (
        SELECT 1 FROM inserted E
        LEFT JOIN QMS_INSPECTION I ON I.INSPECTION_ID = E.INSPECTION_ID
        WHERE I.INSPECTION_ID IS NULL OR I.IDEMPOTENCY_KEY IS NULL
           OR I.ROOT_INSPECTION_ID <> E.ROOT_INSPECTION_ID)
        THROW 51008, ''QMS inspection event execution/root lineage is invalid.'', 1;

    IF EXISTS (
        SELECT 1 FROM inserted E
        LEFT JOIN QMS_INSPECTION R ON R.INSPECTION_ID = E.RELATED_INSPECTION_ID
        WHERE E.RELATED_INSPECTION_ID IS NOT NULL
          AND (R.INSPECTION_ID IS NULL OR R.IDEMPOTENCY_KEY IS NULL
               OR R.ROOT_INSPECTION_ID <> E.ROOT_INSPECTION_ID))
        THROW 51009, ''QMS inspection event related-execution lineage is invalid.'', 1;

    IF EXISTS (
        SELECT 1 FROM inserted E
        LEFT JOIN QMS_INSPECTION P ON P.INSPECTION_ID = E.PARENT_INSPECTION_ID
        WHERE E.PARENT_INSPECTION_ID IS NOT NULL
          AND (P.INSPECTION_ID IS NULL OR P.IDEMPOTENCY_KEY IS NULL
               OR P.ROOT_INSPECTION_ID <> E.ROOT_INSPECTION_ID))
        THROW 51010, ''QMS inspection event parent lineage is invalid.'', 1;

    IF EXISTS (
        SELECT 1 FROM inserted E
        LEFT JOIN QMS_INSPECTION C ON C.INSPECTION_ID = E.RELATED_INSPECTION_ID
        WHERE E.EVENT_TYPE IN (''Corrected'', ''Reinspected'')
          AND (E.RELATED_INSPECTION_ID IS NULL OR E.PARENT_INSPECTION_ID IS NULL
               OR E.PARENT_INSPECTION_ID <> E.INSPECTION_ID
               OR C.PARENT_INSPECTION_ID <> E.INSPECTION_ID
               OR C.ROOT_INSPECTION_ID <> E.ROOT_INSPECTION_ID
               OR (E.EVENT_TYPE = ''Corrected'' AND C.RELATION_TYPE <> ''Correction'')
               OR (E.EVENT_TYPE = ''Reinspected'' AND C.RELATION_TYPE <> ''Reinspection'')))
        THROW 51011, ''QMS correction/reinspection event does not identify its child execution.'', 1;

    IF EXISTS (
        SELECT 1 FROM inserted E
        WHERE E.EVENT_TYPE IN (''Confirmed'', ''Cancelled'')
          AND E.RELATED_INSPECTION_ID IS NOT NULL)
        THROW 51012, ''QMS confirmation/cancellation events cannot identify a successor.'', 1;

    IF EXISTS (
        SELECT 1 FROM inserted E
        WHERE E.EVENT_TYPE = ''Confirmed''
          AND NOT EXISTS (
              SELECT 1 FROM QMS_INSPECTION_RESULT R
              WHERE R.INSPECTION_ID = E.INSPECTION_ID
                AND R.ITEM_SEQUENCE IS NOT NULL))
        THROW 51022, ''A QMS v2 inspection requires at least one result item before confirmation.'', 1;
END');
EXEC(N'CREATE TRIGGER TR_QMS_V2_EVENT_APPEND_ONLY
ON QMS_INSPECTION_EVENT AFTER UPDATE, DELETE AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted)
        THROW 51003, ''QMS inspection history is append-only.'', 1;
END');
EXEC(N'CREATE TRIGGER TR_QMS_AI_MODEL_VERSION_APPEND_ONLY
ON QMS_AI_MODEL_VERSION AFTER UPDATE, DELETE AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted)
        THROW 51013, ''QMS AI model evidence is append-only.'', 1;
END');
EXEC(N'CREATE TRIGGER TR_QMS_AI_INFERENCE_INTEGRITY
ON QMS_AI_INFERENCE AFTER INSERT AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (
        SELECT 1 FROM inserted I
        JOIN QMS_AI_MODEL_VERSION M ON M.MODEL_VERSION_ID = I.MODEL_VERSION_ID
        WHERE M.EFFECTIVE_FROM > I.INFERRED_AT)
        THROW 51016, ''QMS AI model version is not effective at inference time.'', 1;
END');
EXEC(N'CREATE TRIGGER TR_QMS_AI_INFERENCE_APPEND_ONLY
ON QMS_AI_INFERENCE AFTER UPDATE, DELETE AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted)
        THROW 51014, ''QMS AI inference evidence is append-only.'', 1;
END');
EXEC(N'CREATE TRIGGER TR_QMS_AI_REVIEW_APPEND_ONLY
ON QMS_AI_REVIEW AFTER UPDATE, DELETE AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted)
        THROW 51015, ''QMS AI review evidence is append-only.'', 1;
END');
-- SQLITE-OMIT-END
