-- MES navigation terminology normalization (2026-07-16).
-- Stable MENU_ID/resource keys keep their module codes for integration, while user-facing labels use
-- concise MES terms.  The English resources must describe the business area rather than expose QCA/WPM/etc.
UPDATE SYS_MENU SET MENU_NAME = '생산계획'       WHERE MENU_ID = 'FACTORY_PPM'       AND MENU_NAME = '생산 계획(PPM)';
UPDATE SYS_MENU SET MENU_NAME = '생산실행'       WHERE MENU_ID = 'FACTORY_WPM'       AND MENU_NAME = '생산 실행(WPM)';
UPDATE SYS_MENU SET MENU_NAME = '출하관리'       WHERE MENU_ID = 'FACTORY_DLV'       AND MENU_NAME = '출하 관리';
UPDATE SYS_MENU SET MENU_NAME = '구매관리'       WHERE MENU_ID = 'FACTORY_PRC'       AND MENU_NAME = '구매 관리';
UPDATE SYS_MENU SET MENU_NAME = '품질검사'       WHERE MENU_ID = 'FACTORY_QCA'       AND MENU_NAME = '품질 검사(QCA)';
UPDATE SYS_MENU SET MENU_NAME = '설비보전'       WHERE MENU_ID = 'FACTORY_EMS'       AND MENU_NAME = '설비 보전(EMS)';
UPDATE SYS_MENU SET MENU_NAME = '설비지표'       WHERE MENU_ID = 'EES_EPT'           AND MENU_NAME = '설비 지표(EPT)';
UPDATE SYS_MENU SET MENU_NAME = '설비데이터 수집' WHERE MENU_ID = 'EES_FDC'           AND MENU_NAME = '설비 데이터 수집(FDC)';
UPDATE SYS_MENU SET MENU_NAME = '품질관리'       WHERE MENU_ID = 'QMS'               AND MENU_NAME = '품질 관리(QMS)';
UPDATE SYS_MENU SET MENU_NAME = '레시피 기준정보' WHERE MENU_ID = 'FACTORY_STD_SINGLE' AND MENU_NAME = '레시피 기준 정보';
UPDATE SYS_MENU SET MENU_NAME = '기준정보'       WHERE MENU_ID = 'FACTORY_MDM'       AND MENU_NAME = '기준 정보(MDM)';
UPDATE SYS_MENU SET MENU_NAME = '공통관리'       WHERE MENU_ID = 'FACTORY_COM'       AND MENU_NAME = '공통 관리(COM)';
UPDATE SYS_MENU SET MENU_NAME = '시스템관리'     WHERE MENU_ID = 'MI_SYSTEM_2_0'     AND MENU_NAME = '시스템 관리';

UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET VALUE = 'Production Planning'
 WHERE RESOURCE_KEY = 'menu.FACTORY_PPM' AND LANGUAGE = 'EnUs';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET VALUE = 'Production Execution'
 WHERE RESOURCE_KEY = 'menu.FACTORY_WPM' AND LANGUAGE = 'EnUs';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET VALUE = 'Quality Inspection'
 WHERE RESOURCE_KEY = 'menu.FACTORY_QCA' AND LANGUAGE = 'EnUs';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET VALUE = 'Equipment Maintenance'
 WHERE RESOURCE_KEY = 'menu.FACTORY_EMS' AND LANGUAGE = 'EnUs';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET VALUE = 'Equipment Metrics'
 WHERE RESOURCE_KEY = 'menu.EES_EPT' AND LANGUAGE = 'EnUs';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET VALUE = 'Equipment Data Collection'
 WHERE RESOURCE_KEY = 'menu.EES_FDC' AND LANGUAGE = 'EnUs';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET VALUE = 'Quality Management'
 WHERE RESOURCE_KEY = 'menu.QMS' AND LANGUAGE = 'EnUs';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET VALUE = 'Master Data'
 WHERE RESOURCE_KEY = 'menu.FACTORY_MDM' AND LANGUAGE = 'EnUs';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET VALUE = 'Common Administration'
 WHERE RESOURCE_KEY = 'menu.FACTORY_COM' AND LANGUAGE = 'EnUs';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET VALUE = 'System Administration'
 WHERE RESOURCE_KEY = 'menu.MI_SYSTEM_2_0' AND LANGUAGE = 'EnUs';
