-- POM 유연 라우팅 P0: LOT별 통제 모드, 단일 재작업 복귀점, 승인 원장과 구조화 실행 감사.
-- 기존 LOT은 안전한 Strict로 유지하며 ROUTE_STEPS/CURRENT_STEP 선형 모델을 하위호환 projection으로 사용한다.
ALTER TABLE POM_LOT ADD CONTROL_MODE NVARCHAR(20) NOT NULL DEFAULT 'Strict';
ALTER TABLE POM_LOT ADD RETURN_STEP INT NULL;

ALTER TABLE POM_LOT ADD CONSTRAINT CK_POM_LOT_ROUTING_CONTROL CHECK (
    CONTROL_MODE IN ('Strict', 'Flexible', 'NoControl')
    AND CURRENT_STEP >= 0
    AND (RETURN_STEP IS NULL OR RETURN_STEP >= 0)
);

ALTER TABLE POM_WORK_ORDER ADD CONSTRAINT CK_POM_WORK_ORDER_ROUTING_BINDING CHECK (
    (ROUTING_ID IS NULL AND ROUTING_STEP_NO IS NULL)
    OR (ROUTING_ID IS NOT NULL AND ROUTING_ID <> '' AND ROUTING_STEP_NO > 0)
);

-- 기존 멱등 실행 원장에 공정 재배열 전후의 의미와 호출 단말을 구조화해 보존한다.
ALTER TABLE POM_LOT_EXECUTION ADD ROUTE_EXCEPTION_ID NVARCHAR(50) NULL;
ALTER TABLE POM_LOT_EXECUTION ADD FROM_STEP INT NULL;
ALTER TABLE POM_LOT_EXECUTION ADD TO_STEP INT NULL;
ALTER TABLE POM_LOT_EXECUTION ADD FROM_PROCESS_ID NVARCHAR(50) NULL;
ALTER TABLE POM_LOT_EXECUTION ADD TO_PROCESS_ID NVARCHAR(50) NULL;
ALTER TABLE POM_LOT_EXECUTION ADD CONTROL_MODE NVARCHAR(20) NULL;
ALTER TABLE POM_LOT_EXECUTION ADD CLIENT_CHANNEL NVARCHAR(20) NULL;
ALTER TABLE POM_LOT_EXECUTION ADD DEVICE_ID NVARCHAR(100) NULL;
ALTER TABLE POM_LOT_EXECUTION ADD REASON NVARCHAR(500) NULL;

CREATE TABLE POM_ROUTE_EXCEPTION (
    EXCEPTION_ID          NVARCHAR(50)    NOT NULL,
    LOT_ID                NVARCHAR(50)    NOT NULL,
    PLANT_ID              NVARCHAR(50)    NOT NULL,
    DEVIATION_TYPE        NVARCHAR(30)    NOT NULL,
    FROM_STEP             INT             NOT NULL,
    TO_STEP               INT             NOT NULL,
    FROM_PROCESS_ID       NVARCHAR(50)    NOT NULL,
    TO_PROCESS_ID         NVARCHAR(50)    NOT NULL,
    BOUND_LOT_VERSION     INT             NOT NULL,
    REASON                NVARCHAR(500)   NOT NULL,
    STATUS                NVARCHAR(20)    NOT NULL DEFAULT 'Requested',
    REQUESTED_BY          NVARCHAR(50)    NOT NULL,
    REQUESTED_AT          DATETIME2       NOT NULL,
    EXPIRES_AT            DATETIME2       NOT NULL,
    REVIEWED_BY           NVARCHAR(50)    NULL,
    REVIEWED_AT           DATETIME2       NULL,
    REVIEW_REASON         NVARCHAR(500)   NULL,
    APPLIED_BY            NVARCHAR(50)    NULL,
    APPLIED_AT            DATETIME2       NULL,
    APPLIED_EXECUTION_ID  NVARCHAR(50)    NULL,
    CLIENT_CHANNEL        NVARCHAR(20)    NOT NULL,
    DEVICE_ID             NVARCHAR(100)   NULL,
    CREATED_AT            DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_AT            DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_POM_ROUTE_EXCEPTION PRIMARY KEY (EXCEPTION_ID),
    CONSTRAINT FK_POM_ROUTE_EXCEPTION_LOT FOREIGN KEY (LOT_ID, PLANT_ID)
        REFERENCES POM_LOT (LOT_ID, PLANT_ID),
    CONSTRAINT CK_POM_ROUTE_EXCEPTION_TYPE CHECK (
        DEVIATION_TYPE IN ('Bypass', 'Alternative', 'SequenceChange', 'Rework')),
    CONSTRAINT CK_POM_ROUTE_EXCEPTION_STATUS CHECK (
        STATUS IN ('Requested', 'Approved', 'Rejected', 'Applied', 'Expired')),
    CONSTRAINT CK_POM_ROUTE_EXCEPTION_BOUNDARY CHECK (
        FROM_STEP >= 0 AND TO_STEP >= 0 AND BOUND_LOT_VERSION >= 1
        AND REASON <> '' AND EXPIRES_AT > REQUESTED_AT),
    CONSTRAINT CK_POM_ROUTE_EXCEPTION_REVIEWER CHECK (
        REVIEWED_BY IS NULL OR REVIEWED_BY <> REQUESTED_BY),
    CONSTRAINT CK_POM_ROUTE_EXCEPTION_CHANNEL CHECK (
        CLIENT_CHANNEL IN ('MES', 'MOBILE', 'POP')),
    CONSTRAINT CK_POM_ROUTE_EXCEPTION_APPLIED CHECK (
        (STATUS = 'Applied' AND APPLIED_BY IS NOT NULL AND APPLIED_AT IS NOT NULL AND APPLIED_EXECUTION_ID IS NOT NULL)
        OR (STATUS <> 'Applied' AND APPLIED_BY IS NULL AND APPLIED_AT IS NULL AND APPLIED_EXECUTION_ID IS NULL))
);

ALTER TABLE POM_LOT_EXECUTION ADD CONSTRAINT FK_POM_LOT_EXECUTION_ROUTE_EXCEPTION
    FOREIGN KEY (ROUTE_EXCEPTION_ID) REFERENCES POM_ROUTE_EXCEPTION (EXCEPTION_ID);
ALTER TABLE POM_LOT_EXECUTION ADD CONSTRAINT CK_POM_LOT_EXECUTION_ROUTING CHECK (
    (FROM_STEP IS NULL OR FROM_STEP >= 0)
    AND (TO_STEP IS NULL OR TO_STEP >= 0)
    AND (CONTROL_MODE IS NULL OR CONTROL_MODE IN ('Strict', 'Flexible', 'NoControl'))
    AND (CLIENT_CHANNEL IS NULL OR CLIENT_CHANNEL IN ('MES', 'MOBILE', 'POP'))
);

CREATE INDEX IX_POM_ROUTE_EXCEPTION_LOT
    ON POM_ROUTE_EXCEPTION (LOT_ID, STATUS, REQUESTED_AT DESC);
CREATE INDEX IX_POM_ROUTE_EXCEPTION_PENDING
    ON POM_ROUTE_EXCEPTION (STATUS, EXPIRES_AT);
CREATE UNIQUE INDEX UX_POM_ROUTE_EXCEPTION_APPLIED_EXECUTION
    ON POM_ROUTE_EXCEPTION (APPLIED_EXECUTION_ID) WHERE APPLIED_EXECUTION_ID IS NOT NULL;
CREATE INDEX IX_POM_LOT_EXECUTION_ROUTE
    ON POM_LOT_EXECUTION (LOT_ID, CREATED_AT DESC, FROM_STEP, TO_STEP);
