-- Canonical MES screen/menu terminology and routing-step navigation (2026-07-16).
-- Stable identifiers and user-customized labels remain unchanged. Exact legacy-value guards update only
-- untouched seed data; the routing menu insert runs only on an already-seeded menu tree so it cannot make
-- a fresh database look non-empty before NexaOneDevelopmentDatabaseInitializer loads the full JSON seed.

UPDATE SYS_MENU SET MENU_NAME = 'PM 계획 관리'
 WHERE MENU_ID = 'FACTORY_EMS_PM_ORDER_PLAN' AND MENU_NAME = 'PM 계획 생성';
UPDATE SYS_MENU SET MENU_NAME = 'PM 계획 그리드'
 WHERE MENU_ID = 'FACTORY_EMS_PM_ORDER_PLAN_GRIDTYPE' AND MENU_NAME = 'PM 계획 생성_그리드';
UPDATE SYS_MENU SET MENU_NAME = '구매오더 관리'
 WHERE MENU_ID = 'FACTORY_PRC_PURCHASE_ORDER' AND MENU_NAME = '구매 지시 관리';
UPDATE SYS_MENU SET MENU_NAME = '이동오더 현황'
 WHERE MENU_ID = 'FACTORY_PRC_REPORT_MOVEORDER' AND MENU_NAME = '이동지시 현황';
UPDATE SYS_MENU SET MENU_NAME = '구매오더 현황'
 WHERE MENU_ID = 'FACTORY_PRC_REPORT_PURCHASEORDER' AND MENU_NAME = '구매 지시 현황';
UPDATE SYS_MENU SET MENU_NAME = '수입검사 관리'
 WHERE MENU_ID = 'FACTORY_QCA_IMPORT_INSPECTION' AND MENU_NAME = '수입 검사 관리';
UPDATE SYS_MENU SET MENU_NAME = '공정검사 관리'
 WHERE MENU_ID = 'FACTORY_QCA_SEGMENT_INSPECTION' AND MENU_NAME = '공정 검사 관리';
UPDATE SYS_MENU SET MENU_NAME = '출하검사 관리'
 WHERE MENU_ID = 'FACTORY_QCA_DELIVERY_INSPECTION' AND MENU_NAME = '출하 검사 관리';
UPDATE SYS_MENU SET MENU_NAME = 'LOT 관리'
 WHERE MENU_ID = 'FACTORY_WPM_LOT_MANAGEMENT' AND MENU_NAME = '작업 진행 관리';
UPDATE SYS_MENU SET MENU_NAME = 'BOR 관리(조건 기준)'
 WHERE MENU_ID = 'FACTORY_STD_BOR_CONDITION' AND MENU_NAME = 'BOR 관리_조건기준등록';
UPDATE SYS_MENU SET MENU_NAME = 'BOR 관리(자원 기준)'
 WHERE MENU_ID = 'FACTORY_STD_BOR_RESOURCE' AND MENU_NAME = 'BOR 관리_자원기준등록';

-- Preserve custom ordering: shift only the untouched canonical siblings before adding sequence 6.
UPDATE SYS_MENU SET DISPLAY_SEQUENCE = 7
 WHERE MENU_ID = 'FACTORY_STD_WO_PROCESS_PATH'
   AND PARENT_MENU_ID = 'FACTORY_STD_SINGLE_SEGMENT' AND DISPLAY_SEQUENCE = 6;
UPDATE SYS_MENU SET DISPLAY_SEQUENCE = 8
 WHERE MENU_ID = 'FACTORY_STD_SINGLE_BILL_OF_MATERIAL'
   AND PARENT_MENU_ID = 'FACTORY_STD_SINGLE_SEGMENT' AND DISPLAY_SEQUENCE = 7;
UPDATE SYS_MENU SET DISPLAY_SEQUENCE = 9
 WHERE MENU_ID = 'FACTORY_STD_BOR_CONDITION'
   AND PARENT_MENU_ID = 'FACTORY_STD_SINGLE_SEGMENT' AND DISPLAY_SEQUENCE = 8;
UPDATE SYS_MENU SET DISPLAY_SEQUENCE = 10
 WHERE MENU_ID = 'FACTORY_STD_BOR_RESOURCE'
   AND PARENT_MENU_ID = 'FACTORY_STD_SINGLE_SEGMENT' AND DISPLAY_SEQUENCE = 9;

INSERT INTO SYS_MENU
    (MENU_ID, MENU_NAME, PARENT_MENU_ID, DISPLAY_SEQUENCE, MENU_TYPE, PROGRAM_ID, UI_ID, VALID_STATE)
SELECT
    'FACTORY_STD_ROUTING_STEP', '라우팅 스텝 관리', 'FACTORY_STD_SINGLE_SEGMENT', 6,
    'Screen', '', 'FACTORY_STD_ROUTING_STEP', 'Valid'
WHERE EXISTS (SELECT 1 FROM SYS_MENU WHERE MENU_ID = 'FACTORY_STD_SINGLE_SEGMENT')
  AND NOT EXISTS (SELECT 1 FROM SYS_MENU WHERE MENU_ID = 'FACTORY_STD_ROUTING_STEP');

-- Keep English navigation labels consistent with the Korean canonical business terms.
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET VALUE = 'PM Plan Management'
 WHERE RESOURCE_KEY = 'menu.FACTORY_EMS_PM_ORDER_PLAN'
   AND LANGUAGE = 'EnUs' AND VALUE = 'PM Plan Creation';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET VALUE = 'PM Plan Grid'
 WHERE RESOURCE_KEY = 'menu.FACTORY_EMS_PM_ORDER_PLAN_GRIDTYPE'
   AND LANGUAGE = 'EnUs' AND VALUE = 'PM Plan Creation_Grid';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET VALUE = 'LOT Management'
 WHERE RESOURCE_KEY = 'menu.FACTORY_WPM_LOT_MANAGEMENT'
   AND LANGUAGE = 'EnUs' AND VALUE = 'Work Progress Management';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET VALUE = 'BOR Management (Condition Based)'
 WHERE RESOURCE_KEY = 'menu.FACTORY_STD_BOR_CONDITION'
   AND LANGUAGE = 'EnUs' AND VALUE = 'BOR Management_Condition-Based Registration';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET VALUE = 'BOR Management (Resource Based)'
 WHERE RESOURCE_KEY = 'menu.FACTORY_STD_BOR_RESOURCE'
   AND LANGUAGE = 'EnUs' AND VALUE = 'BOR Management_Resource-Based Registration';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET VALUE = 'Supplier Management'
 WHERE RESOURCE_KEY = 'screen.MES_MDM_COM_VENDOR.title'
   AND LANGUAGE = 'EnUs' AND VALUE = 'Vendor Management';
UPDATE SYS_MULTI_LANGUAGE_RESOURCE SET VALUE = 'Supplier Item Management'
 WHERE RESOURCE_KEY = 'screen.MES_MDM_COM_VENDOR_ITEM.title'
   AND LANGUAGE = 'EnUs' AND VALUE = 'Vendor Item Management';

INSERT INTO SYS_MULTI_LANGUAGE_RESOURCE (RESOURCE_KEY, MENU_ID, LANGUAGE, VALUE)
SELECT 'menu.FACTORY_STD_ROUTING_STEP', 'COMMON', 'EnUs', 'Routing Step Management'
WHERE NOT EXISTS (
    SELECT 1 FROM SYS_MULTI_LANGUAGE_RESOURCE
     WHERE RESOURCE_KEY = 'menu.FACTORY_STD_ROUTING_STEP' AND LANGUAGE = 'EnUs');

-- Imported Designer definitions are DB-first at runtime. Replace both literal Korean and the escaped form
-- emitted by System.Text.Json, but only while the catalog title is still the untouched legacy value.
UPDATE SYS_SCREEN_DEFINITION
   SET TITLE = 'LOT 보류',
       DEFINITION_JSON = REPLACE(DEFINITION_JSON, '"LOT Hold"', '"LOT 보류"')
 WHERE UI_ID = 'FACTORY_WPM_LOT_HOLD' AND TITLE = 'LOT Hold';

UPDATE SYS_SCREEN_DEFINITION
   SET TITLE = 'LOT 보류 해제',
       DEFINITION_JSON = REPLACE(
           REPLACE(DEFINITION_JSON, '"LOT Hold 해제"', '"LOT 보류 해제"'),
           '"LOT Hold \uD574\uC81C"', '"LOT \uBCF4\uB958 \uD574\uC81C"')
 WHERE UI_ID = 'FACTORY_WPM_LOT_HOLD_RELEASE' AND TITLE = 'LOT Hold 해제';

UPDATE SYS_SCREEN_DEFINITION
   SET TITLE = '수입검사 정보 연결',
       DEFINITION_JSON = REPLACE(
           REPLACE(DEFINITION_JSON, '"수입검사 정보연결"', '"수입검사 정보 연결"'),
           '"\uC218\uC785\uAC80\uC0AC \uC815\uBCF4\uC5F0\uACB0"',
           '"\uC218\uC785\uAC80\uC0AC \uC815\uBCF4 \uC5F0\uACB0"')
 WHERE UI_ID = 'FACTORY_QCA_IMPORT_INSPECTION_MAPPING' AND TITLE = '수입검사 정보연결';

UPDATE SYS_SCREEN_DEFINITION
   SET TITLE = '공정검사 정보 연결',
       DEFINITION_JSON = REPLACE(
           REPLACE(DEFINITION_JSON, '"공정검사 정보연결"', '"공정검사 정보 연결"'),
           '"\uACF5\uC815\uAC80\uC0AC \uC815\uBCF4\uC5F0\uACB0"',
           '"\uACF5\uC815\uAC80\uC0AC \uC815\uBCF4 \uC5F0\uACB0"')
 WHERE UI_ID = 'FACTORY_QCA_PROCESS_INSPECTION_MAPPING' AND TITLE = '공정검사 정보연결';

UPDATE SYS_SCREEN_DEFINITION
   SET TITLE = '출하검사 정보 연결',
       DEFINITION_JSON = REPLACE(
           REPLACE(DEFINITION_JSON, '"출하검사 정보연결"', '"출하검사 정보 연결"'),
           '"\uCD9C\uD558\uAC80\uC0AC \uC815\uBCF4\uC5F0\uACB0"',
           '"\uCD9C\uD558\uAC80\uC0AC \uC815\uBCF4 \uC5F0\uACB0"')
 WHERE UI_ID = 'FACTORY_QCA_SHIPMENT_INSPECTION_MAPPING' AND TITLE = '출하검사 정보연결';

UPDATE SYS_SCREEN_DEFINITION
   SET TITLE = '협력사 관리',
       DEFINITION_JSON = REPLACE(
           REPLACE(DEFINITION_JSON, '"벤더 관리"', '"협력사 관리"'),
           '"\uBCA4\uB354 \uAD00\uB9AC"', '"\uD611\uB825\uC0AC \uAD00\uB9AC"')
 WHERE UI_ID = 'MES_MDM_COM_VENDOR' AND TITLE = '벤더 관리';

UPDATE SYS_SCREEN_DEFINITION
   SET TITLE = '협력사 품목 관리',
       DEFINITION_JSON = REPLACE(
           REPLACE(DEFINITION_JSON, '"벤더 품목 관리"', '"협력사 품목 관리"'),
           '"\uBCA4\uB354 \uD488\uBAA9 \uAD00\uB9AC"',
           '"\uD611\uB825\uC0AC \uD488\uBAA9 \uAD00\uB9AC"')
 WHERE UI_ID = 'MES_MDM_COM_VENDOR_ITEM' AND TITLE = '벤더 품목 관리';
