CREATE TABLE POM_LOT_DEFECT_EXECUTION (
    EXECUTION_ID        NVARCHAR(50)    NOT NULL,
    LOT_ID              NVARCHAR(50)    NOT NULL,
    PLANT_ID            NVARCHAR(50)    NOT NULL,
    PROCESS_ID          NVARCHAR(50)    NOT NULL,
    DEFECT_CODE         NVARCHAR(50)    NOT NULL,
    DEFECT_QTY          DECIMAL(18,4)   NOT NULL,
    EXECUTION_USER      NVARCHAR(50)    NOT NULL,
    CLIENT_CHANNEL      NVARCHAR(20)    NOT NULL,
    DEVICE_ID           NVARCHAR(100)   NULL,
    OCCURRED_AT         DATETIME2       NOT NULL,
    CREATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_POM_LOT_DEFECT_EXECUTION PRIMARY KEY (EXECUTION_ID, DEFECT_CODE),
    CONSTRAINT FK_POM_LOT_DEFECT_EXECUTION_EXECUTION FOREIGN KEY (EXECUTION_ID)
        REFERENCES POM_LOT_EXECUTION (EXECUTION_ID),
    CONSTRAINT CK_POM_LOT_DEFECT_EXECUTION_QTY CHECK (DEFECT_QTY > 0),
    CONSTRAINT CK_POM_LOT_DEFECT_EXECUTION_CHANNEL CHECK (
        CLIENT_CHANNEL IN ('MES', 'MOBILE', 'POP'))
);

CREATE INDEX IX_POM_LOT_DEFECT_EXECUTION_LOT
    ON POM_LOT_DEFECT_EXECUTION (LOT_ID, OCCURRED_AT DESC);
CREATE INDEX IX_POM_LOT_DEFECT_EXECUTION_CODE
    ON POM_LOT_DEFECT_EXECUTION (PLANT_ID, DEFECT_CODE, OCCURRED_AT DESC);
