-- Separate request provenance from supervisor approval or rejection provenance.
ALTER TABLE POM_ROUTE_EXCEPTION ADD REVIEW_CLIENT_CHANNEL NVARCHAR(20) NULL;
ALTER TABLE POM_ROUTE_EXCEPTION ADD REVIEW_DEVICE_ID NVARCHAR(100) NULL;

UPDATE POM_ROUTE_EXCEPTION
   SET REVIEW_CLIENT_CHANNEL = CLIENT_CHANNEL
 WHERE REVIEWED_BY IS NOT NULL AND REVIEW_CLIENT_CHANNEL IS NULL;

ALTER TABLE POM_ROUTE_EXCEPTION ADD CONSTRAINT CK_POM_ROUTE_EXCEPTION_REVIEW_CHANNEL CHECK (
    (
        (REVIEWED_BY IS NULL AND REVIEW_CLIENT_CHANNEL IS NULL AND REVIEW_DEVICE_ID IS NULL)
        OR
        (REVIEWED_BY IS NOT NULL AND REVIEWED_AT IS NOT NULL
         AND REVIEW_CLIENT_CHANNEL IN ('MES', 'MOBILE', 'POP'))
    )
    AND
    (
        STATUS NOT IN ('Approved', 'Rejected', 'Applied')
        OR (REVIEWED_BY IS NOT NULL AND REVIEWED_AT IS NOT NULL
            AND REVIEW_CLIENT_CHANNEL IS NOT NULL)
    )
);
