-- Persist the optimistic concurrency identity used by each new work-order command.
ALTER TABLE POM_WORK_ORDER_EXECUTION ADD EXPECTED_VERSION INT NULL;
ALTER TABLE POM_WORK_ORDER_EXECUTION ADD RESULT_VERSION INT NULL;

ALTER TABLE POM_WORK_ORDER_EXECUTION ADD CONSTRAINT CK_POM_WORK_ORDER_EXECUTION_VERSION_IDENTITY CHECK (
    (EXPECTED_VERSION IS NULL AND RESULT_VERSION IS NULL)
    OR (EXPECTED_VERSION >= 1 AND RESULT_VERSION = EXPECTED_VERSION + 1)
);
