-- Make the LOT identity part of every routing/defect audit relationship. EXECUTION_ID
-- and EXCEPTION_ID remain globally unique. The composite keys let SQL Server reject a
-- syntactically valid identifier that belongs to a different LOT.
CREATE UNIQUE INDEX UX_POM_LOT_EXECUTION_ID_LOT
    ON POM_LOT_EXECUTION (EXECUTION_ID, LOT_ID);
CREATE UNIQUE INDEX UX_POM_ROUTE_EXCEPTION_ID_LOT
    ON POM_ROUTE_EXCEPTION (EXCEPTION_ID, LOT_ID);

ALTER TABLE POM_LOT_EXECUTION DROP CONSTRAINT FK_POM_LOT_EXECUTION_ROUTE_EXCEPTION;
ALTER TABLE POM_LOT_EXECUTION ADD CONSTRAINT FK_POM_LOT_EXECUTION_ROUTE_EXCEPTION_LOT
    FOREIGN KEY (ROUTE_EXCEPTION_ID, LOT_ID)
    REFERENCES POM_ROUTE_EXCEPTION (EXCEPTION_ID, LOT_ID);

ALTER TABLE POM_LOT_DEFECT_EXECUTION DROP CONSTRAINT FK_POM_LOT_DEFECT_EXECUTION_EXECUTION;
ALTER TABLE POM_LOT_DEFECT_EXECUTION ADD CONSTRAINT FK_POM_LOT_DEFECT_EXECUTION_EXECUTION_LOT
    FOREIGN KEY (EXECUTION_ID, LOT_ID)
    REFERENCES POM_LOT_EXECUTION (EXECUTION_ID, LOT_ID);
ALTER TABLE POM_LOT_DEFECT_EXECUTION ADD CONSTRAINT FK_POM_LOT_DEFECT_EXECUTION_LOT_PLANT
    FOREIGN KEY (LOT_ID, PLANT_ID)
    REFERENCES POM_LOT (LOT_ID, PLANT_ID);

-- An applied approval must identify an execution from the same LOT. The execution row
-- is inserted first and the approval ledger is then marked Applied in the same transaction,
-- so this nullable composite reference preserves the existing atomic write order.
ALTER TABLE POM_ROUTE_EXCEPTION ADD CONSTRAINT FK_POM_ROUTE_EXCEPTION_APPLIED_EXECUTION_LOT
    FOREIGN KEY (APPLIED_EXECUTION_ID, LOT_ID)
    REFERENCES POM_LOT_EXECUTION (EXECUTION_ID, LOT_ID);
