-- IVT 자재 소비 원장. 설비 TRACE/시퀀스, LOT 불출, 레시피 정량 소비와 수동 조정을 한 원장으로
-- 기록하되 MODE로 발생 경로를 보존한다. 실제 방식별 해석은 프로젝트 플러그인이 담당하고 이 테이블은
-- 공통 멱등성·재고 귀속·반전 감사의 단일 원천이다. 삭제/UPDATE 보정 대신 반전 행을 추가한다.
-- 기존 재고/수불 원장도 소비 원장과 같은 정밀도를 가져야 한다. 그렇지 않으면 SQL Server에서
-- 0.001 단위 소비가 0.00으로 반올림되어 소비 이력만 쌓이고 실제 재고는 줄지 않을 수 있다.
ALTER TABLE IVT_MATERIAL_LOT ALTER COLUMN CURRENT_QTY DECIMAL(22,6) NULL;
ALTER TABLE IVT_MATERIAL_TX ALTER COLUMN QTY DECIMAL(22,6) NULL;

CREATE TABLE IVT_MATERIAL_CONSUMPTION_HISTORY (
    CONSUMPTION_ID   NVARCHAR(50)    NOT NULL,
    IDEMPOTENCY_KEY  NVARCHAR(100)   NOT NULL,
    REQUEST_HASH     NVARCHAR(64)    NOT NULL,
    PLANT_ID         NVARCHAR(50)    NOT NULL,
    EQUIPMENT_ID     NVARCHAR(50)    NOT NULL,
    MATERIAL_LOT_ID  NVARCHAR(50)    NOT NULL,
    MATERIAL_ID      NVARCHAR(50)    NOT NULL,
    PROCESS_LOT_ID   NVARCHAR(50)    NULL,
    WORK_ORDER_ID    NVARCHAR(50)    NULL,
    PROCESS_ID       NVARCHAR(50)    NULL,
    RECIPE_ID        NVARCHAR(50)    NULL,
    RECIPE_VERSION   INT             NULL,
    CONSUMPTION_MODE NVARCHAR(30)    NOT NULL,
    QUANTITY         DECIMAL(22,6)   NOT NULL,
    UNIT             NVARCHAR(30)    NOT NULL,
    TRACE_ID         NVARCHAR(100)   NULL,
    TAG_ID           NVARCHAR(100)   NULL,
    SOURCE_EVENT_ID  NVARCHAR(100)   NOT NULL,
    SOURCE_SYSTEM    NVARCHAR(50)    NOT NULL,
    OPERATOR_ID      NVARCHAR(50)    NOT NULL,
    CORRELATION_ID   NVARCHAR(100)   NULL,
    REVERSAL_OF_ID   NVARCHAR(50)    NULL,
    STATUS           NVARCHAR(20)    NOT NULL DEFAULT 'Committed',
    REVERSED_BY      NVARCHAR(50)    NULL,
    REVERSED_AT      DATETIME2       NULL,
    REVERSAL_REASON  NVARCHAR(500)   NULL,
    METADATA_JSON    NVARCHAR(MAX)   NULL,
    OCCURRED_AT      DATETIME2       NOT NULL,
    CREATED_BY       NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT       DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_IVT_MATERIAL_CONSUMPTION PRIMARY KEY (CONSUMPTION_ID),
    CONSTRAINT CK_IVT_MATERIAL_CONSUMPTION_QTY CHECK (QUANTITY > 0),
    CONSTRAINT FK_IVT_MATERIAL_CONSUMPTION_LOT FOREIGN KEY (MATERIAL_LOT_ID)
        REFERENCES IVT_MATERIAL_LOT (LOT_ID),
    CONSTRAINT FK_IVT_MATERIAL_CONSUMPTION_REV FOREIGN KEY (REVERSAL_OF_ID)
        REFERENCES IVT_MATERIAL_CONSUMPTION_HISTORY (CONSUMPTION_ID)
);

CREATE UNIQUE INDEX UX_IVT_MATERIAL_CONSUMPTION_KEY
    ON IVT_MATERIAL_CONSUMPTION_HISTORY (IDEMPOTENCY_KEY);
CREATE UNIQUE INDEX UX_IVT_MATERIAL_CONSUMPTION_REVERSAL
    ON IVT_MATERIAL_CONSUMPTION_HISTORY (REVERSAL_OF_ID) WHERE REVERSAL_OF_ID IS NOT NULL;
CREATE INDEX IX_IVT_MATERIAL_CONSUMPTION_LOT
    ON IVT_MATERIAL_CONSUMPTION_HISTORY (MATERIAL_LOT_ID, OCCURRED_AT DESC);
CREATE INDEX IX_IVT_MATERIAL_CONSUMPTION_PROCESS_LOT
    ON IVT_MATERIAL_CONSUMPTION_HISTORY (PROCESS_LOT_ID, OCCURRED_AT DESC);
CREATE INDEX IX_IVT_MATERIAL_CONSUMPTION_EQUIPMENT
    ON IVT_MATERIAL_CONSUMPTION_HISTORY (EQUIPMENT_ID, OCCURRED_AT DESC);
CREATE UNIQUE INDEX UX_IVT_MATERIAL_CONSUMPTION_SOURCE
    ON IVT_MATERIAL_CONSUMPTION_HISTORY (SOURCE_SYSTEM, SOURCE_EVENT_ID)
    WHERE REVERSAL_OF_ID IS NULL;
