-- EMS 보전/예비부품/생산툴 공통 원장. 기존 EMS_WORK_ORDER, EMS_MAINTENANCE_PLAN,
-- EMS_SPARE_PART, EMS_SPARE_PART_INOUT을 대체하지 않고 누락된 작업자 행동 증거와 계획 데이터를 보강한다.

-- 로그인 작업자가 수행한 보전 W/O 행동의 append-only 증거. ASSIGNEE_ID(담당 예정자)와
-- ACTOR_ID(실제 실행자)를 분리해 수동 운전 감사가 mutable UPDATED_BY 한 칸에 덮어써지지 않게 한다.
CREATE TABLE EMS_MAINTENANCE_ACTION_HISTORY (
    ACTION_ID       NVARCHAR(50)    NOT NULL,
    WO_ID           NVARCHAR(50)    NULL,
    MAINTENANCE_PLAN_ID NVARCHAR(50) NULL,
    EQUIPMENT_ID    NVARCHAR(50)    NOT NULL,
    MAINTENANCE_TYPE NVARCHAR(20)   NOT NULL,
    ACTION_TYPE     NVARCHAR(30)    NOT NULL,
    RESULT_STATUS   NVARCHAR(20)    NOT NULL,
    ACTOR_ID        NVARCHAR(50)    NOT NULL,
    ASSIGNEE_ID     NVARCHAR(50)    NULL,
    SOURCE          NVARCHAR(20)    NOT NULL DEFAULT 'Manual',
    CLIENT_CHANNEL  NVARCHAR(20)    NOT NULL DEFAULT 'MES',
    DEVICE_ID       NVARCHAR(100)   NULL,
    FAILURE_CODE_ID NVARCHAR(50)    NULL,
    REMARK          NVARCHAR(500)   NULL,
    ACTION_AT       DATETIME2       NOT NULL,
    CREATED_BY      NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_EMS_MAINTENANCE_ACTION PRIMARY KEY (ACTION_ID),
    CONSTRAINT FK_EMS_MAINT_ACTION_WO FOREIGN KEY (WO_ID) REFERENCES EMS_WORK_ORDER (WO_ID),
    CONSTRAINT FK_EMS_MAINT_ACTION_PLAN FOREIGN KEY (MAINTENANCE_PLAN_ID)
        REFERENCES EMS_MAINTENANCE_PLAN (PLAN_ID)
);
CREATE INDEX IX_EMS_MAINT_ACTION_WO
    ON EMS_MAINTENANCE_ACTION_HISTORY (WO_ID, ACTION_AT DESC);
CREATE INDEX IX_EMS_MAINT_ACTION_EQUIPMENT
    ON EMS_MAINTENANCE_ACTION_HISTORY (EQUIPMENT_ID, ACTION_AT DESC);
CREATE INDEX IX_EMS_MAINT_ACTION_ACTOR
    ON EMS_MAINTENANCE_ACTION_HISTORY (ACTOR_ID, ACTION_AT DESC);

-- 적정재고/최적화 입력값. EMS_SPARE_PART의 MIN/MAX는 현재 운영 한계값으로 유지하고,
-- 수요·서비스수준·재주문 계산 파라미터는 별도 정책 행으로 버전 독립 관리한다.
CREATE TABLE EMS_SPARE_PART_STOCK_POLICY (
    PART_ID              NVARCHAR(50)    NOT NULL,
    SAFETY_STOCK         DECIMAL(18,4)   NOT NULL DEFAULT 0,
    REORDER_POINT        DECIMAL(18,4)   NOT NULL DEFAULT 0,
    TARGET_STOCK         DECIMAL(18,4)   NOT NULL DEFAULT 0,
    RESERVED_QTY         DECIMAL(18,4)   NOT NULL DEFAULT 0,
    AVG_DAILY_USAGE      DECIMAL(18,6)   NOT NULL DEFAULT 0,
    SERVICE_LEVEL        DECIMAL(8,4)    NULL,
    REVIEW_CYCLE_DAYS    INT             NULL,
    IS_ACTIVE            BIT             NOT NULL DEFAULT 1,
    VERSION_NO           INT             NOT NULL DEFAULT 1,
    LAST_IDEMPOTENCY_KEY NVARCHAR(100)   NOT NULL DEFAULT '',
    LAST_REQUEST_HASH    NVARCHAR(128)   NOT NULL DEFAULT '',
    CREATED_BY           NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT           DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY           NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT           DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_EMS_SPARE_STOCK_POLICY PRIMARY KEY (PART_ID),
    CONSTRAINT FK_EMS_SPARE_STOCK_POLICY_PART FOREIGN KEY (PART_ID) REFERENCES EMS_SPARE_PART (PART_ID),
    CONSTRAINT CK_EMS_SPARE_STOCK_POLICY_VALUES CHECK (
        SAFETY_STOCK >= 0 AND REORDER_POINT >= 0 AND TARGET_STOCK >= SAFETY_STOCK
        AND TARGET_STOCK >= REORDER_POINT AND RESERVED_QTY >= 0 AND AVG_DAILY_USAGE >= 0
        AND (SERVICE_LEVEL IS NULL OR (SERVICE_LEVEL >= 0 AND SERVICE_LEVEL <= 1))
        AND (REVIEW_CYCLE_DAYS IS NULL OR REVIEW_CYCLE_DAYS > 0)
        AND VERSION_NO > 0)
);
CREATE UNIQUE INDEX UX_EMS_SPARE_STOCK_POLICY_IDEMPOTENCY
    ON EMS_SPARE_PART_STOCK_POLICY (LAST_IDEMPOTENCY_KEY)
    WHERE LAST_IDEMPOTENCY_KEY <> '';

-- 부품별 복수 공급처와 조달 조건. 공급처 마스터는 MDM_VENDOR를 문자열로 느슨 참조해 모듈 배포 독립성을 유지한다.
CREATE TABLE EMS_SPARE_PART_SUPPLIER (
    PART_SUPPLIER_ID NVARCHAR(50)    NOT NULL,
    PART_ID          NVARCHAR(50)    NOT NULL,
    VENDOR_ID        NVARCHAR(50)    NOT NULL,
    VENDOR_PART_NO   NVARCHAR(100)   NULL,
    LEAD_TIME_DAYS   INT             NOT NULL DEFAULT 0,
    MOQ              DECIMAL(18,4)   NULL,
    UNIT_PRICE       DECIMAL(18,4)   NULL,
    CURRENCY         NVARCHAR(10)    NULL,
    IS_PRIMARY       BIT             NOT NULL DEFAULT 0,
    IS_ACTIVE        BIT             NOT NULL DEFAULT 1,
    VERSION_NO       INT             NOT NULL DEFAULT 1,
    LAST_IDEMPOTENCY_KEY NVARCHAR(100) NOT NULL DEFAULT '',
    LAST_REQUEST_HASH NVARCHAR(128)  NOT NULL DEFAULT '',
    CREATED_BY       NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT       DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY       NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT       DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_EMS_SPARE_PART_SUPPLIER PRIMARY KEY (PART_SUPPLIER_ID),
    CONSTRAINT FK_EMS_SPARE_PART_SUPPLIER_PART FOREIGN KEY (PART_ID) REFERENCES EMS_SPARE_PART (PART_ID),
    CONSTRAINT FK_EMS_SPARE_PART_SUPPLIER_VENDOR FOREIGN KEY (VENDOR_ID) REFERENCES MDM_VENDOR (VENDOR_ID),
    CONSTRAINT CK_EMS_SPARE_PART_SUPPLIER_VALUES CHECK (
        LEAD_TIME_DAYS >= 0 AND (MOQ IS NULL OR MOQ > 0)
        AND (UNIT_PRICE IS NULL OR UNIT_PRICE >= 0)
        AND ((UNIT_PRICE IS NULL AND CURRENCY IS NULL) OR (UNIT_PRICE IS NOT NULL AND CURRENCY IS NOT NULL))
        AND (IS_PRIMARY = 0 OR IS_ACTIVE = 1) AND VERSION_NO > 0)
);
CREATE UNIQUE INDEX UX_EMS_SPARE_PART_VENDOR
    ON EMS_SPARE_PART_SUPPLIER (PART_ID, VENDOR_ID);
CREATE INDEX IX_EMS_SPARE_PART_LEAD_TIME
    ON EMS_SPARE_PART_SUPPLIER (PART_ID, IS_ACTIVE, LEAD_TIME_DAYS);
CREATE UNIQUE INDEX UX_EMS_SPARE_PART_PRIMARY_ACTIVE
    ON EMS_SPARE_PART_SUPPLIER (PART_ID)
    WHERE IS_PRIMARY = 1 AND IS_ACTIVE = 1;
CREATE UNIQUE INDEX UX_EMS_SPARE_PART_SUPPLIER_IDEMPOTENCY
    ON EMS_SPARE_PART_SUPPLIER (LAST_IDEMPOTENCY_KEY)
    WHERE LAST_IDEMPOTENCY_KEY <> '';

-- 설비/설비등급 BOM과 예비부품 연결. EQUIPMENT_ID와 EQUIPMENT_CLASS_ID 중 실제 적용 범위만 채운다.
CREATE TABLE EMS_EQUIPMENT_PART_BOM (
    BOM_ITEM_ID          NVARCHAR(50)    NOT NULL,
    EQUIPMENT_ID         NVARCHAR(50)    NULL,
    EQUIPMENT_CLASS_ID   NVARCHAR(50)    NULL,
    PART_ID              NVARCHAR(50)    NOT NULL,
    QUANTITY_PER         DECIMAL(18,4)   NOT NULL DEFAULT 1,
    CRITICALITY          NVARCHAR(20)    NULL,
    REPLACEMENT_CYCLE_DAYS INT           NULL,
    REPLACEMENT_CYCLE_COUNT DECIMAL(18,4) NULL,
    POSITION_CODE        NVARCHAR(100)   NULL,
    IS_ACTIVE            BIT             NOT NULL DEFAULT 1,
    VERSION_NO           INT             NOT NULL DEFAULT 1,
    LAST_IDEMPOTENCY_KEY NVARCHAR(100)   NOT NULL DEFAULT '',
    LAST_REQUEST_HASH    NVARCHAR(128)   NOT NULL DEFAULT '',
    CREATED_BY           NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT           DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY           NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT           DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_EMS_EQUIPMENT_PART_BOM PRIMARY KEY (BOM_ITEM_ID),
    CONSTRAINT FK_EMS_EQUIPMENT_PART_BOM_PART FOREIGN KEY (PART_ID) REFERENCES EMS_SPARE_PART (PART_ID),
    CONSTRAINT FK_EMS_EQUIPMENT_PART_BOM_EQUIPMENT FOREIGN KEY (EQUIPMENT_ID) REFERENCES MDM_EQUIPMENT (EQUIPMENT_ID),
    CONSTRAINT FK_EMS_EQUIPMENT_PART_BOM_CLASS FOREIGN KEY (EQUIPMENT_CLASS_ID) REFERENCES MDM_EQUIPMENT_CLASS (EQUIPMENT_CLASS_ID),
    CONSTRAINT CK_EMS_EQUIPMENT_PART_BOM_SCOPE CHECK (
        (EQUIPMENT_ID IS NOT NULL AND EQUIPMENT_CLASS_ID IS NULL)
        OR (EQUIPMENT_ID IS NULL AND EQUIPMENT_CLASS_ID IS NOT NULL)),
    CONSTRAINT CK_EMS_EQUIPMENT_PART_BOM_VALUES CHECK (
        QUANTITY_PER > 0
        AND (CRITICALITY IS NULL OR CRITICALITY IN ('Critical', 'High', 'Medium', 'Low'))
        AND (REPLACEMENT_CYCLE_DAYS IS NULL OR REPLACEMENT_CYCLE_DAYS > 0)
        AND (REPLACEMENT_CYCLE_COUNT IS NULL OR REPLACEMENT_CYCLE_COUNT > 0)
        AND VERSION_NO > 0)
);
CREATE INDEX IX_EMS_EQUIPMENT_PART_BOM_EQUIPMENT
    ON EMS_EQUIPMENT_PART_BOM (EQUIPMENT_ID, PART_ID);
CREATE INDEX IX_EMS_EQUIPMENT_PART_BOM_CLASS
    ON EMS_EQUIPMENT_PART_BOM (EQUIPMENT_CLASS_ID, PART_ID);
CREATE UNIQUE INDEX UX_EMS_EQUIPMENT_PART_BOM_IDEMPOTENCY
    ON EMS_EQUIPMENT_PART_BOM (LAST_IDEMPOTENCY_KEY)
    WHERE LAST_IDEMPOTENCY_KEY <> '';

-- 실제 부품 사용 원장. V110에서 처음 생성되는 신규 테이블이므로 INOUT_ID를 nullable legacy
-- 참조로 남기지 않고 재고 증감 원장과 1:1로 강제한다. BOM은 선택이지만 지정하면 동일 migration의
-- BOM_ITEM_ID를 참조하고, W/O·설비·실제 로그인 작업자를 함께 보존한다.
CREATE TABLE EMS_SPARE_PART_USAGE (
    USAGE_ID       NVARCHAR(50)    NOT NULL,
    INOUT_ID       NVARCHAR(50)    NOT NULL,
    PART_ID        NVARCHAR(50)    NOT NULL,
    BOM_ITEM_ID    NVARCHAR(50)    NULL,
    EQUIPMENT_ID   NVARCHAR(50)    NOT NULL,
    WO_ID          NVARCHAR(50)    NULL,
    QUANTITY       DECIMAL(18,4)   NOT NULL,
    USED_BY        NVARCHAR(50)    NOT NULL,
    USED_AT        DATETIME2       NOT NULL,
    REMOVAL_REASON NVARCHAR(500)   NULL,
    SERIAL_NO      NVARCHAR(100)   NULL,
    LOT_NO         NVARCHAR(100)   NULL,
    CREATED_BY     NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT     DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_EMS_SPARE_PART_USAGE PRIMARY KEY (USAGE_ID),
    CONSTRAINT FK_EMS_SPARE_USAGE_INOUT FOREIGN KEY (INOUT_ID) REFERENCES EMS_SPARE_PART_INOUT (INOUT_ID),
    CONSTRAINT FK_EMS_SPARE_USAGE_PART FOREIGN KEY (PART_ID) REFERENCES EMS_SPARE_PART (PART_ID),
    CONSTRAINT FK_EMS_SPARE_USAGE_BOM FOREIGN KEY (BOM_ITEM_ID) REFERENCES EMS_EQUIPMENT_PART_BOM (BOM_ITEM_ID),
    CONSTRAINT FK_EMS_SPARE_USAGE_EQUIPMENT FOREIGN KEY (EQUIPMENT_ID) REFERENCES MDM_EQUIPMENT (EQUIPMENT_ID),
    CONSTRAINT FK_EMS_SPARE_USAGE_WO FOREIGN KEY (WO_ID) REFERENCES EMS_WORK_ORDER (WO_ID),
    CONSTRAINT CK_EMS_SPARE_USAGE_QUANTITY CHECK (QUANTITY > 0)
);
CREATE UNIQUE INDEX UX_EMS_SPARE_USAGE_INOUT ON EMS_SPARE_PART_USAGE (INOUT_ID);
CREATE INDEX IX_EMS_SPARE_USAGE_PART ON EMS_SPARE_PART_USAGE (PART_ID, USED_AT DESC);
CREATE INDEX IX_EMS_SPARE_USAGE_EQUIPMENT ON EMS_SPARE_PART_USAGE (EQUIPMENT_ID, USED_AT DESC);

-- 생산 툴 마스터. 계측기는 QMS_GAUGE가 소유하므로 여기서는 설비 장착·수명·공정사용 대상만 관리한다.
CREATE TABLE EMS_TOOL (
    TOOL_ID            NVARCHAR(50)    NOT NULL,
    TOOL_NAME          NVARCHAR(200)   NOT NULL,
    TOOL_TYPE          NVARCHAR(50)    NOT NULL,
    TOOL_NUMBER        NVARCHAR(100)   NULL,
    SERIAL_NO          NVARCHAR(100)   NULL,
    EQUIPMENT_CLASS_ID NVARCHAR(50)    NULL,
    MAX_USE_COUNT      DECIMAL(18,4)   NULL,
    MAX_USE_MINUTES    DECIMAL(18,4)   NULL,
    CURRENT_USE_COUNT  DECIMAL(18,4)   NOT NULL DEFAULT 0,
    CURRENT_USE_MINUTES DECIMAL(18,4)  NOT NULL DEFAULT 0,
    INSPECTION_CYCLE_DAYS INT          NULL,
    CALIBRATION_CYCLE_DAYS INT         NULL,
    LAST_INSPECTED_AT  DATETIME2       NULL,
    LAST_CALIBRATED_AT DATETIME2       NULL,
    NEXT_INSPECTION_DUE_AT DATETIME2   NULL,
    NEXT_CALIBRATION_DUE_AT DATETIME2  NULL,
    STATUS             NVARCHAR(20)    NOT NULL DEFAULT 'Available',
    LOCATION           NVARCHAR(200)   NULL,
    IS_ACTIVE          BIT             NOT NULL DEFAULT 1,
    CREATED_BY         NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT         DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY         NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT         DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_EMS_TOOL PRIMARY KEY (TOOL_ID),
    CONSTRAINT FK_EMS_TOOL_EQUIPMENT_CLASS FOREIGN KEY (EQUIPMENT_CLASS_ID)
        REFERENCES MDM_EQUIPMENT_CLASS (EQUIPMENT_CLASS_ID),
    CONSTRAINT CK_EMS_TOOL_STATUS CHECK (
        STATUS IN ('Available', 'Mounted', 'Due', 'Blocked', 'Retired')),
    CONSTRAINT CK_EMS_TOOL_LIFE_LIMIT CHECK (
        (MAX_USE_COUNT IS NULL OR MAX_USE_COUNT >= 0)
        AND (MAX_USE_MINUTES IS NULL OR MAX_USE_MINUTES >= 0)
        AND CURRENT_USE_COUNT >= 0 AND CURRENT_USE_MINUTES >= 0),
    CONSTRAINT CK_EMS_TOOL_CYCLE CHECK (
        (INSPECTION_CYCLE_DAYS IS NULL OR INSPECTION_CYCLE_DAYS > 0)
        AND (CALIBRATION_CYCLE_DAYS IS NULL OR CALIBRATION_CYCLE_DAYS > 0))
);
CREATE INDEX IX_EMS_TOOL_TYPE_STATUS ON EMS_TOOL (TOOL_TYPE, STATUS);

CREATE TABLE EMS_TOOL_MOUNT_HISTORY (
    MOUNT_ID       NVARCHAR(50)    NOT NULL,
    IDEMPOTENCY_KEY NVARCHAR(100)  NOT NULL,
    REQUEST_HASH   NVARCHAR(128)   NOT NULL,
    TOOL_ID        NVARCHAR(50)    NOT NULL,
    EQUIPMENT_ID   NVARCHAR(50)    NOT NULL,
    POSITION_CODE  NVARCHAR(100)   NULL,
    MOUNTED_AT     DATETIME2       NOT NULL,
    MOUNTED_BY     NVARCHAR(50)    NOT NULL,
    UNMOUNTED_AT   DATETIME2       NULL,
    UNMOUNTED_BY   NVARCHAR(50)    NULL,
    UNMOUNT_IDEMPOTENCY_KEY NVARCHAR(100) NULL,
    UNMOUNT_REQUEST_HASH NVARCHAR(128) NULL,
    UNMOUNT_REASON NVARCHAR(500)   NULL,
    CREATED_BY     NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT     DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY     NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT     DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_EMS_TOOL_MOUNT_HISTORY PRIMARY KEY (MOUNT_ID),
    CONSTRAINT FK_EMS_TOOL_MOUNT_TOOL FOREIGN KEY (TOOL_ID) REFERENCES EMS_TOOL (TOOL_ID),
    CONSTRAINT FK_EMS_TOOL_MOUNT_EQUIPMENT FOREIGN KEY (EQUIPMENT_ID)
        REFERENCES MDM_EQUIPMENT (EQUIPMENT_ID),
    CONSTRAINT CK_EMS_TOOL_MOUNT_WINDOW CHECK (
        UNMOUNTED_AT IS NULL OR UNMOUNTED_AT >= MOUNTED_AT)
);
CREATE UNIQUE INDEX UX_EMS_TOOL_MOUNT_IDEMPOTENCY
    ON EMS_TOOL_MOUNT_HISTORY (IDEMPOTENCY_KEY);
CREATE UNIQUE INDEX UX_EMS_TOOL_UNMOUNT_IDEMPOTENCY
    ON EMS_TOOL_MOUNT_HISTORY (UNMOUNT_IDEMPOTENCY_KEY) WHERE UNMOUNT_IDEMPOTENCY_KEY IS NOT NULL;
CREATE UNIQUE INDEX UX_EMS_TOOL_ACTIVE_MOUNT
    ON EMS_TOOL_MOUNT_HISTORY (TOOL_ID) WHERE UNMOUNTED_AT IS NULL;
CREATE INDEX IX_EMS_TOOL_MOUNT_EQUIPMENT
    ON EMS_TOOL_MOUNT_HISTORY (EQUIPMENT_ID, MOUNTED_AT DESC);

CREATE TABLE EMS_TOOL_USAGE_HISTORY (
    USAGE_ID       NVARCHAR(50)    NOT NULL,
    IDEMPOTENCY_KEY NVARCHAR(100)  NOT NULL,
    REQUEST_HASH   NVARCHAR(128)   NOT NULL,
    TOOL_ID        NVARCHAR(50)    NOT NULL,
    MOUNT_ID       NVARCHAR(50)    NULL,
    EQUIPMENT_ID   NVARCHAR(50)    NOT NULL,
    PROCESS_LOT_ID NVARCHAR(50)    NULL,
    WORK_ORDER_ID  NVARCHAR(50)    NULL,
    PROCESS_ID     NVARCHAR(50)    NULL,
    RECIPE_ID      NVARCHAR(50)    NULL,
    RECIPE_VERSION INT             NULL,
    USE_COUNT      DECIMAL(18,4)   NOT NULL DEFAULT 0,
    USE_MINUTES    DECIMAL(18,4)   NOT NULL DEFAULT 0,
    USED_AT        DATETIME2       NOT NULL,
    USED_BY        NVARCHAR(50)    NOT NULL,
    TRACE_ID       NVARCHAR(100)   NULL,
    CONDITION_SNAPSHOT_JSON NVARCHAR(MAX) NULL,
    CREATED_BY     NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT     DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_EMS_TOOL_USAGE_HISTORY PRIMARY KEY (USAGE_ID),
    CONSTRAINT FK_EMS_TOOL_USAGE_TOOL FOREIGN KEY (TOOL_ID) REFERENCES EMS_TOOL (TOOL_ID),
    CONSTRAINT FK_EMS_TOOL_USAGE_MOUNT FOREIGN KEY (MOUNT_ID)
        REFERENCES EMS_TOOL_MOUNT_HISTORY (MOUNT_ID),
    CONSTRAINT FK_EMS_TOOL_USAGE_EQUIPMENT FOREIGN KEY (EQUIPMENT_ID)
        REFERENCES MDM_EQUIPMENT (EQUIPMENT_ID),
    CONSTRAINT CK_EMS_TOOL_USAGE_VALUE CHECK (
        USE_COUNT >= 0 AND USE_MINUTES >= 0 AND (USE_COUNT > 0 OR USE_MINUTES > 0))
);
CREATE UNIQUE INDEX UX_EMS_TOOL_USAGE_IDEMPOTENCY
    ON EMS_TOOL_USAGE_HISTORY (IDEMPOTENCY_KEY);
CREATE INDEX IX_EMS_TOOL_USAGE_TOOL ON EMS_TOOL_USAGE_HISTORY (TOOL_ID, USED_AT DESC);
CREATE INDEX IX_EMS_TOOL_USAGE_LOT ON EMS_TOOL_USAGE_HISTORY (PROCESS_LOT_ID, USED_AT DESC);

-- INSPECTION_TYPE=Inspection/Calibration로 점검과 교정을 한 원장에 기록하되 인증서·차기기한을 보존한다.
CREATE TABLE EMS_TOOL_INSPECTION_HISTORY (
    INSPECTION_ID  NVARCHAR(50)    NOT NULL,
    IDEMPOTENCY_KEY NVARCHAR(100)  NOT NULL,
    REQUEST_HASH   NVARCHAR(128)   NOT NULL,
    TOOL_ID        NVARCHAR(50)    NOT NULL,
    INSPECTION_TYPE NVARCHAR(20)   NOT NULL,
    RESULT         NVARCHAR(20)    NOT NULL,
    MEASURED_VALUE NVARCHAR(200)   NULL,
    STANDARD_VALUE NVARCHAR(200)   NULL,
    CERTIFICATE_NO NVARCHAR(100)   NULL,
    INSPECTED_AT   DATETIME2       NOT NULL,
    INSPECTED_BY   NVARCHAR(50)    NOT NULL,
    NEXT_DUE_AT    DATETIME2       NULL,
    REMARK         NVARCHAR(500)   NULL,
    CREATED_BY     NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT     DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_EMS_TOOL_INSPECTION PRIMARY KEY (INSPECTION_ID),
    CONSTRAINT FK_EMS_TOOL_INSPECTION_TOOL FOREIGN KEY (TOOL_ID) REFERENCES EMS_TOOL (TOOL_ID),
    CONSTRAINT CK_EMS_TOOL_INSPECTION_TYPE CHECK (
        INSPECTION_TYPE IN ('Inspection', 'Calibration')),
    CONSTRAINT CK_EMS_TOOL_INSPECTION_RESULT CHECK (RESULT IN ('Pass', 'Fail')),
    CONSTRAINT CK_EMS_TOOL_INSPECTION_DUE CHECK (
        NEXT_DUE_AT IS NULL OR NEXT_DUE_AT > INSPECTED_AT)
);
CREATE UNIQUE INDEX UX_EMS_TOOL_INSPECTION_IDEMPOTENCY
    ON EMS_TOOL_INSPECTION_HISTORY (IDEMPOTENCY_KEY);
CREATE INDEX IX_EMS_TOOL_INSPECTION_DUE ON EMS_TOOL_INSPECTION_HISTORY (TOOL_ID, NEXT_DUE_AT);
