-- EST 유틸리티/에너지 관리. FDC는 원시 계기 태그를 수집하고 EST는 계기 마스터,
-- 귀속 가능한 판독값과 기간 사용량/비용/탄소 집계를 소유한다.
CREATE TABLE EST_UTILITY_METER (
    METER_ID           NVARCHAR(50)    NOT NULL,
    METER_NAME         NVARCHAR(200)   NOT NULL,
    PLANT_ID           NVARCHAR(50)    NOT NULL,
    EQUIPMENT_ID       NVARCHAR(50)    NULL,
    UTILITY_TYPE       NVARCHAR(30)    NOT NULL,
    UNIT               NVARCHAR(30)    NOT NULL,
    FDC_PARAMETER_ID   NVARCHAR(50)    NULL,
    READING_MODE       NVARCHAR(20)    NOT NULL DEFAULT 'Cumulative',
    SCALE_FACTOR       DECIMAL(18,6)   NOT NULL DEFAULT 1,
    COST_PER_UNIT      DECIMAL(18,6)   NULL,
    CARBON_PER_UNIT    DECIMAL(18,6)   NULL,
    IS_ACTIVE          BIT             NOT NULL DEFAULT 1,
    CREATED_BY         NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT         DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY         NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT         DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_EST_UTILITY_METER PRIMARY KEY (METER_ID)
);
CREATE INDEX IX_EST_UTILITY_METER_EQUIPMENT ON EST_UTILITY_METER (EQUIPMENT_ID, UTILITY_TYPE);

CREATE TABLE EST_UTILITY_READING (
    READING_ID         NVARCHAR(50)    NOT NULL,
    METER_ID           NVARCHAR(50)    NOT NULL,
    EQUIPMENT_ID       NVARCHAR(50)    NULL,
    PROCESS_LOT_ID     NVARCHAR(50)    NULL,
    WORK_ORDER_ID      NVARCHAR(50)    NULL,
    RECIPE_ID          NVARCHAR(50)    NULL,
    RECIPE_VERSION     INT             NULL,
    RAW_VALUE          DECIMAL(18,6)   NOT NULL,
    NORMALIZED_VALUE   DECIMAL(18,6)   NOT NULL,
    UNIT               NVARCHAR(30)    NOT NULL,
    SOURCE             NVARCHAR(20)    NOT NULL,
    SOURCE_EVENT_ID    NVARCHAR(100)   NOT NULL,
    REQUEST_HASH       NVARCHAR(128)   NOT NULL,
    QUALITY            NVARCHAR(20)    NOT NULL DEFAULT 'Good',
    RECORDED_AT        DATETIME2       NOT NULL,
    RECORDED_BY        NVARCHAR(50)    NOT NULL,
    CREATED_AT         DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_EST_UTILITY_READING PRIMARY KEY (READING_ID),
    CONSTRAINT FK_EST_UTILITY_READING_METER FOREIGN KEY (METER_ID) REFERENCES EST_UTILITY_METER (METER_ID)
);
CREATE UNIQUE INDEX UX_EST_UTILITY_READING_SOURCE ON EST_UTILITY_READING (SOURCE, SOURCE_EVENT_ID);
CREATE INDEX IX_EST_UTILITY_READING_METER ON EST_UTILITY_READING (METER_ID, RECORDED_AT DESC);

CREATE TABLE EST_UTILITY_SUMMARY (
    SUMMARY_ID         NVARCHAR(50)    NOT NULL,
    METER_ID           NVARCHAR(50)    NOT NULL,
    PLANT_ID           NVARCHAR(50)    NOT NULL,
    EQUIPMENT_ID       NVARCHAR(50)    NULL,
    PERIOD_TYPE        NVARCHAR(20)    NOT NULL,
    PERIOD_START       DATETIME2       NOT NULL,
    PERIOD_END         DATETIME2       NOT NULL,
    START_READING      DECIMAL(18,6)   NULL,
    END_READING        DECIMAL(18,6)   NULL,
    CONSUMPTION        DECIMAL(18,6)   NOT NULL,
    UNIT               NVARCHAR(30)    NOT NULL,
    COST_AMOUNT        DECIMAL(18,6)   NULL,
    CARBON_AMOUNT      DECIMAL(18,6)   NULL,
    CREATED_BY         NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT         DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY         NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT         DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_EST_UTILITY_SUMMARY PRIMARY KEY (SUMMARY_ID),
    CONSTRAINT FK_EST_UTILITY_SUMMARY_METER FOREIGN KEY (METER_ID) REFERENCES EST_UTILITY_METER (METER_ID)
);
CREATE UNIQUE INDEX UX_EST_UTILITY_SUMMARY_PERIOD
    ON EST_UTILITY_SUMMARY (METER_ID, PERIOD_TYPE, PERIOD_START, PERIOD_END);
CREATE INDEX IX_EST_UTILITY_SUMMARY_EQUIPMENT
    ON EST_UTILITY_SUMMARY (EQUIPMENT_ID, PERIOD_START DESC);
