-- 공정 LOT 불량의 업무 처분 원장. POM_LOT_DEFECT_EXECUTION은 불량 관찰 증거이고,
-- 본 테이블은 그 수량을 Scrap/Rework/Return/UseAsIs/Hold 중 어떻게 결정했는지 별도로 보존한다.
CREATE UNIQUE INDEX UX_POM_LOT_DEFECT_EXECUTION_OWNER
    ON POM_LOT_DEFECT_EXECUTION (LOT_ID, EXECUTION_ID, DEFECT_CODE);

CREATE TABLE POM_LOT_DISPOSITION (
    DISPOSITION_ID    NVARCHAR(50)    NOT NULL,
    PLANT_ID          NVARCHAR(50)    NOT NULL,
    LOT_ID            NVARCHAR(50)    NOT NULL,
    WORK_ORDER_ID     NVARCHAR(50)    NULL,
    PROCESS_ID        NVARCHAR(50)    NULL,
    DEFECT_EXECUTION_ID NVARCHAR(50)  NULL,
    DEFECT_CODE       NVARCHAR(50)    NULL,
    DISPOSITION_TYPE  NVARCHAR(20)    NOT NULL,
    QUANTITY          DECIMAL(18,4)   NOT NULL,
    REASON_CODE       NVARCHAR(50)    NULL,
    REASON            NVARCHAR(500)   NOT NULL,
    DECIDED_BY        NVARCHAR(50)    NOT NULL,
    APPROVED_BY       NVARCHAR(50)    NULL,
    DECIDED_AT        DATETIME2       NOT NULL,
    SOURCE_EXECUTION_ID NVARCHAR(50)  NULL,
    IDEMPOTENCY_KEY   NVARCHAR(100)   NOT NULL,
    REQUEST_HASH      NVARCHAR(128)   NOT NULL,
    CLIENT_CHANNEL    NVARCHAR(20)    NOT NULL DEFAULT 'MES',
    DEVICE_ID         NVARCHAR(100)   NULL,
    CREATED_AT        DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_POM_LOT_DISPOSITION PRIMARY KEY (DISPOSITION_ID),
    CONSTRAINT FK_POM_LOT_DISPOSITION_LOT FOREIGN KEY (LOT_ID) REFERENCES POM_LOT (LOT_ID),
    CONSTRAINT FK_POM_LOT_DISPOSITION_WO FOREIGN KEY (WORK_ORDER_ID) REFERENCES POM_WORK_ORDER (WORK_ORDER_ID),
    CONSTRAINT FK_POM_LOT_DISPOSITION_DEFECT
        FOREIGN KEY (LOT_ID, DEFECT_EXECUTION_ID, DEFECT_CODE)
        REFERENCES POM_LOT_DEFECT_EXECUTION (LOT_ID, EXECUTION_ID, DEFECT_CODE),
    CONSTRAINT CK_POM_LOT_DISPOSITION_DEFECT_PAIR CHECK (
        DEFECT_EXECUTION_ID IS NULL OR DEFECT_CODE IS NOT NULL),
    CONSTRAINT CK_POM_LOT_DISPOSITION_QTY CHECK (QUANTITY > 0),
    CONSTRAINT CK_POM_LOT_DISPOSITION_TYPE CHECK (
        DISPOSITION_TYPE IN ('Scrap', 'Rework', 'Return', 'UseAsIs', 'Hold')),
    CONSTRAINT CK_POM_LOT_DISPOSITION_CHANNEL CHECK (
        CLIENT_CHANNEL IN ('MES', 'MOBILE', 'POP'))
);
CREATE UNIQUE INDEX UX_POM_LOT_DISPOSITION_KEY ON POM_LOT_DISPOSITION (IDEMPOTENCY_KEY);
CREATE INDEX IX_POM_LOT_DISPOSITION_LOT ON POM_LOT_DISPOSITION (LOT_ID, DECIDED_AT DESC);
CREATE INDEX IX_POM_LOT_DISPOSITION_TYPE ON POM_LOT_DISPOSITION (PLANT_ID, DISPOSITION_TYPE, DECIDED_AT DESC);
