-- 설비에 실제 적용된 레시피/파라미터 증거. RMS_RECIPE/RMS_RECIPE_PARAM은 편집 가능한 마스터이고,
-- 실행 시점에는 버전과 파라미터 스냅샷을 고정해 LOT/설비 이력과 재현성을 보장한다.
CREATE TABLE RMS_RECIPE_EQUIPMENT_ASSIGNMENT (
    ASSIGNMENT_ID     NVARCHAR(50)    NOT NULL,
    EQUIPMENT_ID      NVARCHAR(50)    NULL,
    EQUIPMENT_CLASS_ID NVARCHAR(50)   NULL,
    RECIPE_ID         NVARCHAR(50)    NOT NULL,
    RECIPE_VERSION    INT             NOT NULL,
    EFFECTIVE_FROM    DATETIME2       NOT NULL,
    EFFECTIVE_TO      DATETIME2       NULL,
    ASSIGNED_BY       NVARCHAR(50)    NOT NULL,
    IS_ACTIVE         BIT             NOT NULL DEFAULT 1,
    CREATED_BY        NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT        DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY        NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT        DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_RMS_RECIPE_EQUIPMENT_ASSIGNMENT PRIMARY KEY (ASSIGNMENT_ID),
    CONSTRAINT CK_RMS_RECIPE_ASSIGNMENT_TARGET CHECK (
        (EQUIPMENT_ID IS NOT NULL AND EQUIPMENT_CLASS_ID IS NULL)
        OR (EQUIPMENT_ID IS NULL AND EQUIPMENT_CLASS_ID IS NOT NULL))
);
CREATE UNIQUE INDEX UX_RMS_RECIPE_ACTIVE_EQUIPMENT_ASSIGNMENT
    ON RMS_RECIPE_EQUIPMENT_ASSIGNMENT (EQUIPMENT_ID)
    WHERE IS_ACTIVE = 1 AND EQUIPMENT_ID IS NOT NULL;
CREATE UNIQUE INDEX UX_RMS_RECIPE_ACTIVE_CLASS_ASSIGNMENT
    ON RMS_RECIPE_EQUIPMENT_ASSIGNMENT (EQUIPMENT_CLASS_ID)
    WHERE IS_ACTIVE = 1 AND EQUIPMENT_CLASS_ID IS NOT NULL;

CREATE TABLE RMS_RECIPE_EXECUTION_SNAPSHOT (
    EXECUTION_ID       NVARCHAR(50)    NOT NULL,
    IDEMPOTENCY_KEY    NVARCHAR(100)   NOT NULL,
    REQUEST_HASH       NVARCHAR(64)    NOT NULL,
    PLANT_ID           NVARCHAR(50)    NOT NULL,
    EQUIPMENT_ID       NVARCHAR(50)    NOT NULL,
    PROCESS_LOT_ID     NVARCHAR(50)    NULL,
    WORK_ORDER_ID      NVARCHAR(50)    NULL,
    PROCESS_ID         NVARCHAR(50)    NULL,
    RECIPE_ID          NVARCHAR(50)    NOT NULL,
    RECIPE_VERSION     INT             NOT NULL,
    RECIPE_SNAPSHOT_JSON NVARCHAR(MAX) NOT NULL,
    PARAMETER_SNAPSHOT_JSON NVARCHAR(MAX) NOT NULL,
    CONDITION_SNAPSHOT_JSON NVARCHAR(MAX) NULL,
    APPLIED_BY         NVARCHAR(50)    NOT NULL,
    APPLIED_AT         DATETIME2       NOT NULL,
    SOURCE             NVARCHAR(20)    NOT NULL,
    TRACE_ID           NVARCHAR(100)   NULL,
    CREATED_AT         DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_RMS_RECIPE_EXECUTION PRIMARY KEY (EXECUTION_ID)
);
CREATE UNIQUE INDEX UX_RMS_RECIPE_EXECUTION_KEY ON RMS_RECIPE_EXECUTION_SNAPSHOT (IDEMPOTENCY_KEY);
CREATE INDEX IX_RMS_RECIPE_EXECUTION_EQUIPMENT
    ON RMS_RECIPE_EXECUTION_SNAPSHOT (EQUIPMENT_ID, APPLIED_AT DESC);
CREATE INDEX IX_RMS_RECIPE_EXECUTION_LOT
    ON RMS_RECIPE_EXECUTION_SNAPSHOT (PROCESS_LOT_ID, APPLIED_AT DESC);
