-- Persisted FDC TRACE -> IVT material-consumption projection through the Common source contract.
-- The IVT inbox and projection state make restart/retry behaviour durable and idempotent without
-- an IVT migration owning or referencing physical tables owned by the FDC module.

CREATE TABLE IVT_TRACE_CONSUMPTION_BINDING (
    BINDING_ID          NVARCHAR(50)    NOT NULL,
    PLANT_ID            NVARCHAR(50)    NOT NULL,
    EQUIPMENT_ID        NVARCHAR(50)    NOT NULL,
    PARAMETER_ID        NVARCHAR(50)    NOT NULL,
    FEED_POINT_ID       NVARCHAR(50)    NOT NULL,
    CALCULATION_MODE    NVARCHAR(30)    NOT NULL,
    SCALE_FACTOR        DECIMAL(18,6)   NOT NULL DEFAULT 1,
    PULSE_QUANTITY      DECIMAL(18,6)   NULL,
    OUTPUT_UNIT         NVARCHAR(30)    NOT NULL,
    EFFECTIVE_FROM      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    EFFECTIVE_TO        DATETIME2       NULL,
    IS_ACTIVE           BIT             NOT NULL DEFAULT 1,
    CREATED_BY          NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY          NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_IVT_TRACE_CONSUMPTION_BINDING PRIMARY KEY (BINDING_ID),
    CONSTRAINT CK_IVT_TRACE_BINDING_MODE CHECK (
        CALCULATION_MODE IN ('Direct', 'Pulse', 'CounterDelta', 'RateIntegrate')),
    CONSTRAINT CK_IVT_TRACE_BINDING_SCALE CHECK (SCALE_FACTOR > 0),
    CONSTRAINT CK_IVT_TRACE_BINDING_PULSE CHECK (
        (CALCULATION_MODE <> 'Pulse' AND PULSE_QUANTITY IS NULL)
        OR (CALCULATION_MODE = 'Pulse' AND PULSE_QUANTITY > 0)),
    CONSTRAINT CK_IVT_TRACE_BINDING_WINDOW CHECK (
        EFFECTIVE_TO IS NULL OR EFFECTIVE_TO > EFFECTIVE_FROM)
);

CREATE INDEX IX_IVT_TRACE_BINDING_SOURCE
    ON IVT_TRACE_CONSUMPTION_BINDING
       (EQUIPMENT_ID, PARAMETER_ID, IS_ACTIVE, EFFECTIVE_FROM);

-- 같은 현재 TRACE 원천을 둘 이상의 바인딩이 소비하면 각 BINDING_ID별 멱등키가 달라져
-- 동일 샘플이 중복 차감된다. 기간이 끝난 이력은 보존하고 현재 활성 바인딩만 단일화한다.
CREATE UNIQUE INDEX UX_IVT_TRACE_BINDING_ACTIVE_SOURCE
    ON IVT_TRACE_CONSUMPTION_BINDING
       (PLANT_ID, EQUIPMENT_ID, PARAMETER_ID, FEED_POINT_ID)
    WHERE IS_ACTIVE = 1;

-- The feed session is the time-bounded evidence that identifies which material LOT was physically
-- mounted at the equipment feed point when a TRACE sample was collected. Optional production and
-- recipe context is snapshotted here rather than guessed from mutable current-state tables.
CREATE TABLE IVT_MATERIAL_FEED_SESSION (
    FEED_SESSION_ID     NVARCHAR(50)    NOT NULL,
    PLANT_ID            NVARCHAR(50)    NOT NULL,
    EQUIPMENT_ID        NVARCHAR(50)    NOT NULL,
    FEED_POINT_ID       NVARCHAR(50)    NOT NULL,
    MATERIAL_LOT_ID     NVARCHAR(50)    NOT NULL,
    MATERIAL_ID         NVARCHAR(50)    NOT NULL,
    PROCESS_LOT_ID      NVARCHAR(50)    NULL,
    WORK_ORDER_ID       NVARCHAR(50)    NULL,
    PROCESS_ID          NVARCHAR(50)    NULL,
    RECIPE_ID           NVARCHAR(50)    NULL,
    RECIPE_VERSION      INT             NULL,
    MOUNTED_AT          DATETIME2       NOT NULL,
    MOUNTED_BY          NVARCHAR(50)    NOT NULL,
    UNMOUNTED_AT        DATETIME2       NULL,
    UNMOUNTED_BY        NVARCHAR(50)    NULL,
    STATUS              NVARCHAR(20)    NOT NULL DEFAULT 'Mounted',
    CREATED_BY          NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY          NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_IVT_MATERIAL_FEED_SESSION PRIMARY KEY (FEED_SESSION_ID),
    CONSTRAINT FK_IVT_FEED_SESSION_MATERIAL_LOT FOREIGN KEY (MATERIAL_LOT_ID)
        REFERENCES IVT_MATERIAL_LOT (LOT_ID),
    CONSTRAINT CK_IVT_FEED_SESSION_WINDOW CHECK (
        UNMOUNTED_AT IS NULL OR UNMOUNTED_AT > MOUNTED_AT),
    CONSTRAINT CK_IVT_FEED_SESSION_STATUS CHECK (
        STATUS IN ('Mounted', 'Unmounted', 'Cancelled'))
);

CREATE INDEX IX_IVT_FEED_SESSION_ASOF
    ON IVT_MATERIAL_FEED_SESSION
       (PLANT_ID, EQUIPMENT_ID, FEED_POINT_ID, MOUNTED_AT, UNMOUNTED_AT);

CREATE UNIQUE INDEX UX_IVT_FEED_SESSION_ACTIVE
    ON IVT_MATERIAL_FEED_SESSION (PLANT_ID, EQUIPMENT_ID, FEED_POINT_ID)
    WHERE STATUS = 'Mounted' AND UNMOUNTED_AT IS NULL;

-- Mutable calculator checkpoint. Accounting evidence remains append-only in
-- IVT_MATERIAL_CONSUMPTION_HISTORY; only this projection cursor is overwritten.
CREATE TABLE IVT_TRACE_PROJECTION_STATE (
    BINDING_ID          NVARCHAR(50)    NOT NULL,
    LAST_COLLECT_ID     NVARCHAR(50)    NOT NULL,
    LAST_VALUE          DECIMAL(18,6)   NOT NULL,
    LAST_COLLECTED_AT   DATETIME2       NOT NULL,
    CREATED_BY          NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY          NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_IVT_TRACE_PROJECTION_STATE PRIMARY KEY (BINDING_ID),
    CONSTRAINT FK_IVT_TRACE_STATE_BINDING FOREIGN KEY (BINDING_ID)
        REFERENCES IVT_TRACE_CONSUMPTION_BINDING (BINDING_ID)
);

-- A binding is stateful (pulse edge/counter/rate integration), so only one host may project its
-- ordered inbox rows at a time. Leases survive process boundaries and expire after an unclean stop.
CREATE TABLE IVT_TRACE_PROJECTION_LEASE (
    BINDING_ID          NVARCHAR(50)    NOT NULL,
    OWNER_ID            NVARCHAR(100)   NOT NULL,
    ACQUIRED_AT         DATETIME2       NOT NULL,
    LEASE_UNTIL         DATETIME2       NOT NULL,
    CREATED_BY          NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY          NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_IVT_TRACE_PROJECTION_LEASE PRIMARY KEY (BINDING_ID),
    CONSTRAINT FK_IVT_TRACE_LEASE_BINDING FOREIGN KEY (BINDING_ID)
        REFERENCES IVT_TRACE_CONSUMPTION_BINDING (BINDING_ID),
    CONSTRAINT CK_IVT_TRACE_LEASE_WINDOW CHECK (LEASE_UNTIL > ACQUIRED_AT)
);
CREATE INDEX IX_IVT_TRACE_PROJECTION_LEASE_EXPIRY
    ON IVT_TRACE_PROJECTION_LEASE (LEASE_UNTIL);

-- Durable inbox snapshots both the FDC sample and the binding calculation configuration. Binding
-- edits after collection therefore cannot silently change historical consumption. Error rows stay
-- retryable and block later rows for the same binding in the worker until the cause is corrected.
CREATE TABLE IVT_TRACE_PROJECTION_INBOX (
    BINDING_ID          NVARCHAR(50)    NOT NULL,
    COLLECT_ID          NVARCHAR(50)    NOT NULL,
    PLANT_ID            NVARCHAR(50)    NOT NULL,
    EQUIPMENT_ID        NVARCHAR(50)    NOT NULL,
    PARAMETER_ID        NVARCHAR(50)    NOT NULL,
    FEED_POINT_ID       NVARCHAR(50)    NOT NULL,
    CALCULATION_MODE    NVARCHAR(30)    NOT NULL,
    SCALE_FACTOR        DECIMAL(18,6)   NOT NULL,
    PULSE_QUANTITY      DECIMAL(18,6)   NULL,
    OUTPUT_UNIT         NVARCHAR(30)    NOT NULL,
    RAW_VALUE           DECIMAL(18,6)   NOT NULL,
    QUALITY             NVARCHAR(20)    NOT NULL,
    COLLECTED_AT        DATETIME2       NOT NULL,
    STATUS              NVARCHAR(20)    NOT NULL DEFAULT 'Pending',
    ATTEMPT_COUNT       INT             NOT NULL DEFAULT 0,
    LAST_ERROR          NVARCHAR(1000)  NULL,
    CONSUMPTION_ID      NVARCHAR(50)    NULL,
    PROCESSED_AT        DATETIME2       NULL,
    CREATED_BY          NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY          NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_IVT_TRACE_PROJECTION_INBOX PRIMARY KEY (BINDING_ID, COLLECT_ID),
    CONSTRAINT FK_IVT_TRACE_INBOX_BINDING FOREIGN KEY (BINDING_ID)
        REFERENCES IVT_TRACE_CONSUMPTION_BINDING (BINDING_ID),
    -- The source sample is snapshotted rather than cross-linked so the FDC retention lifecycle stays independent.
    CONSTRAINT FK_IVT_TRACE_INBOX_CONSUMPTION FOREIGN KEY (CONSUMPTION_ID)
        REFERENCES IVT_MATERIAL_CONSUMPTION_HISTORY (CONSUMPTION_ID),
    CONSTRAINT CK_IVT_TRACE_INBOX_STATUS CHECK (
        STATUS IN ('Pending', 'Applied', 'Ignored', 'Error')),
    CONSTRAINT CK_IVT_TRACE_INBOX_ATTEMPTS CHECK (ATTEMPT_COUNT >= 0)
);

CREATE INDEX IX_IVT_TRACE_INBOX_WORK
    ON IVT_TRACE_PROJECTION_INBOX (STATUS, COLLECTED_AT, BINDING_ID);
