-- EMS maintenance execution integrity.
-- V008 PLAN_ID points at POM_PRODUCTION_PLAN. Keep the legacy column for deployed data,
-- but move every new EMS work-order relation to the correctly owned MAINTENANCE_PLAN_ID.
ALTER TABLE EMS_WORK_ORDER DROP CONSTRAINT FK_EMS_WO_PLAN;

ALTER TABLE EMS_WORK_ORDER ADD MAINTENANCE_PLAN_ID NVARCHAR(50) NULL;

-- PLAN_ID는 V008에서 POM_PRODUCTION_PLAN을 참조한다. 동일 문자열의 보전 계획이 존재하더라도
-- 의미가 다른 식별자를 자동 이관하면 안 되므로 legacy 행은 추측해서 backfill하지 않는다.
-- 운영 이관 도구가 원본 의미를 확인한 행만 MAINTENANCE_PLAN_ID에 명시적으로 기록한다.

ALTER TABLE EMS_WORK_ORDER ADD CONSTRAINT FK_EMS_WO_MAINTENANCE_PLAN
    FOREIGN KEY (MAINTENANCE_PLAN_ID) REFERENCES EMS_MAINTENANCE_PLAN (PLAN_ID);

CREATE INDEX IX_EMS_WO_MAINTENANCE_PLAN
    ON EMS_WORK_ORDER (MAINTENANCE_PLAN_ID, STATUS);

-- MES login identity and maintenance worker master are separate identities. This one-to-one
-- mapping preserves the worker master while every command is audited with the authenticated user.
CREATE TABLE MDM_WORKER_USER_MAP (
    WORKER_USER_MAP_ID NVARCHAR(50) NOT NULL,
    WORKER_ID          NVARCHAR(50) NOT NULL,
    USER_ID            NVARCHAR(50) NOT NULL,
    IS_ACTIVE          BIT          NOT NULL DEFAULT 1,
    EFFECTIVE_FROM     DATETIME2     NOT NULL,
    EFFECTIVE_TO       DATETIME2     NULL,
    CREATED_BY         NVARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT         DATETIME2     NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY         NVARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT         DATETIME2     NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_MDM_WORKER_USER_MAP PRIMARY KEY (WORKER_USER_MAP_ID),
    CONSTRAINT FK_MDM_WORKER_USER_MAP_WORKER FOREIGN KEY (WORKER_ID)
        REFERENCES MDM_WORKER (WORKER_ID),
    CONSTRAINT FK_MDM_WORKER_USER_MAP_USER FOREIGN KEY (USER_ID)
        REFERENCES SYS_USER (USER_ID),
    CONSTRAINT CK_MDM_WORKER_USER_MAP_EFFECTIVE CHECK (
        EFFECTIVE_TO IS NULL OR EFFECTIVE_TO > EFFECTIVE_FROM)
);

CREATE INDEX IX_MDM_WORKER_USER_MAP_ACTIVE
    ON MDM_WORKER_USER_MAP (IS_ACTIVE, USER_ID);

-- 만료된 매핑은 감사 이력으로 남기고 현재 유효한 사용자/작업자만 1:1로 제한한다.
CREATE UNIQUE INDEX UX_MDM_WORKER_USER_MAP_ACTIVE_WORKER
    ON MDM_WORKER_USER_MAP (WORKER_ID)
    WHERE IS_ACTIVE = 1 AND EFFECTIVE_TO IS NULL;

CREATE UNIQUE INDEX UX_MDM_WORKER_USER_MAP_ACTIVE_USER
    ON MDM_WORKER_USER_MAP (USER_ID)
    WHERE IS_ACTIVE = 1 AND EFFECTIVE_TO IS NULL;

-- Recurring maintenance definition. EMS_MAINTENANCE_PLAN remains the business plan;
-- schedule state is separated so due evaluation and next-due calculation do not mutate the plan.
CREATE TABLE EMS_MAINTENANCE_SCHEDULE (
    SCHEDULE_ID         NVARCHAR(50)  NOT NULL,
    MAINTENANCE_PLAN_ID NVARCHAR(50)  NOT NULL,
    TRIGGER_TYPE        NVARCHAR(20)  NOT NULL DEFAULT 'Calendar',
    INTERVAL_VALUE      DECIMAL(18,4) NULL,
    INTERVAL_UNIT       NVARCHAR(20)  NULL,
    TIME_ZONE_ID        NVARCHAR(100) NOT NULL DEFAULT 'Asia/Seoul',
    LAST_DUE_AT         DATETIME2     NULL,
    NEXT_DUE_AT         DATETIME2     NULL,
    METER_PARAMETER_ID  NVARCHAR(50)  NULL,
    METER_THRESHOLD     DECIMAL(18,4) NULL,
    METER_BASELINE_VALUE DECIMAL(18,4) NULL,
    NEXT_METER_DUE_VALUE DECIMAL(18,4) NULL,
    CONDITION_RULE_ID   NVARCHAR(100) NULL,
    AUTO_CREATE_WO      BIT           NOT NULL DEFAULT 0,
    IS_ACTIVE           BIT           NOT NULL DEFAULT 1,
    VERSION_NO          INT           NOT NULL DEFAULT 1,
    CREATED_BY          NVARCHAR(50)  NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT          DATETIME2     NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY          NVARCHAR(50)  NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT          DATETIME2     NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_EMS_MAINTENANCE_SCHEDULE PRIMARY KEY (SCHEDULE_ID),
    CONSTRAINT UQ_EMS_MAINTENANCE_SCHEDULE_PLAN UNIQUE (MAINTENANCE_PLAN_ID),
    CONSTRAINT FK_EMS_MAINTENANCE_SCHEDULE_PLAN FOREIGN KEY (MAINTENANCE_PLAN_ID)
        REFERENCES EMS_MAINTENANCE_PLAN (PLAN_ID),
    CONSTRAINT CK_EMS_MAINTENANCE_SCHEDULE_TRIGGER CHECK (
        TRIGGER_TYPE IN ('Calendar', 'Meter', 'Condition')),
    CONSTRAINT CK_EMS_MAINTENANCE_SCHEDULE_INTERVAL CHECK (
        (TRIGGER_TYPE = 'Calendar' AND INTERVAL_VALUE IS NOT NULL AND INTERVAL_VALUE > 0
         AND INTERVAL_UNIT IN ('Hour', 'Day', 'Week', 'Month', 'Year')
         AND NEXT_DUE_AT IS NOT NULL
         AND METER_PARAMETER_ID IS NULL AND METER_THRESHOLD IS NULL
         AND METER_BASELINE_VALUE IS NULL AND NEXT_METER_DUE_VALUE IS NULL
         AND CONDITION_RULE_ID IS NULL)
        OR (TRIGGER_TYPE = 'Meter' AND METER_PARAMETER_ID IS NOT NULL
            AND METER_THRESHOLD IS NOT NULL AND METER_THRESHOLD > 0
            AND METER_BASELINE_VALUE IS NOT NULL AND METER_BASELINE_VALUE >= 0
            AND NEXT_METER_DUE_VALUE IS NOT NULL
            AND NEXT_METER_DUE_VALUE > METER_BASELINE_VALUE
            AND INTERVAL_VALUE IS NULL AND INTERVAL_UNIT IS NULL
            AND NEXT_DUE_AT IS NULL AND CONDITION_RULE_ID IS NULL)
        OR (TRIGGER_TYPE = 'Condition' AND CONDITION_RULE_ID IS NOT NULL
            AND INTERVAL_VALUE IS NULL AND INTERVAL_UNIT IS NULL
            AND NEXT_DUE_AT IS NULL AND METER_PARAMETER_ID IS NULL
            AND METER_THRESHOLD IS NULL AND METER_BASELINE_VALUE IS NULL
            AND NEXT_METER_DUE_VALUE IS NULL)),
    CONSTRAINT CK_EMS_MAINTENANCE_SCHEDULE_VERSION CHECK (VERSION_NO > 0)
);

CREATE INDEX IX_EMS_MAINTENANCE_SCHEDULE_DUE
    ON EMS_MAINTENANCE_SCHEDULE (IS_ACTIVE, NEXT_DUE_AT);

-- Manual-mode due acknowledgement. This is append-only evidence; the repository advances the
-- schedule version and inserts exactly one history row in the same transaction. REQUEST_HASH plus
-- the unique idempotency key makes operator retries safe without hiding a changed request.
CREATE TABLE EMS_MAINTENANCE_SCHEDULE_ACK_HISTORY (
    ACK_ID                 NVARCHAR(50)   NOT NULL,
    SCHEDULE_ID            NVARCHAR(50)   NOT NULL,
    MAINTENANCE_PLAN_ID    NVARCHAR(50)   NOT NULL,
    TRIGGER_TYPE           NVARCHAR(20)   NOT NULL,
    DUE_AT                 DATETIME2      NULL,
    NEXT_DUE_AT            DATETIME2      NULL,
    METER_DUE_VALUE        DECIMAL(18,4) NULL,
    OBSERVED_METER_VALUE   DECIMAL(18,4) NULL,
    NEXT_METER_DUE_VALUE   DECIMAL(18,4) NULL,
    CONDITION_RULE_ID      NVARCHAR(100)  NULL,
    CONDITION_MET          BIT            NULL,
    ACKNOWLEDGED_AT        DATETIME2      NOT NULL,
    ACKNOWLEDGED_BY        NVARCHAR(50)   NOT NULL,
    REMARK                 NVARCHAR(500)  NULL,
    IDEMPOTENCY_KEY        NVARCHAR(150)  NOT NULL,
    REQUEST_HASH           NVARCHAR(64)   NOT NULL,
    CLIENT_CHANNEL         NVARCHAR(20)   NOT NULL,
    DEVICE_ID              NVARCHAR(100)  NULL,
    CORRELATION_ID         NVARCHAR(100)  NULL,
    FROM_VERSION           INT            NOT NULL,
    TO_VERSION             INT            NOT NULL,
    CREATED_BY             NVARCHAR(50)   NOT NULL,
    CREATED_AT             DATETIME2      NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_EMS_MAINT_SCHEDULE_ACK PRIMARY KEY (ACK_ID),
    CONSTRAINT UQ_EMS_MAINT_SCHEDULE_ACK_IDEMPOTENCY UNIQUE (IDEMPOTENCY_KEY),
    CONSTRAINT FK_EMS_MAINT_SCHEDULE_ACK_SCHEDULE FOREIGN KEY (SCHEDULE_ID)
        REFERENCES EMS_MAINTENANCE_SCHEDULE (SCHEDULE_ID),
    CONSTRAINT CK_EMS_MAINT_SCHEDULE_ACK_TRIGGER CHECK (
        (TRIGGER_TYPE = 'Calendar' AND DUE_AT IS NOT NULL
         AND METER_DUE_VALUE IS NULL AND OBSERVED_METER_VALUE IS NULL
         AND NEXT_METER_DUE_VALUE IS NULL AND CONDITION_RULE_ID IS NULL
         AND CONDITION_MET IS NULL)
        OR (TRIGGER_TYPE = 'Meter' AND DUE_AT IS NULL
            AND METER_DUE_VALUE IS NOT NULL AND OBSERVED_METER_VALUE IS NOT NULL
            AND OBSERVED_METER_VALUE >= METER_DUE_VALUE
            AND NEXT_METER_DUE_VALUE IS NOT NULL AND CONDITION_RULE_ID IS NULL
            AND CONDITION_MET IS NULL)
        OR (TRIGGER_TYPE = 'Condition' AND DUE_AT IS NULL
            AND METER_DUE_VALUE IS NULL AND OBSERVED_METER_VALUE IS NULL
            AND NEXT_METER_DUE_VALUE IS NULL AND CONDITION_RULE_ID IS NOT NULL
            AND CONDITION_MET IS NOT NULL AND CONDITION_MET = 1)),
    CONSTRAINT CK_EMS_MAINT_SCHEDULE_ACK_CHANNEL CHECK (
        CLIENT_CHANNEL IN ('MES', 'MOBILE', 'POP')),
    CONSTRAINT CK_EMS_MAINT_SCHEDULE_ACK_VERSION CHECK (
        FROM_VERSION > 0 AND TO_VERSION = FROM_VERSION + 1)
);

CREATE INDEX IX_EMS_MAINT_SCHEDULE_ACK_SCHEDULE
    ON EMS_MAINTENANCE_SCHEDULE_ACK_HISTORY (SCHEDULE_ID, ACKNOWLEDGED_AT);

CREATE INDEX IX_EMS_MAINT_SCHEDULE_ACK_CORRELATION
    ON EMS_MAINTENANCE_SCHEDULE_ACK_HISTORY (CORRELATION_ID, ACKNOWLEDGED_AT)
    WHERE CORRELATION_ID IS NOT NULL;

-- Immutable checklist result captured during a work-order execution.
CREATE TABLE EMS_WORK_ORDER_CHECK_RESULT (
    CHECK_RESULT_ID NVARCHAR(50)    NOT NULL,
    IDEMPOTENCY_KEY NVARCHAR(150)   NOT NULL,
    REQUEST_HASH    NVARCHAR(64)    NOT NULL,
    WO_ID           NVARCHAR(50)    NOT NULL,
    ITEM_ID         NVARCHAR(50)    NULL,
    ITEM_SEQUENCE   INT             NOT NULL,
    CHECK_NAME      NVARCHAR(200)   NOT NULL,
    MEASURED_VALUE  DECIMAL(18,6)  NULL,
    ATTRIBUTE_VALUE NVARCHAR(100)   NULL,
    UNIT            NVARCHAR(50)    NULL,
    IS_PASS         BIT             NULL,
    FINDING         NVARCHAR(1000)  NULL,
    RECORDED_BY     NVARCHAR(50)    NOT NULL,
    RECORDED_AT     DATETIME2       NOT NULL,
    CLIENT_CHANNEL  NVARCHAR(20)    NOT NULL,
    DEVICE_ID       NVARCHAR(100)   NULL,
    CORRELATION_ID  NVARCHAR(100)   NULL,
    CREATED_BY      NVARCHAR(50)    NOT NULL,
    CREATED_AT      DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_EMS_WORK_ORDER_CHECK_RESULT PRIMARY KEY (CHECK_RESULT_ID),
    CONSTRAINT UQ_EMS_WORK_ORDER_CHECK_IDEMPOTENCY UNIQUE (IDEMPOTENCY_KEY),
    CONSTRAINT UQ_EMS_WORK_ORDER_CHECK_SEQUENCE UNIQUE (WO_ID, ITEM_SEQUENCE),
    CONSTRAINT FK_EMS_WORK_ORDER_CHECK_WO FOREIGN KEY (WO_ID)
        REFERENCES EMS_WORK_ORDER (WO_ID),
    CONSTRAINT FK_EMS_WORK_ORDER_CHECK_ITEM FOREIGN KEY (ITEM_ID)
        REFERENCES EMS_MAINT_ITEM (ITEM_ID),
    CONSTRAINT FK_EMS_WORK_ORDER_CHECK_USER FOREIGN KEY (RECORDED_BY)
        REFERENCES SYS_USER (USER_ID),
    CONSTRAINT CK_EMS_WORK_ORDER_CHECK_SEQUENCE CHECK (ITEM_SEQUENCE > 0),
    CONSTRAINT CK_EMS_WORK_ORDER_CHECK_EVIDENCE CHECK (
        MEASURED_VALUE IS NOT NULL OR ATTRIBUTE_VALUE IS NOT NULL
        OR IS_PASS IS NOT NULL OR FINDING IS NOT NULL),
    CONSTRAINT CK_EMS_WORK_ORDER_CHECK_CHANNEL CHECK (
        CLIENT_CHANNEL IN ('MES', 'MOBILE', 'POP'))
);

CREATE INDEX IX_EMS_WORK_ORDER_CHECK_RESULT_WO
    ON EMS_WORK_ORDER_CHECK_RESULT (WO_ID, ITEM_SEQUENCE);

-- Actual maintenance labor. USER_ID is the authenticated account; WORKER_ID is the optional
-- maintenance-master identity resolved through MDM_WORKER_USER_MAP.
CREATE TABLE EMS_WORK_ORDER_LABOR (
    LABOR_ID             NVARCHAR(50)   NOT NULL,
    START_IDEMPOTENCY_KEY NVARCHAR(150) NOT NULL,
    START_REQUEST_HASH   NVARCHAR(64)   NOT NULL,
    WO_ID                NVARCHAR(50)   NOT NULL,
    USER_ID              NVARCHAR(50)   NOT NULL,
    WORKER_ID            NVARCHAR(50)   NULL,
    LABOR_TYPE           NVARCHAR(30)   NOT NULL DEFAULT 'Work',
    STARTED_AT           DATETIME2      NOT NULL,
    ENDED_AT             DATETIME2      NULL,
    ENDED_BY             NVARCHAR(50)   NULL,
    LABOR_HOURS          DECIMAL(18,4)  NULL,
    REMARK               NVARCHAR(500)  NULL,
    CORRELATION_ID       NVARCHAR(100)  NULL,
    START_CLIENT_CHANNEL NVARCHAR(20)   NOT NULL,
    START_DEVICE_ID      NVARCHAR(100)  NULL,
    END_IDEMPOTENCY_KEY  NVARCHAR(150)  NULL,
    END_REQUEST_HASH     NVARCHAR(64)   NULL,
    END_CLIENT_CHANNEL   NVARCHAR(20)   NULL,
    END_DEVICE_ID        NVARCHAR(100)  NULL,
    VERSION_NO           INT            NOT NULL DEFAULT 1,
    CREATED_BY           NVARCHAR(50)   NOT NULL,
    CREATED_AT           DATETIME2      NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY           NVARCHAR(50)   NOT NULL,
    UPDATED_AT           DATETIME2      NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_EMS_WORK_ORDER_LABOR PRIMARY KEY (LABOR_ID),
    CONSTRAINT UQ_EMS_WORK_ORDER_LABOR_START_IDEMPOTENCY UNIQUE (START_IDEMPOTENCY_KEY),
    CONSTRAINT FK_EMS_WORK_ORDER_LABOR_WO FOREIGN KEY (WO_ID)
        REFERENCES EMS_WORK_ORDER (WO_ID),
    CONSTRAINT FK_EMS_WORK_ORDER_LABOR_USER FOREIGN KEY (USER_ID)
        REFERENCES SYS_USER (USER_ID),
    CONSTRAINT FK_EMS_WORK_ORDER_LABOR_WORKER FOREIGN KEY (WORKER_ID)
        REFERENCES MDM_WORKER (WORKER_ID),
    CONSTRAINT FK_EMS_WORK_ORDER_LABOR_ENDED_BY FOREIGN KEY (ENDED_BY)
        REFERENCES SYS_USER (USER_ID),
    CONSTRAINT CK_EMS_WORK_ORDER_LABOR_TYPE CHECK (
        LABOR_TYPE IN ('Work', 'Inspection', 'Travel', 'Standby')),
    CONSTRAINT CK_EMS_WORK_ORDER_LABOR_START_CHANNEL CHECK (
        START_CLIENT_CHANNEL IN ('MES', 'MOBILE', 'POP')),
    CONSTRAINT CK_EMS_WORK_ORDER_LABOR_END_CHANNEL CHECK (
        END_CLIENT_CHANNEL IS NULL OR END_CLIENT_CHANNEL IN ('MES', 'MOBILE', 'POP')),
    CONSTRAINT CK_EMS_WORK_ORDER_LABOR_VERSION CHECK (VERSION_NO > 0),
    CONSTRAINT CK_EMS_WORK_ORDER_LABOR_TIME CHECK (
        (ENDED_AT IS NULL AND ENDED_BY IS NULL AND LABOR_HOURS IS NULL
         AND END_IDEMPOTENCY_KEY IS NULL AND END_REQUEST_HASH IS NULL
         AND END_CLIENT_CHANNEL IS NULL AND END_DEVICE_ID IS NULL)
        OR (ENDED_AT >= STARTED_AT AND ENDED_BY IS NOT NULL
            AND LABOR_HOURS IS NOT NULL AND LABOR_HOURS >= 0
            AND END_IDEMPOTENCY_KEY IS NOT NULL AND END_REQUEST_HASH IS NOT NULL
            AND END_CLIENT_CHANNEL IS NOT NULL))
);

CREATE INDEX IX_EMS_WORK_ORDER_LABOR_WO
    ON EMS_WORK_ORDER_LABOR (WO_ID, STARTED_AT);

CREATE UNIQUE INDEX UX_EMS_WORK_ORDER_LABOR_OPEN_USER
    ON EMS_WORK_ORDER_LABOR (WO_ID, USER_ID)
    WHERE ENDED_AT IS NULL;

CREATE UNIQUE INDEX UX_EMS_WORK_ORDER_LABOR_END_IDEMPOTENCY
    ON EMS_WORK_ORDER_LABOR (END_IDEMPOTENCY_KEY)
    WHERE END_IDEMPOTENCY_KEY IS NOT NULL;

-- V110 introduced the append-only maintenance action table. Add retry protection and an explicit
-- transition/correlation identity without rewriting existing history rows.
ALTER TABLE EMS_MAINTENANCE_ACTION_HISTORY ADD
    IDEMPOTENCY_KEY NVARCHAR(150) NULL,
    FROM_STATUS     NVARCHAR(20)  NULL,
    TO_STATUS       NVARCHAR(20)  NULL,
    CORRELATION_ID  NVARCHAR(100) NULL;

CREATE UNIQUE INDEX UX_EMS_MAINTENANCE_ACTION_IDEMPOTENCY
    ON EMS_MAINTENANCE_ACTION_HISTORY (IDEMPOTENCY_KEY)
    WHERE IDEMPOTENCY_KEY IS NOT NULL;

CREATE INDEX IX_EMS_MAINTENANCE_ACTION_CORRELATION
    ON EMS_MAINTENANCE_ACTION_HISTORY (CORRELATION_ID, ACTION_AT)
    WHERE CORRELATION_ID IS NOT NULL;

CREATE INDEX IX_EMS_MAINTENANCE_ACTION_PLAN
    ON EMS_MAINTENANCE_ACTION_HISTORY (MAINTENANCE_PLAN_ID, ACTION_AT DESC);

-- Stock balance and ledger evidence must be committed together. Nullable columns preserve legacy
-- rows; the EMS repository always fills them for new adjustments.
ALTER TABLE EMS_SPARE_PART_INOUT ADD
    IDEMPOTENCY_KEY NVARCHAR(150) NULL,
    CORRELATION_ID  NVARCHAR(100) NULL,
    WO_ID           NVARCHAR(50)  NULL,
    EQUIPMENT_ID    NVARCHAR(50)  NULL,
    BALANCE_BEFORE  DECIMAL(18,4) NULL,
    BALANCE_AFTER   DECIMAL(18,4) NULL,
    CLIENT_CHANNEL  NVARCHAR(20)  NULL,
    DEVICE_ID       NVARCHAR(100) NULL;

ALTER TABLE EMS_SPARE_PART_INOUT
    ALTER COLUMN QUANTITY DECIMAL(20,4) NULL;

-- V045부터 PART_ID는 legacy 수불 이력을 보존하기 위한 soft reference다. 기존 orphan 행 때문에
-- 배포가 중단되지 않도록 사후 FK를 추가하지 않고 신규 쓰기는 EMS 서비스에서 part 존재를 검증한다.
ALTER TABLE EMS_SPARE_PART_INOUT ADD CONSTRAINT FK_EMS_SPARE_PART_INOUT_WO
    FOREIGN KEY (WO_ID) REFERENCES EMS_WORK_ORDER (WO_ID);

ALTER TABLE EMS_SPARE_PART_INOUT ADD CONSTRAINT CK_EMS_SPARE_PART_INOUT_EXECUTION CHECK (
    IDEMPOTENCY_KEY IS NULL
    OR (QUANTITY IS NOT NULL AND QUANTITY > 0
        AND BALANCE_BEFORE IS NOT NULL AND BALANCE_BEFORE >= 0
        AND BALANCE_AFTER IS NOT NULL AND BALANCE_AFTER >= 0
        AND PROCESSED_BY IS NOT NULL
        AND CLIENT_CHANNEL IN ('MES', 'MOBILE', 'POP'))
);

CREATE UNIQUE INDEX UX_EMS_SPARE_PART_INOUT_IDEMPOTENCY
    ON EMS_SPARE_PART_INOUT (IDEMPOTENCY_KEY)
    WHERE IDEMPOTENCY_KEY IS NOT NULL;

CREATE INDEX IX_EMS_SPARE_PART_INOUT_CORRELATION
    ON EMS_SPARE_PART_INOUT (CORRELATION_ID, TRANSACTION_AT)
    WHERE CORRELATION_ID IS NOT NULL;
