-- LOT 생산과 LOT이 없는 설비(예: 캐리어 세척)의 완료 실적을 OEE가 같은 방식으로 집계하도록
-- 표준 출력 이벤트를 둔다. 프로젝트 플러그인은 장비 신호를 이 계약으로 변환하고 EST가 회계성 원장을 소유한다.
CREATE TABLE EST_EQUIPMENT_OUTPUT_EVENT (
    OUTPUT_EVENT_ID   NVARCHAR(50)    NOT NULL,
    IDEMPOTENCY_KEY   NVARCHAR(100)   NOT NULL,
    REQUEST_HASH      NVARCHAR(128)   NOT NULL,
    PLANT_ID          NVARCHAR(50)    NOT NULL,
    EQUIPMENT_ID      NVARCHAR(50)    NOT NULL,
    OUTPUT_TYPE       NVARCHAR(30)    NOT NULL,
    CARRIER_ID        NVARCHAR(100)   NULL,
    PROCESS_LOT_ID    NVARCHAR(50)    NULL,
    WORK_ORDER_ID     NVARCHAR(50)    NULL,
    PROCESS_ID        NVARCHAR(50)    NULL,
    RECIPE_ID         NVARCHAR(50)    NULL,
    RECIPE_VERSION    INT             NULL,
    TOTAL_QTY         DECIMAL(18,4)   NOT NULL,
    GOOD_QTY          DECIMAL(18,4)   NOT NULL,
    DEFECT_QTY        DECIMAL(18,4)   NOT NULL,
    UNIT              NVARCHAR(30)    NOT NULL,
    SOURCE            NVARCHAR(30)    NOT NULL,
    SOURCE_EVENT_ID   NVARCHAR(100)   NULL,
    ACTOR_ID          NVARCHAR(50)    NOT NULL,
    CORRELATION_ID    NVARCHAR(100)   NULL,
    METADATA_JSON     NVARCHAR(MAX)   NULL,
    OCCURRED_AT       DATETIME2       NOT NULL,
    CREATED_BY        NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT        DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_EST_EQUIPMENT_OUTPUT_EVENT PRIMARY KEY (OUTPUT_EVENT_ID),
    CONSTRAINT CK_EST_EQUIPMENT_OUTPUT_QUANTITY CHECK (
        TOTAL_QTY > 0 AND GOOD_QTY >= 0 AND DEFECT_QTY >= 0
        AND GOOD_QTY + DEFECT_QTY = TOTAL_QTY)
);
CREATE UNIQUE INDEX UX_EST_EQUIPMENT_OUTPUT_IDEMPOTENCY
    ON EST_EQUIPMENT_OUTPUT_EVENT (IDEMPOTENCY_KEY);
CREATE UNIQUE INDEX UX_EST_EQUIPMENT_OUTPUT_SOURCE
    ON EST_EQUIPMENT_OUTPUT_EVENT (SOURCE, SOURCE_EVENT_ID)
    WHERE SOURCE_EVENT_ID IS NOT NULL;
CREATE INDEX IX_EST_EQUIPMENT_OUTPUT_OEE
    ON EST_EQUIPMENT_OUTPUT_EVENT (EQUIPMENT_ID, OCCURRED_AT);
CREATE INDEX IX_EST_EQUIPMENT_OUTPUT_CARRIER
    ON EST_EQUIPMENT_OUTPUT_EVENT (CARRIER_ID, OCCURRED_AT DESC);
