-- IVT 자재 LOT 생명주기. V048의 LOT/TX를 그대로 단일 재고·수불 원장으로 확장한다.
-- 기존 TX는 nullable 확장 컬럼을 갖게 하여 증분 설치를 깨지 않으며, 신규 공통 서비스 행만
-- 멱등성/소스 이벤트/낙관적 버전/잔량 스냅샷을 모두 기록한다.
ALTER TABLE IVT_MATERIAL_LOT ADD VERSION_NO INT NOT NULL DEFAULT 1;

ALTER TABLE IVT_MATERIAL_TX ADD IDEMPOTENCY_KEY NVARCHAR(100) NULL;
ALTER TABLE IVT_MATERIAL_TX ADD REQUEST_HASH NVARCHAR(64) NULL;
ALTER TABLE IVT_MATERIAL_TX ADD EXPECTED_VERSION INT NULL;
ALTER TABLE IVT_MATERIAL_TX ADD RESULT_VERSION INT NULL;
ALTER TABLE IVT_MATERIAL_TX ADD SOURCE_SYSTEM NVARCHAR(50) NULL;
ALTER TABLE IVT_MATERIAL_TX ADD SOURCE_EVENT_ID NVARCHAR(100) NULL;
ALTER TABLE IVT_MATERIAL_TX ADD CORRELATION_ID NVARCHAR(100) NULL;
ALTER TABLE IVT_MATERIAL_TX ADD METADATA_JSON NVARCHAR(MAX) NULL;
ALTER TABLE IVT_MATERIAL_TX ADD BALANCE_BEFORE DECIMAL(22,6) NULL;
ALTER TABLE IVT_MATERIAL_TX ADD BALANCE_AFTER DECIMAL(22,6) NULL;
ALTER TABLE IVT_MATERIAL_TX ADD BALANCE_DELTA DECIMAL(22,6) NULL;
ALTER TABLE IVT_MATERIAL_TX ADD RESULT_STATUS NVARCHAR(20) NULL;

CREATE UNIQUE INDEX UX_IVT_MATERIAL_TX_IDEMPOTENCY
    ON IVT_MATERIAL_TX (IDEMPOTENCY_KEY) WHERE IDEMPOTENCY_KEY IS NOT NULL;
CREATE UNIQUE INDEX UX_IVT_MATERIAL_TX_SOURCE_EVENT
    ON IVT_MATERIAL_TX (SOURCE_SYSTEM, SOURCE_EVENT_ID)
    WHERE SOURCE_SYSTEM IS NOT NULL AND SOURCE_EVENT_ID IS NOT NULL;
CREATE INDEX IX_IVT_MATERIAL_TX_LOT_EVENT
    ON IVT_MATERIAL_TX (LOT_ID, TX_AT DESC);
