-- Owner: EST. 누적 계량기의 교체·리셋·롤오버·교정은 실제 utility 소비가 아니라 계수 기준의 변경이다.
-- 불연속 사건을 판독값과 분리한 append-only 원장으로 보존해 기간 사용량이 계수 점프를 소비로 오인하지 않게 한다.
CREATE TABLE EST_UTILITY_METER_EVENT (
    EVENT_ID           NVARCHAR(50)    NOT NULL,
    IDEMPOTENCY_KEY    NVARCHAR(100)   NOT NULL,
    REQUEST_HASH       NVARCHAR(128)   NOT NULL,
    METER_ID           NVARCHAR(50)    NOT NULL,
    PLANT_ID           NVARCHAR(50)    NOT NULL,
    EQUIPMENT_ID       NVARCHAR(50)    NULL,
    EVENT_TYPE         NVARCHAR(20)    NOT NULL,
    OCCURRED_AT        DATETIME2       NOT NULL,
    REASON             NVARCHAR(500)   NOT NULL,
    PREVIOUS_VALUE     DECIMAL(18,6)   NULL,
    AFTER_VALUE        DECIMAL(18,6)   NULL,
    BASELINE_VALUE     DECIMAL(18,6)   NULL,
    UNIT               NVARCHAR(30)    NOT NULL,
    ACTOR_USER_ID      NVARCHAR(50)    NOT NULL,
    CREATED_AT         DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_EST_UTILITY_METER_EVENT PRIMARY KEY (EVENT_ID),
    CONSTRAINT FK_EST_UTILITY_METER_EVENT_METER
        FOREIGN KEY (METER_ID) REFERENCES EST_UTILITY_METER (METER_ID),
    CONSTRAINT CK_EST_UTILITY_METER_EVENT_TYPE
        CHECK (EVENT_TYPE IN ('Replacement', 'Reset', 'Rollover', 'Calibration')),
    CONSTRAINT CK_EST_UTILITY_METER_EVENT_VALUES
        CHECK (
            (PREVIOUS_VALUE IS NOT NULL AND AFTER_VALUE IS NOT NULL AND BASELINE_VALUE IS NULL)
            OR
            (PREVIOUS_VALUE IS NULL AND AFTER_VALUE IS NULL AND BASELINE_VALUE IS NOT NULL)
        ),
    CONSTRAINT CK_EST_UTILITY_METER_EVENT_NONNEGATIVE
        CHECK (
            (PREVIOUS_VALUE IS NULL OR PREVIOUS_VALUE >= 0)
            AND (AFTER_VALUE IS NULL OR AFTER_VALUE >= 0)
            AND (BASELINE_VALUE IS NULL OR BASELINE_VALUE >= 0)
        ),
    CONSTRAINT CK_EST_UTILITY_METER_EVENT_CHANGED
        CHECK (PREVIOUS_VALUE IS NULL OR AFTER_VALUE IS NULL OR PREVIOUS_VALUE <> AFTER_VALUE),
    CONSTRAINT CK_EST_UTILITY_METER_EVENT_AUDIT
        CHECK (
            LEN(LTRIM(RTRIM(IDEMPOTENCY_KEY))) > 0
            AND LEN(LTRIM(RTRIM(REQUEST_HASH))) > 0
            AND LEN(LTRIM(RTRIM(REASON))) > 0
            AND LEN(LTRIM(RTRIM(ACTOR_USER_ID))) > 0
        )
);

CREATE UNIQUE INDEX UX_EST_UTILITY_METER_EVENT_IDEMPOTENCY
    ON EST_UTILITY_METER_EVENT (IDEMPOTENCY_KEY);
CREATE INDEX IX_EST_UTILITY_METER_EVENT_HISTORY
    ON EST_UTILITY_METER_EVENT (METER_ID, OCCURRED_AT DESC);
