-- Owner: EST. OEE aggregation provenance and loss-occurrence integrity.
-- Generated mart rows retain their exact UTC window and the manual run that produced them;
-- loss rows remain one row per occurrence instead of collapsing a category into one synthetic row.
ALTER TABLE EST_OEE_SUMMARY ADD
    AGGREGATION_KIND    NVARCHAR(30) NULL,
    WINDOW_START_UTC    DATETIME2    NULL,
    WINDOW_END_UTC      DATETIME2    NULL,
    AGGREGATION_RUN_ID  NVARCHAR(50) NULL;

ALTER TABLE EST_OEE_LOSS ADD
    ENDED_AT            DATETIME2    NULL,
    AGGREGATION_KIND    NVARCHAR(30) NULL,
    WINDOW_START_UTC    DATETIME2    NULL,
    WINDOW_END_UTC      DATETIME2    NULL,
    AGGREGATION_RUN_ID  NVARCHAR(50) NULL;

ALTER TABLE EST_EQUIPMENT_OUTPUT_EVENT ADD CONSTRAINT CK_EST_OUTPUT_CARRIER_REQUIRED CHECK (
    UPPER(OUTPUT_TYPE) <> 'CARRIERCLEANED'
    OR (CARRIER_ID IS NOT NULL AND LEN(LTRIM(RTRIM(CARRIER_ID))) > 0)
);

CREATE TABLE EST_OEE_AGGREGATION_RUN (
    RUN_ID              NVARCHAR(50)  NOT NULL,
    RUN_TYPE            NVARCHAR(30)  NOT NULL,
    SCOPE_KEY           NVARCHAR(64)  NOT NULL,
    LOCAL_DATE          DATETIME2     NULL,
    WINDOW_START_UTC    DATETIME2     NULL,
    WINDOW_END_UTC      DATETIME2     NULL,
    SHIFT_ID            NVARCHAR(50)  NULL,
    PLANNED_MINUTES     DECIMAL(18,4) NOT NULL DEFAULT 0,
    ACTOR_ID            NVARCHAR(50)  NOT NULL,
    STATUS              NVARCHAR(20)  NOT NULL,
    AFFECTED_ROWS       INT           NOT NULL DEFAULT 0,
    ERROR_MESSAGE       NVARCHAR(1000) NULL,
    STARTED_AT          DATETIME2     NOT NULL,
    COMPLETED_AT        DATETIME2     NULL,
    CONSTRAINT PK_EST_OEE_AGGREGATION_RUN PRIMARY KEY (RUN_ID),
    CONSTRAINT CK_EST_OEE_AGGREGATION_RUN_STATUS CHECK (
        STATUS IN ('Started', 'Completed', 'Failed')),
    CONSTRAINT CK_EST_OEE_AGGREGATION_RUN_WINDOW CHECK (
        (WINDOW_START_UTC IS NULL AND WINDOW_END_UTC IS NULL)
        OR (WINDOW_START_UTC IS NOT NULL AND WINDOW_END_UTC IS NOT NULL
            AND WINDOW_END_UTC > WINDOW_START_UTC))
);

CREATE INDEX IX_EST_OEE_AGGREGATION_RUN_ACTOR
    ON EST_OEE_AGGREGATION_RUN (ACTOR_ID, STARTED_AT DESC);
CREATE INDEX IX_EST_OEE_AGGREGATION_RUN_SCOPE
    ON EST_OEE_AGGREGATION_RUN (SCOPE_KEY, STARTED_AT DESC);
CREATE INDEX IX_EST_OEE_SUMMARY_WINDOW
    ON EST_OEE_SUMMARY (EQUIPMENT_ID, WINDOW_START_UTC, WINDOW_END_UTC);
CREATE INDEX IX_EST_OEE_LOSS_WINDOW
    ON EST_OEE_LOSS (EQUIPMENT_ID, WINDOW_START_UTC, WINDOW_END_UTC);
