-- Owner: MDM. Immutable before/after evidence for equipment-master writes.

CREATE TABLE MDM_EQUIPMENT_CHANGE_HISTORY (
    CHANGE_ID          NVARCHAR(50)  NOT NULL,
    EQUIPMENT_ID       NVARCHAR(50)  NOT NULL,
    CHANGE_TYPE        NVARCHAR(30)  NOT NULL,
    ACTOR_ID           NVARCHAR(50)  NOT NULL,
    BEFORE_STATE_JSON  NVARCHAR(MAX) NULL,
    AFTER_STATE_JSON   NVARCHAR(MAX) NULL,
    CHANGED_AT         DATETIME2     NOT NULL,
    CREATED_BY         NVARCHAR(50)  NOT NULL,
    CREATED_AT         DATETIME2     NOT NULL,
    CONSTRAINT PK_MDM_EQUIPMENT_CHANGE_HISTORY PRIMARY KEY (CHANGE_ID),
    CONSTRAINT CK_MDM_EQUIPMENT_CHANGE_TYPE CHECK (
        CHANGE_TYPE IN ('Create', 'Update', 'Activate', 'Deactivate', 'ParentChange')),
    CONSTRAINT CK_MDM_EQUIPMENT_CHANGE_ACTOR CHECK (LEN(LTRIM(RTRIM(ACTOR_ID))) > 0),
    CONSTRAINT CK_MDM_EQUIPMENT_CHANGE_SHAPE CHECK (
        (CHANGE_TYPE = 'Create' AND BEFORE_STATE_JSON IS NULL AND AFTER_STATE_JSON IS NOT NULL)
        OR (CHANGE_TYPE <> 'Create' AND BEFORE_STATE_JSON IS NOT NULL AND AFTER_STATE_JSON IS NOT NULL))
);

CREATE INDEX IX_MDM_EQUIPMENT_CHANGE_EQUIPMENT
    ON MDM_EQUIPMENT_CHANGE_HISTORY (EQUIPMENT_ID, CHANGED_AT DESC);

-- SQLITE-OMIT-BEGIN
EXEC(N'CREATE TRIGGER TR_MDM_EQUIPMENT_CHANGE_APPEND_ONLY
ON MDM_EQUIPMENT_CHANGE_HISTORY
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    THROW 51000, ''MDM_EQUIPMENT_CHANGE_HISTORY is append-only'', 1;
END');
-- SQLITE-OMIT-END
