-- Owner: EMS. Maintenance-plan scope, spare opening balance, and tool chronology guards.

ALTER TABLE EMS_SPARE_PART_INOUT DROP CONSTRAINT CK_EMS_SPARE_PART_INOUT_EXECUTION;

ALTER TABLE EMS_SPARE_PART_INOUT ADD CONSTRAINT CK_EMS_SPARE_PART_INOUT_EXECUTION CHECK (
    IDEMPOTENCY_KEY IS NULL
    OR (QUANTITY IS NOT NULL
        AND ((TRANSACTION_TYPE = 'Opening' AND QUANTITY >= 0
              AND BALANCE_BEFORE = 0 AND BALANCE_AFTER = QUANTITY
              AND WO_ID IS NULL AND EQUIPMENT_ID IS NULL)
             OR (TRANSACTION_TYPE <> 'Opening' AND QUANTITY > 0))
        AND BALANCE_BEFORE IS NOT NULL AND BALANCE_BEFORE >= 0
        AND BALANCE_AFTER IS NOT NULL AND BALANCE_AFTER >= 0
        AND PROCESSED_BY IS NOT NULL
        AND CLIENT_CHANNEL IN ('MES', 'MOBILE', 'POP'))
);

-- SQLITE-OMIT-BEGIN
EXEC(N'CREATE TRIGGER TR_EMS_WORK_ORDER_PLAN_SCOPE
ON EMS_WORK_ORDER
AFTER INSERT, UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (
        SELECT 1
        FROM inserted W
        LEFT JOIN EMS_MAINTENANCE_PLAN P ON P.PLAN_ID = W.MAINTENANCE_PLAN_ID
        WHERE W.MAINTENANCE_PLAN_ID IS NOT NULL
          AND (P.PLAN_ID IS NULL
               OR P.EQUIPMENT_ID <> W.EQUIPMENT_ID
               OR (CASE WHEN P.PLAN_TYPE = ''CM'' THEN ''BM'' ELSE P.PLAN_TYPE END)
                  <> (CASE WHEN W.WO_TYPE = ''CM'' THEN ''BM'' ELSE W.WO_TYPE END))
    )
        THROW 51001, ''Maintenance work order plan scope/type mismatch'', 1;
END');

EXEC(N'CREATE TRIGGER TR_EMS_MAINTENANCE_PLAN_CHILD_SCOPE
ON EMS_MAINTENANCE_PLAN
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (
        SELECT 1
        FROM inserted P
        JOIN EMS_WORK_ORDER W ON W.MAINTENANCE_PLAN_ID = P.PLAN_ID
        WHERE P.EQUIPMENT_ID <> W.EQUIPMENT_ID
           OR (CASE WHEN P.PLAN_TYPE = ''CM'' THEN ''BM'' ELSE P.PLAN_TYPE END)
              <> (CASE WHEN W.WO_TYPE = ''CM'' THEN ''BM'' ELSE W.WO_TYPE END)
    )
        THROW 51002, ''Maintenance plan has incompatible work orders'', 1;
END');

EXEC(N'CREATE TRIGGER TR_EMS_TOOL_MOUNTED_CLASS_IMMUTABLE
ON EMS_TOOL
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (
        SELECT 1
        FROM inserted I
        JOIN deleted D ON D.TOOL_ID = I.TOOL_ID
        WHERE ISNULL(I.EQUIPMENT_CLASS_ID, '''') <> ISNULL(D.EQUIPMENT_CLASS_ID, '''')
          AND EXISTS (
              SELECT 1 FROM EMS_TOOL_MOUNT_HISTORY M
              WHERE M.TOOL_ID = I.TOOL_ID AND M.UNMOUNTED_AT IS NULL)
    )
        THROW 51003, ''Mounted tool equipment class is immutable'', 1;
END');

EXEC(N'CREATE TRIGGER TR_EMS_TOOL_USAGE_MOUNT_TIME
ON EMS_TOOL_USAGE_HISTORY
AFTER INSERT, UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (
        SELECT 1
        FROM inserted U
        JOIN EMS_TOOL_MOUNT_HISTORY M ON M.MOUNT_ID = U.MOUNT_ID
        WHERE U.MOUNT_ID IS NOT NULL AND U.USED_AT < M.MOUNTED_AT
    )
        THROW 51004, ''Tool usage cannot precede its mount'', 1;
    IF EXISTS (
        SELECT 1
        FROM inserted U
        JOIN EMS_TOOL_MOUNT_HISTORY M ON M.MOUNT_ID = U.MOUNT_ID
        WHERE U.MOUNT_ID IS NOT NULL
          AND M.UNMOUNTED_AT IS NOT NULL
          AND U.USED_AT > M.UNMOUNTED_AT
    )
        THROW 51006, ''Tool usage cannot follow its unmount'', 1;
END');

EXEC(N'CREATE TRIGGER TR_EMS_TOOL_UNMOUNT_USAGE_TIME
ON EMS_TOOL_MOUNT_HISTORY
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (
        SELECT 1
        FROM inserted M
        WHERE M.UNMOUNTED_AT IS NOT NULL
          AND EXISTS (
              SELECT 1 FROM EMS_TOOL_USAGE_HISTORY U
              WHERE U.MOUNT_ID = M.MOUNT_ID AND U.USED_AT > M.UNMOUNTED_AT)
    )
        THROW 51005, ''Tool unmount cannot precede recorded usage'', 1;
END');
-- SQLITE-OMIT-END
