-- Owner: RMS. Idempotent, append-only evidence for Recipe approval-state transitions.

CREATE TABLE RMS_RECIPE_APPROVAL_HISTORY (
    HISTORY_ID       NVARCHAR(50)   NOT NULL,
    IDEMPOTENCY_KEY  NVARCHAR(100)  NOT NULL,
    REQUEST_HASH     NVARCHAR(128)  NOT NULL,
    RECIPE_ID        NVARCHAR(50)   NOT NULL,
    FROM_STATE       NVARCHAR(20)   NOT NULL,
    TO_STATE         NVARCHAR(20)   NOT NULL,
    CHANGED_BY       NVARCHAR(50)   NOT NULL,
    REASON           NVARCHAR(500)  NULL,
    CHANGED_AT       DATETIME2      NOT NULL,
    CONSTRAINT PK_RMS_RECIPE_APPROVAL_HISTORY PRIMARY KEY (HISTORY_ID),
    CONSTRAINT FK_RMS_RECIPE_APPROVAL_HISTORY_RECIPE
        FOREIGN KEY (RECIPE_ID) REFERENCES RMS_RECIPE (RECIPE_ID),
    CONSTRAINT CK_RMS_RECIPE_APPROVAL_HISTORY_CHANGE CHECK (FROM_STATE <> TO_STATE)
);

CREATE UNIQUE INDEX UX_RMS_RECIPE_APPROVAL_HISTORY_IDEMPOTENCY
    ON RMS_RECIPE_APPROVAL_HISTORY (IDEMPOTENCY_KEY);
CREATE INDEX IX_RMS_RECIPE_APPROVAL_HISTORY_RECIPE
    ON RMS_RECIPE_APPROVAL_HISTORY (RECIPE_ID, CHANGED_AT, HISTORY_ID);

-- SQLITE-OMIT-BEGIN
EXEC(N'CREATE TRIGGER TR_RMS_RECIPE_APPROVAL_HISTORY_APPEND_ONLY
ON RMS_RECIPE_APPROVAL_HISTORY
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    THROW 51226, ''RMS_RECIPE_APPROVAL_HISTORY is append-only'', 1;
END');
-- SQLITE-OMIT-END
