-- Owner: EST. Versioned Utility meter configuration and immutable audit evidence.

ALTER TABLE EST_UTILITY_METER ADD CONFIG_VERSION INT NOT NULL DEFAULT 1;

ALTER TABLE EST_UTILITY_READING ADD METER_CONFIG_VERSION INT NOT NULL DEFAULT 1;
ALTER TABLE EST_UTILITY_READING ADD PLANT_ID NVARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE EST_UTILITY_READING ADD READING_MODE NVARCHAR(20) NOT NULL DEFAULT 'Cumulative';
ALTER TABLE EST_UTILITY_READING ADD COST_PER_UNIT DECIMAL(18,6) NULL;
ALTER TABLE EST_UTILITY_READING ADD CARBON_PER_UNIT DECIMAL(18,6) NULL;

ALTER TABLE EST_UTILITY_METER_EVENT ADD METER_CONFIG_VERSION INT NOT NULL DEFAULT 1;

CREATE TABLE EST_UTILITY_METER_CONFIG_HISTORY (
    HISTORY_ID        NVARCHAR(50)    NOT NULL,
    METER_ID          NVARCHAR(50)    NOT NULL,
    CONFIG_VERSION    INT             NOT NULL,
    METER_NAME        NVARCHAR(200)   NOT NULL,
    PLANT_ID          NVARCHAR(50)    NOT NULL,
    EQUIPMENT_ID      NVARCHAR(50)    NULL,
    UTILITY_TYPE      NVARCHAR(30)    NOT NULL,
    UNIT              NVARCHAR(30)    NOT NULL,
    FDC_PARAMETER_ID  NVARCHAR(50)    NULL,
    READING_MODE      NVARCHAR(20)    NOT NULL,
    SCALE_FACTOR      DECIMAL(18,6)   NOT NULL,
    COST_PER_UNIT     DECIMAL(18,6)   NULL,
    CARBON_PER_UNIT   DECIMAL(18,6)   NULL,
    IS_ACTIVE         BIT             NOT NULL,
    CHANGED_BY        NVARCHAR(50)    NOT NULL,
    CHANGED_AT        DATETIME2       NOT NULL,
    CONSTRAINT PK_EST_UTILITY_METER_CONFIG_HISTORY PRIMARY KEY (METER_ID, CONFIG_VERSION),
    CONSTRAINT FK_EST_UTILITY_METER_CONFIG_HISTORY_METER
        FOREIGN KEY (METER_ID) REFERENCES EST_UTILITY_METER (METER_ID),
    CONSTRAINT CK_EST_UTILITY_METER_CONFIG_VERSION CHECK (CONFIG_VERSION > 0)
);

CREATE UNIQUE INDEX UX_EST_UTILITY_METER_CONFIG_HISTORY_ID
    ON EST_UTILITY_METER_CONFIG_HISTORY (HISTORY_ID);

CREATE TABLE EST_UTILITY_METER_SAVE_COMMAND (
    IDEMPOTENCY_KEY  NVARCHAR(100) NOT NULL,
    REQUEST_HASH     NVARCHAR(128) NOT NULL,
    METER_ID         NVARCHAR(50)  NOT NULL,
    EXPECTED_VERSION INT           NOT NULL,
    RESULT_VERSION   INT           NOT NULL,
    ACTOR_ID         NVARCHAR(50)  NOT NULL,
    CREATED_AT       DATETIME2     NOT NULL,
    CONSTRAINT PK_EST_UTILITY_METER_SAVE_COMMAND PRIMARY KEY (IDEMPOTENCY_KEY),
    CONSTRAINT FK_EST_UTILITY_METER_SAVE_COMMAND_HISTORY
        FOREIGN KEY (METER_ID, RESULT_VERSION)
        REFERENCES EST_UTILITY_METER_CONFIG_HISTORY (METER_ID, CONFIG_VERSION),
    CONSTRAINT CK_EST_UTILITY_METER_SAVE_COMMAND_VERSION
        CHECK (EXPECTED_VERSION >= 0 AND RESULT_VERSION = EXPECTED_VERSION + 1)
);
CREATE INDEX IX_EST_UTILITY_METER_SAVE_COMMAND_METER
    ON EST_UTILITY_METER_SAVE_COMMAND (METER_ID, RESULT_VERSION);

INSERT INTO EST_UTILITY_METER_CONFIG_HISTORY
    (HISTORY_ID, METER_ID, CONFIG_VERSION, METER_NAME, PLANT_ID, EQUIPMENT_ID,
     UTILITY_TYPE, UNIT, FDC_PARAMETER_ID, READING_MODE, SCALE_FACTOR,
     COST_PER_UNIT, CARBON_PER_UNIT, IS_ACTIVE, CHANGED_BY, CHANGED_AT)
SELECT METER_ID, METER_ID, 1, METER_NAME, PLANT_ID, EQUIPMENT_ID,
       UTILITY_TYPE, UNIT, FDC_PARAMETER_ID, READING_MODE, SCALE_FACTOR,
       COST_PER_UNIT, CARBON_PER_UNIT, IS_ACTIVE, UPDATED_BY, UPDATED_AT
FROM EST_UTILITY_METER;

UPDATE EST_UTILITY_READING SET
    METER_CONFIG_VERSION = 1,
    PLANT_ID = (SELECT M.PLANT_ID FROM EST_UTILITY_METER M
                WHERE M.METER_ID = EST_UTILITY_READING.METER_ID),
    READING_MODE = (SELECT M.READING_MODE FROM EST_UTILITY_METER M
                    WHERE M.METER_ID = EST_UTILITY_READING.METER_ID),
    COST_PER_UNIT = (SELECT M.COST_PER_UNIT FROM EST_UTILITY_METER M
                     WHERE M.METER_ID = EST_UTILITY_READING.METER_ID),
    CARBON_PER_UNIT = (SELECT M.CARBON_PER_UNIT FROM EST_UTILITY_METER M
                       WHERE M.METER_ID = EST_UTILITY_READING.METER_ID);

-- SQLITE-OMIT-BEGIN
EXEC(N'CREATE TRIGGER TR_EST_UTILITY_METER_EVENT_APPEND_ONLY
ON EST_UTILITY_METER_EVENT
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    THROW 51227, ''EST_UTILITY_METER_EVENT is append-only'', 1;
END');

EXEC(N'CREATE TRIGGER TR_EST_UTILITY_CONFIG_HISTORY_APPEND_ONLY
ON EST_UTILITY_METER_CONFIG_HISTORY
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    THROW 51229, ''EST_UTILITY_METER_CONFIG_HISTORY is append-only'', 1;
END');
-- SQLITE-OMIT-END
