-- Owner: EST. Forward reconciliation after V127: create a missing legacy version-1 snapshot only while the
-- current master is still version 1, repair only rows carrying the blank upgrade marker in bounded
-- batches, then fail with an actionable report if history is non-contiguous or any meter/event/
-- reading points at a missing immutable configuration version.

-- SQLITE-OMIT-BEGIN
INSERT INTO EST_UTILITY_METER_CONFIG_HISTORY
    (HISTORY_ID, METER_ID, CONFIG_VERSION, METER_NAME, PLANT_ID, EQUIPMENT_ID,
     UTILITY_TYPE, UNIT, FDC_PARAMETER_ID, READING_MODE, SCALE_FACTOR,
     COST_PER_UNIT, CARBON_PER_UNIT, IS_ACTIVE, CHANGED_BY, CHANGED_AT)
SELECT M.METER_ID, M.METER_ID, 1, M.METER_NAME, M.PLANT_ID, M.EQUIPMENT_ID,
       M.UTILITY_TYPE, M.UNIT, M.FDC_PARAMETER_ID, M.READING_MODE, M.SCALE_FACTOR,
       M.COST_PER_UNIT, M.CARBON_PER_UNIT, M.IS_ACTIVE, M.UPDATED_BY, M.UPDATED_AT
FROM EST_UTILITY_METER M
WHERE M.CONFIG_VERSION = 1
  AND NOT EXISTS (
    SELECT 1
    FROM EST_UTILITY_METER_CONFIG_HISTORY H
    WHERE H.METER_ID = M.METER_ID AND H.CONFIG_VERSION = 1
);

DECLARE @V128BackfilledRows INT = 1;
WHILE @V128BackfilledRows > 0
BEGIN
    ;WITH PendingReading AS (
        SELECT TOP (5000) R.READING_ID
        FROM EST_UTILITY_READING R
        INNER JOIN EST_UTILITY_METER_CONFIG_HISTORY H
            ON H.METER_ID = R.METER_ID AND H.CONFIG_VERSION = 1
        WHERE NULLIF(LTRIM(RTRIM(R.PLANT_ID)), N'') IS NULL
          AND NULLIF(LTRIM(RTRIM(H.PLANT_ID)), N'') IS NOT NULL
        ORDER BY R.READING_ID
    )
    UPDATE R
       SET R.METER_CONFIG_VERSION = 1,
           R.PLANT_ID = H.PLANT_ID,
           R.READING_MODE = H.READING_MODE,
           R.COST_PER_UNIT = H.COST_PER_UNIT,
           R.CARBON_PER_UNIT = H.CARBON_PER_UNIT
      FROM EST_UTILITY_READING R
      INNER JOIN PendingReading P ON P.READING_ID = R.READING_ID
      INNER JOIN EST_UTILITY_METER_CONFIG_HISTORY H
        ON H.METER_ID = R.METER_ID AND H.CONFIG_VERSION = 1;

    SET @V128BackfilledRows = @@ROWCOUNT;
END;

IF EXISTS (
    SELECT 1
    FROM EST_UTILITY_METER M
    LEFT JOIN EST_UTILITY_METER_CONFIG_HISTORY H
      ON H.METER_ID = M.METER_ID AND H.CONFIG_VERSION = M.CONFIG_VERSION
    WHERE H.METER_ID IS NULL OR NULLIF(LTRIM(RTRIM(H.PLANT_ID)), N'') IS NULL
)
OR EXISTS (
    SELECT 1
    FROM EST_UTILITY_METER M
    WHERE (SELECT COUNT_BIG(*)
           FROM EST_UTILITY_METER_CONFIG_HISTORY H
           WHERE H.METER_ID = M.METER_ID
             AND H.CONFIG_VERSION BETWEEN 1 AND M.CONFIG_VERSION) <> M.CONFIG_VERSION
)
OR EXISTS (
    SELECT 1
    FROM EST_UTILITY_READING R
    LEFT JOIN EST_UTILITY_METER_CONFIG_HISTORY H
      ON H.METER_ID = R.METER_ID AND H.CONFIG_VERSION = R.METER_CONFIG_VERSION
    WHERE H.METER_ID IS NULL
       OR NULLIF(LTRIM(RTRIM(H.PLANT_ID)), N'') IS NULL
       OR NULLIF(LTRIM(RTRIM(R.PLANT_ID)), N'') IS NULL
)
OR EXISTS (
    SELECT 1
    FROM EST_UTILITY_METER_EVENT E
    LEFT JOIN EST_UTILITY_METER_CONFIG_HISTORY H
      ON H.METER_ID = E.METER_ID AND H.CONFIG_VERSION = E.METER_CONFIG_VERSION
    WHERE H.METER_ID IS NULL OR NULLIF(LTRIM(RTRIM(H.PLANT_ID)), N'') IS NULL
)
BEGIN
    SELECT N'METER' AS OBJECT_TYPE, M.METER_ID AS OBJECT_ID, M.CONFIG_VERSION
    FROM EST_UTILITY_METER M
    LEFT JOIN EST_UTILITY_METER_CONFIG_HISTORY H
      ON H.METER_ID = M.METER_ID AND H.CONFIG_VERSION = M.CONFIG_VERSION
    WHERE H.METER_ID IS NULL OR NULLIF(LTRIM(RTRIM(H.PLANT_ID)), N'') IS NULL
    UNION ALL
    SELECT N'METER_HISTORY_GAP', M.METER_ID, M.CONFIG_VERSION
    FROM EST_UTILITY_METER M
    WHERE (SELECT COUNT_BIG(*)
           FROM EST_UTILITY_METER_CONFIG_HISTORY H
           WHERE H.METER_ID = M.METER_ID
             AND H.CONFIG_VERSION BETWEEN 1 AND M.CONFIG_VERSION) <> M.CONFIG_VERSION
    UNION ALL
    SELECT N'READING', R.READING_ID, R.METER_CONFIG_VERSION
    FROM EST_UTILITY_READING R
    LEFT JOIN EST_UTILITY_METER_CONFIG_HISTORY H
      ON H.METER_ID = R.METER_ID AND H.CONFIG_VERSION = R.METER_CONFIG_VERSION
    WHERE H.METER_ID IS NULL
       OR NULLIF(LTRIM(RTRIM(H.PLANT_ID)), N'') IS NULL
       OR NULLIF(LTRIM(RTRIM(R.PLANT_ID)), N'') IS NULL
    UNION ALL
    SELECT N'EVENT', E.EVENT_ID, E.METER_CONFIG_VERSION
    FROM EST_UTILITY_METER_EVENT E
    LEFT JOIN EST_UTILITY_METER_CONFIG_HISTORY H
      ON H.METER_ID = E.METER_ID AND H.CONFIG_VERSION = E.METER_CONFIG_VERSION
    WHERE H.METER_ID IS NULL OR NULLIF(LTRIM(RTRIM(H.PLANT_ID)), N'') IS NULL;

    THROW 51228,
        'V128 utility configuration reconciliation failed. Review the reported meter, reading, and event rows.',
        1;
END;
-- SQLITE-OMIT-END
