-- Owner: RMS. Every recipe/parameter write carries an explicit actor, canonical request hash,
-- durable idempotency key and (for parameter update/delete) optimistic expected version.

ALTER TABLE RMS_RECIPE_PARAM
    ADD VERSION_NO INT NOT NULL CONSTRAINT DF_RMS_RECIPE_PARAM_VERSION DEFAULT 1;

ALTER TABLE RMS_RECIPE_PARAM
    ADD CONSTRAINT CK_RMS_RECIPE_PARAM_VERSION CHECK (VERSION_NO > 0);

CREATE TABLE RMS_RECIPE_COMMAND (
    COMMAND_ID        NVARCHAR(50)   NOT NULL,
    COMMAND_TYPE      NVARCHAR(20)   NOT NULL,
    IDEMPOTENCY_KEY   NVARCHAR(100)  NOT NULL,
    REQUEST_HASH      NVARCHAR(128)  NOT NULL,
    RECIPE_ID         NVARCHAR(50)   NOT NULL,
    SOURCE_RECIPE_ID  NVARCHAR(50)   NULL,
    ACTOR_ID          NVARCHAR(50)   NOT NULL,
    CREATED_AT        DATETIME2      NOT NULL,
    CONSTRAINT PK_RMS_RECIPE_COMMAND PRIMARY KEY (COMMAND_ID),
    CONSTRAINT CK_RMS_RECIPE_COMMAND_TYPE
        CHECK (COMMAND_TYPE IN ('Create', 'CreateVersion')),
    CONSTRAINT CK_RMS_RECIPE_COMMAND_SOURCE
        CHECK ((COMMAND_TYPE = 'Create' AND SOURCE_RECIPE_ID IS NULL)
            OR (COMMAND_TYPE = 'CreateVersion' AND SOURCE_RECIPE_ID IS NOT NULL))
);

-- RECIPE_ID intentionally has no FK. The immutable replay/evidence row must survive any future
-- archival strategy for recipe master data.
CREATE UNIQUE INDEX UX_RMS_RECIPE_COMMAND_IDEMPOTENCY
    ON RMS_RECIPE_COMMAND (IDEMPOTENCY_KEY);
CREATE INDEX IX_RMS_RECIPE_COMMAND_RECIPE_CREATED
    ON RMS_RECIPE_COMMAND (RECIPE_ID, CREATED_AT, COMMAND_ID);

CREATE TABLE RMS_RECIPE_PARAM_COMMAND (
    COMMAND_ID        NVARCHAR(50)   NOT NULL,
    COMMAND_TYPE      NVARCHAR(10)   NOT NULL,
    IDEMPOTENCY_KEY   NVARCHAR(100)  NOT NULL,
    REQUEST_HASH      NVARCHAR(128)  NOT NULL,
    PARAM_ID          NVARCHAR(50)   NOT NULL,
    RECIPE_ID         NVARCHAR(50)   NOT NULL,
    PARAM_NAME        NVARCHAR(200)  NULL,
    PARAM_VALUE       NVARCHAR(500)  NULL,
    UNIT              NVARCHAR(50)   NULL,
    SORT_ORDER        INT            NULL,
    EXPECTED_VERSION  INT            NULL,
    RESULT_VERSION    INT            NOT NULL,
    CHANGED_BY        NVARCHAR(50)   NOT NULL,
    CHANGED_AT        DATETIME2      NOT NULL,
    CONSTRAINT PK_RMS_RECIPE_PARAM_COMMAND PRIMARY KEY (COMMAND_ID),
    CONSTRAINT CK_RMS_RECIPE_PARAM_COMMAND_TYPE
        CHECK (COMMAND_TYPE IN ('Add', 'Update', 'Delete')),
    CONSTRAINT CK_RMS_RECIPE_PARAM_COMMAND_VERSION CHECK (
        (COMMAND_TYPE = 'Add' AND EXPECTED_VERSION IS NULL AND RESULT_VERSION = 1)
        OR (COMMAND_TYPE = 'Update' AND EXPECTED_VERSION > 0
            AND RESULT_VERSION = EXPECTED_VERSION + 1)
        OR (COMMAND_TYPE = 'Delete' AND EXPECTED_VERSION > 0
            AND RESULT_VERSION = EXPECTED_VERSION)),
    CONSTRAINT CK_RMS_RECIPE_PARAM_COMMAND_SNAPSHOT CHECK (
        PARAM_NAME IS NOT NULL AND PARAM_VALUE IS NOT NULL
        AND UNIT IS NOT NULL AND SORT_ORDER IS NOT NULL)
);

-- PARAM_ID intentionally has no FK: Delete removes the Draft parameter while its immutable
-- command snapshot must remain available for exact replay and audit.
CREATE UNIQUE INDEX UX_RMS_RECIPE_PARAM_COMMAND_IDEMPOTENCY
    ON RMS_RECIPE_PARAM_COMMAND (IDEMPOTENCY_KEY);
CREATE INDEX IX_RMS_RECIPE_PARAM_COMMAND_PARAM_CHANGED
    ON RMS_RECIPE_PARAM_COMMAND (PARAM_ID, CHANGED_AT, COMMAND_ID);

-- SQLITE-OMIT-BEGIN
EXEC(N'CREATE TRIGGER TR_RMS_RECIPE_COMMAND_APPEND_ONLY
ON RMS_RECIPE_COMMAND
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    THROW 51235, ''RMS_RECIPE_COMMAND is append-only'', 1;
END');

EXEC(N'CREATE TRIGGER TR_RMS_RECIPE_PARAM_COMMAND_APPEND_ONLY
ON RMS_RECIPE_PARAM_COMMAND
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    THROW 51236, ''RMS_RECIPE_PARAM_COMMAND is append-only'', 1;
END');
-- SQLITE-OMIT-END
