-- Owner: EMS. Tool-master writes use optimistic versions and an immutable command ledger.

ALTER TABLE EMS_TOOL
    ADD VERSION_NO INT NOT NULL CONSTRAINT DF_EMS_TOOL_VERSION DEFAULT 1;

ALTER TABLE EMS_TOOL
    ADD CONSTRAINT CK_EMS_TOOL_VERSION CHECK (VERSION_NO > 0);

CREATE TABLE EMS_TOOL_SAVE_COMMAND (
    COMMAND_ID        NVARCHAR(50)   NOT NULL,
    IDEMPOTENCY_KEY   NVARCHAR(100)  NOT NULL,
    REQUEST_HASH      NVARCHAR(128)  NOT NULL,
    TOOL_ID           NVARCHAR(50)   NOT NULL,
    EXPECTED_VERSION  INT            NOT NULL,
    RESULT_VERSION    INT            NOT NULL,
    RESULT_JSON       NVARCHAR(MAX)  NOT NULL,
    ACTOR_ID          NVARCHAR(50)   NOT NULL,
    CREATED_AT        DATETIME2      NOT NULL,
    CONSTRAINT PK_EMS_TOOL_SAVE_COMMAND PRIMARY KEY (COMMAND_ID),
    CONSTRAINT CK_EMS_TOOL_SAVE_COMMAND_VERSION
        CHECK (EXPECTED_VERSION >= 0 AND RESULT_VERSION = EXPECTED_VERSION + 1)
);

CREATE UNIQUE INDEX UX_EMS_TOOL_SAVE_COMMAND_IDEMPOTENCY
    ON EMS_TOOL_SAVE_COMMAND (IDEMPOTENCY_KEY);
CREATE INDEX IX_EMS_TOOL_SAVE_COMMAND_TOOL_CREATED
    ON EMS_TOOL_SAVE_COMMAND (TOOL_ID, CREATED_AT, COMMAND_ID);

-- SQLITE-OMIT-BEGIN
EXEC(N'CREATE TRIGGER TR_EMS_TOOL_SAVE_COMMAND_APPEND_ONLY
ON EMS_TOOL_SAVE_COMMAND
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    THROW 51238, ''EMS_TOOL_SAVE_COMMAND is append-only'', 1;
END');
-- SQLITE-OMIT-END
