-- Owner: EMS. Spare policy, supplier, and equipment-BOM commands retain immutable replay results.

CREATE TABLE EMS_SPARE_MASTER_COMMAND (
    COMMAND_ID        NVARCHAR(50)   NOT NULL,
    ENTITY_TYPE       NVARCHAR(30)   NOT NULL,
    ENTITY_ID         NVARCHAR(50)   NOT NULL,
    IDEMPOTENCY_KEY   NVARCHAR(100)  NOT NULL,
    REQUEST_HASH      NVARCHAR(128)  NOT NULL,
    EXPECTED_VERSION  INT            NOT NULL,
    RESULT_VERSION    INT            NOT NULL,
    RESULT_JSON       NVARCHAR(MAX)  NOT NULL,
    ACTOR_ID          NVARCHAR(50)   NOT NULL,
    CREATED_AT        DATETIME2      NOT NULL,
    CONSTRAINT PK_EMS_SPARE_MASTER_COMMAND PRIMARY KEY (COMMAND_ID),
    CONSTRAINT CK_EMS_SPARE_MASTER_COMMAND_TYPE
        CHECK (ENTITY_TYPE IN ('StockPolicy', 'Supplier', 'EquipmentBom')),
    CONSTRAINT CK_EMS_SPARE_MASTER_COMMAND_VERSION
        CHECK (EXPECTED_VERSION >= 0 AND RESULT_VERSION = EXPECTED_VERSION + 1)
);

CREATE UNIQUE INDEX UX_EMS_SPARE_MASTER_COMMAND_IDEMPOTENCY
    ON EMS_SPARE_MASTER_COMMAND (IDEMPOTENCY_KEY);
CREATE INDEX IX_EMS_SPARE_MASTER_COMMAND_ENTITY_CREATED
    ON EMS_SPARE_MASTER_COMMAND (ENTITY_TYPE, ENTITY_ID, CREATED_AT, COMMAND_ID);

-- SQLITE-OMIT-BEGIN
EXEC(N'CREATE TRIGGER TR_EMS_SPARE_MASTER_COMMAND_APPEND_ONLY
ON EMS_SPARE_MASTER_COMMAND
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    THROW 51239, ''EMS_SPARE_MASTER_COMMAND is append-only'', 1;
END');
-- SQLITE-OMIT-END
