-- Owner: EMS. Maintenance work-order creation retains immutable request and actor evidence.

CREATE TABLE EMS_WORK_ORDER_CREATE_COMMAND (
    COMMAND_ID           NVARCHAR(50)   NOT NULL,
    IDEMPOTENCY_KEY      NVARCHAR(150)  NOT NULL,
    REQUEST_HASH         NVARCHAR(128)  NOT NULL,
    WO_ID                NVARCHAR(50)   NOT NULL,
    EQUIPMENT_ID         NVARCHAR(50)   NOT NULL,
    WO_TYPE              NVARCHAR(20)   NOT NULL,
    DESCRIPTION          NVARCHAR(500)  NOT NULL,
    ASSIGNEE_ID          NVARCHAR(50)   NOT NULL,
    MAINTENANCE_PLAN_ID  NVARCHAR(50)   NULL,
    ISSUED_AT            DATETIME2      NOT NULL,
    ACTOR_ID             NVARCHAR(50)   NOT NULL,
    SOURCE               NVARCHAR(20)   NOT NULL,
    CLIENT_CHANNEL       NVARCHAR(20)   NOT NULL,
    DEVICE_ID            NVARCHAR(100)  NULL,
    CORRELATION_ID       NVARCHAR(100)  NULL,
    CREATED_AT           DATETIME2      NOT NULL,
    CONSTRAINT PK_EMS_WORK_ORDER_CREATE_COMMAND PRIMARY KEY (COMMAND_ID)
);

CREATE UNIQUE INDEX UX_EMS_WORK_ORDER_CREATE_COMMAND_IDEMPOTENCY
    ON EMS_WORK_ORDER_CREATE_COMMAND (IDEMPOTENCY_KEY);
CREATE INDEX IX_EMS_WORK_ORDER_CREATE_COMMAND_WO_CREATED
    ON EMS_WORK_ORDER_CREATE_COMMAND (WO_ID, CREATED_AT, COMMAND_ID);

-- SQLITE-OMIT-BEGIN
EXEC(N'CREATE TRIGGER TR_EMS_WORK_ORDER_CREATE_COMMAND_APPEND_ONLY
ON EMS_WORK_ORDER_CREATE_COMMAND
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    THROW 51240, ''EMS_WORK_ORDER_CREATE_COMMAND is append-only'', 1;
END');
-- SQLITE-OMIT-END
