-- Owner: FDC. Secret-free structured PLC endpoint options, timeouts, and polling recovery policy.
-- Only the four atomic polling protocols are mapped by FDC. OPC UA credentials/certificates and
-- arbitrary driver options are intentionally not persisted in this table.
ALTER TABLE FDC_EQUIPMENT_ENDPOINT
    ADD MODBUS_UNIT_ID SMALLINT NULL;

ALTER TABLE FDC_EQUIPMENT_ENDPOINT
    ADD S7_RACK SMALLINT NULL;

ALTER TABLE FDC_EQUIPMENT_ENDPOINT
    ADD S7_SLOT SMALLINT NULL;

ALTER TABLE FDC_EQUIPMENT_ENDPOINT
    ADD MITSUBISHI_STATION_NO SMALLINT NULL;

ALTER TABLE FDC_EQUIPMENT_ENDPOINT
    ADD MITSUBISHI_NETWORK_NO SMALLINT NULL;

ALTER TABLE FDC_EQUIPMENT_ENDPOINT
    ADD MITSUBISHI_PC_NO SMALLINT NULL;

ALTER TABLE FDC_EQUIPMENT_ENDPOINT
    ADD MITSUBISHI_IO_NO INT NULL;

ALTER TABLE FDC_EQUIPMENT_ENDPOINT
    ADD MITSUBISHI_FRAME_FORMAT NVARCHAR(10) NULL;

ALTER TABLE FDC_EQUIPMENT_ENDPOINT
    ADD CONNECTION_TIMEOUT_MS INT NOT NULL
        CONSTRAINT DF_FDC_ENDPOINT_CONNECTION_TIMEOUT DEFAULT 5000;

ALTER TABLE FDC_EQUIPMENT_ENDPOINT
    ADD READ_WRITE_TIMEOUT_MS INT NOT NULL
        CONSTRAINT DF_FDC_ENDPOINT_READ_WRITE_TIMEOUT DEFAULT 5000;

ALTER TABLE FDC_EQUIPMENT_ENDPOINT
    ADD HEARTBEAT_TIMEOUT_MS INT NOT NULL
        CONSTRAINT DF_FDC_ENDPOINT_HEARTBEAT_TIMEOUT DEFAULT 5000;

ALTER TABLE FDC_EQUIPMENT_ENDPOINT
    ADD POLLING_DISCONNECT_BACKOFF_MS INT NOT NULL
        CONSTRAINT DF_FDC_ENDPOINT_POLL_BACKOFF DEFAULT 100;

ALTER TABLE FDC_EQUIPMENT_ENDPOINT
    ADD POLLING_MAX_DISCONNECT_BACKOFF_MS INT NOT NULL
        CONSTRAINT DF_FDC_ENDPOINT_POLL_MAX_BACKOFF DEFAULT 1000;

-- SQLITE-OMIT-BEGIN
ALTER TABLE FDC_EQUIPMENT_ENDPOINT
    ADD CONSTRAINT CK_FDC_ENDPOINT_PLC_NUMERIC_RANGES CHECK (
        (MODBUS_UNIT_ID IS NULL OR MODBUS_UNIT_ID BETWEEN 0 AND 255)
        AND (S7_RACK IS NULL OR S7_RACK BETWEEN 0 AND 7)
        AND (S7_SLOT IS NULL OR S7_SLOT BETWEEN 0 AND 31)
        AND (MITSUBISHI_STATION_NO IS NULL OR MITSUBISHI_STATION_NO BETWEEN 0 AND 255)
        AND (MITSUBISHI_NETWORK_NO IS NULL OR MITSUBISHI_NETWORK_NO BETWEEN 0 AND 255)
        AND (MITSUBISHI_PC_NO IS NULL OR MITSUBISHI_PC_NO BETWEEN 0 AND 255)
        AND (MITSUBISHI_IO_NO IS NULL OR MITSUBISHI_IO_NO BETWEEN 0 AND 65535)
        AND (MITSUBISHI_FRAME_FORMAT IS NULL OR UPPER(MITSUBISHI_FRAME_FORMAT) IN ('BINARY', 'ASCII'))
    );

ALTER TABLE FDC_EQUIPMENT_ENDPOINT
    ADD CONSTRAINT CK_FDC_ENDPOINT_PLC_PROTOCOL_OPTIONS CHECK (
        (MODBUS_UNIT_ID IS NULL OR UPPER(PROTOCOL) = 'MODBUSTCP')
        AND ((S7_RACK IS NULL AND S7_SLOT IS NULL) OR UPPER(PROTOCOL) = 'SIEMENSS7')
        AND ((MITSUBISHI_STATION_NO IS NULL
              AND MITSUBISHI_NETWORK_NO IS NULL
              AND MITSUBISHI_PC_NO IS NULL
              AND MITSUBISHI_IO_NO IS NULL
              AND MITSUBISHI_FRAME_FORMAT IS NULL)
             OR UPPER(PROTOCOL) = 'MITSUBISHIMC')
    );

ALTER TABLE FDC_EQUIPMENT_ENDPOINT
    ADD CONSTRAINT CK_FDC_ENDPOINT_PLC_TIMEOUTS CHECK (
        CONNECTION_TIMEOUT_MS > 0
        AND READ_WRITE_TIMEOUT_MS > 0
        AND HEARTBEAT_TIMEOUT_MS > 0
        AND POLLING_DISCONNECT_BACKOFF_MS > 0
        AND POLLING_MAX_DISCONNECT_BACKOFF_MS >= POLLING_DISCONNECT_BACKOFF_MS
    );

-- FDC consumes only host/port. Reject fields commonly used to smuggle inline credentials or
-- unused query/path payloads into the plaintext endpoint column.
ALTER TABLE FDC_EQUIPMENT_ENDPOINT
    ADD CONSTRAINT CK_FDC_ENDPOINT_NO_INLINE_SECRET CHECK (
        ENDPOINT_URL NOT LIKE '%@%'
        AND ENDPOINT_URL NOT LIKE '%?%'
        AND ENDPOINT_URL NOT LIKE '%#%'
        AND ENDPOINT_URL NOT LIKE '%\%'
        AND (ENDPOINT_URL NOT LIKE '%://%'
             OR UPPER(LEFT(LTRIM(RTRIM(ENDPOINT_URL)), 6)) = 'TCP://')
        AND (
            (ENDPOINT_URL LIKE '%://%' AND ENDPOINT_URL NOT LIKE '%://%/%')
            OR (ENDPOINT_URL NOT LIKE '%://%' AND ENDPOINT_URL NOT LIKE '%/%')
        )
    );
-- SQLITE-OMIT-END
