-- Owner: FDC. Durable operational-interlock effect lifecycle and optimistic concurrency.
ALTER TABLE FDC_INTERLOCK_HISTORY ADD EFFECT_STATE VARCHAR(32) NOT NULL DEFAULT 'Prepared';
ALTER TABLE FDC_INTERLOCK_HISTORY ADD APPLY_ACK_ID VARCHAR(200) NULL;
ALTER TABLE FDC_INTERLOCK_HISTORY ADD APPLY_CONFIRMED_AT DATETIME2 NULL;
ALTER TABLE FDC_INTERLOCK_HISTORY ADD CONDITION_NORMALIZED_AT DATETIME2 NULL;
ALTER TABLE FDC_INTERLOCK_HISTORY ADD CONDITION_NORMALIZED_VALUE DECIMAL(18,6) NULL;
ALTER TABLE FDC_INTERLOCK_HISTORY ADD RELEASE_ACK_ID VARCHAR(200) NULL;
ALTER TABLE FDC_INTERLOCK_HISTORY ADD RELEASE_CONFIRMED_AT DATETIME2 NULL;
ALTER TABLE FDC_INTERLOCK_HISTORY ADD LAST_ERROR VARCHAR(1000) NULL;
ALTER TABLE FDC_INTERLOCK_HISTORY ADD VERSION INT NOT NULL DEFAULT 1;

-- Rows resolved before V146 have no action acknowledgement columns, but their durable terminal
-- fact must still map to the terminal lifecycle state instead of being mislabeled as Applied.
UPDATE FDC_INTERLOCK_HISTORY
   SET EFFECT_STATE = CASE WHEN IS_RESOLVED = 1 THEN 'Resolved' ELSE 'Prepared' END,
       LAST_ERROR = CASE WHEN IS_RESOLVED = 1 THEN 'LegacyResolvedBeforeV146' ELSE LAST_ERROR END;

-- SQLITE-OMIT-BEGIN
ALTER TABLE FDC_INTERLOCK_HISTORY ADD CONSTRAINT CK_FDC_INTERLOCK_EFFECT_STATE
    CHECK (EFFECT_STATE IN ('Prepared', 'Applied', 'ConditionNormalized', 'ReleasePending', 'Resolved'));
ALTER TABLE FDC_INTERLOCK_HISTORY ADD CONSTRAINT CK_FDC_INTERLOCK_EFFECT_VERSION
    CHECK (VERSION > 0);
ALTER TABLE FDC_INTERLOCK_HISTORY ADD CONSTRAINT CK_FDC_INTERLOCK_EFFECT_RESOLUTION
    CHECK (
        (IS_RESOLVED = 0 AND EFFECT_STATE <> 'Resolved')
        OR (IS_RESOLVED = 1 AND EFFECT_STATE = 'Resolved')
    );
ALTER TABLE FDC_INTERLOCK_HISTORY ADD CONSTRAINT CK_FDC_INTERLOCK_EFFECT_EVIDENCE
    CHECK (
        (
            EFFECT_STATE = 'Prepared'
            AND APPLY_ACK_ID IS NULL
            AND APPLY_CONFIRMED_AT IS NULL
            AND CONDITION_NORMALIZED_AT IS NULL
            AND CONDITION_NORMALIZED_VALUE IS NULL
            AND RELEASE_ACK_ID IS NULL
            AND RELEASE_CONFIRMED_AT IS NULL
        )
        OR (
            EFFECT_STATE = 'Applied'
            AND NULLIF(LTRIM(RTRIM(APPLY_ACK_ID)), '') IS NOT NULL
            AND APPLY_CONFIRMED_AT IS NOT NULL
            AND CONDITION_NORMALIZED_AT IS NULL
            AND CONDITION_NORMALIZED_VALUE IS NULL
            AND RELEASE_ACK_ID IS NULL
            AND RELEASE_CONFIRMED_AT IS NULL
        )
        OR (
            EFFECT_STATE IN ('ConditionNormalized', 'ReleasePending')
            AND NULLIF(LTRIM(RTRIM(APPLY_ACK_ID)), '') IS NOT NULL
            AND APPLY_CONFIRMED_AT IS NOT NULL
            AND CONDITION_NORMALIZED_AT IS NOT NULL
            AND CONDITION_NORMALIZED_VALUE IS NOT NULL
            AND CONDITION_NORMALIZED_AT >= APPLY_CONFIRMED_AT
            AND RELEASE_ACK_ID IS NULL
            AND RELEASE_CONFIRMED_AT IS NULL
        )
        OR (
            EFFECT_STATE = 'Resolved'
            AND (
                (
                    NULLIF(LTRIM(RTRIM(APPLY_ACK_ID)), '') IS NOT NULL
                    AND APPLY_CONFIRMED_AT IS NOT NULL
                    AND CONDITION_NORMALIZED_AT IS NOT NULL
                    AND CONDITION_NORMALIZED_VALUE IS NOT NULL
                    AND NULLIF(LTRIM(RTRIM(RELEASE_ACK_ID)), '') IS NOT NULL
                    AND RELEASE_CONFIRMED_AT IS NOT NULL
                    AND RESOLVED_AT IS NOT NULL
                    AND CONDITION_NORMALIZED_AT >= APPLY_CONFIRMED_AT
                    AND RELEASE_CONFIRMED_AT >= CONDITION_NORMALIZED_AT
                    AND RESOLVED_AT >= RELEASE_CONFIRMED_AT
                )
                OR LAST_ERROR = 'LegacyResolvedBeforeV146'
            )
        )
    );
-- SQLITE-OMIT-END
