-- Owner: IVT. Versioned, replayable management commands for TRACE material bindings and feed sessions.
-- Binding mutation is additionally gated by the IVT application and is not an online-operation path.

ALTER TABLE IVT_TRACE_CONSUMPTION_BINDING ADD VERSION_NO INT NOT NULL DEFAULT 1;
ALTER TABLE IVT_MATERIAL_FEED_SESSION ADD VERSION_NO INT NOT NULL DEFAULT 1;
ALTER TABLE IVT_MATERIAL_LOT ADD ACTIVE_FEED_SESSION_ID NVARCHAR(50) NULL;
ALTER TABLE IVT_MATERIAL_CONSUMPTION_HISTORY ADD FEED_SESSION_ID NVARCHAR(50) NULL;

-- Do not guess physical attribution while collapsing the wider V114 source key or reserving a LOT.
-- The migration runner wraps this file in one transaction, so either preflight failure preserves
-- the original columns and V114 indexes.
-- SQLITE-OMIT-BEGIN
IF EXISTS (
    SELECT EQUIPMENT_ID, PARAMETER_ID
      FROM IVT_TRACE_CONSUMPTION_BINDING
     WHERE IS_ACTIVE = 1
     GROUP BY EQUIPMENT_ID, PARAMETER_ID
    HAVING COUNT_BIG(*) > 1)
    THROW 51513, 'V151 duplicate active TRACE source; resolve physical attribution before migration', 1;

IF EXISTS (
    SELECT MATERIAL_LOT_ID
      FROM IVT_MATERIAL_FEED_SESSION
     WHERE STATUS = 'Mounted' AND UNMOUNTED_AT IS NULL
     GROUP BY MATERIAL_LOT_ID
    HAVING COUNT_BIG(*) > 1)
    THROW 51514, 'V151 material LOT has multiple active feed sessions; resolve the physical mount before migration', 1;

-- V151 treats Unmounted as PendingDrain until a durable FDC upper-watermark finalizer exists.
-- A legacy closed interval has no trustworthy winner when several historical sessions share a LOT,
-- so migration must not guess or silently leave the material lifecycle unfenced.
IF EXISTS (
    SELECT 1
      FROM IVT_MATERIAL_FEED_SESSION
     WHERE STATUS = 'Unmounted' OR UNMOUNTED_AT IS NOT NULL)
    THROW 51519, 'V151 legacy Unmounted feed sessions require audited PendingDrain reconciliation before migration', 1;
-- SQLITE-OMIT-END

-- FDC source identity is Equipment+Parameter. Plant/feed point describe the downstream
-- attribution and must not permit the same physical sample to enter two bindings.
-- SQLITE-OMIT-BEGIN
DROP INDEX UX_IVT_TRACE_BINDING_ACTIVE_SOURCE ON IVT_TRACE_CONSUMPTION_BINDING;
DROP INDEX IX_IVT_TRACE_BINDING_SOURCE ON IVT_TRACE_CONSUMPTION_BINDING;
-- SQLITE-OMIT-END
CREATE UNIQUE INDEX UX_IVT_TRACE_BINDING_ACTIVE_SOURCE
    ON IVT_TRACE_CONSUMPTION_BINDING (EQUIPMENT_ID, PARAMETER_ID)
    WHERE IS_ACTIVE = 1;
CREATE INDEX IX_IVT_TRACE_BINDING_INTERVAL
    ON IVT_TRACE_CONSUMPTION_BINDING
       (EQUIPMENT_ID, PARAMETER_ID, EFFECTIVE_TO);

-- A physical material LOT can be mounted in one feed session at a time. The LOT-side
-- reservation gives Mount and inventory lifecycle commands one atomic CAS row.
CREATE UNIQUE INDEX UX_IVT_FEED_SESSION_ACTIVE_LOT
    ON IVT_MATERIAL_FEED_SESSION (MATERIAL_LOT_ID)
    WHERE STATUS = 'Mounted' AND UNMOUNTED_AT IS NULL;

-- ACTIVE_FEED_SESSION_ID is also retained after Unmount while late pre-cutoff TRACE drains.
-- A composite candidate key lets the LOT-side reservation prove that the referenced session
-- belongs to that same material LOT instead of merely pointing at any existing session.
CREATE UNIQUE INDEX UX_IVT_FEED_SESSION_ID_MATERIAL_LOT
    ON IVT_MATERIAL_FEED_SESSION (FEED_SESSION_ID, MATERIAL_LOT_ID);

UPDATE IVT_MATERIAL_LOT
   SET ACTIVE_FEED_SESSION_ID = (
       SELECT S.FEED_SESSION_ID
         FROM IVT_MATERIAL_FEED_SESSION S
        WHERE S.MATERIAL_LOT_ID = IVT_MATERIAL_LOT.LOT_ID
          AND S.STATUS = 'Mounted' AND S.UNMOUNTED_AT IS NULL)
 WHERE EXISTS (
       SELECT 1 FROM IVT_MATERIAL_FEED_SESSION S
        WHERE S.MATERIAL_LOT_ID = IVT_MATERIAL_LOT.LOT_ID
          AND S.STATUS = 'Mounted' AND S.UNMOUNTED_AT IS NULL);

CREATE UNIQUE INDEX UX_IVT_MATERIAL_LOT_ACTIVE_FEED_SESSION
    ON IVT_MATERIAL_LOT (ACTIVE_FEED_SESSION_ID)
    WHERE ACTIVE_FEED_SESSION_ID IS NOT NULL;

-- Preserve V137 append-only evidence: legacy TRACE rows keep their historical feed-session
-- identity in CORRELATION_ID. Only new consumption writes populate the typed FEED_SESSION_ID.
-- SQLITE-OMIT-BEGIN
ALTER TABLE IVT_MATERIAL_LOT ADD CONSTRAINT
    FK_IVT_MATERIAL_LOT_ACTIVE_FEED_SESSION FOREIGN KEY (ACTIVE_FEED_SESSION_ID, LOT_ID)
    REFERENCES IVT_MATERIAL_FEED_SESSION (FEED_SESSION_ID, MATERIAL_LOT_ID);
-- SQLITE-OMIT-END

ALTER TABLE IVT_MATERIAL_CONSUMPTION_HISTORY ADD CONSTRAINT
    FK_IVT_MATERIAL_CONSUMPTION_FEED_SESSION FOREIGN KEY (FEED_SESSION_ID, MATERIAL_LOT_ID)
    REFERENCES IVT_MATERIAL_FEED_SESSION (FEED_SESSION_ID, MATERIAL_LOT_ID);

CREATE INDEX IX_IVT_MATERIAL_CONSUMPTION_FEED_SESSION
    ON IVT_MATERIAL_CONSUMPTION_HISTORY (FEED_SESSION_ID)
    WHERE FEED_SESSION_ID IS NOT NULL;

CREATE TABLE IVT_TRACE_BINDING_COMMAND (
    COMMAND_ID          NVARCHAR(50)    NOT NULL,
    COMMAND_TYPE        NVARCHAR(20)    NOT NULL,
    IDEMPOTENCY_KEY     NVARCHAR(100)   NOT NULL,
    REQUEST_HASH        NVARCHAR(64)    NOT NULL,
    BINDING_ID          NVARCHAR(50)    NOT NULL,
    PLANT_ID            NVARCHAR(50)    NOT NULL,
    EQUIPMENT_ID        NVARCHAR(50)    NOT NULL,
    PARAMETER_ID        NVARCHAR(50)    NOT NULL,
    FEED_POINT_ID       NVARCHAR(50)    NOT NULL,
    CALCULATION_MODE    NVARCHAR(30)    NOT NULL,
    SCALE_FACTOR        DECIMAL(18,6)   NOT NULL,
    PULSE_QUANTITY      DECIMAL(18,6)   NULL,
    OUTPUT_UNIT         NVARCHAR(30)    NOT NULL,
    EFFECTIVE_FROM      DATETIME2       NOT NULL,
    EFFECTIVE_TO        DATETIME2       NULL,
    RESULT_IS_ACTIVE    BIT             NOT NULL,
    EXPECTED_VERSION    INT             NOT NULL,
    RESULT_VERSION      INT             NOT NULL,
    ACTOR_ID            NVARCHAR(50)    NOT NULL,
    OCCURRED_AT         DATETIME2       NOT NULL,
    SOURCE_SYSTEM       NVARCHAR(50)    NOT NULL,
    SOURCE_EVENT_ID     NVARCHAR(100)   NOT NULL,
    CORRELATION_ID      NVARCHAR(100)   NULL,
    REASON              NVARCHAR(500)   NULL,
    CREATED_BY          NVARCHAR(50)    NOT NULL,
    CREATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_IVT_TRACE_BINDING_COMMAND PRIMARY KEY (COMMAND_ID),
    CONSTRAINT FK_IVT_TRACE_BINDING_COMMAND_BINDING FOREIGN KEY (BINDING_ID)
        REFERENCES IVT_TRACE_CONSUMPTION_BINDING (BINDING_ID),
    CONSTRAINT CK_IVT_TRACE_BINDING_COMMAND_TYPE CHECK (COMMAND_TYPE IN ('Create', 'Retire')),
    CONSTRAINT CK_IVT_TRACE_BINDING_COMMAND_VERSION CHECK (
        (COMMAND_TYPE = 'Create' AND EXPECTED_VERSION = 0 AND RESULT_VERSION = 1
            AND RESULT_IS_ACTIVE = 1 AND EFFECTIVE_TO IS NULL)
        OR (COMMAND_TYPE = 'Retire' AND EXPECTED_VERSION >= 1
            AND RESULT_VERSION = EXPECTED_VERSION + 1 AND RESULT_IS_ACTIVE = 0
            AND EFFECTIVE_TO IS NOT NULL)),
    CONSTRAINT CK_IVT_TRACE_BINDING_COMMAND_WINDOW CHECK (
        EFFECTIVE_TO IS NULL OR EFFECTIVE_TO > EFFECTIVE_FROM)
);

-- Opaque replay identities use ordinal semantics. SQLite TEXT indexes are BINARY by default;
-- production SQL Server columns are aligned explicitly before their unique indexes are created.
-- SQLITE-OMIT-BEGIN
ALTER TABLE IVT_TRACE_BINDING_COMMAND ALTER COLUMN IDEMPOTENCY_KEY
    NVARCHAR(100) COLLATE Latin1_General_100_BIN2 NOT NULL;
ALTER TABLE IVT_TRACE_BINDING_COMMAND ALTER COLUMN SOURCE_SYSTEM
    NVARCHAR(50) COLLATE Latin1_General_100_BIN2 NOT NULL;
ALTER TABLE IVT_TRACE_BINDING_COMMAND ALTER COLUMN SOURCE_EVENT_ID
    NVARCHAR(100) COLLATE Latin1_General_100_BIN2 NOT NULL;
-- SQLITE-OMIT-END

CREATE UNIQUE INDEX UX_IVT_TRACE_BINDING_COMMAND_IDEMPOTENCY
    ON IVT_TRACE_BINDING_COMMAND (IDEMPOTENCY_KEY);
CREATE UNIQUE INDEX UX_IVT_TRACE_BINDING_COMMAND_SOURCE
    ON IVT_TRACE_BINDING_COMMAND (SOURCE_SYSTEM, SOURCE_EVENT_ID);
CREATE INDEX IX_IVT_TRACE_BINDING_COMMAND_HISTORY
    ON IVT_TRACE_BINDING_COMMAND (BINDING_ID, OCCURRED_AT, COMMAND_ID);

CREATE TABLE IVT_FEED_SESSION_COMMAND (
    COMMAND_ID          NVARCHAR(50)    NOT NULL,
    COMMAND_TYPE        NVARCHAR(20)    NOT NULL,
    IDEMPOTENCY_KEY     NVARCHAR(100)   NOT NULL,
    REQUEST_HASH        NVARCHAR(64)    NOT NULL,
    FEED_SESSION_ID     NVARCHAR(50)    NOT NULL,
    PLANT_ID            NVARCHAR(50)    NOT NULL,
    EQUIPMENT_ID        NVARCHAR(50)    NOT NULL,
    FEED_POINT_ID       NVARCHAR(50)    NOT NULL,
    MATERIAL_LOT_ID     NVARCHAR(50)    NOT NULL,
    MATERIAL_ID         NVARCHAR(50)    NOT NULL,
    PROCESS_LOT_ID      NVARCHAR(50)    NULL,
    WORK_ORDER_ID       NVARCHAR(50)    NULL,
    PROCESS_ID          NVARCHAR(50)    NULL,
    RECIPE_ID           NVARCHAR(50)    NULL,
    RECIPE_VERSION      INT             NULL,
    MOUNTED_AT          DATETIME2       NOT NULL,
    MOUNTED_BY          NVARCHAR(50)    NOT NULL,
    UNMOUNTED_AT        DATETIME2       NULL,
    UNMOUNTED_BY        NVARCHAR(50)    NULL,
    RESULT_STATUS       NVARCHAR(20)    NOT NULL,
    EXPECTED_VERSION    INT             NOT NULL,
    RESULT_VERSION      INT             NOT NULL,
    ACTOR_ID            NVARCHAR(50)    NOT NULL,
    OCCURRED_AT         DATETIME2       NOT NULL,
    SOURCE_SYSTEM       NVARCHAR(50)    NOT NULL,
    SOURCE_EVENT_ID     NVARCHAR(100)   NOT NULL,
    CORRELATION_ID      NVARCHAR(100)   NULL,
    REASON              NVARCHAR(500)   NULL,
    CREATED_BY          NVARCHAR(50)    NOT NULL,
    CREATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_IVT_FEED_SESSION_COMMAND PRIMARY KEY (COMMAND_ID),
    CONSTRAINT FK_IVT_FEED_SESSION_COMMAND_SESSION FOREIGN KEY (FEED_SESSION_ID)
        REFERENCES IVT_MATERIAL_FEED_SESSION (FEED_SESSION_ID),
    CONSTRAINT CK_IVT_FEED_SESSION_COMMAND_TYPE CHECK (
        COMMAND_TYPE IN ('Mount', 'Unmount')),
    CONSTRAINT CK_IVT_FEED_SESSION_COMMAND_STATUS CHECK (
        RESULT_STATUS IN ('Mounted', 'Unmounted')),
    CONSTRAINT CK_IVT_FEED_SESSION_COMMAND_VERSION CHECK (
        (COMMAND_TYPE = 'Mount' AND EXPECTED_VERSION = 0 AND RESULT_VERSION = 1
            AND RESULT_STATUS = 'Mounted'
            AND UNMOUNTED_AT IS NULL AND UNMOUNTED_BY IS NULL)
        OR (COMMAND_TYPE = 'Unmount' AND EXPECTED_VERSION >= 1
            AND RESULT_VERSION = EXPECTED_VERSION + 1
            AND RESULT_STATUS = 'Unmounted'
            AND UNMOUNTED_AT IS NOT NULL AND UNMOUNTED_BY IS NOT NULL)),
    CONSTRAINT CK_IVT_FEED_SESSION_COMMAND_WINDOW CHECK (
        UNMOUNTED_AT IS NULL OR UNMOUNTED_AT > MOUNTED_AT)
);

-- SQLITE-OMIT-BEGIN
ALTER TABLE IVT_FEED_SESSION_COMMAND ALTER COLUMN IDEMPOTENCY_KEY
    NVARCHAR(100) COLLATE Latin1_General_100_BIN2 NOT NULL;
ALTER TABLE IVT_FEED_SESSION_COMMAND ALTER COLUMN SOURCE_SYSTEM
    NVARCHAR(50) COLLATE Latin1_General_100_BIN2 NOT NULL;
ALTER TABLE IVT_FEED_SESSION_COMMAND ALTER COLUMN SOURCE_EVENT_ID
    NVARCHAR(100) COLLATE Latin1_General_100_BIN2 NOT NULL;
-- SQLITE-OMIT-END

CREATE UNIQUE INDEX UX_IVT_FEED_SESSION_COMMAND_IDEMPOTENCY
    ON IVT_FEED_SESSION_COMMAND (IDEMPOTENCY_KEY);
CREATE UNIQUE INDEX UX_IVT_FEED_SESSION_COMMAND_SOURCE
    ON IVT_FEED_SESSION_COMMAND (SOURCE_SYSTEM, SOURCE_EVENT_ID);
CREATE INDEX IX_IVT_FEED_SESSION_COMMAND_HISTORY
    ON IVT_FEED_SESSION_COMMAND (FEED_SESSION_ID, OCCURRED_AT, COMMAND_ID);

-- SQLITE-OMIT-BEGIN
EXEC(N'CREATE TRIGGER TR_IVT_TRACE_BINDING_COMMAND_APPEND_ONLY
ON IVT_TRACE_BINDING_COMMAND
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    THROW 51511, ''IVT_TRACE_BINDING_COMMAND is append-only'', 1;
END');

EXEC(N'CREATE TRIGGER TR_IVT_FEED_SESSION_COMMAND_APPEND_ONLY
ON IVT_FEED_SESSION_COMMAND
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    THROW 51512, ''IVT_FEED_SESSION_COMMAND is append-only'', 1;
END');

EXEC(N'CREATE TRIGGER TR_IVT_FEED_SESSION_RESERVE_LOT
ON IVT_MATERIAL_FEED_SESSION
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (
        SELECT 1 FROM inserted
         WHERE STATUS <> ''Mounted'' OR UNMOUNTED_AT IS NOT NULL OR UNMOUNTED_BY IS NOT NULL)
        THROW 51515, ''A feed session must begin Mounted and reserve its material LOT'', 1;

    UPDATE L
       SET ACTIVE_FEED_SESSION_ID = I.FEED_SESSION_ID,
           UPDATED_BY = I.MOUNTED_BY,
           UPDATED_AT = I.CREATED_AT
      FROM IVT_MATERIAL_LOT L
      JOIN inserted I
        ON I.MATERIAL_LOT_ID = L.LOT_ID
       AND I.MATERIAL_ID = L.MATERIAL_ID
     WHERE L.STATUS = ''InStock''
       AND L.CURRENT_QTY > 0
       AND L.ACTIVE_FEED_SESSION_ID IS NULL;

    DECLARE @ReservedRows INT = @@ROWCOUNT;
    IF @ReservedRows <> (SELECT COUNT(*) FROM inserted)
        THROW 51516, ''Feed-session material LOT reservation failed'', 1;
END');

EXEC(N'CREATE TRIGGER TR_IVT_MATERIAL_LOT_FEED_RESERVATION_GUARD
ON IVT_MATERIAL_LOT
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (
        SELECT 1
          FROM inserted I
          JOIN deleted D ON D.LOT_ID = I.LOT_ID
         WHERE D.ACTIVE_FEED_SESSION_ID IS NOT NULL
           AND (I.ACTIVE_FEED_SESSION_ID IS NULL
                OR I.ACTIVE_FEED_SESSION_ID COLLATE Latin1_General_100_BIN2
                   <> D.ACTIVE_FEED_SESSION_ID COLLATE Latin1_General_100_BIN2))
        THROW 51517, ''PendingDrain feed-session reservation cannot be cleared or replaced before durable finalization'', 1;

    IF EXISTS (
        SELECT 1
          FROM inserted I
          LEFT JOIN IVT_MATERIAL_FEED_SESSION S
            ON S.FEED_SESSION_ID = I.ACTIVE_FEED_SESSION_ID
           AND S.MATERIAL_LOT_ID = I.LOT_ID
         WHERE I.ACTIVE_FEED_SESSION_ID IS NOT NULL
           AND S.FEED_SESSION_ID IS NULL)
        THROW 51518, ''Material LOT reservation must reference a feed session for the same LOT'', 1;
END');
-- SQLITE-OMIT-END
