-- Owner: POM. 작업 관리 범위와 Carrier 세척 이력. 기존 POM_WORK_ORDER를 변경하지 않고
-- 생산 W/O/LOT가 없는 설비 작업을 별도 애그리거트로 보존한다.
-- WorkOrderId는 선택적 상관관계 키이며 생산 W/O FK를 두지 않아 범위 생성이 레거시 W/O에
-- 종속되지 않는다. Carrier 세척은 WorkScopeId + CarrierId + CleaningProgramId/Result로
-- EST 출력 원장과 EMS Tool usage 원장을 함께 추적한다.

CREATE TABLE POM_WORK_SCOPE (
    WORK_SCOPE_ID       NVARCHAR(50)    NOT NULL,
    PLANT_ID            NVARCHAR(50)    NOT NULL,
    SCOPE_TYPE          NVARCHAR(20)    NOT NULL,
    TARGET_ID           NVARCHAR(100)   NOT NULL,
    NAME                NVARCHAR(200)   NOT NULL,
    PARENT_SCOPE_ID     NVARCHAR(50)    NULL,
    WORK_ORDER_ID       NVARCHAR(50)    NULL,
    CARRIER_ID          NVARCHAR(100)   NULL,
    EQUIPMENT_ID        NVARCHAR(50)    NULL,
    PRODUCT_ID          NVARCHAR(50)    NULL,
    PROCESS_ID          NVARCHAR(50)    NULL,
    RECIPE_ID           NVARCHAR(50)    NULL,
    RECIPE_VERSION      INT             NULL,
    PLAN_QTY            DECIMAL(18,4)   NULL,
    START_QTY           DECIMAL(18,4)   NOT NULL DEFAULT 0,
    COMPLETE_QTY        DECIMAL(18,4)   NOT NULL DEFAULT 0,
    SCRAP_QTY           DECIMAL(18,4)   NOT NULL DEFAULT 0,
    OWNER_ID            NVARCHAR(50)    NULL,
    STATUS              NVARCHAR(20)    NOT NULL DEFAULT 'Created',
    IS_HOLD             CHAR(1)         NOT NULL DEFAULT 'N',
    STARTED_AT          DATETIME2       NULL,
    COMPLETED_AT        DATETIME2       NULL,
    DESCRIPTION         NVARCHAR(500)   NULL,
    VERSION_NO          INT             NOT NULL DEFAULT 1,
    CREATED_BY          NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY          NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CREATE_IDEMPOTENCY_KEY NVARCHAR(100) NOT NULL,
    CREATE_REQUEST_HASH    NVARCHAR(64)  NOT NULL,
    CONSTRAINT PK_POM_WORK_SCOPE PRIMARY KEY (WORK_SCOPE_ID),
    CONSTRAINT FK_POM_WORK_SCOPE_PARENT FOREIGN KEY (PARENT_SCOPE_ID)
        REFERENCES POM_WORK_SCOPE (WORK_SCOPE_ID),
    CONSTRAINT CK_POM_WORK_SCOPE_TYPE CHECK (
        SCOPE_TYPE IN ('Batch', 'Campaign', 'Carrier', 'Lot', 'Equipment', 'Other')),
    CONSTRAINT CK_POM_WORK_SCOPE_STATUS CHECK (
        STATUS IN ('Created', 'Released', 'Started', 'Completed', 'Cancelled')),
    CONSTRAINT CK_POM_WORK_SCOPE_HOLD CHECK (IS_HOLD IN ('Y', 'N')),
    CONSTRAINT CK_POM_WORK_SCOPE_VERSION CHECK (VERSION_NO > 0),
    CONSTRAINT CK_POM_WORK_SCOPE_CREATE_IDENTITY CHECK (
        LEN(CREATE_IDEMPOTENCY_KEY) BETWEEN 1 AND 100
        AND LEN(CREATE_REQUEST_HASH) = 64),
    CONSTRAINT CK_POM_WORK_SCOPE_QUANTITY CHECK (
        (PLAN_QTY IS NULL OR PLAN_QTY > 0)
        AND START_QTY >= 0 AND COMPLETE_QTY >= 0 AND SCRAP_QTY >= 0
        AND (PLAN_QTY IS NULL OR START_QTY <= PLAN_QTY)
        AND (START_QTY = 0 OR COMPLETE_QTY + SCRAP_QTY <= START_QTY)),
    CONSTRAINT CK_POM_WORK_SCOPE_SPECIAL_TARGET CHECK (
        (SCOPE_TYPE <> 'Carrier' OR (CARRIER_ID IS NOT NULL AND TARGET_ID = CARRIER_ID))
        AND (SCOPE_TYPE <> 'Equipment' OR (EQUIPMENT_ID IS NOT NULL AND TARGET_ID = EQUIPMENT_ID)))
);

-- A target can have one active scope at a time. Completed/cancelled history remains append-only.
CREATE UNIQUE INDEX UX_POM_WORK_SCOPE_ACTIVE_TARGET
    ON POM_WORK_SCOPE (PLANT_ID, SCOPE_TYPE, TARGET_ID)
    WHERE STATUS IN ('Created', 'Released', 'Started');
CREATE INDEX IX_POM_WORK_SCOPE_LIST
    ON POM_WORK_SCOPE (PLANT_ID, STATUS, CREATED_AT DESC, WORK_SCOPE_ID);
CREATE INDEX IX_POM_WORK_SCOPE_TARGET
    ON POM_WORK_SCOPE (PLANT_ID, TARGET_ID, CREATED_AT DESC);
CREATE INDEX IX_POM_WORK_SCOPE_PARENT
    ON POM_WORK_SCOPE (PARENT_SCOPE_ID, CREATED_AT DESC);
CREATE INDEX IX_POM_WORK_SCOPE_CARRIER
    ON POM_WORK_SCOPE (CARRIER_ID, CREATED_AT DESC)
    WHERE CARRIER_ID IS NOT NULL;
CREATE INDEX IX_POM_WORK_SCOPE_WORK_ORDER
    ON POM_WORK_SCOPE (WORK_ORDER_ID, CREATED_AT DESC)
    WHERE WORK_ORDER_ID IS NOT NULL;
CREATE INDEX IX_POM_WORK_SCOPE_EQUIPMENT
    ON POM_WORK_SCOPE (EQUIPMENT_ID, CREATED_AT DESC)
    WHERE EQUIPMENT_ID IS NOT NULL;
CREATE UNIQUE INDEX UX_POM_WORK_SCOPE_CREATE_IDEMPOTENCY
    ON POM_WORK_SCOPE (CREATE_IDEMPOTENCY_KEY);

-- A parent scope owns the ordered children used by the 작업 관리 screen. The child scope
-- remains the source of truth for lifecycle state; this table is an immutable scheduling/read
-- model so batch/campaign membership can be queried without reusing SYS_BATCH_PROCESS.
CREATE TABLE POM_WORK_SCOPE_MEMBER (
    MEMBER_ID           NVARCHAR(50)    NOT NULL,
    WORK_SCOPE_ID       NVARCHAR(50)    NOT NULL,
    MEMBER_SCOPE_ID     NVARCHAR(50)    NOT NULL,
    MEMBER_TYPE         NVARCHAR(20)    NOT NULL,
    MEMBER_TARGET_ID    NVARCHAR(100)   NOT NULL,
    SEQUENCE_NO         INT             NOT NULL,
    IDEMPOTENCY_KEY     NVARCHAR(100)   NOT NULL,
    CREATED_BY          NVARCHAR(50)    NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_POM_WORK_SCOPE_MEMBER PRIMARY KEY (MEMBER_ID),
    CONSTRAINT UQ_POM_WORK_SCOPE_MEMBER_SCOPE UNIQUE (WORK_SCOPE_ID, MEMBER_SCOPE_ID),
    CONSTRAINT UQ_POM_WORK_SCOPE_MEMBER_KEY UNIQUE (IDEMPOTENCY_KEY),
    CONSTRAINT FK_POM_WORK_SCOPE_MEMBER_PARENT FOREIGN KEY (WORK_SCOPE_ID)
        REFERENCES POM_WORK_SCOPE (WORK_SCOPE_ID),
    CONSTRAINT FK_POM_WORK_SCOPE_MEMBER_CHILD FOREIGN KEY (MEMBER_SCOPE_ID)
        REFERENCES POM_WORK_SCOPE (WORK_SCOPE_ID),
    CONSTRAINT CK_POM_WORK_SCOPE_MEMBER_TYPE CHECK (
        MEMBER_TYPE IN ('Batch', 'Campaign', 'Carrier', 'Lot', 'Equipment', 'Other')),
    CONSTRAINT CK_POM_WORK_SCOPE_MEMBER_SEQUENCE CHECK (SEQUENCE_NO > 0),
    CONSTRAINT CK_POM_WORK_SCOPE_MEMBER_NOT_SELF CHECK (WORK_SCOPE_ID <> MEMBER_SCOPE_ID)
);
CREATE INDEX IX_POM_WORK_SCOPE_MEMBER_PARENT
    ON POM_WORK_SCOPE_MEMBER (WORK_SCOPE_ID, SEQUENCE_NO, MEMBER_SCOPE_ID);
CREATE INDEX IX_POM_WORK_SCOPE_MEMBER_CHILD
    ON POM_WORK_SCOPE_MEMBER (MEMBER_SCOPE_ID);

CREATE TABLE POM_WORK_SCOPE_EXECUTION (
    EXECUTION_ID       NVARCHAR(50)    NOT NULL,
    WORK_SCOPE_ID      NVARCHAR(50)    NOT NULL,
    IDEMPOTENCY_KEY    NVARCHAR(100)   NOT NULL,
    ACTION              NVARCHAR(30)    NOT NULL,
    FROM_STATUS         NVARCHAR(20)    NOT NULL,
    TO_STATUS           NVARCHAR(20)    NOT NULL,
    GOOD_QTY            DECIMAL(18,4)   NULL,
    DEFECT_QTY          DECIMAL(18,4)   NULL,
    USER_ID             NVARCHAR(50)    NOT NULL,
    EQUIPMENT_ID       NVARCHAR(50)    NULL,
    CLIENT_CHANNEL      NVARCHAR(20)    NOT NULL,
    DEVICE_ID           NVARCHAR(100)   NULL,
    OCCURRED_AT         DATETIME2       NOT NULL,
    REMARK              NVARCHAR(500)   NULL,
    EXPECTED_VERSION    INT             NOT NULL,
    RESULT_VERSION      INT             NOT NULL,
    CARRIER_ID          NVARCHAR(100)   NULL,
    RESULT_CODE         NVARCHAR(50)    NULL,
    RESULT_METADATA_JSON NVARCHAR(4000) NULL,
    CREATED_BY          NVARCHAR(50)    NOT NULL,
    CREATED_AT          DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_POM_WORK_SCOPE_EXECUTION PRIMARY KEY (EXECUTION_ID),
    CONSTRAINT UQ_POM_WORK_SCOPE_EXECUTION_KEY UNIQUE (IDEMPOTENCY_KEY),
    CONSTRAINT FK_POM_WORK_SCOPE_EXECUTION_SCOPE FOREIGN KEY (WORK_SCOPE_ID)
        REFERENCES POM_WORK_SCOPE (WORK_SCOPE_ID),
    CONSTRAINT CK_POM_WORK_SCOPE_EXECUTION_CHANNEL CHECK (
        CLIENT_CHANNEL IN ('MES', 'MOBILE', 'POP')),
    CONSTRAINT CK_POM_WORK_SCOPE_EXECUTION_ACTION CHECK (
        ACTION IN ('Release', 'Start', 'Report', 'Hold', 'ReleaseHold', 'Complete', 'Cancel')),
    CONSTRAINT CK_POM_WORK_SCOPE_EXECUTION_VERSION CHECK (
        EXPECTED_VERSION >= 1 AND RESULT_VERSION = EXPECTED_VERSION + 1),
    CONSTRAINT CK_POM_WORK_SCOPE_EXECUTION_QUANTITY CHECK (
        (GOOD_QTY IS NULL OR GOOD_QTY >= 0)
        AND (DEFECT_QTY IS NULL OR DEFECT_QTY >= 0))
);
CREATE INDEX IX_POM_WORK_SCOPE_EXECUTION_SCOPE
    ON POM_WORK_SCOPE_EXECUTION (WORK_SCOPE_ID, OCCURRED_AT DESC, EXECUTION_ID DESC);
CREATE INDEX IX_POM_WORK_SCOPE_EXECUTION_USER
    ON POM_WORK_SCOPE_EXECUTION (USER_ID, OCCURRED_AT DESC);

-- EST output is the common OEE ledger. The optional scope correlation keeps Carrier
-- cleaning non-LOT while allowing the WorkScope/Execution history to be joined without
-- coupling EST's table to the POM module's foreign keys.
ALTER TABLE EST_EQUIPMENT_OUTPUT_EVENT ADD WORK_SCOPE_ID NVARCHAR(50) NULL;
CREATE INDEX IX_EST_EQUIPMENT_OUTPUT_WORK_SCOPE
    ON EST_EQUIPMENT_OUTPUT_EVENT (WORK_SCOPE_ID, OCCURRED_AT DESC)
    WHERE WORK_SCOPE_ID IS NOT NULL;

-- Material consumption keeps MaterialLotId for inventory accounting, while these optional
-- correlations let a LOT-less Carrier cleaning run be traced back to its WorkScope.
ALTER TABLE IVT_MATERIAL_CONSUMPTION_HISTORY ADD WORK_SCOPE_ID NVARCHAR(50) NULL;
ALTER TABLE IVT_MATERIAL_CONSUMPTION_HISTORY ADD CARRIER_ID NVARCHAR(100) NULL;
CREATE INDEX IX_IVT_MATERIAL_CONSUMPTION_SCOPE
    ON IVT_MATERIAL_CONSUMPTION_HISTORY (WORK_SCOPE_ID, OCCURRED_AT DESC)
    WHERE WORK_SCOPE_ID IS NOT NULL;
CREATE INDEX IX_IVT_MATERIAL_CONSUMPTION_CARRIER
    ON IVT_MATERIAL_CONSUMPTION_HISTORY (CARRIER_ID, OCCURRED_AT DESC)
    WHERE CARRIER_ID IS NOT NULL;

-- The compatibility UI id remains FACTORY_PPM_WORK_ORDER, but the user-facing label is
-- now the scope-neutral 작업 관리/Work Management name on upgraded databases as well.
UPDATE SYS_MULTI_LANGUAGE_RESOURCE
   SET VALUE = 'Work Management'
 WHERE RESOURCE_KEY IN ('menu.FACTORY_PPM_WORK_ORDER', 'screen.FACTORY_PPM_WORK_ORDER.title')
   AND LANGUAGE = 'EnUs';

-- Existing EMS tool usage rows remain valid: legacy rows default to ordinary Use activity.
ALTER TABLE EMS_TOOL_USAGE_HISTORY ADD WORK_SCOPE_ID NVARCHAR(50) NULL;
ALTER TABLE EMS_TOOL_USAGE_HISTORY ADD CARRIER_ID NVARCHAR(100) NULL;
ALTER TABLE EMS_TOOL_USAGE_HISTORY ADD ACTIVITY_TYPE NVARCHAR(20) NOT NULL DEFAULT 'Use';
ALTER TABLE EMS_TOOL_USAGE_HISTORY ADD CLEANING_PROGRAM_ID NVARCHAR(100) NULL;
ALTER TABLE EMS_TOOL_USAGE_HISTORY ADD CLEANING_RESULT NVARCHAR(20) NULL;

ALTER TABLE EMS_TOOL_USAGE_HISTORY ADD CONSTRAINT CK_EMS_TOOL_USAGE_ACTIVITY CHECK (
    ACTIVITY_TYPE IN ('Use', 'Cleaning')
    AND ((ACTIVITY_TYPE = 'Use' AND CLEANING_PROGRAM_ID IS NULL AND CLEANING_RESULT IS NULL)
         OR (ACTIVITY_TYPE = 'Cleaning' AND CARRIER_ID IS NOT NULL
             AND WORK_SCOPE_ID IS NOT NULL AND CLEANING_PROGRAM_ID IS NOT NULL
             AND CLEANING_RESULT IN ('Pass', 'Fail'))));
CREATE INDEX IX_EMS_TOOL_USAGE_SCOPE
    ON EMS_TOOL_USAGE_HISTORY (WORK_SCOPE_ID, USED_AT DESC)
    WHERE WORK_SCOPE_ID IS NOT NULL;
CREATE INDEX IX_EMS_TOOL_USAGE_CARRIER
    ON EMS_TOOL_USAGE_HISTORY (CARRIER_ID, USED_AT DESC)
    WHERE CARRIER_ID IS NOT NULL;

-- SQLITE-OMIT-BEGIN
EXEC(N'CREATE TRIGGER TR_POM_WORK_SCOPE_EXECUTION_APPEND_ONLY
ON POM_WORK_SCOPE_EXECUTION
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    THROW 51520, ''POM_WORK_SCOPE_EXECUTION is append-only'', 1;
END');

EXEC(N'CREATE TRIGGER TR_POM_WORK_SCOPE_MEMBER_GUARD
ON POM_WORK_SCOPE_MEMBER
AFTER INSERT, UPDATE
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (
        SELECT 1
          FROM inserted I
          LEFT JOIN POM_WORK_SCOPE P ON P.WORK_SCOPE_ID = I.WORK_SCOPE_ID
          LEFT JOIN POM_WORK_SCOPE C ON C.WORK_SCOPE_ID = I.MEMBER_SCOPE_ID
         WHERE I.WORK_SCOPE_ID = I.MEMBER_SCOPE_ID
            OR I.SEQUENCE_NO <= 0
            OR P.WORK_SCOPE_ID IS NULL
            OR C.WORK_SCOPE_ID IS NULL
            OR P.PLANT_ID <> C.PLANT_ID
            OR I.MEMBER_TYPE <> C.SCOPE_TYPE
            OR I.MEMBER_TARGET_ID <> C.TARGET_ID
            OR ISNULL(C.PARENT_SCOPE_ID, '''') <> P.WORK_SCOPE_ID
            OR NOT (
                (P.SCOPE_TYPE = ''Campaign''
                    AND C.SCOPE_TYPE IN (''Batch'', ''Carrier'', ''Lot'', ''Other''))
                OR (P.SCOPE_TYPE = ''Batch''
                    AND C.SCOPE_TYPE IN (''Carrier'', ''Lot'', ''Other''))))
        THROW 51521, ''POM_WORK_SCOPE_MEMBER parent/child relationship is invalid'', 1;
END');

EXEC(N'CREATE TRIGGER TR_POM_WORK_SCOPE_MEMBER_APPEND_ONLY
ON POM_WORK_SCOPE_MEMBER
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    THROW 51522, ''POM_WORK_SCOPE_MEMBER is append-only'', 1;
END');
-- SQLITE-OMIT-END
