-- Owner: RMS. 레시피 실행 스냅샷을 작업 범위와 LOT 없는 Carrier 세척 이력에 연결한다.
-- WorkScopeId/CarrierId는 선택적 상관관계 키이며 RMS가 POM 테이블을 직접 참조하지 않는다.
-- CarrierId가 기록될 때 WorkScopeId도 함께 기록하는 규칙은 애플리케이션 계약에서 검증한다.

ALTER TABLE RMS_RECIPE_EXECUTION_SNAPSHOT ADD WORK_SCOPE_ID NVARCHAR(50) NULL;
ALTER TABLE RMS_RECIPE_EXECUTION_SNAPSHOT ADD CARRIER_ID NVARCHAR(100) NULL;

CREATE INDEX IX_RMS_RECIPE_EXECUTION_SCOPE
    ON RMS_RECIPE_EXECUTION_SNAPSHOT (WORK_SCOPE_ID, APPLIED_AT DESC)
    WHERE WORK_SCOPE_ID IS NOT NULL;
CREATE INDEX IX_RMS_RECIPE_EXECUTION_CARRIER
    ON RMS_RECIPE_EXECUTION_SNAPSHOT (CARRIER_ID, APPLIED_AT DESC)
    WHERE CARRIER_ID IS NOT NULL;
