-- Owner: POM/RMS/SYS integration boundary (ADR-0005).
-- These tables are append-only authority evidence. V113 raw JSON remains readable execution history
-- but cannot become authority unless a separate canonical evidence row is inserted.

CREATE TABLE RMS_CANONICAL_RECIPE_EXECUTION_EVIDENCE (
    EXECUTION_ID             NVARCHAR(100) COLLATE Latin1_General_100_BIN2 NOT NULL,
    WORK_SCOPE_ID            NVARCHAR(50)  COLLATE Latin1_General_100_BIN2 NOT NULL,
    PAIR_RUN_ID              NVARCHAR(100) COLLATE Latin1_General_100_BIN2 NOT NULL,
    SEQUENCE_RUN_ID          NVARCHAR(100) COLLATE Latin1_General_100_BIN2 NOT NULL,
    EQUIPMENT_ID             NVARCHAR(100) COLLATE Latin1_General_100_BIN2 NOT NULL,
    OPERATION_KEY            NVARCHAR(200) COLLATE Latin1_General_100_BIN2 NOT NULL,
    RECIPE_ID                NVARCHAR(100) COLLATE Latin1_General_100_BIN2 NOT NULL,
    RECIPE_VERSION           INT NOT NULL,
    SNAPSHOT_SCHEMA          NVARCHAR(100) COLLATE Latin1_General_100_BIN2 NOT NULL,
    SNAPSHOT_HASH            CHAR(64) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CAPTURED_AT              DATETIME2(7) NOT NULL,
    CONSTRAINT PK_RMS_CANONICAL_RECIPE_EXECUTION_EVIDENCE PRIMARY KEY (EXECUTION_ID),
    CONSTRAINT CK_RMS_CANONICAL_RECIPE_EXECUTION_HASH CHECK
      (LEN(SNAPSHOT_HASH)=64 AND SNAPSHOT_HASH NOT LIKE '%[^0-9A-F]%'),
    CONSTRAINT CK_RMS_CANONICAL_RECIPE_EXECUTION_VERSION CHECK (RECIPE_VERSION > 0)
);
CREATE UNIQUE INDEX UX_RMS_CANONICAL_RECIPE_EXECUTION_STREAM
  ON RMS_CANONICAL_RECIPE_EXECUTION_EVIDENCE(WORK_SCOPE_ID, PAIR_RUN_ID, SEQUENCE_RUN_ID);
CREATE INDEX IX_RMS_CANONICAL_RECIPE_EXECUTION_RECIPE
  ON RMS_CANONICAL_RECIPE_EXECUTION_EVIDENCE(RECIPE_ID, RECIPE_VERSION);

CREATE TABLE SYS_RELEASED_PROGRAM_ARTIFACT (
    ARTIFACT_ID                    NVARCHAR(200) COLLATE Latin1_General_100_BIN2 NOT NULL,
    EQUIPMENT_ID                   NVARCHAR(100) COLLATE Latin1_General_100_BIN2 NOT NULL,
    OPERATION_KEY                  NVARCHAR(200) COLLATE Latin1_General_100_BIN2 NOT NULL,
    PRODUCT_PROFILE_ID             NVARCHAR(100) COLLATE Latin1_General_100_BIN2 NOT NULL,
    PLUGIN_ID                      NVARCHAR(200) COLLATE Latin1_General_100_BIN2 NOT NULL,
    PRODUCT_DEFINITION_VERSION     NVARCHAR(100) COLLATE Latin1_General_100_BIN2 NOT NULL,
    PROGRAM_VERSION                NVARCHAR(100) COLLATE Latin1_General_100_BIN2 NOT NULL,
    PROGRAM_SCHEMA                 NVARCHAR(100) COLLATE Latin1_General_100_BIN2 NOT NULL,
    PROGRAM_HASH                   CHAR(64) COLLATE Latin1_General_100_BIN2 NOT NULL,
    BOUND_RECIPE_SNAPSHOT_SCHEMA   NVARCHAR(100) COLLATE Latin1_General_100_BIN2 NOT NULL,
    BOUND_RECIPE_SNAPSHOT_HASH     CHAR(64) COLLATE Latin1_General_100_BIN2 NOT NULL,
    RELEASED_AT                    DATETIME2(7) NOT NULL,
    RELEASED_BY                    NVARCHAR(50) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CONSTRAINT PK_SYS_RELEASED_PROGRAM_ARTIFACT PRIMARY KEY (ARTIFACT_ID),
    CONSTRAINT CK_SYS_RELEASED_PROGRAM_ARTIFACT_HASH CHECK
      (LEN(PROGRAM_HASH)=64 AND PROGRAM_HASH NOT LIKE '%[^0-9A-F]%'
       AND LEN(BOUND_RECIPE_SNAPSHOT_HASH)=64
       AND BOUND_RECIPE_SNAPSHOT_HASH NOT LIKE '%[^0-9A-F]%')
);
-- A release coordinate deliberately excludes PROGRAM_HASH: one coordinate can identify exactly
-- one released payload. The seven NVARCHAR keys can occupy 1,800 bytes and therefore cannot be a
-- SQL Server unique key (limit: 1,700 bytes). Hash an unambiguous, length-prefixed UTF-16
-- serialization into a fixed 32-byte key instead. A SHA-256 collision fails closed by refusing the
-- second release; it can never allow two payloads at the same coordinate.
-- SQLite installs an equivalent full-coordinate BINARY guard during schema reconciliation.
-- SQLITE-OMIT-BEGIN
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET QUOTED_IDENTIFIER ON;
SET NUMERIC_ROUNDABORT OFF;
ALTER TABLE SYS_RELEASED_PROGRAM_ARTIFACT ADD RELEASE_COORDINATE_DIGEST AS
  CONVERT(BINARY(32), HASHBYTES('SHA2_256',
    CONCAT(
      N'E', RIGHT(REPLICATE(N'0', 10) + CONVERT(NVARCHAR(10), DATALENGTH(EQUIPMENT_ID)), 10), EQUIPMENT_ID,
      N'O', RIGHT(REPLICATE(N'0', 10) + CONVERT(NVARCHAR(10), DATALENGTH(OPERATION_KEY)), 10), OPERATION_KEY,
      N'R', RIGHT(REPLICATE(N'0', 10) + CONVERT(NVARCHAR(10), DATALENGTH(PRODUCT_PROFILE_ID)), 10), PRODUCT_PROFILE_ID,
      N'P', RIGHT(REPLICATE(N'0', 10) + CONVERT(NVARCHAR(10), DATALENGTH(PLUGIN_ID)), 10), PLUGIN_ID,
      N'D', RIGHT(REPLICATE(N'0', 10) + CONVERT(NVARCHAR(10), DATALENGTH(PRODUCT_DEFINITION_VERSION)), 10), PRODUCT_DEFINITION_VERSION,
      N'V', RIGHT(REPLICATE(N'0', 10) + CONVERT(NVARCHAR(10), DATALENGTH(PROGRAM_VERSION)), 10), PROGRAM_VERSION,
      N'S', RIGHT(REPLICATE(N'0', 10) + CONVERT(NVARCHAR(10), DATALENGTH(PROGRAM_SCHEMA)), 10), PROGRAM_SCHEMA))) PERSISTED;
CREATE UNIQUE INDEX UX_SYS_RELEASED_PROGRAM_ARTIFACT_COORDINATE_DIGEST
  ON SYS_RELEASED_PROGRAM_ARTIFACT(RELEASE_COORDINATE_DIGEST);
-- SQLITE-OMIT-END
CREATE INDEX IX_SYS_RELEASED_PROGRAM_ARTIFACT_RECIPE_BINDING
  ON SYS_RELEASED_PROGRAM_ARTIFACT(BOUND_RECIPE_SNAPSHOT_SCHEMA, BOUND_RECIPE_SNAPSHOT_HASH);

CREATE TABLE SYS_RELEASED_PROGRAM_ARTIFACT_REVOCATION (
    REVOCATION_ID NVARCHAR(100) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ARTIFACT_ID   NVARCHAR(200) COLLATE Latin1_General_100_BIN2 NOT NULL,
    REVOKED_AT    DATETIME2(7) NOT NULL,
    REVOKED_BY    NVARCHAR(50) COLLATE Latin1_General_100_BIN2 NOT NULL,
    REASON        NVARCHAR(1000) NOT NULL,
    CONSTRAINT PK_SYS_RELEASED_PROGRAM_ARTIFACT_REVOCATION PRIMARY KEY (REVOCATION_ID),
    CONSTRAINT FK_SYS_RELEASED_PROGRAM_ARTIFACT_REVOCATION_ARTIFACT FOREIGN KEY (ARTIFACT_ID)
      REFERENCES SYS_RELEASED_PROGRAM_ARTIFACT(ARTIFACT_ID),
    CONSTRAINT UQ_SYS_RELEASED_PROGRAM_ARTIFACT_REVOCATION_ARTIFACT UNIQUE (ARTIFACT_ID)
);
CREATE INDEX IX_SYS_RELEASED_PROGRAM_ARTIFACT_REVOCATION_TIME
  ON SYS_RELEASED_PROGRAM_ARTIFACT_REVOCATION(REVOKED_AT, ARTIFACT_ID);

CREATE TABLE POM_WORK_SCOPE_PROJECTION_AUTHORITY_TRUST_STATE (
    STATE_ID       NVARCHAR(50) COLLATE Latin1_General_100_BIN2 NOT NULL,
    TRUST_VERSION  INT NOT NULL,
    APPLIED_AT     DATETIME2(7) NOT NULL,
    APPLIED_BY     NVARCHAR(50) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CONSTRAINT PK_POM_WORK_SCOPE_PROJECTION_AUTHORITY_TRUST_STATE PRIMARY KEY (STATE_ID),
    CONSTRAINT CK_POM_WORK_SCOPE_PROJECTION_AUTHORITY_TRUST_STATE CHECK
      (STATE_ID = 'V159_TRUSTED_AUTHORITY' AND TRUST_VERSION = 159)
);

-- SQLITE-OMIT-BEGIN
-- V158 predates trusted RMS/SYS evidence. Never synthesize trust from a legacy authority row:
-- commissioning must explicitly remove/re-provision it before this migration can proceed.
IF EXISTS (SELECT 1 FROM POM_WORK_SCOPE_PROJECTION_AUTHORITY)
  THROW 51564, 'V159 refuses legacy projection authority without explicit trusted evidence reprovisioning', 1;

ALTER TABLE POM_WORK_SCOPE_PROJECTION_AUTHORITY ADD CONSTRAINT
  CK_POM_WORK_SCOPE_PROJECTION_AUTHORITY_BOUNDARY_SPACE CHECK
  (DATALENGTH(WORK_SCOPE_ID)>0 AND DATALENGTH(WORK_SCOPE_ID)=DATALENGTH(LTRIM(RTRIM(WORK_SCOPE_ID)))
   AND DATALENGTH(SOURCE_CLIENT_ID)>0 AND DATALENGTH(SOURCE_CLIENT_ID)=DATALENGTH(LTRIM(RTRIM(SOURCE_CLIENT_ID)))
   AND DATALENGTH(EQUIPMENT_ID)>0 AND DATALENGTH(EQUIPMENT_ID)=DATALENGTH(LTRIM(RTRIM(EQUIPMENT_ID)))
   AND DATALENGTH(OPERATION_KEY)>0 AND DATALENGTH(OPERATION_KEY)=DATALENGTH(LTRIM(RTRIM(OPERATION_KEY)))
   AND DATALENGTH(PAIR_RUN_ID)>0 AND DATALENGTH(PAIR_RUN_ID)=DATALENGTH(LTRIM(RTRIM(PAIR_RUN_ID)))
   AND DATALENGTH(SEQUENCE_RUN_ID)>0 AND DATALENGTH(SEQUENCE_RUN_ID)=DATALENGTH(LTRIM(RTRIM(SEQUENCE_RUN_ID)))
   AND DATALENGTH(RECIPE_EXECUTION_ID)>0 AND DATALENGTH(RECIPE_EXECUTION_ID)=DATALENGTH(LTRIM(RTRIM(RECIPE_EXECUTION_ID)))
   AND DATALENGTH(RECIPE_ID)>0 AND DATALENGTH(RECIPE_ID)=DATALENGTH(LTRIM(RTRIM(RECIPE_ID)))
   AND DATALENGTH(RECIPE_SNAPSHOT_SCHEMA)>0 AND DATALENGTH(RECIPE_SNAPSHOT_SCHEMA)=DATALENGTH(LTRIM(RTRIM(RECIPE_SNAPSHOT_SCHEMA)))
   AND DATALENGTH(PROGRAM_ARTIFACT_ID)>0 AND DATALENGTH(PROGRAM_ARTIFACT_ID)=DATALENGTH(LTRIM(RTRIM(PROGRAM_ARTIFACT_ID)))
   AND DATALENGTH(PROGRAM_SCHEMA)>0 AND DATALENGTH(PROGRAM_SCHEMA)=DATALENGTH(LTRIM(RTRIM(PROGRAM_SCHEMA)))
   AND DATALENGTH(PROVISION_IDEMPOTENCY_KEY)>0 AND DATALENGTH(PROVISION_IDEMPOTENCY_KEY)=DATALENGTH(LTRIM(RTRIM(PROVISION_IDEMPOTENCY_KEY)))
   AND DATALENGTH(PROVISIONED_BY)>0 AND DATALENGTH(PROVISIONED_BY)=DATALENGTH(LTRIM(RTRIM(PROVISIONED_BY))));

ALTER TABLE RMS_CANONICAL_RECIPE_EXECUTION_EVIDENCE ADD CONSTRAINT
  CK_RMS_CANONICAL_RECIPE_EXECUTION_BOUNDARY_SPACE CHECK
  (DATALENGTH(EXECUTION_ID)>0 AND DATALENGTH(EXECUTION_ID)=DATALENGTH(LTRIM(RTRIM(EXECUTION_ID)))
   AND DATALENGTH(WORK_SCOPE_ID)>0 AND DATALENGTH(WORK_SCOPE_ID)=DATALENGTH(LTRIM(RTRIM(WORK_SCOPE_ID)))
   AND DATALENGTH(PAIR_RUN_ID)>0 AND DATALENGTH(PAIR_RUN_ID)=DATALENGTH(LTRIM(RTRIM(PAIR_RUN_ID)))
   AND DATALENGTH(SEQUENCE_RUN_ID)>0 AND DATALENGTH(SEQUENCE_RUN_ID)=DATALENGTH(LTRIM(RTRIM(SEQUENCE_RUN_ID)))
   AND DATALENGTH(EQUIPMENT_ID)>0 AND DATALENGTH(EQUIPMENT_ID)=DATALENGTH(LTRIM(RTRIM(EQUIPMENT_ID)))
   AND DATALENGTH(OPERATION_KEY)>0 AND DATALENGTH(OPERATION_KEY)=DATALENGTH(LTRIM(RTRIM(OPERATION_KEY)))
   AND DATALENGTH(RECIPE_ID)>0 AND DATALENGTH(RECIPE_ID)=DATALENGTH(LTRIM(RTRIM(RECIPE_ID)))
   AND DATALENGTH(SNAPSHOT_SCHEMA)>0 AND DATALENGTH(SNAPSHOT_SCHEMA)=DATALENGTH(LTRIM(RTRIM(SNAPSHOT_SCHEMA))));

ALTER TABLE SYS_RELEASED_PROGRAM_ARTIFACT ADD CONSTRAINT
  CK_SYS_RELEASED_PROGRAM_ARTIFACT_BOUNDARY_SPACE CHECK
  (DATALENGTH(ARTIFACT_ID)>0 AND DATALENGTH(ARTIFACT_ID)=DATALENGTH(LTRIM(RTRIM(ARTIFACT_ID)))
   AND DATALENGTH(EQUIPMENT_ID)>0 AND DATALENGTH(EQUIPMENT_ID)=DATALENGTH(LTRIM(RTRIM(EQUIPMENT_ID)))
   AND DATALENGTH(OPERATION_KEY)>0 AND DATALENGTH(OPERATION_KEY)=DATALENGTH(LTRIM(RTRIM(OPERATION_KEY)))
   AND DATALENGTH(PRODUCT_PROFILE_ID)>0 AND DATALENGTH(PRODUCT_PROFILE_ID)=DATALENGTH(LTRIM(RTRIM(PRODUCT_PROFILE_ID)))
   AND DATALENGTH(PLUGIN_ID)>0 AND DATALENGTH(PLUGIN_ID)=DATALENGTH(LTRIM(RTRIM(PLUGIN_ID)))
   AND DATALENGTH(PRODUCT_DEFINITION_VERSION)>0 AND DATALENGTH(PRODUCT_DEFINITION_VERSION)=DATALENGTH(LTRIM(RTRIM(PRODUCT_DEFINITION_VERSION)))
   AND DATALENGTH(PROGRAM_VERSION)>0 AND DATALENGTH(PROGRAM_VERSION)=DATALENGTH(LTRIM(RTRIM(PROGRAM_VERSION)))
   AND DATALENGTH(PROGRAM_SCHEMA)>0 AND DATALENGTH(PROGRAM_SCHEMA)=DATALENGTH(LTRIM(RTRIM(PROGRAM_SCHEMA)))
   AND DATALENGTH(BOUND_RECIPE_SNAPSHOT_SCHEMA)>0 AND DATALENGTH(BOUND_RECIPE_SNAPSHOT_SCHEMA)=DATALENGTH(LTRIM(RTRIM(BOUND_RECIPE_SNAPSHOT_SCHEMA)))
   AND DATALENGTH(RELEASED_BY)>0 AND DATALENGTH(RELEASED_BY)=DATALENGTH(LTRIM(RTRIM(RELEASED_BY))));

ALTER TABLE SYS_RELEASED_PROGRAM_ARTIFACT_REVOCATION ADD CONSTRAINT
  CK_SYS_RELEASED_PROGRAM_ARTIFACT_REVOCATION_BOUNDARY_SPACE CHECK
  (DATALENGTH(REVOCATION_ID)>0 AND DATALENGTH(REVOCATION_ID)=DATALENGTH(LTRIM(RTRIM(REVOCATION_ID)))
   AND DATALENGTH(ARTIFACT_ID)>0 AND DATALENGTH(ARTIFACT_ID)=DATALENGTH(LTRIM(RTRIM(ARTIFACT_ID)))
   AND DATALENGTH(REVOKED_BY)>0 AND DATALENGTH(REVOKED_BY)=DATALENGTH(LTRIM(RTRIM(REVOKED_BY)))
   AND DATALENGTH(REASON)>0 AND DATALENGTH(REASON)=DATALENGTH(LTRIM(RTRIM(REASON))));

-- Strengthen V158's already-installed guard without changing the applied V158 checksum.
EXEC(N'ALTER TRIGGER TR_POM_WORK_SCOPE_PROJECTION_AUTHORITY_GUARD
ON POM_WORK_SCOPE_PROJECTION_AUTHORITY
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (
        SELECT 1 FROM deleted D
        LEFT JOIN inserted I
          ON I.WORK_SCOPE_ID = D.WORK_SCOPE_ID
       WHERE I.WORK_SCOPE_ID IS NULL)
        THROW 51550, ''POM projection authority is not deletable'', 1;

    IF EXISTS (
        SELECT 1 FROM inserted I
        JOIN deleted D ON D.WORK_SCOPE_ID = I.WORK_SCOPE_ID
       WHERE D.WORK_SCOPE_ID COLLATE Latin1_General_100_BIN2
                 <> I.WORK_SCOPE_ID COLLATE Latin1_General_100_BIN2
          OR D.SOURCE_CLIENT_ID <> I.SOURCE_CLIENT_ID
          OR D.EQUIPMENT_ID <> I.EQUIPMENT_ID
          OR D.OPERATION_KEY <> I.OPERATION_KEY
          OR D.PAIR_RUN_ID <> I.PAIR_RUN_ID
          OR D.SEQUENCE_RUN_ID <> I.SEQUENCE_RUN_ID
          OR D.RECIPE_EXECUTION_ID <> I.RECIPE_EXECUTION_ID
          OR D.RECIPE_ID COLLATE Latin1_General_100_BIN2
                 <> I.RECIPE_ID COLLATE Latin1_General_100_BIN2
          OR D.RECIPE_VERSION <> I.RECIPE_VERSION
          OR D.RECIPE_SNAPSHOT_SCHEMA <> I.RECIPE_SNAPSHOT_SCHEMA
          OR D.RECIPE_SNAPSHOT_HASH <> I.RECIPE_SNAPSHOT_HASH
          OR D.PROGRAM_ARTIFACT_ID <> I.PROGRAM_ARTIFACT_ID
          OR D.PROGRAM_SCHEMA <> I.PROGRAM_SCHEMA
          OR D.PROGRAM_HASH <> I.PROGRAM_HASH
          OR D.BASELINE_VERSION_NO <> I.BASELINE_VERSION_NO
          OR D.PROVISION_IDEMPOTENCY_KEY <> I.PROVISION_IDEMPOTENCY_KEY
          OR D.PROVISION_REQUEST_HASH <> I.PROVISION_REQUEST_HASH
          OR D.PROVISIONED_AT <> I.PROVISIONED_AT
          OR D.PROVISIONED_BY <> I.PROVISIONED_BY)
        THROW 51551, ''POM projection authority identity is immutable'', 1;

    IF EXISTS (
        SELECT 1 FROM inserted I
        JOIN deleted D ON D.WORK_SCOPE_ID = I.WORK_SCOPE_ID
        LEFT JOIN POM_WORK_SCOPE S WITH (UPDLOCK, HOLDLOCK)
          ON S.WORK_SCOPE_ID COLLATE Latin1_General_100_BIN2
               = I.WORK_SCOPE_ID COLLATE Latin1_General_100_BIN2
         AND DATALENGTH(CONVERT(NVARCHAR(MAX), S.WORK_SCOPE_ID))
               = DATALENGTH(CONVERT(NVARCHAR(MAX), I.WORK_SCOPE_ID))
       WHERE I.LAST_APPLIED_VERSION_NO < D.LAST_APPLIED_VERSION_NO
          OR (I.LAST_APPLIED_VERSION_NO = D.LAST_APPLIED_VERSION_NO
              AND ISNULL(I.LAST_APPLIED_AT, ''0001-01-01'')
                    <> ISNULL(D.LAST_APPLIED_AT, ''0001-01-01''))
          OR (I.LAST_APPLIED_VERSION_NO > D.LAST_APPLIED_VERSION_NO
              AND (S.WORK_SCOPE_ID IS NULL
                   OR I.LAST_APPLIED_VERSION_NO <> S.VERSION_NO
                   OR (I.LAST_APPLIED_VERSION_NO > I.BASELINE_VERSION_NO
                       AND I.LAST_APPLIED_AT IS NULL)
                   OR (D.LAST_APPLIED_AT IS NOT NULL
                       AND (I.LAST_APPLIED_AT IS NULL
                            OR I.LAST_APPLIED_AT < D.LAST_APPLIED_AT)))))
        THROW 51552, ''POM projection authority applied lineage is monotonic and scope-aligned'', 1;

    IF EXISTS (
        SELECT 1 FROM inserted I
        LEFT JOIN deleted D ON D.WORK_SCOPE_ID = I.WORK_SCOPE_ID
        LEFT JOIN POM_WORK_SCOPE S WITH (UPDLOCK, HOLDLOCK)
          ON S.WORK_SCOPE_ID COLLATE Latin1_General_100_BIN2
               = I.WORK_SCOPE_ID COLLATE Latin1_General_100_BIN2
         AND DATALENGTH(CONVERT(NVARCHAR(MAX), S.WORK_SCOPE_ID))
               = DATALENGTH(CONVERT(NVARCHAR(MAX), I.WORK_SCOPE_ID))
       WHERE D.WORK_SCOPE_ID IS NULL
         AND (S.WORK_SCOPE_ID IS NULL
              OR S.STATUS <> ''Created''
              OR S.IS_HOLD <> ''N''
              OR S.VERSION_NO <> 1
              OR S.START_QTY <> 0
              OR S.COMPLETE_QTY <> 0
              OR S.SCRAP_QTY <> 0
              OR S.SCOPE_TYPE COLLATE Latin1_General_100_BIN2
                   <> N''Other'' COLLATE Latin1_General_100_BIN2
              OR DATALENGTH(CONVERT(NVARCHAR(MAX), S.SCOPE_TYPE))
                   <> DATALENGTH(N''Other'')
              OR S.EQUIPMENT_ID IS NULL
              OR S.EQUIPMENT_ID COLLATE Latin1_General_100_BIN2 <> I.EQUIPMENT_ID
              OR DATALENGTH(CONVERT(NVARCHAR(MAX), S.EQUIPMENT_ID))
                   <> DATALENGTH(CONVERT(NVARCHAR(MAX), I.EQUIPMENT_ID))
              OR S.PROCESS_ID IS NULL
              OR S.PROCESS_ID COLLATE Latin1_General_100_BIN2
                   <> I.OPERATION_KEY COLLATE Latin1_General_100_BIN2
              OR DATALENGTH(CONVERT(NVARCHAR(MAX), S.PROCESS_ID))
                   <> DATALENGTH(CONVERT(NVARCHAR(MAX), I.OPERATION_KEY))
              OR S.TARGET_ID IS NULL
              OR S.TARGET_ID COLLATE Latin1_General_100_BIN2 <> I.PAIR_RUN_ID
              OR DATALENGTH(CONVERT(NVARCHAR(MAX), S.TARGET_ID))
                   <> DATALENGTH(CONVERT(NVARCHAR(MAX), I.PAIR_RUN_ID))
              OR S.RECIPE_ID IS NULL
              OR S.RECIPE_ID COLLATE Latin1_General_100_BIN2 <> I.RECIPE_ID
              OR DATALENGTH(CONVERT(NVARCHAR(MAX), S.RECIPE_ID))
                   <> DATALENGTH(CONVERT(NVARCHAR(MAX), I.RECIPE_ID))
              OR S.RECIPE_VERSION IS NULL
              OR S.RECIPE_VERSION <> I.RECIPE_VERSION
              OR I.BASELINE_VERSION_NO <> S.VERSION_NO
              OR I.LAST_APPLIED_VERSION_NO <> S.VERSION_NO
              OR EXISTS (SELECT 1 FROM POM_WORK_SCOPE_EXECUTION E WITH (HOLDLOCK)
                          WHERE E.WORK_SCOPE_ID = I.WORK_SCOPE_ID)))
        THROW 51553, ''POM projection authority requires an exact pristine WorkScope'', 1;
END');

EXEC(N'CREATE TRIGGER TR_RMS_CANONICAL_RECIPE_EXECUTION_APPEND_ONLY
ON RMS_CANONICAL_RECIPE_EXECUTION_EVIDENCE AFTER UPDATE, DELETE AS
BEGIN
  SET NOCOUNT ON;
  THROW 51560, ''Trusted authority evidence is append-only'', 1;
END');
EXEC(N'CREATE TRIGGER TR_SYS_RELEASED_PROGRAM_ARTIFACT_APPEND_ONLY
ON SYS_RELEASED_PROGRAM_ARTIFACT AFTER UPDATE, DELETE AS
BEGIN
  SET NOCOUNT ON;
  THROW 51560, ''Trusted authority evidence is append-only'', 1;
END');
EXEC(N'CREATE TRIGGER TR_SYS_RELEASED_PROGRAM_ARTIFACT_REVOCATION_APPEND_ONLY
ON SYS_RELEASED_PROGRAM_ARTIFACT_REVOCATION AFTER UPDATE, DELETE AS
BEGIN
  SET NOCOUNT ON;
  THROW 51560, ''Trusted authority evidence is append-only'', 1;
END');
EXEC(N'CREATE TRIGGER TR_POM_WORK_SCOPE_PROJECTION_AUTHORITY_TRUST_STATE_APPEND_ONLY
ON POM_WORK_SCOPE_PROJECTION_AUTHORITY_TRUST_STATE AFTER UPDATE, DELETE AS
BEGIN
  SET NOCOUNT ON;
  THROW 51565, ''Projection authority trust state is immutable'', 1;
END');

EXEC(N'CREATE TRIGGER TR_RMS_CANONICAL_RECIPE_EXECUTION_PRISTINE
ON RMS_CANONICAL_RECIPE_EXECUTION_EVIDENCE AFTER INSERT AS
BEGIN
  SET NOCOUNT ON;
  IF EXISTS (SELECT 1 FROM inserted I LEFT JOIN RMS_RECIPE_EXECUTION_SNAPSHOT S
      ON S.EXECUTION_ID COLLATE Latin1_General_100_BIN2
           = I.EXECUTION_ID COLLATE Latin1_General_100_BIN2
     AND DATALENGTH(CONVERT(NVARCHAR(MAX), S.EXECUTION_ID))
           = DATALENGTH(CONVERT(NVARCHAR(MAX), I.EXECUTION_ID))
      WHERE S.EXECUTION_ID IS NULL
         OR S.WORK_SCOPE_ID IS NULL
         OR S.WORK_SCOPE_ID COLLATE Latin1_General_100_BIN2
              <> I.WORK_SCOPE_ID COLLATE Latin1_General_100_BIN2
         OR DATALENGTH(CONVERT(NVARCHAR(MAX), S.WORK_SCOPE_ID))
              <> DATALENGTH(CONVERT(NVARCHAR(MAX), I.WORK_SCOPE_ID))
         OR S.EQUIPMENT_ID COLLATE Latin1_General_100_BIN2 <> I.EQUIPMENT_ID
         OR DATALENGTH(CONVERT(NVARCHAR(MAX), S.EQUIPMENT_ID))
              <> DATALENGTH(CONVERT(NVARCHAR(MAX), I.EQUIPMENT_ID))
         OR S.PROCESS_ID IS NULL
         OR S.PROCESS_ID COLLATE Latin1_General_100_BIN2
              <> I.OPERATION_KEY COLLATE Latin1_General_100_BIN2
         OR DATALENGTH(CONVERT(NVARCHAR(MAX), S.PROCESS_ID))
              <> DATALENGTH(CONVERT(NVARCHAR(MAX), I.OPERATION_KEY))
         OR S.RECIPE_ID COLLATE Latin1_General_100_BIN2 <> I.RECIPE_ID
         OR DATALENGTH(CONVERT(NVARCHAR(MAX), S.RECIPE_ID))
              <> DATALENGTH(CONVERT(NVARCHAR(MAX), I.RECIPE_ID))
         OR S.RECIPE_VERSION <> I.RECIPE_VERSION)
    THROW 51561, ''Canonical recipe evidence must bind an exact V113 execution'', 1;
END');

EXEC(N'CREATE TRIGGER TR_POM_WORK_SCOPE_PROJECTION_AUTHORITY_TRUSTED_EVIDENCE
ON POM_WORK_SCOPE_PROJECTION_AUTHORITY AFTER INSERT AS
BEGIN
  SET NOCOUNT ON;

  IF EXISTS (
      SELECT 1 FROM inserted I
      LEFT JOIN RMS_CANONICAL_RECIPE_EXECUTION_EVIDENCE R WITH (UPDLOCK, HOLDLOCK)
        ON R.EXECUTION_ID COLLATE Latin1_General_100_BIN2
             = I.RECIPE_EXECUTION_ID COLLATE Latin1_General_100_BIN2
       AND DATALENGTH(CONVERT(NVARCHAR(MAX), R.EXECUTION_ID))
             = DATALENGTH(CONVERT(NVARCHAR(MAX), I.RECIPE_EXECUTION_ID))
       AND R.WORK_SCOPE_ID COLLATE Latin1_General_100_BIN2
             = I.WORK_SCOPE_ID COLLATE Latin1_General_100_BIN2
       AND DATALENGTH(CONVERT(NVARCHAR(MAX), R.WORK_SCOPE_ID))
             = DATALENGTH(CONVERT(NVARCHAR(MAX), I.WORK_SCOPE_ID))
       AND R.PAIR_RUN_ID COLLATE Latin1_General_100_BIN2
             = I.PAIR_RUN_ID COLLATE Latin1_General_100_BIN2
       AND DATALENGTH(CONVERT(NVARCHAR(MAX), R.PAIR_RUN_ID))
             = DATALENGTH(CONVERT(NVARCHAR(MAX), I.PAIR_RUN_ID))
       AND R.SEQUENCE_RUN_ID COLLATE Latin1_General_100_BIN2
             = I.SEQUENCE_RUN_ID COLLATE Latin1_General_100_BIN2
       AND DATALENGTH(CONVERT(NVARCHAR(MAX), R.SEQUENCE_RUN_ID))
             = DATALENGTH(CONVERT(NVARCHAR(MAX), I.SEQUENCE_RUN_ID))
       AND R.EQUIPMENT_ID COLLATE Latin1_General_100_BIN2
             = I.EQUIPMENT_ID COLLATE Latin1_General_100_BIN2
       AND DATALENGTH(CONVERT(NVARCHAR(MAX), R.EQUIPMENT_ID))
             = DATALENGTH(CONVERT(NVARCHAR(MAX), I.EQUIPMENT_ID))
       AND R.OPERATION_KEY COLLATE Latin1_General_100_BIN2
             = I.OPERATION_KEY COLLATE Latin1_General_100_BIN2
       AND DATALENGTH(CONVERT(NVARCHAR(MAX), R.OPERATION_KEY))
             = DATALENGTH(CONVERT(NVARCHAR(MAX), I.OPERATION_KEY))
       AND R.RECIPE_ID COLLATE Latin1_General_100_BIN2
             = I.RECIPE_ID COLLATE Latin1_General_100_BIN2
       AND DATALENGTH(CONVERT(NVARCHAR(MAX), R.RECIPE_ID))
             = DATALENGTH(CONVERT(NVARCHAR(MAX), I.RECIPE_ID))
       AND R.RECIPE_VERSION = I.RECIPE_VERSION
       AND R.SNAPSHOT_SCHEMA COLLATE Latin1_General_100_BIN2
             = I.RECIPE_SNAPSHOT_SCHEMA COLLATE Latin1_General_100_BIN2
       AND DATALENGTH(CONVERT(NVARCHAR(MAX), R.SNAPSHOT_SCHEMA))
             = DATALENGTH(CONVERT(NVARCHAR(MAX), I.RECIPE_SNAPSHOT_SCHEMA))
       AND R.SNAPSHOT_HASH COLLATE Latin1_General_100_BIN2
             = I.RECIPE_SNAPSHOT_HASH COLLATE Latin1_General_100_BIN2
       AND DATALENGTH(CONVERT(NVARCHAR(MAX), R.SNAPSHOT_HASH))
             = DATALENGTH(CONVERT(NVARCHAR(MAX), I.RECIPE_SNAPSHOT_HASH))
     WHERE R.EXECUTION_ID IS NULL)
    THROW 51562, ''Projection authority requires exact canonical recipe evidence'', 1;

  -- Acquire the immutable artifact row before the revocation key/range.
  IF EXISTS (
      SELECT 1 FROM inserted I
      LEFT JOIN SYS_RELEASED_PROGRAM_ARTIFACT A WITH (UPDLOCK, HOLDLOCK)
        ON A.ARTIFACT_ID COLLATE Latin1_General_100_BIN2
             = I.PROGRAM_ARTIFACT_ID COLLATE Latin1_General_100_BIN2
       AND DATALENGTH(CONVERT(NVARCHAR(MAX), A.ARTIFACT_ID))
             = DATALENGTH(CONVERT(NVARCHAR(MAX), I.PROGRAM_ARTIFACT_ID))
       AND A.EQUIPMENT_ID COLLATE Latin1_General_100_BIN2
             = I.EQUIPMENT_ID COLLATE Latin1_General_100_BIN2
       AND DATALENGTH(CONVERT(NVARCHAR(MAX), A.EQUIPMENT_ID))
             = DATALENGTH(CONVERT(NVARCHAR(MAX), I.EQUIPMENT_ID))
       AND A.OPERATION_KEY COLLATE Latin1_General_100_BIN2
             = I.OPERATION_KEY COLLATE Latin1_General_100_BIN2
       AND DATALENGTH(CONVERT(NVARCHAR(MAX), A.OPERATION_KEY))
             = DATALENGTH(CONVERT(NVARCHAR(MAX), I.OPERATION_KEY))
       AND A.PROGRAM_SCHEMA COLLATE Latin1_General_100_BIN2
             = I.PROGRAM_SCHEMA COLLATE Latin1_General_100_BIN2
       AND DATALENGTH(CONVERT(NVARCHAR(MAX), A.PROGRAM_SCHEMA))
             = DATALENGTH(CONVERT(NVARCHAR(MAX), I.PROGRAM_SCHEMA))
       AND A.PROGRAM_HASH COLLATE Latin1_General_100_BIN2
             = I.PROGRAM_HASH COLLATE Latin1_General_100_BIN2
       AND DATALENGTH(CONVERT(NVARCHAR(MAX), A.PROGRAM_HASH))
             = DATALENGTH(CONVERT(NVARCHAR(MAX), I.PROGRAM_HASH))
       AND A.BOUND_RECIPE_SNAPSHOT_SCHEMA COLLATE Latin1_General_100_BIN2
             = I.RECIPE_SNAPSHOT_SCHEMA COLLATE Latin1_General_100_BIN2
       AND DATALENGTH(CONVERT(NVARCHAR(MAX), A.BOUND_RECIPE_SNAPSHOT_SCHEMA))
             = DATALENGTH(CONVERT(NVARCHAR(MAX), I.RECIPE_SNAPSHOT_SCHEMA))
       AND A.BOUND_RECIPE_SNAPSHOT_HASH COLLATE Latin1_General_100_BIN2
             = I.RECIPE_SNAPSHOT_HASH COLLATE Latin1_General_100_BIN2
       AND DATALENGTH(CONVERT(NVARCHAR(MAX), A.BOUND_RECIPE_SNAPSHOT_HASH))
             = DATALENGTH(CONVERT(NVARCHAR(MAX), I.RECIPE_SNAPSHOT_HASH))
     WHERE A.ARTIFACT_ID IS NULL)
    THROW 51562, ''Projection authority requires an exact released program artifact'', 1;

  IF EXISTS (
      SELECT 1 FROM inserted I
      JOIN SYS_RELEASED_PROGRAM_ARTIFACT_REVOCATION V WITH (UPDLOCK, HOLDLOCK)
        ON V.ARTIFACT_ID COLLATE Latin1_General_100_BIN2
             = I.PROGRAM_ARTIFACT_ID COLLATE Latin1_General_100_BIN2
       AND DATALENGTH(CONVERT(NVARCHAR(MAX), V.ARTIFACT_ID))
             = DATALENGTH(CONVERT(NVARCHAR(MAX), I.PROGRAM_ARTIFACT_ID)))
    THROW 51563, ''Revoked program artifacts cannot acquire new projection authority'', 1;
END');
-- SQLITE-OMIT-END

INSERT INTO POM_WORK_SCOPE_PROJECTION_AUTHORITY_TRUST_STATE
    (STATE_ID, TRUST_VERSION, APPLIED_AT, APPLIED_BY)
SELECT 'V159_TRUSTED_AUTHORITY', 159, GETUTCDATE(), 'V159'
 WHERE NOT EXISTS (
    SELECT 1 FROM POM_WORK_SCOPE_PROJECTION_AUTHORITY_TRUST_STATE
     WHERE STATE_ID = 'V159_TRUSTED_AUTHORITY');
