-- Explicit business scope grants. No plant claim or default ADMIN membership is seeded.
-- SYS_USER remains the owner of login identity; this GUID mapping survives revocation/reactivation.
CREATE TABLE SYS_BUSINESS_IDENTITY (
    USER_ID NVARCHAR(50) NOT NULL,
    BUSINESS_USER_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CREATED_BY NVARCHAR(50) NOT NULL,
    CREATED_AT DATETIME2 NOT NULL,
    CONSTRAINT PK_SYS_BUSINESS_IDENTITY PRIMARY KEY (USER_ID),
    CONSTRAINT UQ_SYS_BUSINESS_IDENTITY_GUID UNIQUE (BUSINESS_USER_ID),
    CONSTRAINT FK_SYS_BUSINESS_IDENTITY_USER FOREIGN KEY (USER_ID) REFERENCES SYS_USER (USER_ID),
    CONSTRAINT CK_SYS_BUSINESS_IDENTITY_GUID CHECK (LEN(BUSINESS_USER_ID)=36 AND BUSINESS_USER_ID<>'00000000-0000-0000-0000-000000000000')
);

CREATE TABLE SYS_BUSINESS_MEMBERSHIP (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    USER_ID NVARCHAR(50) NOT NULL,
    IS_ACTIVE BIT NOT NULL,
    PERMISSIONS NVARCHAR(1000) NOT NULL,
    MEMBERSHIP_VERSION BIGINT NOT NULL,
    UPDATED_BY NVARCHAR(50) NOT NULL,
    UPDATED_AT DATETIME2 NOT NULL,
    CONSTRAINT PK_SYS_BUSINESS_MEMBERSHIP PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, USER_ID),
    CONSTRAINT FK_SYS_BUSINESS_MEMBERSHIP_IDENTITY FOREIGN KEY (USER_ID) REFERENCES SYS_BUSINESS_IDENTITY (USER_ID),
    CONSTRAINT CK_SYS_BUSINESS_MEMBERSHIP_VERSION CHECK (MEMBERSHIP_VERSION>0),
    CONSTRAINT CK_SYS_BUSINESS_MEMBERSHIP_ACTIVE CHECK (IS_ACTIVE IN (0,1)),
    CONSTRAINT CK_SYS_BUSINESS_MEMBERSHIP_SCOPE CHECK (
        LEN(TENANT_ID)=36 AND LEN(ORGANIZATION_ID)=36
        AND TENANT_ID<>'00000000-0000-0000-0000-000000000000'
        AND ORGANIZATION_ID<>'00000000-0000-0000-0000-000000000000')
);

CREATE TABLE SYS_BUSINESS_MEMBERSHIP_AUDIT (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    USER_ID NVARCHAR(50) NOT NULL,
    MEMBERSHIP_VERSION BIGINT NOT NULL,
    IS_ACTIVE BIT NOT NULL,
    PERMISSIONS NVARCHAR(1000) NOT NULL,
    CHANGED_BY NVARCHAR(50) NOT NULL,
    CHANGED_AT DATETIME2 NOT NULL,
    CONSTRAINT PK_SYS_BUSINESS_MEMBERSHIP_AUDIT PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, USER_ID, MEMBERSHIP_VERSION),
    CONSTRAINT FK_SYS_BUSINESS_MEMBERSHIP_AUDIT_MEMBER FOREIGN KEY (TENANT_ID, ORGANIZATION_ID, USER_ID)
        REFERENCES SYS_BUSINESS_MEMBERSHIP (TENANT_ID, ORGANIZATION_ID, USER_ID),
    CONSTRAINT CK_SYS_BUSINESS_MEMBERSHIP_AUDIT_VERSION CHECK (MEMBERSHIP_VERSION>0),
    CONSTRAINT CK_SYS_BUSINESS_MEMBERSHIP_AUDIT_ACTIVE CHECK (IS_ACTIVE IN (0,1))
);
