-- Shared assets are separate from manufacturing LOT inventory and equipment runtime control.
-- No business scope, grant or identity is inferred from a request plant claim or seeded by default.
CREATE TABLE IVT_BUSINESS_SCOPE (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    PLANT_ID NVARCHAR(50) NOT NULL,
    VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    IS_ACTIVE BIT NOT NULL,
    UPDATED_BY NVARCHAR(50) NOT NULL,
    UPDATED_AT DATETIME2 NOT NULL,
    CONSTRAINT PK_IVT_BUSINESS_SCOPE PRIMARY KEY (TENANT_ID, ORGANIZATION_ID),
    CONSTRAINT UQ_IVT_BUSINESS_SCOPE_PLANT UNIQUE (PLANT_ID),
    CONSTRAINT FK_IVT_BUSINESS_SCOPE_PLANT FOREIGN KEY (PLANT_ID) REFERENCES MDM_PLANT (PLANT_ID),
    CONSTRAINT CK_IVT_BUSINESS_SCOPE_ACTIVE CHECK (IS_ACTIVE IN (0,1))
);

-- One stable employee GUID per real MES worker, retained across transfers and deactivation.
CREATE TABLE IVT_WORKER_IDENTITY (
    WORKER_ID NVARCHAR(50) NOT NULL,
    EMPLOYEE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CONSTRAINT PK_IVT_WORKER_IDENTITY PRIMARY KEY (WORKER_ID),
    CONSTRAINT UQ_IVT_WORKER_IDENTITY_EMPLOYEE UNIQUE (EMPLOYEE_ID),
    CONSTRAINT FK_IVT_WORKER_IDENTITY_WORKER FOREIGN KEY (WORKER_ID) REFERENCES MDM_WORKER (WORKER_ID)
);

CREATE TABLE IVT_BUSINESS_SCOPE_AUDIT (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    PLANT_ID NVARCHAR(50) NOT NULL,
    IS_ACTIVE BIT NOT NULL,
    CHANGED_BY NVARCHAR(50) NOT NULL,
    CHANGED_AT DATETIME2 NOT NULL,
    CONSTRAINT PK_IVT_BUSINESS_SCOPE_AUDIT PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, VERSION),
    CONSTRAINT FK_IVT_BUSINESS_SCOPE_AUDIT_SCOPE FOREIGN KEY (TENANT_ID, ORGANIZATION_ID)
        REFERENCES IVT_BUSINESS_SCOPE (TENANT_ID, ORGANIZATION_ID)
);

CREATE TABLE IVT_SHARED_EQUIPMENT (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    EQUIPMENT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CODE NVARCHAR(80) COLLATE Latin1_General_100_BIN2 NOT NULL,
    NAME NVARCHAR(255) NOT NULL,
    CAPACITY INT NOT NULL,
    REQUIRES_APPROVAL BIT NOT NULL,
    IS_ACTIVE BIT NOT NULL,
    CONSTRAINT PK_IVT_SHARED_EQUIPMENT PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, EQUIPMENT_ID),
    CONSTRAINT UQ_IVT_SHARED_EQUIPMENT_CODE UNIQUE (TENANT_ID, ORGANIZATION_ID, CODE),
    CONSTRAINT FK_IVT_SHARED_EQUIPMENT_SCOPE FOREIGN KEY (TENANT_ID, ORGANIZATION_ID)
        REFERENCES IVT_BUSINESS_SCOPE (TENANT_ID, ORGANIZATION_ID),
    CONSTRAINT CK_IVT_SHARED_EQUIPMENT_CAPACITY CHECK (CAPACITY>0),
    CONSTRAINT CK_IVT_SHARED_EQUIPMENT_FLAGS CHECK (IS_ACTIVE IN (0,1) AND REQUIRES_APPROVAL IN (0,1))
);

-- Stable creation receipt survives code/name changes and reconciles a lost response without a second asset.
CREATE TABLE IVT_SHARED_EQUIPMENT_CREATION (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    OPERATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    EQUIPMENT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    REQUESTED_BY VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CODE NVARCHAR(80) COLLATE Latin1_General_100_BIN2 NOT NULL,
    NAME NVARCHAR(255) NOT NULL,
    CAPACITY INT NOT NULL,
    REQUIRES_APPROVAL BIT NOT NULL,
    CONSTRAINT PK_IVT_SHARED_EQUIPMENT_CREATION PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, OPERATION_ID),
    CONSTRAINT FK_IVT_SHARED_EQUIPMENT_CREATION_ASSET FOREIGN KEY (TENANT_ID, ORGANIZATION_ID, EQUIPMENT_ID)
        REFERENCES IVT_SHARED_EQUIPMENT (TENANT_ID, ORGANIZATION_ID, EQUIPMENT_ID),
    CONSTRAINT FK_IVT_SHARED_EQUIPMENT_CREATION_USER FOREIGN KEY (REQUESTED_BY) REFERENCES SYS_BUSINESS_IDENTITY (BUSINESS_USER_ID)
);

CREATE TABLE IVT_SHARED_BOOKING (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    BOOKING_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    EQUIPMENT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    EMPLOYEE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    START_TICKS BIGINT NOT NULL,
    END_TICKS BIGINT NOT NULL,
    QUANTITY INT NOT NULL,
    REQUESTED_BY VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    STATE INT NOT NULL,
    RETURNED_TICKS BIGINT NULL,
    CONSTRAINT PK_IVT_SHARED_BOOKING PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, BOOKING_ID),
    CONSTRAINT FK_IVT_SHARED_BOOKING_EQUIPMENT FOREIGN KEY (TENANT_ID, ORGANIZATION_ID, EQUIPMENT_ID)
        REFERENCES IVT_SHARED_EQUIPMENT (TENANT_ID, ORGANIZATION_ID, EQUIPMENT_ID),
    CONSTRAINT FK_IVT_SHARED_BOOKING_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES IVT_WORKER_IDENTITY (EMPLOYEE_ID),
    CONSTRAINT FK_IVT_SHARED_BOOKING_USER FOREIGN KEY (REQUESTED_BY) REFERENCES SYS_BUSINESS_IDENTITY (BUSINESS_USER_ID),
    CONSTRAINT CK_IVT_SHARED_BOOKING_QUANTITY CHECK (QUANTITY>0),
    CONSTRAINT CK_IVT_SHARED_BOOKING_INTERVAL CHECK (START_TICKS>0 AND END_TICKS>START_TICKS AND END_TICKS<=3155378975999999999),
    CONSTRAINT CK_IVT_SHARED_BOOKING_STATE CHECK (STATE IN (0,1,2,3,4,5)),
    CONSTRAINT CK_IVT_SHARED_BOOKING_RETURN CHECK (
        (STATE=3 AND RETURNED_TICKS IS NOT NULL AND RETURNED_TICKS>=START_TICKS AND RETURNED_TICKS<=3155378975999999999)
        OR (STATE<>3 AND RETURNED_TICKS IS NULL))
);
CREATE INDEX IX_IVT_SHARED_BOOKING_CAPACITY ON IVT_SHARED_BOOKING
    (TENANT_ID, ORGANIZATION_ID, EQUIPMENT_ID, STATE, START_TICKS);

CREATE TABLE IVT_SHARED_EQUIPMENT_AUDIT (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    AUDIT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    USER_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    RESOURCE_TYPE NVARCHAR(40) NOT NULL,
    RESOURCE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    OPERATION NVARCHAR(40) NOT NULL,
    PREVIOUS_VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NULL,
    VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    AT_TICKS BIGINT NOT NULL,
    CONSTRAINT PK_IVT_SHARED_EQUIPMENT_AUDIT PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, AUDIT_ID),
    CONSTRAINT FK_IVT_SHARED_EQUIPMENT_AUDIT_SCOPE FOREIGN KEY (TENANT_ID, ORGANIZATION_ID)
        REFERENCES IVT_BUSINESS_SCOPE (TENANT_ID, ORGANIZATION_ID),
    CONSTRAINT FK_IVT_SHARED_EQUIPMENT_AUDIT_USER FOREIGN KEY (USER_ID) REFERENCES SYS_BUSINESS_IDENTITY (BUSINESS_USER_ID)
);
