-- Business stock is explicitly enrolled and does not replace the manufacturing LOT/MRP ledger.
-- Plain canonical decimal strings preserve .NET decimal exactly on SQL Server and SQLite.
-- The IVT adapter validates quantities and updates all balances/ledger/reservations/audit atomically.
CREATE TABLE IVT_STOCK_PRODUCT (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    PRODUCT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VARIANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    MASTER_PRODUCT_ID NVARCHAR(50) NOT NULL,
    UNIT NVARCHAR(40) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CONSTRAINT PK_IVT_STOCK_PRODUCT PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, PRODUCT_ID),
    CONSTRAINT UQ_IVT_STOCK_PRODUCT_VARIANT UNIQUE (TENANT_ID, ORGANIZATION_ID, VARIANT_ID),
    CONSTRAINT UQ_IVT_STOCK_PRODUCT_MASTER UNIQUE (TENANT_ID, ORGANIZATION_ID, MASTER_PRODUCT_ID),
    CONSTRAINT FK_IVT_STOCK_PRODUCT_SCOPE FOREIGN KEY (TENANT_ID, ORGANIZATION_ID)
        REFERENCES IVT_BUSINESS_SCOPE (TENANT_ID, ORGANIZATION_ID),
    CONSTRAINT FK_IVT_STOCK_PRODUCT_MASTER FOREIGN KEY (MASTER_PRODUCT_ID) REFERENCES MDM_PRODUCT (PRODUCT_ID)
);

CREATE TABLE IVT_STOCK_WAREHOUSE (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    WAREHOUSE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CODE NVARCHAR(80) COLLATE Latin1_General_100_BIN2 NOT NULL,
    NAME NVARCHAR(255) NOT NULL,
    IS_ACTIVE BIT NOT NULL,
    CONSTRAINT PK_IVT_STOCK_WAREHOUSE PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, WAREHOUSE_ID),
    CONSTRAINT UQ_IVT_STOCK_WAREHOUSE_CODE UNIQUE (TENANT_ID, ORGANIZATION_ID, CODE),
    CONSTRAINT FK_IVT_STOCK_WAREHOUSE_SCOPE FOREIGN KEY (TENANT_ID, ORGANIZATION_ID)
        REFERENCES IVT_BUSINESS_SCOPE (TENANT_ID, ORGANIZATION_ID),
    CONSTRAINT CK_IVT_STOCK_WAREHOUSE_ACTIVE CHECK (IS_ACTIVE IN (0,1))
);

CREATE TABLE IVT_STOCK_WAREHOUSE_CREATION (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    OPERATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    WAREHOUSE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    REQUESTED_BY VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CODE NVARCHAR(80) COLLATE Latin1_General_100_BIN2 NOT NULL,
    NAME NVARCHAR(255) NOT NULL,
    CONSTRAINT PK_IVT_STOCK_WAREHOUSE_CREATION PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, OPERATION_ID),
    CONSTRAINT FK_IVT_STOCK_WAREHOUSE_CREATION_WAREHOUSE FOREIGN KEY (TENANT_ID, ORGANIZATION_ID, WAREHOUSE_ID)
        REFERENCES IVT_STOCK_WAREHOUSE (TENANT_ID, ORGANIZATION_ID, WAREHOUSE_ID),
    CONSTRAINT FK_IVT_STOCK_WAREHOUSE_CREATION_USER FOREIGN KEY (REQUESTED_BY) REFERENCES SYS_BUSINESS_IDENTITY (BUSINESS_USER_ID)
);

CREATE TABLE IVT_STOCK_BALANCE (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    BALANCE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VARIANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    WAREHOUSE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ON_HAND VARCHAR(40) COLLATE Latin1_General_100_BIN2 NOT NULL,
    RESERVED VARCHAR(40) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CONSTRAINT PK_IVT_STOCK_BALANCE PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, BALANCE_ID),
    CONSTRAINT UQ_IVT_STOCK_BALANCE_LOCATION UNIQUE (TENANT_ID, ORGANIZATION_ID, VARIANT_ID, WAREHOUSE_ID),
    CONSTRAINT FK_IVT_STOCK_BALANCE_VARIANT FOREIGN KEY (TENANT_ID, ORGANIZATION_ID, VARIANT_ID)
        REFERENCES IVT_STOCK_PRODUCT (TENANT_ID, ORGANIZATION_ID, VARIANT_ID),
    CONSTRAINT FK_IVT_STOCK_BALANCE_WAREHOUSE FOREIGN KEY (TENANT_ID, ORGANIZATION_ID, WAREHOUSE_ID)
        REFERENCES IVT_STOCK_WAREHOUSE (TENANT_ID, ORGANIZATION_ID, WAREHOUSE_ID),
    CONSTRAINT CK_IVT_STOCK_BALANCE_NONNEGATIVE CHECK (ON_HAND NOT LIKE '-%' AND RESERVED NOT LIKE '-%' AND LEN(ON_HAND)>0 AND LEN(RESERVED)>0)
);

CREATE TABLE IVT_STOCK_MOVEMENT (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    MOVEMENT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    OPERATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VARIANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    KIND INT NOT NULL,
    QUANTITY VARCHAR(40) COLLATE Latin1_General_100_BIN2 NOT NULL,
    FROM_WAREHOUSE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NULL,
    TO_WAREHOUSE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NULL,
    REFERENCE NVARCHAR(255) NOT NULL,
    CREATED_BY VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    DELTAS_JSON NVARCHAR(400) NOT NULL,
    REVERSAL_OF_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NULL,
    REVERSED_BY_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NULL,
    AT_TICKS BIGINT NOT NULL,
    CONSTRAINT PK_IVT_STOCK_MOVEMENT PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, MOVEMENT_ID),
    CONSTRAINT UQ_IVT_STOCK_MOVEMENT_OPERATION UNIQUE (TENANT_ID, ORGANIZATION_ID, OPERATION_ID),
    CONSTRAINT FK_IVT_STOCK_MOVEMENT_VARIANT FOREIGN KEY (TENANT_ID, ORGANIZATION_ID, VARIANT_ID)
        REFERENCES IVT_STOCK_PRODUCT (TENANT_ID, ORGANIZATION_ID, VARIANT_ID),
    CONSTRAINT FK_IVT_STOCK_MOVEMENT_FROM FOREIGN KEY (TENANT_ID, ORGANIZATION_ID, FROM_WAREHOUSE_ID)
        REFERENCES IVT_STOCK_WAREHOUSE (TENANT_ID, ORGANIZATION_ID, WAREHOUSE_ID),
    CONSTRAINT FK_IVT_STOCK_MOVEMENT_TO FOREIGN KEY (TENANT_ID, ORGANIZATION_ID, TO_WAREHOUSE_ID)
        REFERENCES IVT_STOCK_WAREHOUSE (TENANT_ID, ORGANIZATION_ID, WAREHOUSE_ID),
    CONSTRAINT FK_IVT_STOCK_MOVEMENT_ORIGINAL FOREIGN KEY (TENANT_ID, ORGANIZATION_ID, REVERSAL_OF_ID)
        REFERENCES IVT_STOCK_MOVEMENT (TENANT_ID, ORGANIZATION_ID, MOVEMENT_ID),
    CONSTRAINT FK_IVT_STOCK_MOVEMENT_REVERSED_BY FOREIGN KEY (TENANT_ID, ORGANIZATION_ID, REVERSED_BY_ID)
        REFERENCES IVT_STOCK_MOVEMENT (TENANT_ID, ORGANIZATION_ID, MOVEMENT_ID),
    CONSTRAINT FK_IVT_STOCK_MOVEMENT_USER FOREIGN KEY (CREATED_BY) REFERENCES SYS_BUSINESS_IDENTITY (BUSINESS_USER_ID),
    CONSTRAINT CK_IVT_STOCK_MOVEMENT_KIND CHECK (KIND IN (0,1,2,3,4)),
    CONSTRAINT CK_IVT_STOCK_MOVEMENT_REVERSAL CHECK (
        (KIND=4 AND REVERSAL_OF_ID IS NOT NULL AND REVERSED_BY_ID IS NULL AND REVERSAL_OF_ID<>MOVEMENT_ID)
        OR (KIND<>4 AND REVERSAL_OF_ID IS NULL)),
    CONSTRAINT CK_IVT_STOCK_MOVEMENT_REVERSED_BY CHECK (REVERSED_BY_ID IS NULL OR REVERSED_BY_ID<>MOVEMENT_ID)
);
CREATE UNIQUE INDEX UQ_IVT_STOCK_MOVEMENT_REVERSAL ON IVT_STOCK_MOVEMENT
    (TENANT_ID, ORGANIZATION_ID, REVERSAL_OF_ID) WHERE REVERSAL_OF_ID IS NOT NULL;
CREATE INDEX IX_IVT_STOCK_MOVEMENT_PAGE ON IVT_STOCK_MOVEMENT
    (TENANT_ID, ORGANIZATION_ID, VARIANT_ID, AT_TICKS, MOVEMENT_ID);

CREATE TABLE IVT_STOCK_RESERVATION (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    RESERVATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    OPERATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VARIANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    WAREHOUSE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    QUANTITY VARCHAR(40) COLLATE Latin1_General_100_BIN2 NOT NULL,
    REFERENCE NVARCHAR(255) NOT NULL,
    CREATED_BY VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    STATE INT NOT NULL,
    CONSTRAINT PK_IVT_STOCK_RESERVATION PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, RESERVATION_ID),
    CONSTRAINT UQ_IVT_STOCK_RESERVATION_OPERATION UNIQUE (TENANT_ID, ORGANIZATION_ID, OPERATION_ID),
    CONSTRAINT FK_IVT_STOCK_RESERVATION_VARIANT FOREIGN KEY (TENANT_ID, ORGANIZATION_ID, VARIANT_ID)
        REFERENCES IVT_STOCK_PRODUCT (TENANT_ID, ORGANIZATION_ID, VARIANT_ID),
    CONSTRAINT FK_IVT_STOCK_RESERVATION_WAREHOUSE FOREIGN KEY (TENANT_ID, ORGANIZATION_ID, WAREHOUSE_ID)
        REFERENCES IVT_STOCK_WAREHOUSE (TENANT_ID, ORGANIZATION_ID, WAREHOUSE_ID),
    CONSTRAINT FK_IVT_STOCK_RESERVATION_USER FOREIGN KEY (CREATED_BY) REFERENCES SYS_BUSINESS_IDENTITY (BUSINESS_USER_ID),
    CONSTRAINT CK_IVT_STOCK_RESERVATION_STATE CHECK (STATE IN (0,1,2)),
    CONSTRAINT CK_IVT_STOCK_RESERVATION_POSITIVE CHECK (QUANTITY<>'0' AND QUANTITY NOT LIKE '-%' AND LEN(QUANTITY)>0)
);

CREATE TABLE IVT_STOCK_AUDIT (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    AUDIT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    USER_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    RESOURCE_TYPE NVARCHAR(40) NOT NULL,
    RESOURCE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    OPERATION NVARCHAR(40) NOT NULL,
    PREVIOUS_VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NULL,
    VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    AT_TICKS BIGINT NOT NULL,
    CONSTRAINT PK_IVT_STOCK_AUDIT PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, AUDIT_ID),
    CONSTRAINT FK_IVT_STOCK_AUDIT_SCOPE FOREIGN KEY (TENANT_ID, ORGANIZATION_ID)
        REFERENCES IVT_BUSINESS_SCOPE (TENANT_ID, ORGANIZATION_ID),
    CONSTRAINT FK_IVT_STOCK_AUDIT_USER FOREIGN KEY (USER_ID) REFERENCES SYS_BUSINESS_IDENTITY (BUSINESS_USER_ID)
);
