-- Stock workflow English resources; Korean text remains in the UI fallbacks.
-- Insert missing keys only, preserving existing values (including empty/custom translations) and MENU_ID.
-- No menu, role, permission or business-data changes.
INSERT INTO SYS_MULTI_LANGUAGE_RESOURCE (RESOURCE_KEY, MENU_ID, LANGUAGE, VALUE)
SELECT seed.RESOURCE_KEY, 'COMMON', 'EnUs', seed.VALUE
FROM (
    SELECT 'inventory.stock.activateWarehouse' AS RESOURCE_KEY, 'Activate warehouse' AS VALUE
    UNION ALL SELECT 'inventory.stock.adjustment', 'Adjustment'
    UNION ALL SELECT 'inventory.stock.changeWarehouseActivity', 'Change warehouse activity'
    UNION ALL SELECT 'inventory.stock.chooseMovement', 'Select movement'
    UNION ALL SELECT 'inventory.stock.chooseProduct', 'Select product'
    UNION ALL SELECT 'inventory.stock.chooseWarehouse', 'Select warehouse'
    UNION ALL SELECT 'inventory.stock.consume', 'Consume reservation'
    UNION ALL SELECT 'inventory.stock.createWarehouse', 'Register warehouse'
    UNION ALL SELECT 'inventory.stock.deactivateWarehouse', 'Deactivate warehouse'
    UNION ALL SELECT 'inventory.stock.fromWarehouse', 'From warehouse'
    UNION ALL SELECT 'inventory.stock.heading', 'Stock actions'
    UNION ALL SELECT 'inventory.stock.invalidInput', 'Check the warehouses for the movement kind, a nonzero quantity with at most 6 decimals, and a reference.'
    UNION ALL SELECT 'inventory.stock.invalidReference', 'Enter a reference of up to 255 characters without surrounding whitespace.'
    UNION ALL SELECT 'inventory.stock.invalidReservation', 'Check the active warehouse, a positive quantity with at most 6 decimals, and a reference.'
    UNION ALL SELECT 'inventory.stock.invalidReservationId', 'The reservation ID must be a GUID.'
    UNION ALL SELECT 'inventory.stock.invalidWarehouse', 'Check the warehouse code (up to 80 characters) and name (up to 255 characters).'
    UNION ALL SELECT 'inventory.stock.issue', 'Issue'
    UNION ALL SELECT 'inventory.stock.kind', 'Movement kind'
    UNION ALL SELECT 'inventory.stock.movement', 'Movement'
    UNION ALL SELECT 'inventory.stock.movementId', 'Movement ID'
    UNION ALL SELECT 'inventory.stock.movementListError', 'The product was selected, but its movement list could not be loaded. Search again.'
    UNION ALL SELECT 'inventory.stock.movementNote', 'Ledger entries of the selected product variant. Warehouses and reversal state are shown by stored identifiers.'
    UNION ALL SELECT 'inventory.stock.movements', 'Movement history'
    UNION ALL SELECT 'inventory.stock.noWarehouse', 'None'
    UNION ALL SELECT 'inventory.stock.open', 'Open'
    UNION ALL SELECT 'inventory.stock.post', 'Post movement'
    UNION ALL SELECT 'inventory.stock.readRequired', 'Selecting a product for a movement or reservation requires stock read permission. Write permission does not grant access to the product list.'
    UNION ALL SELECT 'inventory.stock.readReservation', 'Read reservation'
    UNION ALL SELECT 'inventory.stock.receipt', 'Receipt'
    UNION ALL SELECT 'inventory.stock.reference', 'Reference'
    UNION ALL SELECT 'inventory.stock.release', 'Release reservation'
    UNION ALL SELECT 'inventory.stock.reservation', 'Reservation'
    UNION ALL SELECT 'inventory.stock.reservationActive', 'Active'
    UNION ALL SELECT 'inventory.stock.reservationConsumed', 'Consumed'
    UNION ALL SELECT 'inventory.stock.reservationId', 'Reservation ID'
    UNION ALL SELECT 'inventory.stock.reservationNote', 'No reservation list is provided. Use a reservation registered in this tab or a known reservation ID.'
    UNION ALL SELECT 'inventory.stock.reservationReleased', 'Released'
    UNION ALL SELECT 'inventory.stock.reserve', 'Reserve stock'
    UNION ALL SELECT 'inventory.stock.reversal', 'Reversal'
    UNION ALL SELECT 'inventory.stock.reversalEntry', 'Reversal entry'
    UNION ALL SELECT 'inventory.stock.reversalOf', 'Reversed movement ID'
    UNION ALL SELECT 'inventory.stock.reversalReference', 'Reversal reference'
    UNION ALL SELECT 'inventory.stock.reversalState', 'Reversal state'
    UNION ALL SELECT 'inventory.stock.reverse', 'Reverse movement'
    UNION ALL SELECT 'inventory.stock.reversed', 'Reversed'
    UNION ALL SELECT 'inventory.stock.reversedBy', 'Reversal movement ID'
    UNION ALL SELECT 'inventory.stock.saveWarehouse', 'Save warehouse changes'
    UNION ALL SELECT 'inventory.stock.selectHint', 'Select an enrolled product row below to post movements and reservations.'
    UNION ALL SELECT 'inventory.stock.toWarehouse', 'To warehouse'
    UNION ALL SELECT 'inventory.stock.transfer', 'Transfer'
    UNION ALL SELECT 'inventory.stock.variantId', 'Variant ID'
    UNION ALL SELECT 'inventory.stock.warehouse', 'Warehouse'
    UNION ALL SELECT 'inventory.stock.warehouseCodeConflict', 'A warehouse with this code already exists.'
    UNION ALL SELECT 'inventory.stock.warehouseReadRequired', 'Choosing a warehouse for a movement or reservation requires warehouse read permission. Write and read permissions are independent.'
) seed
WHERE NOT EXISTS (SELECT 1 FROM SYS_MULTI_LANGUAGE_RESOURCE existing
                   WHERE existing.RESOURCE_KEY = seed.RESOURCE_KEY AND existing.LANGUAGE = 'EnUs');
