-- ERP billing: estimates, invoices, their lines, per-kind numbers, payments and audit for one organization scope.
-- Scope is SYS membership only; no plant binding is referenced. Plain canonical decimal strings preserve
-- .NET decimal exactly on SQL Server and SQLite. The ERP adapter validates amounts and writes document,
-- lines, counter, payment and audit rows in one Serializable transaction.
CREATE TABLE ERP_BILLING_CONTACT (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CONTACT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    MASTER_CUSTOMER_ID NVARCHAR(50) NOT NULL,
    CONSTRAINT PK_ERP_BILLING_CONTACT PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, CONTACT_ID),
    CONSTRAINT UQ_ERP_BILLING_CONTACT_MASTER UNIQUE (TENANT_ID, ORGANIZATION_ID, MASTER_CUSTOMER_ID),
    CONSTRAINT FK_ERP_BILLING_CONTACT_MASTER FOREIGN KEY (MASTER_CUSTOMER_ID) REFERENCES MDM_CUSTOMER (CUSTOMER_ID)
);

CREATE TABLE ERP_BILLING_NUMBER (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    KIND INT NOT NULL,
    NEXT_NUMBER BIGINT NOT NULL,
    CONSTRAINT PK_ERP_BILLING_NUMBER PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, KIND),
    CONSTRAINT CK_ERP_BILLING_NUMBER_KIND CHECK (KIND IN (0,1)),
    CONSTRAINT CK_ERP_BILLING_NUMBER_NEXT CHECK (NEXT_NUMBER > 0)
);

CREATE TABLE ERP_BILLING_DOCUMENT (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    DOCUMENT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    OPERATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    KIND INT NOT NULL,
    NUMBER BIGINT NOT NULL,
    STATUS INT NOT NULL,
    CONTACT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    DOCUMENT_DATE VARCHAR(10) COLLATE Latin1_General_100_BIN2 NOT NULL,
    DUE_DATE VARCHAR(10) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CURRENCY VARCHAR(3) COLLATE Latin1_General_100_BIN2 NOT NULL,
    DISCOUNT_TYPE INT NULL,
    DISCOUNT_VALUE VARCHAR(40) COLLATE Latin1_General_100_BIN2 NULL,
    TAX_TYPE INT NULL,
    TAX_VALUE VARCHAR(40) COLLATE Latin1_General_100_BIN2 NULL,
    TAX2_TYPE INT NULL,
    TAX2_VALUE VARCHAR(40) COLLATE Latin1_General_100_BIN2 NULL,
    TERMS NVARCHAR(4000) NULL,
    NOTE NVARCHAR(4000) NULL,
    SUBTOTAL VARCHAR(40) COLLATE Latin1_General_100_BIN2 NOT NULL,
    DISCOUNT_AMOUNT VARCHAR(40) COLLATE Latin1_General_100_BIN2 NOT NULL,
    TAX_AMOUNT VARCHAR(40) COLLATE Latin1_General_100_BIN2 NOT NULL,
    TOTAL VARCHAR(40) COLLATE Latin1_General_100_BIN2 NOT NULL,
    PAID VARCHAR(40) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CREATED_BY VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CONVERTED_FROM_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NULL,
    CONVERTED_TO_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NULL,
    AT_TICKS BIGINT NOT NULL,
    CONSTRAINT PK_ERP_BILLING_DOCUMENT PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, DOCUMENT_ID),
    CONSTRAINT UQ_ERP_BILLING_DOCUMENT_OPERATION UNIQUE (TENANT_ID, ORGANIZATION_ID, OPERATION_ID),
    CONSTRAINT UQ_ERP_BILLING_DOCUMENT_NUMBER UNIQUE (TENANT_ID, ORGANIZATION_ID, KIND, NUMBER),
    CONSTRAINT FK_ERP_BILLING_DOCUMENT_CONTACT FOREIGN KEY (TENANT_ID, ORGANIZATION_ID, CONTACT_ID)
        REFERENCES ERP_BILLING_CONTACT (TENANT_ID, ORGANIZATION_ID, CONTACT_ID),
    CONSTRAINT FK_ERP_BILLING_DOCUMENT_FROM FOREIGN KEY (TENANT_ID, ORGANIZATION_ID, CONVERTED_FROM_ID)
        REFERENCES ERP_BILLING_DOCUMENT (TENANT_ID, ORGANIZATION_ID, DOCUMENT_ID),
    CONSTRAINT FK_ERP_BILLING_DOCUMENT_TO FOREIGN KEY (TENANT_ID, ORGANIZATION_ID, CONVERTED_TO_ID)
        REFERENCES ERP_BILLING_DOCUMENT (TENANT_ID, ORGANIZATION_ID, DOCUMENT_ID),
    CONSTRAINT FK_ERP_BILLING_DOCUMENT_USER FOREIGN KEY (CREATED_BY) REFERENCES SYS_BUSINESS_IDENTITY (BUSINESS_USER_ID),
    CONSTRAINT CK_ERP_BILLING_DOCUMENT_KIND CHECK (KIND IN (0,1)),
    CONSTRAINT CK_ERP_BILLING_DOCUMENT_STATUS CHECK (STATUS BETWEEN 0 AND 7),
    CONSTRAINT CK_ERP_BILLING_DOCUMENT_NUMBER CHECK (NUMBER > 0),
    CONSTRAINT CK_ERP_BILLING_DOCUMENT_LINKS CHECK (
        (CONVERTED_FROM_ID IS NULL OR (KIND=1 AND CONVERTED_FROM_ID<>DOCUMENT_ID))
        AND (CONVERTED_TO_ID IS NULL OR (KIND=0 AND STATUS=2 AND CONVERTED_TO_ID<>DOCUMENT_ID))),
    CONSTRAINT CK_ERP_BILLING_DOCUMENT_AMOUNTS CHECK (
        SUBTOTAL NOT LIKE '-%' AND DISCOUNT_AMOUNT NOT LIKE '-%' AND TAX_AMOUNT NOT LIKE '-%' AND TOTAL NOT LIKE '-%' AND PAID NOT LIKE '-%'
        AND LEN(SUBTOTAL)>0 AND LEN(DISCOUNT_AMOUNT)>0 AND LEN(TAX_AMOUNT)>0 AND LEN(TOTAL)>0 AND LEN(PAID)>0)
);
CREATE UNIQUE INDEX UQ_ERP_BILLING_DOCUMENT_FROM ON ERP_BILLING_DOCUMENT
    (TENANT_ID, ORGANIZATION_ID, CONVERTED_FROM_ID) WHERE CONVERTED_FROM_ID IS NOT NULL;
CREATE UNIQUE INDEX UQ_ERP_BILLING_DOCUMENT_TO ON ERP_BILLING_DOCUMENT
    (TENANT_ID, ORGANIZATION_ID, CONVERTED_TO_ID) WHERE CONVERTED_TO_ID IS NOT NULL;
CREATE INDEX IX_ERP_BILLING_DOCUMENT_PAGE ON ERP_BILLING_DOCUMENT
    (TENANT_ID, ORGANIZATION_ID, KIND, NUMBER);

CREATE TABLE ERP_BILLING_LINE (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    DOCUMENT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    LINE_NO INT NOT NULL,
    DESCRIPTION NVARCHAR(255) NOT NULL,
    UNIT_PRICE VARCHAR(40) COLLATE Latin1_General_100_BIN2 NOT NULL,
    QUANTITY VARCHAR(40) COLLATE Latin1_General_100_BIN2 NOT NULL,
    APPLY_TAX BIT NOT NULL,
    APPLY_DISCOUNT BIT NOT NULL,
    CONSTRAINT PK_ERP_BILLING_LINE PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, DOCUMENT_ID, LINE_NO),
    CONSTRAINT FK_ERP_BILLING_LINE_DOCUMENT FOREIGN KEY (TENANT_ID, ORGANIZATION_ID, DOCUMENT_ID)
        REFERENCES ERP_BILLING_DOCUMENT (TENANT_ID, ORGANIZATION_ID, DOCUMENT_ID),
    CONSTRAINT CK_ERP_BILLING_LINE_NO CHECK (LINE_NO BETWEEN 1 AND 200),
    CONSTRAINT CK_ERP_BILLING_LINE_FLAGS CHECK (APPLY_TAX IN (0,1) AND APPLY_DISCOUNT IN (0,1)),
    CONSTRAINT CK_ERP_BILLING_LINE_AMOUNTS CHECK (UNIT_PRICE NOT LIKE '-%' AND QUANTITY NOT LIKE '-%' AND LEN(UNIT_PRICE)>0 AND LEN(QUANTITY)>0)
);

CREATE TABLE ERP_BILLING_PAYMENT (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    PAYMENT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    OPERATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    DOCUMENT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    AMOUNT VARCHAR(40) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CURRENCY VARCHAR(3) COLLATE Latin1_General_100_BIN2 NOT NULL,
    PAID_AT_TICKS BIGINT NOT NULL,
    METHOD INT NOT NULL,
    REFERENCE NVARCHAR(255) NULL,
    NOTE NVARCHAR(4000) NULL,
    CREATED_BY VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    STATE INT NOT NULL,
    CANCELLED_BY VARCHAR(36) COLLATE Latin1_General_100_BIN2 NULL,
    CANCELLED_AT_TICKS BIGINT NULL,
    CANCEL_REASON NVARCHAR(4000) NULL,
    CONSTRAINT PK_ERP_BILLING_PAYMENT PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, PAYMENT_ID),
    CONSTRAINT UQ_ERP_BILLING_PAYMENT_OPERATION UNIQUE (TENANT_ID, ORGANIZATION_ID, OPERATION_ID),
    CONSTRAINT FK_ERP_BILLING_PAYMENT_DOCUMENT FOREIGN KEY (TENANT_ID, ORGANIZATION_ID, DOCUMENT_ID)
        REFERENCES ERP_BILLING_DOCUMENT (TENANT_ID, ORGANIZATION_ID, DOCUMENT_ID),
    CONSTRAINT FK_ERP_BILLING_PAYMENT_USER FOREIGN KEY (CREATED_BY) REFERENCES SYS_BUSINESS_IDENTITY (BUSINESS_USER_ID),
    CONSTRAINT FK_ERP_BILLING_PAYMENT_CANCELLER FOREIGN KEY (CANCELLED_BY) REFERENCES SYS_BUSINESS_IDENTITY (BUSINESS_USER_ID),
    CONSTRAINT CK_ERP_BILLING_PAYMENT_METHOD CHECK (METHOD BETWEEN 0 AND 5),
    CONSTRAINT CK_ERP_BILLING_PAYMENT_STATE CHECK (STATE IN (0,1)),
    CONSTRAINT CK_ERP_BILLING_PAYMENT_AMOUNT CHECK (AMOUNT NOT LIKE '-%' AND LEN(AMOUNT)>0),
    CONSTRAINT CK_ERP_BILLING_PAYMENT_CANCEL CHECK (
        (STATE=0 AND CANCELLED_BY IS NULL AND CANCELLED_AT_TICKS IS NULL AND CANCEL_REASON IS NULL)
        OR (STATE=1 AND CANCELLED_BY IS NOT NULL AND CANCELLED_AT_TICKS IS NOT NULL))
);
CREATE INDEX IX_ERP_BILLING_PAYMENT_PAGE ON ERP_BILLING_PAYMENT
    (TENANT_ID, ORGANIZATION_ID, DOCUMENT_ID, PAID_AT_TICKS, PAYMENT_ID);

CREATE TABLE ERP_BILLING_AUDIT (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    AUDIT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    USER_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    RESOURCE_TYPE NVARCHAR(40) NOT NULL,
    RESOURCE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    OPERATION NVARCHAR(40) NOT NULL,
    PREVIOUS_VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NULL,
    VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    AT_TICKS BIGINT NOT NULL,
    CONSTRAINT PK_ERP_BILLING_AUDIT PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, AUDIT_ID),
    CONSTRAINT FK_ERP_BILLING_AUDIT_USER FOREIGN KEY (USER_ID) REFERENCES SYS_BUSINESS_IDENTITY (BUSINESS_USER_ID)
);
