-- Billing workspace English resources; Korean text remains in the UI fallbacks.
-- Insert missing keys only, preserving existing values (including empty/custom translations) and MENU_ID.
-- No menu, role, permission or business-data changes.
-- SQL Server Unicode pre-inserts; SQLite uses the portable rows below.
-- SQLITE-OMIT-BEGIN
INSERT INTO SYS_MULTI_LANGUAGE_RESOURCE (RESOURCE_KEY, MENU_ID, LANGUAGE, VALUE)
SELECT seed.RESOURCE_KEY, 'COMMON', 'EnUs', seed.VALUE
FROM (
    SELECT 'billing.invalidDocument' AS RESOURCE_KEY, N'Check the dates (due on or after the document date), the 3-letter currency, each line (description, unit price ≥ 0, positive quantity, at most 6 decimals) and the discount/tax values.' AS VALUE
) seed
WHERE NOT EXISTS (SELECT 1 FROM SYS_MULTI_LANGUAGE_RESOURCE existing
                   WHERE existing.RESOURCE_KEY = seed.RESOURCE_KEY AND existing.LANGUAGE = 'EnUs');
-- SQLITE-OMIT-END

INSERT INTO SYS_MULTI_LANGUAGE_RESOURCE (RESOURCE_KEY, MENU_ID, LANGUAGE, VALUE)
SELECT seed.RESOURCE_KEY, 'COMMON', 'EnUs', seed.VALUE
FROM (
    SELECT 'billing.accept' AS RESOURCE_KEY, 'Accept' AS VALUE
    UNION ALL SELECT 'billing.accepted', 'Accepted'
    UNION ALL SELECT 'billing.addLine', 'Add line'
    UNION ALL SELECT 'billing.allKinds', 'All kinds'
    UNION ALL SELECT 'billing.amount', 'Amount'
    UNION ALL SELECT 'billing.applyDiscount', 'Discount'
    UNION ALL SELECT 'billing.applyTax', 'Tax'
    UNION ALL SELECT 'billing.bankTransfer', 'Bank transfer'
    UNION ALL SELECT 'billing.cancelPayment', 'Cancel payment'
    UNION ALL SELECT 'billing.cancelReason', 'Cancel reason'
    UNION ALL SELECT 'billing.cancelledBy', 'Cancelled'
    UNION ALL SELECT 'billing.cancelledPayment', 'Cancelled'
    UNION ALL SELECT 'billing.cash', 'Cash'
    UNION ALL SELECT 'billing.cheque', 'Cheque'
    UNION ALL SELECT 'billing.chooseContact', 'Select contact'
    UNION ALL SELECT 'billing.chooseDocument', 'Select document'
    UNION ALL SELECT 'billing.choosePayment', 'Select payment'
    UNION ALL SELECT 'billing.chooseScope', 'Select a scope to see the lists and actions you currently have permission for.'
    UNION ALL SELECT 'billing.contact', 'Contact'
    UNION ALL SELECT 'billing.contactNotFound', 'The selected contact is not in this scope. Select a contact again.'
    UNION ALL SELECT 'billing.contactNote', 'Enrolled MDM customers. Name and activity are the current master values; select a row to use it as the contact of a new document.'
    UNION ALL SELECT 'billing.contacts', 'Contacts'
    UNION ALL SELECT 'billing.convert', 'Convert to invoice'
    UNION ALL SELECT 'billing.converted', 'This estimate was already converted to an invoice.'
    UNION ALL SELECT 'billing.convertedFrom', 'Converted from estimate'
    UNION ALL SELECT 'billing.convertedTo', 'Converted to invoice'
    UNION ALL SELECT 'billing.createDocument', 'Create document'
    UNION ALL SELECT 'billing.creditCard', 'Credit card'
    UNION ALL SELECT 'billing.currency', 'Currency (ISO 3 letters)'
    UNION ALL SELECT 'billing.currencyMismatch', 'The payment currency differs from the invoice currency.'
    UNION ALL SELECT 'billing.customerCode', 'Customer code'
    UNION ALL SELECT 'billing.customerInactive', 'An inactive customer cannot be enrolled as a contact.'
    UNION ALL SELECT 'billing.customerNotFound', 'The customer code was not found.'
    UNION ALL SELECT 'billing.debit', 'Debit'
    UNION ALL SELECT 'billing.decide', 'Decide estimate'
    UNION ALL SELECT 'billing.decision', 'Decision'
    UNION ALL SELECT 'billing.description', 'Description'
    UNION ALL SELECT 'billing.discount', 'Discount'
    UNION ALL SELECT 'billing.documentDate', 'Document date'
    UNION ALL SELECT 'billing.documentRefreshError', 'The payment was saved, but the document''s current state could not be re-read. Read the current state.'
    UNION ALL SELECT 'billing.documents', 'Estimates and invoices'
    UNION ALL SELECT 'billing.draft', 'Draft'
    UNION ALL SELECT 'billing.due', 'Due'
    UNION ALL SELECT 'billing.dueDate', 'Due date'
    UNION ALL SELECT 'billing.edit', 'Edit document'
    UNION ALL SELECT 'billing.enrollContact', 'Enroll contact'
    UNION ALL SELECT 'billing.enrollCustomer', 'Enroll a contact by MDM customer code'
    UNION ALL SELECT 'billing.estimate', 'Estimate'
    UNION ALL SELECT 'billing.flat', 'Flat'
    UNION ALL SELECT 'billing.fullyPaid', 'Fully paid'
    UNION ALL SELECT 'billing.hasPayments', 'An invoice with recorded payments cannot be voided. Cancel its payments first.'
    UNION ALL SELECT 'billing.heading', 'Billing actions'
    UNION ALL SELECT 'billing.intro', 'Choose an accessible organization to browse and write contacts, estimates, invoices and payments.'
    UNION ALL SELECT 'billing.invalidCustomer', 'Enter a customer code of up to 50 characters without surrounding whitespace.'
    UNION ALL SELECT 'billing.invalidPayment', 'Check a positive amount with at most 6 decimals, the method, the UTC paid time and a reference of up to 255 characters.'
    UNION ALL SELECT 'billing.invoice', 'Invoice'
    UNION ALL SELECT 'billing.kind', 'Kind'
    UNION ALL SELECT 'billing.lines', 'Lines'
    UNION ALL SELECT 'billing.method', 'Method'
    UNION ALL SELECT 'billing.newEstimate', 'New estimate'
    UNION ALL SELECT 'billing.newInvoice', 'New invoice'
    UNION ALL SELECT 'billing.noReadAccess', 'This scope is accessible, but you currently have no list-reading permission (billing.read).'
    UNION ALL SELECT 'billing.noScopes', 'No billing scopes are currently accessible.'
    UNION ALL SELECT 'billing.none', 'None'
    UNION ALL SELECT 'billing.note', 'Note'
    UNION ALL SELECT 'billing.number', 'Number'
    UNION ALL SELECT 'billing.online', 'Online'
    UNION ALL SELECT 'billing.overpaid', 'Overpaid'
    UNION ALL SELECT 'billing.paid', 'Paid'
    UNION ALL SELECT 'billing.paidAt', 'Paid at (UTC)'
    UNION ALL SELECT 'billing.partiallyPaid', 'Partially paid'
    UNION ALL SELECT 'billing.payment', 'Payment'
    UNION ALL SELECT 'billing.paymentListError', 'The document was selected, but its payment list could not be loaded. Search again.'
    UNION ALL SELECT 'billing.paymentListNote', 'Payments of the selected document, including cancelled ones. Select a row to cancel it.'
    UNION ALL SELECT 'billing.payments', 'Payments'
    UNION ALL SELECT 'billing.percent', 'Percent (%)'
    UNION ALL SELECT 'billing.recordPayment', 'Record payment'
    UNION ALL SELECT 'billing.recorded', 'Recorded'
    UNION ALL SELECT 'billing.reference', 'Reference'
    UNION ALL SELECT 'billing.reject', 'Reject'
    UNION ALL SELECT 'billing.rejected', 'Rejected'
    UNION ALL SELECT 'billing.removeLine', 'Remove line'
    UNION ALL SELECT 'billing.saveDocument', 'Save document changes'
    UNION ALL SELECT 'billing.scopes', 'My billing scopes'
    UNION ALL SELECT 'billing.selectedContact', 'Selected contact'
    UNION ALL SELECT 'billing.send', 'Mark sent'
    UNION ALL SELECT 'billing.sent', 'Sent'
    UNION ALL SELECT 'billing.statusConflict', 'This action is not allowed in the document''s current status. Read the current state.'
    UNION ALL SELECT 'billing.subtotal', 'Subtotal'
    UNION ALL SELECT 'billing.tax', 'Tax'
    UNION ALL SELECT 'billing.tax2', 'Second tax'
    UNION ALL SELECT 'billing.terms', 'Terms'
    UNION ALL SELECT 'billing.title', 'Billing workspace'
    UNION ALL SELECT 'billing.total', 'Total'
    UNION ALL SELECT 'billing.totalsNote', 'Subtotal, discount, tax and total are computed by the server. A flat discount or tax applies once per document; the second tax is not compounded on the first.'
    UNION ALL SELECT 'billing.unitPrice', 'Unit price'
    UNION ALL SELECT 'billing.void', 'Void'
    UNION ALL SELECT 'billing.voidAction', 'Void'
    UNION ALL SELECT 'billing.invalidDocument', 'Check the dates (due on or after the document date), the 3-letter currency, each line (description, unit price ≥ 0, positive quantity, at most 6 decimals) and the discount/tax values.'
) seed
WHERE NOT EXISTS (SELECT 1 FROM SYS_MULTI_LANGUAGE_RESOURCE existing
                   WHERE existing.RESOURCE_KEY = seed.RESOURCE_KEY AND existing.LANGUAGE = 'EnUs');
