-- ERP expense directories, expense snapshots and invoice source linkage.
-- Full Framework records are stored as JSON payloads while indexed columns enforce scoped identity,
-- operation uniqueness, CAS lookup and list filters. All writes and audit rows share one Serializable transaction.
CREATE TABLE ERP_EXPENSE_CATEGORY (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CATEGORY_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    NAME NVARCHAR(255) COLLATE Latin1_General_100_BIN2 NOT NULL,
    NAME_KEY NVARCHAR(255) COLLATE Latin1_General_100_BIN2 NOT NULL,
    IS_ACTIVE BIT NOT NULL,
    PAYLOAD NVARCHAR(MAX) NOT NULL,
    CONSTRAINT PK_ERP_EXPENSE_CATEGORY PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, CATEGORY_ID),
    CONSTRAINT UQ_ERP_EXPENSE_CATEGORY_NAME UNIQUE (TENANT_ID, ORGANIZATION_ID, NAME_KEY),
    CONSTRAINT CK_ERP_EXPENSE_CATEGORY_ACTIVE CHECK (IS_ACTIVE IN (0,1))
);

CREATE TABLE ERP_EXPENSE_VENDOR (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VENDOR_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    NAME NVARCHAR(255) COLLATE Latin1_General_100_BIN2 NOT NULL,
    NAME_KEY NVARCHAR(255) COLLATE Latin1_General_100_BIN2 NOT NULL,
    IS_ACTIVE BIT NOT NULL,
    PAYLOAD NVARCHAR(MAX) NOT NULL,
    CONSTRAINT PK_ERP_EXPENSE_VENDOR PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, VENDOR_ID),
    CONSTRAINT UQ_ERP_EXPENSE_VENDOR_NAME UNIQUE (TENANT_ID, ORGANIZATION_ID, NAME_KEY),
    CONSTRAINT CK_ERP_EXPENSE_VENDOR_ACTIVE CHECK (IS_ACTIVE IN (0,1))
);

CREATE TABLE ERP_EXPENSE (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    EXPENSE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    OPERATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    REIMBURSEMENT_OPERATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NULL,
    CATEGORY_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VENDOR_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    EMPLOYEE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NULL,
    CONTACT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NULL,
    PROJECT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NULL,
    INVOICE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NULL,
    VALUE_DATE VARCHAR(10) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CURRENCY VARCHAR(3) COLLATE Latin1_General_100_BIN2 NOT NULL,
    TYPE INT NOT NULL,
    STATUS INT NOT NULL,
    STATE INT NOT NULL,
    PAYLOAD NVARCHAR(MAX) NOT NULL,
    CONSTRAINT PK_ERP_EXPENSE PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, EXPENSE_ID),
    CONSTRAINT UQ_ERP_EXPENSE_OPERATION UNIQUE (TENANT_ID, ORGANIZATION_ID, OPERATION_ID),
    CONSTRAINT FK_ERP_EXPENSE_CATEGORY FOREIGN KEY (TENANT_ID, ORGANIZATION_ID, CATEGORY_ID)
        REFERENCES ERP_EXPENSE_CATEGORY (TENANT_ID, ORGANIZATION_ID, CATEGORY_ID),
    CONSTRAINT FK_ERP_EXPENSE_VENDOR FOREIGN KEY (TENANT_ID, ORGANIZATION_ID, VENDOR_ID)
        REFERENCES ERP_EXPENSE_VENDOR (TENANT_ID, ORGANIZATION_ID, VENDOR_ID),
    CONSTRAINT FK_ERP_EXPENSE_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES SYS_BUSINESS_IDENTITY (BUSINESS_USER_ID),
    CONSTRAINT FK_ERP_EXPENSE_CONTACT FOREIGN KEY (TENANT_ID, ORGANIZATION_ID, CONTACT_ID)
        REFERENCES ERP_BILLING_CONTACT (TENANT_ID, ORGANIZATION_ID, CONTACT_ID),
    CONSTRAINT CK_ERP_EXPENSE_TYPE CHECK (TYPE BETWEEN 0 AND 2),
    CONSTRAINT CK_ERP_EXPENSE_STATUS CHECK (STATUS BETWEEN 0 AND 3),
    CONSTRAINT CK_ERP_EXPENSE_STATE CHECK (STATE IN (0,1))
);
CREATE UNIQUE INDEX UQ_ERP_EXPENSE_REIMBURSEMENT_OPERATION ON ERP_EXPENSE
    (TENANT_ID, ORGANIZATION_ID, REIMBURSEMENT_OPERATION_ID) WHERE REIMBURSEMENT_OPERATION_ID IS NOT NULL;
CREATE INDEX IX_ERP_EXPENSE_PAGE ON ERP_EXPENSE
    (TENANT_ID, ORGANIZATION_ID, VALUE_DATE, EXPENSE_ID);

ALTER TABLE ERP_BILLING_LINE ADD EXPENSE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NULL;
CREATE UNIQUE INDEX UQ_ERP_BILLING_LINE_EXPENSE ON ERP_BILLING_LINE
    (TENANT_ID, ORGANIZATION_ID, EXPENSE_ID) WHERE EXPENSE_ID IS NOT NULL;
