-- Durable monthly ERP rules, generated occurrences, and income records used by recurring execution.
-- The rule/month unique key is the product-level idempotency boundary for scheduler retries.
CREATE TABLE ERP_INCOME (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    INCOME_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    OPERATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CONTACT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    EMPLOYEE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NULL,
    VALUE_DATE VARCHAR(10) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CURRENCY VARCHAR(3) COLLATE Latin1_General_100_BIN2 NOT NULL,
    IS_BONUS BIT NOT NULL,
    STATE INT NOT NULL,
    PAYLOAD NVARCHAR(MAX) NOT NULL,
    CONSTRAINT PK_ERP_INCOME PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, INCOME_ID),
    CONSTRAINT UQ_ERP_INCOME_OPERATION UNIQUE (TENANT_ID, ORGANIZATION_ID, OPERATION_ID),
    CONSTRAINT FK_ERP_INCOME_CONTACT FOREIGN KEY (TENANT_ID, ORGANIZATION_ID, CONTACT_ID)
        REFERENCES ERP_BILLING_CONTACT (TENANT_ID, ORGANIZATION_ID, CONTACT_ID),
    CONSTRAINT FK_ERP_INCOME_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES SYS_BUSINESS_IDENTITY (BUSINESS_USER_ID),
    CONSTRAINT CK_ERP_INCOME_BONUS CHECK (IS_BONUS IN (0,1)),
    CONSTRAINT CK_ERP_INCOME_STATE CHECK (STATE IN (0,1))
);
CREATE INDEX IX_ERP_INCOME_PAGE ON ERP_INCOME
    (TENANT_ID, ORGANIZATION_ID, VALUE_DATE, INCOME_ID);

CREATE TABLE ERP_RECURRING_RULE (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    RULE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    OPERATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    NAME NVARCHAR(200) COLLATE Latin1_General_100_BIN2 NOT NULL,
    START_MONTH VARCHAR(10) COLLATE Latin1_General_100_BIN2 NOT NULL,
    END_MONTH VARCHAR(10) COLLATE Latin1_General_100_BIN2 NULL,
    DAY_OF_MONTH INT NOT NULL,
    TARGET INT NOT NULL,
    IS_ACTIVE BIT NOT NULL,
    PAYLOAD NVARCHAR(MAX) NOT NULL,
    CONSTRAINT PK_ERP_RECURRING_RULE PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, RULE_ID),
    CONSTRAINT UQ_ERP_RECURRING_RULE_OPERATION UNIQUE (TENANT_ID, ORGANIZATION_ID, OPERATION_ID),
    CONSTRAINT CK_ERP_RECURRING_RULE_DAY CHECK (DAY_OF_MONTH BETWEEN 1 AND 31),
    CONSTRAINT CK_ERP_RECURRING_RULE_TARGET CHECK (TARGET BETWEEN 0 AND 2),
    CONSTRAINT CK_ERP_RECURRING_RULE_ACTIVE CHECK (IS_ACTIVE IN (0,1))
);
CREATE INDEX IX_ERP_RECURRING_RULE_PAGE ON ERP_RECURRING_RULE
    (TENANT_ID, ORGANIZATION_ID, TARGET, IS_ACTIVE, NAME, RULE_ID);

CREATE TABLE ERP_RECURRING_OCCURRENCE (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    OCCURRENCE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    RULE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    OCCURRENCE_MONTH VARCHAR(10) COLLATE Latin1_General_100_BIN2 NOT NULL,
    TARGET INT NOT NULL,
    RESOURCE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    RESOURCE_OPERATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    PAYLOAD NVARCHAR(MAX) NOT NULL,
    CONSTRAINT PK_ERP_RECURRING_OCCURRENCE PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, OCCURRENCE_ID),
    CONSTRAINT UQ_ERP_RECURRING_OCCURRENCE_MONTH UNIQUE
        (TENANT_ID, ORGANIZATION_ID, RULE_ID, OCCURRENCE_MONTH),
    CONSTRAINT UQ_ERP_RECURRING_OCCURRENCE_RESOURCE UNIQUE
        (TENANT_ID, ORGANIZATION_ID, TARGET, RESOURCE_ID),
    CONSTRAINT UQ_ERP_RECURRING_OCCURRENCE_OPERATION UNIQUE
        (TENANT_ID, ORGANIZATION_ID, TARGET, RESOURCE_OPERATION_ID),
    CONSTRAINT FK_ERP_RECURRING_OCCURRENCE_RULE FOREIGN KEY (TENANT_ID, ORGANIZATION_ID, RULE_ID)
        REFERENCES ERP_RECURRING_RULE (TENANT_ID, ORGANIZATION_ID, RULE_ID),
    CONSTRAINT CK_ERP_RECURRING_OCCURRENCE_TARGET CHECK (TARGET BETWEEN 0 AND 2)
);
