-- Non-interactive recurring ERP authority. No principal or scope grant is seeded.

CREATE TABLE ERP_RECURRING_SERVICE_PRINCIPAL (
    PRINCIPAL_ID NVARCHAR(64) NOT NULL,
    AUDIT_ACTOR_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    NAME NVARCHAR(200) NOT NULL,
    IS_ACTIVE BIT NOT NULL,
    PRINCIPAL_VERSION BIGINT NOT NULL,
    UPDATED_BY NVARCHAR(50) NOT NULL,
    UPDATED_AT DATETIME2 NOT NULL,
    CONSTRAINT PK_ERP_RECURRING_SERVICE_PRINCIPAL PRIMARY KEY (PRINCIPAL_ID),
    CONSTRAINT UQ_ERP_RECURRING_SERVICE_PRINCIPAL_ACTOR UNIQUE (AUDIT_ACTOR_ID),
    CONSTRAINT FK_ERP_RECURRING_SERVICE_PRINCIPAL_ACTOR FOREIGN KEY (AUDIT_ACTOR_ID)
        REFERENCES SYS_BUSINESS_IDENTITY (BUSINESS_USER_ID),
    CONSTRAINT CK_ERP_RECURRING_SERVICE_PRINCIPAL_ACTIVE CHECK (IS_ACTIVE IN (0,1)),
    CONSTRAINT CK_ERP_RECURRING_SERVICE_PRINCIPAL_VERSION CHECK (PRINCIPAL_VERSION>0)
);

CREATE TABLE ERP_RECURRING_SERVICE_PRINCIPAL_AUDIT (
    PRINCIPAL_ID NVARCHAR(64) NOT NULL,
    PRINCIPAL_VERSION BIGINT NOT NULL,
    NAME NVARCHAR(200) NOT NULL,
    IS_ACTIVE BIT NOT NULL,
    CHANGED_BY NVARCHAR(50) NOT NULL,
    CHANGED_AT DATETIME2 NOT NULL,
    CONSTRAINT PK_ERP_RECURRING_SERVICE_PRINCIPAL_AUDIT PRIMARY KEY (PRINCIPAL_ID, PRINCIPAL_VERSION),
    CONSTRAINT FK_ERP_RECURRING_SERVICE_PRINCIPAL_AUDIT FOREIGN KEY (PRINCIPAL_ID)
        REFERENCES ERP_RECURRING_SERVICE_PRINCIPAL (PRINCIPAL_ID),
    CONSTRAINT CK_ERP_RECURRING_SERVICE_PRINCIPAL_AUDIT_ACTIVE CHECK (IS_ACTIVE IN (0,1)),
    CONSTRAINT CK_ERP_RECURRING_SERVICE_PRINCIPAL_AUDIT_VERSION CHECK (PRINCIPAL_VERSION>0)
);

CREATE TABLE ERP_RECURRING_SERVICE_SCOPE (
    PRINCIPAL_ID NVARCHAR(64) NOT NULL,
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    IS_ACTIVE BIT NOT NULL,
    SCOPE_VERSION BIGINT NOT NULL,
    UPDATED_BY NVARCHAR(50) NOT NULL,
    UPDATED_AT DATETIME2 NOT NULL,
    CONSTRAINT PK_ERP_RECURRING_SERVICE_SCOPE PRIMARY KEY (PRINCIPAL_ID, TENANT_ID, ORGANIZATION_ID),
    CONSTRAINT FK_ERP_RECURRING_SERVICE_SCOPE_PRINCIPAL FOREIGN KEY (PRINCIPAL_ID)
        REFERENCES ERP_RECURRING_SERVICE_PRINCIPAL (PRINCIPAL_ID),
    CONSTRAINT CK_ERP_RECURRING_SERVICE_SCOPE_ACTIVE CHECK (IS_ACTIVE IN (0,1)),
    CONSTRAINT CK_ERP_RECURRING_SERVICE_SCOPE_VERSION CHECK (SCOPE_VERSION>0),
    CONSTRAINT CK_ERP_RECURRING_SERVICE_SCOPE_IDS CHECK (
        LEN(TENANT_ID)=36 AND LEN(ORGANIZATION_ID)=36
        AND TENANT_ID<>'00000000-0000-0000-0000-000000000000'
        AND ORGANIZATION_ID<>'00000000-0000-0000-0000-000000000000')
);

CREATE TABLE ERP_RECURRING_SERVICE_SCOPE_AUDIT (
    PRINCIPAL_ID NVARCHAR(64) NOT NULL,
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    SCOPE_VERSION BIGINT NOT NULL,
    IS_ACTIVE BIT NOT NULL,
    CHANGED_BY NVARCHAR(50) NOT NULL,
    CHANGED_AT DATETIME2 NOT NULL,
    CONSTRAINT PK_ERP_RECURRING_SERVICE_SCOPE_AUDIT PRIMARY KEY
        (PRINCIPAL_ID, TENANT_ID, ORGANIZATION_ID, SCOPE_VERSION),
    CONSTRAINT FK_ERP_RECURRING_SERVICE_SCOPE_AUDIT FOREIGN KEY (PRINCIPAL_ID, TENANT_ID, ORGANIZATION_ID)
        REFERENCES ERP_RECURRING_SERVICE_SCOPE (PRINCIPAL_ID, TENANT_ID, ORGANIZATION_ID),
    CONSTRAINT CK_ERP_RECURRING_SERVICE_SCOPE_AUDIT_ACTIVE CHECK (IS_ACTIVE IN (0,1)),
    CONSTRAINT CK_ERP_RECURRING_SERVICE_SCOPE_AUDIT_VERSION CHECK (SCOPE_VERSION>0)
);
