-- Organization-local recurring calendar and bounded missed-month catch-up policy.

ALTER TABLE ERP_RECURRING_SERVICE_SCOPE ADD TIME_ZONE_ID NVARCHAR(100) NULL;
ALTER TABLE ERP_RECURRING_SERVICE_SCOPE ADD CATCH_UP_MONTHS INT NOT NULL DEFAULT 0;
ALTER TABLE ERP_RECURRING_SERVICE_SCOPE_AUDIT ADD TIME_ZONE_ID NVARCHAR(100) NULL;
ALTER TABLE ERP_RECURRING_SERVICE_SCOPE_AUDIT ADD CATCH_UP_MONTHS INT NOT NULL DEFAULT 0;

ALTER TABLE ERP_RECURRING_SERVICE_SCOPE ADD CONSTRAINT CK_ERP_RECURRING_SCOPE_CATCH_UP
    CHECK (CATCH_UP_MONTHS BETWEEN 0 AND 24);
ALTER TABLE ERP_RECURRING_SERVICE_SCOPE_AUDIT ADD CONSTRAINT CK_ERP_RECURRING_SCOPE_AUDIT_CATCH_UP
    CHECK (CATCH_UP_MONTHS BETWEEN 0 AND 24);
