-- Cover the immutable business-date filters used by the atomic financial report snapshot.
CREATE INDEX IX_ERP_BILLING_DOCUMENT_REPORT ON ERP_BILLING_DOCUMENT
    (TENANT_ID, ORGANIZATION_ID, KIND, STATUS, DOCUMENT_DATE, DOCUMENT_ID);

CREATE INDEX IX_ERP_INCOME_REPORT ON ERP_INCOME
    (TENANT_ID, ORGANIZATION_ID, STATE, VALUE_DATE, INCOME_ID);

CREATE INDEX IX_ERP_EXPENSE_REPORT ON ERP_EXPENSE
    (TENANT_ID, ORGANIZATION_ID, STATE, VALUE_DATE, EXPENSE_ID);
