-- Immutable organization-scoped financial/cash-flow report payloads and append-only usage history.
-- SNAPSHOT_ID is the caller operation identity, making a retried create request idempotent.
CREATE TABLE ERP_FINANCIAL_REPORT_SNAPSHOT (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    SNAPSHOT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    REPORT_KIND INT NOT NULL,
    PERIOD_START VARCHAR(10) COLLATE Latin1_General_100_BIN2 NOT NULL,
    PERIOD_END VARCHAR(10) COLLATE Latin1_General_100_BIN2 NOT NULL,
    REPORT_JSON NVARCHAR(MAX) NOT NULL,
    CSV_CONTENT NVARCHAR(MAX) NOT NULL,
    CONTENT_HASH VARCHAR(64) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CREATED_BY VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CREATED_AT_TICKS BIGINT NOT NULL,
    CONSTRAINT PK_ERP_FINANCIAL_REPORT_SNAPSHOT PRIMARY KEY
        (TENANT_ID, ORGANIZATION_ID, SNAPSHOT_ID),
    CONSTRAINT FK_ERP_FINANCIAL_REPORT_SNAPSHOT_USER FOREIGN KEY (CREATED_BY)
        REFERENCES SYS_BUSINESS_IDENTITY (BUSINESS_USER_ID),
    CONSTRAINT CK_ERP_FINANCIAL_REPORT_SNAPSHOT_KIND CHECK (REPORT_KIND IN (0,1)),
    CONSTRAINT CK_ERP_FINANCIAL_REPORT_SNAPSHOT_HASH CHECK (LEN(CONTENT_HASH)=64),
    CONSTRAINT CK_ERP_FINANCIAL_REPORT_SNAPSHOT_PERIOD CHECK (PERIOD_START<=PERIOD_END)
);
CREATE INDEX IX_ERP_FINANCIAL_REPORT_SNAPSHOT_PAGE ON ERP_FINANCIAL_REPORT_SNAPSHOT
    (TENANT_ID, ORGANIZATION_ID, CREATED_AT_TICKS DESC, SNAPSHOT_ID DESC, REPORT_KIND);

CREATE TABLE ERP_FINANCIAL_REPORT_SNAPSHOT_AUDIT (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    AUDIT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    SNAPSHOT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ACTION INT NOT NULL,
    USER_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    AT_TICKS BIGINT NOT NULL,
    OBSERVED_CONTENT_HASH VARCHAR(64) COLLATE Latin1_General_100_BIN2 NOT NULL,
    MATCHED BIT NULL,
    CONSTRAINT PK_ERP_FINANCIAL_REPORT_SNAPSHOT_AUDIT PRIMARY KEY
        (TENANT_ID, ORGANIZATION_ID, AUDIT_ID),
    CONSTRAINT FK_ERP_FINANCIAL_REPORT_SNAPSHOT_AUDIT_SNAPSHOT FOREIGN KEY
        (TENANT_ID, ORGANIZATION_ID, SNAPSHOT_ID)
        REFERENCES ERP_FINANCIAL_REPORT_SNAPSHOT (TENANT_ID, ORGANIZATION_ID, SNAPSHOT_ID),
    CONSTRAINT FK_ERP_FINANCIAL_REPORT_SNAPSHOT_AUDIT_USER FOREIGN KEY (USER_ID)
        REFERENCES SYS_BUSINESS_IDENTITY (BUSINESS_USER_ID),
    CONSTRAINT CK_ERP_FINANCIAL_REPORT_SNAPSHOT_AUDIT_ACTION CHECK (ACTION BETWEEN 0 AND 2),
    CONSTRAINT CK_ERP_FINANCIAL_REPORT_SNAPSHOT_AUDIT_HASH CHECK (LEN(OBSERVED_CONTENT_HASH)=64),
    CONSTRAINT CK_ERP_FINANCIAL_REPORT_SNAPSHOT_AUDIT_MATCH CHECK (
        (ACTION=1 AND MATCHED IN (0,1)) OR (ACTION IN (0,2) AND MATCHED IS NULL))
);
CREATE INDEX IX_ERP_FINANCIAL_REPORT_SNAPSHOT_AUDIT_PAGE ON ERP_FINANCIAL_REPORT_SNAPSHOT_AUDIT
    (TENANT_ID, ORGANIZATION_ID, SNAPSHOT_ID, AT_TICKS, AUDIT_ID);
