-- Organization-scoped durable email templates, provider references and lease-ready delivery requests.
-- Provider credentials are never stored here; CREDENTIAL_REFERENCE remains inside the validated opaque payload.
CREATE TABLE COL_DELIVERY_TEMPLATE (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    TEMPLATE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    PAYLOAD NVARCHAR(MAX) NOT NULL,
    CONSTRAINT PK_COL_DELIVERY_TEMPLATE PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, TEMPLATE_ID)
);

CREATE TABLE COL_DELIVERY_PROFILE (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    PROFILE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    PAYLOAD NVARCHAR(MAX) NOT NULL,
    CONSTRAINT PK_COL_DELIVERY_PROFILE PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, PROFILE_ID)
);

CREATE TABLE COL_DELIVERY_REQUEST (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    DELIVERY_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    OPERATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    STATE INT NOT NULL,
    NEXT_ATTEMPT_AT_TICKS BIGINT NOT NULL,
    LEASE_EXPIRES_AT_TICKS BIGINT NULL,
    PAYLOAD NVARCHAR(MAX) NOT NULL,
    CONSTRAINT PK_COL_DELIVERY_REQUEST PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, DELIVERY_ID),
    CONSTRAINT UQ_COL_DELIVERY_REQUEST_OPERATION UNIQUE (TENANT_ID, ORGANIZATION_ID, OPERATION_ID),
    CONSTRAINT CK_COL_DELIVERY_REQUEST_STATE CHECK (STATE BETWEEN 0 AND 5),
    CONSTRAINT CK_COL_DELIVERY_REQUEST_LEASE CHECK (
        (STATE=1 AND LEASE_EXPIRES_AT_TICKS IS NOT NULL)
        OR (STATE<>1 AND LEASE_EXPIRES_AT_TICKS IS NULL))
);
CREATE INDEX IX_COL_DELIVERY_REQUEST_DUE ON COL_DELIVERY_REQUEST
    (TENANT_ID, ORGANIZATION_ID, STATE, NEXT_ATTEMPT_AT_TICKS, LEASE_EXPIRES_AT_TICKS, DELIVERY_ID);
