-- Idempotent operator actions for terminal outbound delivery requests.
CREATE TABLE COL_DELIVERY_DEAD_LETTER_OPERATION (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    OPERATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    DELIVERY_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ACTION INT NOT NULL,
    RESULT_VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ACTOR_ID VARCHAR(128) COLLATE Latin1_General_100_BIN2 NOT NULL,
    OCCURRED_AT_TICKS BIGINT NOT NULL,
    PAYLOAD NVARCHAR(MAX) NOT NULL,
    CONSTRAINT PK_COL_DELIVERY_DEAD_LETTER_OPERATION
        PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, OPERATION_ID),
    CONSTRAINT FK_COL_DELIVERY_DEAD_LETTER_OPERATION_REQUEST
        FOREIGN KEY (TENANT_ID, ORGANIZATION_ID, DELIVERY_ID)
        REFERENCES COL_DELIVERY_REQUEST (TENANT_ID, ORGANIZATION_ID, DELIVERY_ID),
    CONSTRAINT CK_COL_DELIVERY_DEAD_LETTER_OPERATION_ACTION CHECK (ACTION IN (0,1)),
    CONSTRAINT CK_COL_DELIVERY_DEAD_LETTER_OPERATION_OCCURRED CHECK (OCCURRED_AT_TICKS>0)
);

CREATE INDEX IX_COL_DELIVERY_REQUEST_DEAD_LETTER
    ON COL_DELIVERY_REQUEST (TENANT_ID, ORGANIZATION_ID, STATE, DELIVERY_ID);
