CREATE TABLE ERP_AUTOMATIC_BILLING_GENERATION (
    TENANT_ID       VARCHAR(36)  NOT NULL,
    ORGANIZATION_ID VARCHAR(36)  NOT NULL,
    GENERATION_ID   VARCHAR(36)  NOT NULL,
    VERSION         VARCHAR(36)  NOT NULL,
    OPERATION_ID    VARCHAR(36)  NOT NULL,
    DOCUMENT_ID     VARCHAR(36)  NOT NULL,
    INVOICE_TYPE    INT          NOT NULL,
    CREATED_BY      NVARCHAR(128) NOT NULL,
    PAYLOAD         NVARCHAR(MAX) NOT NULL,
    CONSTRAINT PK_ERP_AUTOMATIC_BILLING_GENERATION
        PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, GENERATION_ID),
    CONSTRAINT UQ_ERP_AUTOMATIC_BILLING_OPERATION
        UNIQUE (TENANT_ID, ORGANIZATION_ID, OPERATION_ID),
    CONSTRAINT UQ_ERP_AUTOMATIC_BILLING_DOCUMENT
        UNIQUE (TENANT_ID, ORGANIZATION_ID, DOCUMENT_ID),
    CONSTRAINT FK_ERP_AUTOMATIC_BILLING_DOCUMENT FOREIGN KEY (TENANT_ID, ORGANIZATION_ID, DOCUMENT_ID)
        REFERENCES ERP_BILLING_DOCUMENT (TENANT_ID, ORGANIZATION_ID, DOCUMENT_ID),
    CONSTRAINT CK_ERP_AUTOMATIC_BILLING_TYPE CHECK (INVOICE_TYPE BETWEEN 0 AND 5)
);

CREATE TABLE ERP_AUTOMATIC_BILLING_SOURCE (
    TENANT_ID       VARCHAR(36) NOT NULL,
    ORGANIZATION_ID VARCHAR(36) NOT NULL,
    SOURCE_KIND     INT         NOT NULL,
    SOURCE_ID       VARCHAR(36) NOT NULL,
    GENERATION_ID   VARCHAR(36) NOT NULL,
    LINE_NO         INT         NOT NULL,
    EMPLOYEE_ID     VARCHAR(36) NULL,
    PROJECT_ID      VARCHAR(36) NULL,
    TASK_ID         VARCHAR(36) NULL,
    PRODUCT_ID      VARCHAR(36) NULL,
    EXPENSE_ID      VARCHAR(36) NULL,
    CONSTRAINT PK_ERP_AUTOMATIC_BILLING_SOURCE
        PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, SOURCE_KIND, SOURCE_ID),
    CONSTRAINT UQ_ERP_AUTOMATIC_BILLING_LINE
        UNIQUE (TENANT_ID, ORGANIZATION_ID, GENERATION_ID, LINE_NO),
    CONSTRAINT FK_ERP_AUTOMATIC_BILLING_GENERATION FOREIGN KEY (TENANT_ID, ORGANIZATION_ID, GENERATION_ID)
        REFERENCES ERP_AUTOMATIC_BILLING_GENERATION (TENANT_ID, ORGANIZATION_ID, GENERATION_ID),
    CONSTRAINT FK_ERP_AUTOMATIC_BILLING_EXPENSE FOREIGN KEY (TENANT_ID, ORGANIZATION_ID, EXPENSE_ID)
        REFERENCES ERP_EXPENSE (TENANT_ID, ORGANIZATION_ID, EXPENSE_ID),
    CONSTRAINT CK_ERP_AUTOMATIC_BILLING_SOURCE_KIND CHECK (SOURCE_KIND BETWEEN 0 AND 2),
    CONSTRAINT CK_ERP_AUTOMATIC_BILLING_LINE_NO CHECK (LINE_NO BETWEEN 1 AND 200)
);

CREATE INDEX IX_ERP_AUTOMATIC_BILLING_GENERATION_TYPE
    ON ERP_AUTOMATIC_BILLING_GENERATION (TENANT_ID, ORGANIZATION_ID, INVOICE_TYPE, GENERATION_ID);
