-- Invoice-linked credit notes. A credit is a positive billing document whose issue/void transition
-- adjusts the referenced invoice in the same Serializable transaction.
ALTER TABLE ERP_BILLING_NUMBER DROP CONSTRAINT CK_ERP_BILLING_NUMBER_KIND;
ALTER TABLE ERP_BILLING_NUMBER ADD CONSTRAINT CK_ERP_BILLING_NUMBER_KIND CHECK (KIND IN (0,1,2));

ALTER TABLE ERP_BILLING_DOCUMENT ADD
    CREDITED VARCHAR(40) COLLATE Latin1_General_100_BIN2 NOT NULL
        CONSTRAINT DF_ERP_BILLING_DOCUMENT_CREDITED DEFAULT '0',
    ADJUSTED_INVOICE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NULL;

ALTER TABLE ERP_BILLING_DOCUMENT DROP CONSTRAINT CK_ERP_BILLING_DOCUMENT_KIND;
ALTER TABLE ERP_BILLING_DOCUMENT DROP CONSTRAINT CK_ERP_BILLING_DOCUMENT_STATUS;
ALTER TABLE ERP_BILLING_DOCUMENT DROP CONSTRAINT CK_ERP_BILLING_DOCUMENT_LINKS;
ALTER TABLE ERP_BILLING_DOCUMENT DROP CONSTRAINT CK_ERP_BILLING_DOCUMENT_AMOUNTS;

ALTER TABLE ERP_BILLING_DOCUMENT ADD CONSTRAINT CK_ERP_BILLING_DOCUMENT_KIND
    CHECK (KIND IN (0,1,2));
ALTER TABLE ERP_BILLING_DOCUMENT ADD CONSTRAINT CK_ERP_BILLING_DOCUMENT_STATUS
    CHECK (STATUS BETWEEN 0 AND 9);
ALTER TABLE ERP_BILLING_DOCUMENT ADD CONSTRAINT CK_ERP_BILLING_DOCUMENT_LINKS CHECK (
    (CONVERTED_FROM_ID IS NULL OR (KIND=1 AND CONVERTED_FROM_ID<>DOCUMENT_ID))
    AND (CONVERTED_TO_ID IS NULL OR (KIND=0 AND STATUS=2 AND CONVERTED_TO_ID<>DOCUMENT_ID))
    AND ((KIND=2 AND ADJUSTED_INVOICE_ID IS NOT NULL AND ADJUSTED_INVOICE_ID<>DOCUMENT_ID)
         OR (KIND<>2 AND ADJUSTED_INVOICE_ID IS NULL)));
ALTER TABLE ERP_BILLING_DOCUMENT ADD CONSTRAINT CK_ERP_BILLING_DOCUMENT_AMOUNTS CHECK (
    SUBTOTAL NOT LIKE '-%' AND DISCOUNT_AMOUNT NOT LIKE '-%' AND TAX_AMOUNT NOT LIKE '-%'
    AND TOTAL NOT LIKE '-%' AND PAID NOT LIKE '-%' AND CREDITED NOT LIKE '-%'
    AND LEN(SUBTOTAL)>0 AND LEN(DISCOUNT_AMOUNT)>0 AND LEN(TAX_AMOUNT)>0
    AND LEN(TOTAL)>0 AND LEN(PAID)>0 AND LEN(CREDITED)>0);
ALTER TABLE ERP_BILLING_DOCUMENT ADD CONSTRAINT FK_ERP_BILLING_DOCUMENT_ADJUSTED
    FOREIGN KEY (TENANT_ID, ORGANIZATION_ID, ADJUSTED_INVOICE_ID)
    REFERENCES ERP_BILLING_DOCUMENT (TENANT_ID, ORGANIZATION_ID, DOCUMENT_ID);

CREATE INDEX IX_ERP_BILLING_DOCUMENT_ADJUSTED
    ON ERP_BILLING_DOCUMENT (TENANT_ID, ORGANIZATION_ID, ADJUSTED_INVOICE_ID, NUMBER)
    WHERE ADJUSTED_INVOICE_ID IS NOT NULL;
