-- Immutable billing snapshots exposed through revocable, expiring bearer links.
-- Only a SHA-256 token digest is durable; the secret is returned once to the creator.
CREATE TABLE ERP_BILLING_SHARE_LINK (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    SHARE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    OPERATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    DOCUMENT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    DOCUMENT_VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    TOKEN_HASH CHAR(64) COLLATE Latin1_General_100_BIN2 NOT NULL,
    EXPIRES_AT_TICKS BIGINT NOT NULL,
    CREATED_BY VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CREATED_AT_TICKS BIGINT NOT NULL,
    REVOKED_AT_TICKS BIGINT NULL,
    ACCESS_COUNT BIGINT NOT NULL CONSTRAINT DF_ERP_BILLING_SHARE_ACCESS_COUNT DEFAULT 0,
    LAST_ACCESSED_AT_TICKS BIGINT NULL,
    PAYLOAD NVARCHAR(MAX) NOT NULL,
    CONSTRAINT PK_ERP_BILLING_SHARE_LINK PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, SHARE_ID),
    CONSTRAINT UQ_ERP_BILLING_SHARE_OPERATION UNIQUE (TENANT_ID, ORGANIZATION_ID, OPERATION_ID),
    CONSTRAINT UQ_ERP_BILLING_SHARE_TOKEN UNIQUE (TOKEN_HASH),
    CONSTRAINT FK_ERP_BILLING_SHARE_DOCUMENT FOREIGN KEY (TENANT_ID, ORGANIZATION_ID, DOCUMENT_ID)
        REFERENCES ERP_BILLING_DOCUMENT (TENANT_ID, ORGANIZATION_ID, DOCUMENT_ID),
    CONSTRAINT CK_ERP_BILLING_SHARE_EXPIRY CHECK (EXPIRES_AT_TICKS > CREATED_AT_TICKS),
    CONSTRAINT CK_ERP_BILLING_SHARE_ACCESS CHECK (ACCESS_COUNT >= 0)
);
CREATE INDEX IX_ERP_BILLING_SHARE_DOCUMENT ON ERP_BILLING_SHARE_LINK
    (TENANT_ID, ORGANIZATION_ID, DOCUMENT_ID, CREATED_AT_TICKS, SHARE_ID);

CREATE TABLE ERP_BILLING_SHARE_ACCESS (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ACCESS_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    SHARE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ACCESSED_AT_TICKS BIGINT NOT NULL,
    CLIENT_ADDRESS_HASH CHAR(64) COLLATE Latin1_General_100_BIN2 NULL,
    USER_AGENT NVARCHAR(256) NULL,
    CONSTRAINT PK_ERP_BILLING_SHARE_ACCESS PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, ACCESS_ID),
    CONSTRAINT FK_ERP_BILLING_SHARE_ACCESS_LINK FOREIGN KEY (TENANT_ID, ORGANIZATION_ID, SHARE_ID)
        REFERENCES ERP_BILLING_SHARE_LINK (TENANT_ID, ORGANIZATION_ID, SHARE_ID)
);
CREATE INDEX IX_ERP_BILLING_SHARE_ACCESS_LINK ON ERP_BILLING_SHARE_ACCESS
    (TENANT_ID, ORGANIZATION_ID, SHARE_ID, ACCESSED_AT_TICKS, ACCESS_ID);

CREATE TABLE ERP_BILLING_SHARE_DELIVERY (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    SHARE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    DELIVERY_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CREATED_AT_TICKS BIGINT NOT NULL,
    CONSTRAINT PK_ERP_BILLING_SHARE_DELIVERY PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, DELIVERY_ID),
    CONSTRAINT FK_ERP_BILLING_SHARE_DELIVERY_LINK FOREIGN KEY (TENANT_ID, ORGANIZATION_ID, SHARE_ID)
        REFERENCES ERP_BILLING_SHARE_LINK (TENANT_ID, ORGANIZATION_ID, SHARE_ID),
    CONSTRAINT FK_ERP_BILLING_SHARE_DELIVERY_REQUEST FOREIGN KEY (TENANT_ID, ORGANIZATION_ID, DELIVERY_ID)
        REFERENCES COL_DELIVERY_REQUEST (TENANT_ID, ORGANIZATION_ID, DELIVERY_ID)
);
