CREATE TABLE CRM_PIPELINE (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    PIPELINE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    NAME NVARCHAR(255) NOT NULL, DESCRIPTION NVARCHAR(4000) NULL,
    CONSTRAINT PK_CRM_PIPELINE PRIMARY KEY (TENANT_ID,ORGANIZATION_ID,PIPELINE_ID));
CREATE INDEX IX_CRM_PIPELINE_PAGE ON CRM_PIPELINE (TENANT_ID,ORGANIZATION_ID,NAME,PIPELINE_ID);

CREATE TABLE CRM_PIPELINE_STAGE (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    STAGE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    PIPELINE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    NAME NVARCHAR(255) NOT NULL, DESCRIPTION NVARCHAR(4000) NULL, STAGE_INDEX INT NOT NULL,
    CONSTRAINT PK_CRM_PIPELINE_STAGE PRIMARY KEY (TENANT_ID,ORGANIZATION_ID,STAGE_ID),
    CONSTRAINT UQ_CRM_PIPELINE_STAGE_INDEX UNIQUE (TENANT_ID,ORGANIZATION_ID,PIPELINE_ID,STAGE_INDEX),
    CONSTRAINT FK_CRM_PIPELINE_STAGE_PIPELINE FOREIGN KEY (TENANT_ID,ORGANIZATION_ID,PIPELINE_ID)
        REFERENCES CRM_PIPELINE (TENANT_ID,ORGANIZATION_ID,PIPELINE_ID),
    CONSTRAINT CK_CRM_PIPELINE_STAGE_INDEX CHECK (STAGE_INDEX>0));

CREATE TABLE CRM_DEAL (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    DEAL_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    STAGE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    TITLE NVARCHAR(255) NOT NULL, PROBABILITY INT NOT NULL,
    CLIENT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NULL,
    CREATED_BY NVARCHAR(128) NULL,
    CONSTRAINT PK_CRM_DEAL PRIMARY KEY (TENANT_ID,ORGANIZATION_ID,DEAL_ID),
    CONSTRAINT FK_CRM_DEAL_STAGE FOREIGN KEY (TENANT_ID,ORGANIZATION_ID,STAGE_ID)
        REFERENCES CRM_PIPELINE_STAGE (TENANT_ID,ORGANIZATION_ID,STAGE_ID),
    CONSTRAINT CK_CRM_DEAL_PROBABILITY CHECK (PROBABILITY BETWEEN 0 AND 5));
CREATE INDEX IX_CRM_DEAL_PAGE ON CRM_DEAL (TENANT_ID,ORGANIZATION_ID,STAGE_ID,DEAL_ID);
CREATE INDEX IX_CRM_DEAL_CREATED ON CRM_DEAL (TENANT_ID,ORGANIZATION_ID,CREATED_BY,STAGE_ID,DEAL_ID);
CREATE UNIQUE INDEX UQ_CRM_DEAL_CLIENT ON CRM_DEAL (TENANT_ID,ORGANIZATION_ID,CLIENT_ID)
    WHERE CLIENT_ID IS NOT NULL;

CREATE TABLE CRM_DEAL_ASSIGNEE (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    DEAL_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    EMPLOYEE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CONSTRAINT PK_CRM_DEAL_ASSIGNEE PRIMARY KEY (TENANT_ID,ORGANIZATION_ID,DEAL_ID,EMPLOYEE_ID),
    CONSTRAINT FK_CRM_DEAL_ASSIGNEE_DEAL FOREIGN KEY (TENANT_ID,ORGANIZATION_ID,DEAL_ID)
        REFERENCES CRM_DEAL (TENANT_ID,ORGANIZATION_ID,DEAL_ID));
CREATE INDEX IX_CRM_DEAL_ASSIGNEE_EMPLOYEE ON CRM_DEAL_ASSIGNEE
    (TENANT_ID,ORGANIZATION_ID,EMPLOYEE_ID,DEAL_ID);

CREATE TABLE CRM_AUDIT (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CHANGE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ACTOR_USER_ID NVARCHAR(128) NOT NULL, OPERATION VARCHAR(64) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ENTITY_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    PREVIOUS_VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NULL,
    VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NULL, RECORDED_AT_TICKS BIGINT NOT NULL,
    CONSTRAINT PK_CRM_AUDIT PRIMARY KEY (TENANT_ID,ORGANIZATION_ID,CHANGE_ID));
CREATE INDEX IX_CRM_AUDIT_ENTITY ON CRM_AUDIT
    (TENANT_ID,ORGANIZATION_ID,ENTITY_ID,RECORDED_AT_TICKS,CHANGE_ID);
