CREATE TABLE CRM_TEAM (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    TEAM_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CREATED_BY NVARCHAR(128) NOT NULL, NAME NVARCHAR(255) NOT NULL, TEAM_PREFIX NVARCHAR(32) NULL,
    IS_PUBLIC BIT NOT NULL, SHARE_PROFILE_VIEW BIT NOT NULL, REQUIRE_PLAN_TO_TRACK BIT NOT NULL,
    CONSTRAINT PK_CRM_TEAM PRIMARY KEY (TENANT_ID,ORGANIZATION_ID,TEAM_ID));
CREATE INDEX IX_CRM_TEAM_PAGE ON CRM_TEAM (TENANT_ID,ORGANIZATION_ID,NAME,TEAM_ID);

CREATE TABLE CRM_TEAM_MEMBER (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    TEAM_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    EMPLOYEE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    IS_MANAGER BIT NOT NULL,
    CONSTRAINT PK_CRM_TEAM_MEMBER PRIMARY KEY (TENANT_ID,ORGANIZATION_ID,TEAM_ID,EMPLOYEE_ID),
    CONSTRAINT FK_CRM_TEAM_MEMBER_TEAM FOREIGN KEY (TENANT_ID,ORGANIZATION_ID,TEAM_ID)
        REFERENCES CRM_TEAM (TENANT_ID,ORGANIZATION_ID,TEAM_ID));
CREATE INDEX IX_CRM_TEAM_MEMBER_EMPLOYEE ON CRM_TEAM_MEMBER
    (TENANT_ID,ORGANIZATION_ID,EMPLOYEE_ID,TEAM_ID);

CREATE TABLE CRM_PROJECT (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    PROJECT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CREATED_BY NVARCHAR(128) NOT NULL, NAME NVARCHAR(255) NOT NULL,
    DESCRIPTION NVARCHAR(MAX) NULL, CODE NVARCHAR(64) NULL,
    PROJECT_STATUS VARCHAR(32) COLLATE Latin1_General_100_BIN2 NOT NULL,
    START_AT_TICKS BIGINT NULL, END_AT_TICKS BIGINT NULL,
    IS_BILLABLE BIT NOT NULL, IS_PUBLIC BIT NOT NULL, BUDGET DECIMAL(19,4) NULL,
    BUDGET_TYPE VARCHAR(16) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CUSTOMER_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NULL,
    CONSTRAINT PK_CRM_PROJECT PRIMARY KEY (TENANT_ID,ORGANIZATION_ID,PROJECT_ID));
CREATE INDEX IX_CRM_PROJECT_PAGE ON CRM_PROJECT (TENANT_ID,ORGANIZATION_ID,NAME,PROJECT_ID);
CREATE INDEX IX_CRM_PROJECT_CREATED ON CRM_PROJECT (TENANT_ID,ORGANIZATION_ID,CREATED_BY,NAME,PROJECT_ID);

CREATE TABLE CRM_PROJECT_MEMBER (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    PROJECT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    EMPLOYEE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    IS_MANAGER BIT NOT NULL,
    CONSTRAINT PK_CRM_PROJECT_MEMBER PRIMARY KEY (TENANT_ID,ORGANIZATION_ID,PROJECT_ID,EMPLOYEE_ID),
    CONSTRAINT FK_CRM_PROJECT_MEMBER_PROJECT FOREIGN KEY (TENANT_ID,ORGANIZATION_ID,PROJECT_ID)
        REFERENCES CRM_PROJECT (TENANT_ID,ORGANIZATION_ID,PROJECT_ID));
CREATE INDEX IX_CRM_PROJECT_MEMBER_EMPLOYEE ON CRM_PROJECT_MEMBER
    (TENANT_ID,ORGANIZATION_ID,EMPLOYEE_ID,PROJECT_ID);

CREATE TABLE CRM_PROJECT_TEAM (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    PROJECT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    TEAM_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CONSTRAINT PK_CRM_PROJECT_TEAM PRIMARY KEY (TENANT_ID,ORGANIZATION_ID,PROJECT_ID,TEAM_ID),
    CONSTRAINT FK_CRM_PROJECT_TEAM_PROJECT FOREIGN KEY (TENANT_ID,ORGANIZATION_ID,PROJECT_ID)
        REFERENCES CRM_PROJECT (TENANT_ID,ORGANIZATION_ID,PROJECT_ID),
    CONSTRAINT FK_CRM_PROJECT_TEAM_TEAM FOREIGN KEY (TENANT_ID,ORGANIZATION_ID,TEAM_ID)
        REFERENCES CRM_TEAM (TENANT_ID,ORGANIZATION_ID,TEAM_ID));
CREATE INDEX IX_CRM_PROJECT_TEAM_TEAM ON CRM_PROJECT_TEAM
    (TENANT_ID,ORGANIZATION_ID,TEAM_ID,PROJECT_ID);
