CREATE TABLE CRM_CUSTOMER_ENROLLMENT (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CONTACT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    MDM_CUSTOMER_ID NVARCHAR(50) NOT NULL,
    CUSTOMER_NAME NVARCHAR(255) NOT NULL,
    ENROLLED_BY NVARCHAR(128) NOT NULL,
    ENROLLED_AT_TICKS BIGINT NOT NULL,
    CONSTRAINT PK_CRM_CUSTOMER_ENROLLMENT PRIMARY KEY (TENANT_ID,ORGANIZATION_ID,CONTACT_ID),
    CONSTRAINT UQ_CRM_CUSTOMER_ENROLLMENT_MDM UNIQUE (TENANT_ID,ORGANIZATION_ID,MDM_CUSTOMER_ID));
CREATE INDEX IX_CRM_CUSTOMER_ENROLLMENT_PAGE ON CRM_CUSTOMER_ENROLLMENT
    (TENANT_ID,ORGANIZATION_ID,MDM_CUSTOMER_ID,CONTACT_ID);
