-- Expense workspace UI resources. No menu, role, or business grants are seeded here.
INSERT INTO SYS_MULTI_LANGUAGE_RESOURCE (RESOURCE_KEY, MENU_ID, LANGUAGE, VALUE)
SELECT seed.RESOURCE_KEY, 'COMMON', 'EnUs', seed.VALUE FROM (
    SELECT 'billing.expenseWorkspace' AS RESOURCE_KEY, 'Expense workspace' AS VALUE
    UNION ALL SELECT 'expenseWorkspace.title', 'Expense workspace'
    UNION ALL SELECT 'expenseWorkspace.eyebrow', 'ERP · Expense control'
    UNION ALL SELECT 'expenseWorkspace.intro', 'Manage expense directories by organization and track each expense through billing, payment, reimbursement, and cancellation.'
    UNION ALL SELECT 'expenseWorkspace.backBilling', 'Back to billing workspace'
    UNION ALL SELECT 'expenseWorkspace.scopes', 'My expense scopes'
    UNION ALL SELECT 'expenseWorkspace.noScopes', 'No expense scopes are currently accessible.'
    UNION ALL SELECT 'expenseWorkspace.selectedScope', 'Selected scope'
    UNION ALL SELECT 'expenseWorkspace.noRead', 'You currently have no expense or directory read permission in this scope.'
    UNION ALL SELECT 'expenseWorkspace.directory', 'Expense directory'
    UNION ALL SELECT 'expenseWorkspace.refresh', 'Refresh'
    UNION ALL SELECT 'expenseWorkspace.categoryName', 'New category name'
    UNION ALL SELECT 'expenseWorkspace.vendorName', 'New vendor name'
    UNION ALL SELECT 'expenseWorkspace.addCategory', 'Add category'
    UNION ALL SELECT 'expenseWorkspace.addVendor', 'Add vendor'
    UNION ALL SELECT 'expenseWorkspace.categories', 'Categories'
    UNION ALL SELECT 'expenseWorkspace.vendors', 'Vendors'
    UNION ALL SELECT 'expenseWorkspace.noCategories', 'No active categories.'
    UNION ALL SELECT 'expenseWorkspace.noVendors', 'No active vendors.'
    UNION ALL SELECT 'expenseWorkspace.create', 'Record expense'
    UNION ALL SELECT 'expenseWorkspace.amount', 'Amount'
    UNION ALL SELECT 'expenseWorkspace.currency', 'Currency'
    UNION ALL SELECT 'expenseWorkspace.valueDate', 'Value date'
    UNION ALL SELECT 'expenseWorkspace.type', 'Expense type'
    UNION ALL SELECT 'expenseWorkspace.category', 'Category'
    UNION ALL SELECT 'expenseWorkspace.vendor', 'Vendor'
    UNION ALL SELECT 'expenseWorkspace.chooseCategory', 'Choose category'
    UNION ALL SELECT 'expenseWorkspace.chooseVendor', 'Choose vendor'
    UNION ALL SELECT 'expenseWorkspace.employeeId', 'Employee ID (optional)'
    UNION ALL SELECT 'expenseWorkspace.contactId', 'Customer contact ID'
    UNION ALL SELECT 'expenseWorkspace.purpose', 'Purpose'
    UNION ALL SELECT 'expenseWorkspace.receipt', 'Receipt locator'
    UNION ALL SELECT 'expenseWorkspace.record', 'Record expense'
    UNION ALL SELECT 'expenseWorkspace.retryCreate', 'Retry same request'
    UNION ALL SELECT 'expenseWorkspace.list', 'Expense ledger'
    UNION ALL SELECT 'expenseWorkspace.noExpenses', 'No expenses have been recorded.'
    UNION ALL SELECT 'expenseWorkspace.status', 'Status'
    UNION ALL SELECT 'expenseWorkspace.selected', 'Selected expense'
    UNION ALL SELECT 'expenseWorkspace.net', 'Net'
    UNION ALL SELECT 'expenseWorkspace.tax', 'Included tax'
    UNION ALL SELECT 'expenseWorkspace.createdBy', 'Created by'
    UNION ALL SELECT 'expenseWorkspace.markInvoiced', 'Mark invoiced'
    UNION ALL SELECT 'expenseWorkspace.markPaid', 'Mark paid'
    UNION ALL SELECT 'expenseWorkspace.reimburse', 'Record reimbursement'
    UNION ALL SELECT 'expenseWorkspace.cancel', 'Cancel expense'
    UNION ALL SELECT 'expenseWorkspace.reimbursed', 'Reimbursed'
    UNION ALL SELECT 'expenseWorkspace.cancelReason', 'Cancellation reason'
    UNION ALL SELECT 'expenseWorkspace.nameRequired', 'Enter a name.'
    UNION ALL SELECT 'expenseWorkspace.directorySaved', 'Directory entry added.'
    UNION ALL SELECT 'expenseWorkspace.created', 'Expense recorded.'
    UNION ALL SELECT 'expenseWorkspace.invalidResponse', 'The server response does not match this request. Refresh the ledger.'
    UNION ALL SELECT 'expenseWorkspace.createdRecovered', 'The stored result was recovered from the ledger.'
    UNION ALL SELECT 'expenseWorkspace.invalidInput', 'Check the positive amount, three-letter currency, category, and vendor.'
    UNION ALL SELECT 'expenseWorkspace.contactRequired', 'A valid customer contact ID is required for a billable expense.'
    UNION ALL SELECT 'expenseWorkspace.employeeInvalid', 'Employee ID must be empty or a valid GUID.'
    UNION ALL SELECT 'expenseWorkspace.updated', 'Expense status updated.'
    UNION ALL SELECT 'expenseWorkspace.reimbursementSaved', 'Reimbursement recorded.'
    UNION ALL SELECT 'expenseWorkspace.reimbursementRecovered', 'The reimbursement was recovered from the ledger.'
    UNION ALL SELECT 'expenseWorkspace.cancelledInWorkspace', 'Cancelled in expense workspace'
    UNION ALL SELECT 'expenseWorkspace.cancelled', 'Expense cancelled.'
    UNION ALL SELECT 'expenseWorkspace.taxDeductible', 'Tax deductible'
    UNION ALL SELECT 'expenseWorkspace.notTaxDeductible', 'Not tax deductible'
    UNION ALL SELECT 'expenseWorkspace.billable', 'Billable to contact'
    UNION ALL SELECT 'expenseWorkspace.cancelledState', 'Cancelled'
    UNION ALL SELECT 'expenseWorkspace.uninvoiced', 'Uninvoiced'
    UNION ALL SELECT 'expenseWorkspace.invoiced', 'Invoiced'
    UNION ALL SELECT 'expenseWorkspace.paid', 'Paid'
    UNION ALL SELECT 'expenseWorkspace.notBillable', 'Not billable'
) seed
WHERE NOT EXISTS (SELECT 1 FROM SYS_MULTI_LANGUAGE_RESOURCE existing
                   WHERE existing.RESOURCE_KEY = seed.RESOURCE_KEY AND existing.LANGUAGE = 'EnUs');
