-- Organization-scoped expense tags. Historical payloads retain tag IDs after deactivation;
-- new and updated expense values may reference active rows only.
CREATE TABLE ERP_EXPENSE_TAG (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    TAG_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    NAME NVARCHAR(255) COLLATE Latin1_General_100_BIN2 NOT NULL,
    NAME_KEY NVARCHAR(255) COLLATE Latin1_General_100_BIN2 NOT NULL,
    IS_ACTIVE BIT NOT NULL,
    PAYLOAD NVARCHAR(MAX) NOT NULL,
    CONSTRAINT PK_ERP_EXPENSE_TAG PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, TAG_ID),
    CONSTRAINT UQ_ERP_EXPENSE_TAG_NAME UNIQUE (TENANT_ID, ORGANIZATION_ID, NAME_KEY),
    CONSTRAINT CK_ERP_EXPENSE_TAG_ACTIVE CHECK (IS_ACTIVE IN (0,1))
);
CREATE INDEX IX_ERP_EXPENSE_TAG_PAGE ON ERP_EXPENSE_TAG
    (TENANT_ID, ORGANIZATION_ID, IS_ACTIVE, NAME, TAG_ID);
