-- Organization-scoped receipt bytes. Expense cancellation preserves the receipt until explicit deletion.
CREATE TABLE ERP_EXPENSE_RECEIPT (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    RECEIPT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    EXPENSE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    FILE_NAME NVARCHAR(255) NOT NULL,
    CONTENT_TYPE VARCHAR(100) COLLATE Latin1_General_100_BIN2 NOT NULL,
    FILE_SIZE BIGINT NOT NULL,
    SHA256 VARCHAR(64) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CONTENT VARBINARY(MAX) NOT NULL,
    UPLOADED_BY VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    UPLOADED_AT_TICKS BIGINT NOT NULL,
    CONSTRAINT PK_ERP_EXPENSE_RECEIPT PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, RECEIPT_ID),
    CONSTRAINT UQ_ERP_EXPENSE_RECEIPT_EXPENSE UNIQUE (TENANT_ID, ORGANIZATION_ID, EXPENSE_ID),
    CONSTRAINT CK_ERP_EXPENSE_RECEIPT_SIZE CHECK (FILE_SIZE BETWEEN 1 AND 10485760),
    CONSTRAINT CK_ERP_EXPENSE_RECEIPT_HASH CHECK (LEN(SHA256)=64)
);
