-- Durable provider-neutral expense reimbursement execution. Credentials and employee destination details remain host-owned.
CREATE TABLE ERP_EXPENSE_PAYOUT (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    PAYOUT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    OPERATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    EXPENSE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    STATE INT NOT NULL,
    LEASE_EXPIRES_AT_TICKS BIGINT NULL,
    PAYLOAD NVARCHAR(MAX) NOT NULL,
    CONSTRAINT PK_ERP_EXPENSE_PAYOUT PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, PAYOUT_ID),
    CONSTRAINT UQ_ERP_EXPENSE_PAYOUT_OPERATION UNIQUE (TENANT_ID, ORGANIZATION_ID, OPERATION_ID),
    CONSTRAINT FK_ERP_EXPENSE_PAYOUT_EXPENSE FOREIGN KEY (TENANT_ID, ORGANIZATION_ID, EXPENSE_ID)
        REFERENCES ERP_EXPENSE (TENANT_ID, ORGANIZATION_ID, EXPENSE_ID),
    CONSTRAINT CK_ERP_EXPENSE_PAYOUT_STATE CHECK (STATE BETWEEN 0 AND 4),
    CONSTRAINT CK_ERP_EXPENSE_PAYOUT_LEASE CHECK (
        (STATE=1 AND LEASE_EXPIRES_AT_TICKS IS NOT NULL)
        OR (STATE<>1 AND LEASE_EXPIRES_AT_TICKS IS NULL))
);
CREATE INDEX IX_ERP_EXPENSE_PAYOUT_EXPENSE ON ERP_EXPENSE_PAYOUT
    (TENANT_ID, ORGANIZATION_ID, EXPENSE_ID, PAYOUT_ID);
CREATE INDEX IX_ERP_EXPENSE_PAYOUT_DUE ON ERP_EXPENSE_PAYOUT
    (TENANT_ID, ORGANIZATION_ID, STATE, LEASE_EXPIRES_AT_TICKS, PAYOUT_ID);
