-- Idempotency receipts for explicit failed-payout retry and discard decisions.
CREATE TABLE ERP_EXPENSE_PAYOUT_FAILURE_OPERATION (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    OPERATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    PAYOUT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ACTION INT NOT NULL,
    RESULT_VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ACTOR_ID VARCHAR(50) NOT NULL,
    OCCURRED_AT_TICKS BIGINT NOT NULL,
    PAYLOAD NVARCHAR(MAX) NOT NULL,
    CONSTRAINT PK_ERP_EXPENSE_PAYOUT_FAILURE_OPERATION
        PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, OPERATION_ID),
    CONSTRAINT FK_ERP_EXPENSE_PAYOUT_FAILURE_OPERATION_PAYOUT
        FOREIGN KEY (TENANT_ID, ORGANIZATION_ID, PAYOUT_ID)
        REFERENCES ERP_EXPENSE_PAYOUT (TENANT_ID, ORGANIZATION_ID, PAYOUT_ID),
    CONSTRAINT CK_ERP_EXPENSE_PAYOUT_FAILURE_OPERATION_ACTION CHECK (ACTION BETWEEN 0 AND 1)
);
CREATE INDEX IX_ERP_EXPENSE_PAYOUT_FAILURE_OPERATION_PAYOUT
    ON ERP_EXPENSE_PAYOUT_FAILURE_OPERATION
    (TENANT_ID, ORGANIZATION_ID, PAYOUT_ID, OPERATION_ID);
