-- Durable receipt for atomic product/warehouse master imports. Invalid imports never create a receipt.
CREATE TABLE IVT_STOCK_MASTER_IMPORT (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    OPERATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    REQUESTED_BY VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    REQUEST_HASH VARCHAR(64) COLLATE Latin1_General_100_BIN2 NOT NULL,
    PRODUCTS_CREATED INT NOT NULL,
    PRODUCTS_UNCHANGED INT NOT NULL,
    WAREHOUSES_CREATED INT NOT NULL,
    WAREHOUSES_UNCHANGED INT NOT NULL,
    IMPORTED_AT_TICKS BIGINT NOT NULL,
    CONSTRAINT PK_IVT_STOCK_MASTER_IMPORT PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, OPERATION_ID),
    CONSTRAINT FK_IVT_STOCK_MASTER_IMPORT_SCOPE FOREIGN KEY (TENANT_ID, ORGANIZATION_ID)
        REFERENCES IVT_BUSINESS_SCOPE (TENANT_ID, ORGANIZATION_ID),
    CONSTRAINT FK_IVT_STOCK_MASTER_IMPORT_USER FOREIGN KEY (REQUESTED_BY)
        REFERENCES SYS_BUSINESS_IDENTITY (BUSINESS_USER_ID),
    CONSTRAINT CK_IVT_STOCK_MASTER_IMPORT_HASH CHECK (LEN(REQUEST_HASH)=64),
    CONSTRAINT CK_IVT_STOCK_MASTER_IMPORT_COUNTS CHECK (
        PRODUCTS_CREATED>=0 AND PRODUCTS_UNCHANGED>=0
        AND WAREHOUSES_CREATED>=0 AND WAREHOUSES_UNCHANGED>=0
        AND PRODUCTS_CREATED+PRODUCTS_UNCHANGED+WAREHOUSES_CREATED+WAREHOUSES_UNCHANGED BETWEEN 1 AND 1000)
);
