-- Durable, scope-bound product/warehouse CSV exports. Artifact bytes are bounded by the application contract.
CREATE TABLE IVT_STOCK_MASTER_EXPORT (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    EXPORT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    OPERATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    REQUESTED_BY VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    REQUEST_HASH VARCHAR(64) COLLATE Latin1_General_100_BIN2 NOT NULL,
    EXPORT_KIND INT NOT NULL,
    FIELDS_JSON NVARCHAR(1000) NOT NULL,
    INCLUDE_INACTIVE BIT NOT NULL,
    STATE INT NOT NULL,
    LEASE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NULL,
    LEASE_EXPIRES_AT_TICKS BIGINT NULL,
    FILE_NAME NVARCHAR(255) NULL,
    CONTENT_TYPE VARCHAR(100) NULL,
    FILE_SIZE INT NULL,
    CONTENT VARBINARY(MAX) NULL,
    ROW_COUNT INT NULL,
    ERROR_CODE VARCHAR(100) NULL,
    REQUESTED_AT_TICKS BIGINT NOT NULL,
    COMPLETED_AT_TICKS BIGINT NULL,
    CONSTRAINT PK_IVT_STOCK_MASTER_EXPORT PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, EXPORT_ID),
    CONSTRAINT UQ_IVT_STOCK_MASTER_EXPORT_OPERATION UNIQUE (TENANT_ID, ORGANIZATION_ID, OPERATION_ID),
    CONSTRAINT FK_IVT_STOCK_MASTER_EXPORT_SCOPE FOREIGN KEY (TENANT_ID, ORGANIZATION_ID)
        REFERENCES IVT_BUSINESS_SCOPE (TENANT_ID, ORGANIZATION_ID),
    CONSTRAINT FK_IVT_STOCK_MASTER_EXPORT_USER FOREIGN KEY (REQUESTED_BY)
        REFERENCES SYS_BUSINESS_IDENTITY (BUSINESS_USER_ID),
    CONSTRAINT CK_IVT_STOCK_MASTER_EXPORT_HASH CHECK (LEN(REQUEST_HASH)=64),
    CONSTRAINT CK_IVT_STOCK_MASTER_EXPORT_KIND CHECK (EXPORT_KIND IN (0,1)),
    CONSTRAINT CK_IVT_STOCK_MASTER_EXPORT_STATE CHECK (STATE BETWEEN 0 AND 3),
    CONSTRAINT CK_IVT_STOCK_MASTER_EXPORT_LEASE CHECK (
        (STATE=1 AND LEASE_ID IS NOT NULL AND LEASE_EXPIRES_AT_TICKS IS NOT NULL)
        OR (STATE<>1 AND LEASE_ID IS NULL AND LEASE_EXPIRES_AT_TICKS IS NULL)),
    CONSTRAINT CK_IVT_STOCK_MASTER_EXPORT_RESULT CHECK (
        (STATE=2 AND FILE_NAME IS NOT NULL AND CONTENT_TYPE IS NOT NULL AND FILE_SIZE IS NOT NULL
            AND CONTENT IS NOT NULL AND ROW_COUNT IS NOT NULL AND ERROR_CODE IS NULL AND COMPLETED_AT_TICKS IS NOT NULL)
        OR (STATE=3 AND CONTENT IS NULL AND ERROR_CODE IS NOT NULL AND COMPLETED_AT_TICKS IS NOT NULL)
        OR (STATE IN (0,1) AND CONTENT IS NULL AND ERROR_CODE IS NULL AND COMPLETED_AT_TICKS IS NULL))
);
CREATE INDEX IX_IVT_STOCK_MASTER_EXPORT_DUE ON IVT_STOCK_MASTER_EXPORT
    (STATE, LEASE_EXPIRES_AT_TICKS, REQUESTED_AT_TICKS, EXPORT_ID);
