-- Explicitly priced inventory issues are the product occurrences consumed by ERP automatic billing.
-- Product catalogs alone are never billable occurrences; reversed issues remain visible but ineligible.
CREATE TABLE ERP_BILLING_PRODUCT_SOURCE (
    TENANT_ID       VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    MOVEMENT_ID     VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CONTACT_ID      VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    OCCURRED_ON     VARCHAR(10) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CURRENCY        VARCHAR(3) COLLATE Latin1_General_100_BIN2 NOT NULL,
    DESCRIPTION     NVARCHAR(255) NOT NULL,
    UNIT_PRICE      VARCHAR(40) COLLATE Latin1_General_100_BIN2 NOT NULL,
    APPLY_TAX       BIT NOT NULL,
    APPLY_DISCOUNT  BIT NOT NULL,
    CREATED_BY      VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CREATED_AT_TICKS BIGINT NOT NULL,
    CONSTRAINT PK_ERP_BILLING_PRODUCT_SOURCE
        PRIMARY KEY (TENANT_ID, ORGANIZATION_ID, MOVEMENT_ID),
    CONSTRAINT FK_ERP_BILLING_PRODUCT_SOURCE_MOVEMENT
        FOREIGN KEY (TENANT_ID, ORGANIZATION_ID, MOVEMENT_ID)
        REFERENCES IVT_STOCK_MOVEMENT (TENANT_ID, ORGANIZATION_ID, MOVEMENT_ID),
    CONSTRAINT FK_ERP_BILLING_PRODUCT_SOURCE_CONTACT
        FOREIGN KEY (TENANT_ID, ORGANIZATION_ID, CONTACT_ID)
        REFERENCES ERP_BILLING_CONTACT (TENANT_ID, ORGANIZATION_ID, CONTACT_ID),
    CONSTRAINT FK_ERP_BILLING_PRODUCT_SOURCE_USER FOREIGN KEY (CREATED_BY)
        REFERENCES SYS_BUSINESS_IDENTITY (BUSINESS_USER_ID),
    CONSTRAINT CK_ERP_BILLING_PRODUCT_SOURCE_CURRENCY CHECK (LEN(CURRENCY)=3),
    CONSTRAINT CK_ERP_BILLING_PRODUCT_SOURCE_FLAGS
        CHECK (APPLY_TAX IN (0,1) AND APPLY_DISCOUNT IN (0,1)),
    CONSTRAINT CK_ERP_BILLING_PRODUCT_SOURCE_PRICE
        CHECK (UNIT_PRICE NOT LIKE '-%' AND LEN(UNIT_PRICE)>0)
);

CREATE INDEX IX_ERP_BILLING_PRODUCT_SOURCE_CANDIDATE
    ON ERP_BILLING_PRODUCT_SOURCE
       (TENANT_ID, ORGANIZATION_ID, CONTACT_ID, CURRENCY, OCCURRED_ON, MOVEMENT_ID);
