CREATE TABLE HR_TASK (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    TASK_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    NAME NVARCHAR(255) NOT NULL,
    PROJECT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NULL,
    IS_ACTIVE BIT NOT NULL,
    CREATED_BY VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CONSTRAINT PK_HR_TASK PRIMARY KEY (TENANT_ID,ORGANIZATION_ID,TASK_ID),
    CONSTRAINT FK_HR_TASK_PROJECT FOREIGN KEY (TENANT_ID,ORGANIZATION_ID,PROJECT_ID)
        REFERENCES CRM_PROJECT (TENANT_ID,ORGANIZATION_ID,PROJECT_ID),
    CONSTRAINT FK_HR_TASK_USER FOREIGN KEY (CREATED_BY)
        REFERENCES SYS_BUSINESS_IDENTITY (BUSINESS_USER_ID),
    CONSTRAINT CK_HR_TASK_ACTIVE CHECK (IS_ACTIVE IN (0,1))
);

CREATE TABLE HR_TIMESHEET (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    TIMESHEET_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    EMPLOYEE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    START_TICKS BIGINT NOT NULL,
    END_TICKS BIGINT NOT NULL,
    STATE INT NOT NULL,
    PAYLOAD NVARCHAR(MAX) NOT NULL,
    CONSTRAINT PK_HR_TIMESHEET PRIMARY KEY (TENANT_ID,ORGANIZATION_ID,TIMESHEET_ID),
    CONSTRAINT FK_HR_TIMESHEET_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES SYS_BUSINESS_IDENTITY (BUSINESS_USER_ID),
    CONSTRAINT CK_HR_TIMESHEET_RANGE CHECK (END_TICKS>START_TICKS),
    CONSTRAINT CK_HR_TIMESHEET_STATE CHECK (STATE BETWEEN 0 AND 2)
);

CREATE TABLE HR_TIME_ENTRY (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    TIME_ENTRY_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    EMPLOYEE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    START_TICKS BIGINT NOT NULL,
    END_TICKS BIGINT NULL,
    PROJECT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NULL,
    TASK_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NULL,
    TIMESHEET_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NULL,
    PAYLOAD NVARCHAR(MAX) NOT NULL,
    CONSTRAINT PK_HR_TIME_ENTRY PRIMARY KEY (TENANT_ID,ORGANIZATION_ID,TIME_ENTRY_ID),
    CONSTRAINT FK_HR_TIME_ENTRY_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES SYS_BUSINESS_IDENTITY (BUSINESS_USER_ID),
    CONSTRAINT FK_HR_TIME_ENTRY_PROJECT FOREIGN KEY (TENANT_ID,ORGANIZATION_ID,PROJECT_ID)
        REFERENCES CRM_PROJECT (TENANT_ID,ORGANIZATION_ID,PROJECT_ID),
    CONSTRAINT FK_HR_TIME_ENTRY_TASK FOREIGN KEY (TENANT_ID,ORGANIZATION_ID,TASK_ID)
        REFERENCES HR_TASK (TENANT_ID,ORGANIZATION_ID,TASK_ID),
    CONSTRAINT FK_HR_TIME_ENTRY_TIMESHEET FOREIGN KEY (TENANT_ID,ORGANIZATION_ID,TIMESHEET_ID)
        REFERENCES HR_TIMESHEET (TENANT_ID,ORGANIZATION_ID,TIMESHEET_ID),
    CONSTRAINT CK_HR_TIME_ENTRY_RANGE CHECK (END_TICKS IS NULL OR END_TICKS>START_TICKS)
);
CREATE UNIQUE INDEX UQ_HR_TIME_ENTRY_RUNNING ON HR_TIME_ENTRY
    (TENANT_ID,ORGANIZATION_ID,EMPLOYEE_ID) WHERE END_TICKS IS NULL;
CREATE INDEX IX_HR_TIME_ENTRY_PERIOD ON HR_TIME_ENTRY
    (TENANT_ID,ORGANIZATION_ID,EMPLOYEE_ID,START_TICKS,END_TICKS);
CREATE INDEX IX_HR_TIMESHEET_PERIOD ON HR_TIMESHEET
    (TENANT_ID,ORGANIZATION_ID,EMPLOYEE_ID,START_TICKS,END_TICKS);

CREATE TABLE HR_TIME_AUDIT (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    AUDIT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    USER_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    RESOURCE_TYPE NVARCHAR(64) NOT NULL,
    RESOURCE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    OPERATION NVARCHAR(64) NOT NULL,
    PREVIOUS_VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NULL,
    VERSION VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    AT_TICKS BIGINT NOT NULL,
    CONSTRAINT PK_HR_TIME_AUDIT PRIMARY KEY (TENANT_ID,ORGANIZATION_ID,AUDIT_ID),
    CONSTRAINT FK_HR_TIME_AUDIT_USER FOREIGN KEY (USER_ID)
        REFERENCES SYS_BUSINESS_IDENTITY (BUSINESS_USER_ID)
);

CREATE TABLE ERP_BILLING_TIME_SOURCE (
    TENANT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    ORGANIZATION_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    TIME_ENTRY_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CONTACT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    EMPLOYEE_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    PROJECT_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NULL,
    TASK_ID VARCHAR(36) COLLATE Latin1_General_100_BIN2 NULL,
    OCCURRED_ON CHAR(10) COLLATE Latin1_General_100_BIN2 NOT NULL,
    DURATION_TICKS BIGINT NOT NULL,
    CURRENCY CHAR(3) COLLATE Latin1_General_100_BIN2 NOT NULL,
    DESCRIPTION NVARCHAR(255) NOT NULL,
    HOURLY_RATE VARCHAR(64) COLLATE Latin1_General_100_BIN2 NOT NULL,
    APPLY_TAX BIT NOT NULL,
    APPLY_DISCOUNT BIT NOT NULL,
    CREATED_BY VARCHAR(36) COLLATE Latin1_General_100_BIN2 NOT NULL,
    CREATED_AT_TICKS BIGINT NOT NULL,
    CONSTRAINT PK_ERP_BILLING_TIME_SOURCE PRIMARY KEY (TENANT_ID,ORGANIZATION_ID,TIME_ENTRY_ID),
    CONSTRAINT FK_ERP_BILLING_TIME_SOURCE_ENTRY FOREIGN KEY (TENANT_ID,ORGANIZATION_ID,TIME_ENTRY_ID)
        REFERENCES HR_TIME_ENTRY (TENANT_ID,ORGANIZATION_ID,TIME_ENTRY_ID),
    CONSTRAINT FK_ERP_BILLING_TIME_SOURCE_CONTACT FOREIGN KEY (TENANT_ID,ORGANIZATION_ID,CONTACT_ID)
        REFERENCES ERP_BILLING_CONTACT (TENANT_ID,ORGANIZATION_ID,CONTACT_ID),
    CONSTRAINT FK_ERP_BILLING_TIME_SOURCE_USER FOREIGN KEY (CREATED_BY)
        REFERENCES SYS_BUSINESS_IDENTITY (BUSINESS_USER_ID),
    CONSTRAINT CK_ERP_BILLING_TIME_SOURCE_DURATION CHECK (DURATION_TICKS>0),
    CONSTRAINT CK_ERP_BILLING_TIME_SOURCE_FLAGS CHECK (APPLY_TAX IN (0,1) AND APPLY_DISCOUNT IN (0,1))
);
CREATE INDEX IX_ERP_BILLING_TIME_SOURCE_CANDIDATE ON ERP_BILLING_TIME_SOURCE
    (TENANT_ID,ORGANIZATION_ID,CONTACT_ID,CURRENCY,OCCURRED_ON,TIME_ENTRY_ID);
