-- Owner: SYS. 문서군 무관 범용 승인 — COM_APPROVAL은 (DOC_KIND, DOC_ID)별 현재 요청 1행,
-- COM_APPROVAL_HISTORY는 append-only 전이 이력. RMS_RECIPE_APPROVAL_HISTORY 패턴을 공통 스키마로 승격한다.

CREATE TABLE COM_APPROVAL (
    APPROVAL_ID      NVARCHAR(50)   NOT NULL,
    DOC_KIND         NVARCHAR(50)   NOT NULL,
    DOC_ID           NVARCHAR(100)  NOT NULL,
    TITLE            NVARCHAR(300)  NULL,
    STATUS           NVARCHAR(20)   NOT NULL DEFAULT 'Pending',
    REQUESTED_BY     NVARCHAR(50)   NOT NULL,
    REQUESTED_AT     DATETIME2      NOT NULL,
    DECIDED_BY       NVARCHAR(50)   NULL,
    DECIDED_AT       DATETIME2      NULL,
    DECISION_COMMENT NVARCHAR(500)  NULL,
    IDEMPOTENCY_KEY  NVARCHAR(100)  NOT NULL,
    REQUEST_HASH     NVARCHAR(128)  NOT NULL,
    CREATED_BY       NVARCHAR(50)   NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT       DATETIME2      NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY       NVARCHAR(50)   NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT       DATETIME2      NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_COM_APPROVAL PRIMARY KEY (APPROVAL_ID),
    CONSTRAINT UQ_COM_APPROVAL_DOC UNIQUE (DOC_KIND, DOC_ID),
    CONSTRAINT CK_COM_APPROVAL_STATUS
        CHECK (STATUS IN ('Pending', 'Approved', 'Rejected', 'Cancelled'))
);
CREATE UNIQUE INDEX UX_COM_APPROVAL_IDEMPOTENCY ON COM_APPROVAL (IDEMPOTENCY_KEY);
CREATE INDEX IX_COM_APPROVAL_STATUS ON COM_APPROVAL (STATUS, DOC_KIND, REQUESTED_AT);

CREATE TABLE COM_APPROVAL_HISTORY (
    HISTORY_ID       NVARCHAR(50)   NOT NULL,
    IDEMPOTENCY_KEY  NVARCHAR(100)  NOT NULL,
    REQUEST_HASH     NVARCHAR(128)  NOT NULL,
    APPROVAL_ID      NVARCHAR(50)   NOT NULL,
    DOC_KIND         NVARCHAR(50)   NOT NULL,
    DOC_ID           NVARCHAR(100)  NOT NULL,
    FROM_STATUS      NVARCHAR(20)   NOT NULL,
    TO_STATUS        NVARCHAR(20)   NOT NULL,
    CHANGED_BY       NVARCHAR(50)   NOT NULL,
    REASON           NVARCHAR(500)  NULL,
    CHANGED_AT       DATETIME2      NOT NULL,
    CONSTRAINT PK_COM_APPROVAL_HISTORY PRIMARY KEY (HISTORY_ID),
    CONSTRAINT FK_COM_APPROVAL_HISTORY_APPROVAL
        FOREIGN KEY (APPROVAL_ID) REFERENCES COM_APPROVAL (APPROVAL_ID),
    CONSTRAINT CK_COM_APPROVAL_HISTORY_CHANGE CHECK (FROM_STATUS <> TO_STATUS)
);
CREATE UNIQUE INDEX UX_COM_APPROVAL_HISTORY_IDEMPOTENCY
    ON COM_APPROVAL_HISTORY (IDEMPOTENCY_KEY);
CREATE INDEX IX_COM_APPROVAL_HISTORY_DOC
    ON COM_APPROVAL_HISTORY (DOC_KIND, DOC_ID, CHANGED_AT, HISTORY_ID);

-- SQLITE-OMIT-BEGIN
EXEC(N'CREATE TRIGGER TR_COM_APPROVAL_HISTORY_APPEND_ONLY
ON COM_APPROVAL_HISTORY
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    THROW 51219, ''COM_APPROVAL_HISTORY is append-only'', 1;
END');
-- SQLITE-OMIT-END
