-- A sales order requests at most one SHP delivery order. The nullable link keeps existing orders intact.
ALTER TABLE SLS_SALES_ORDER ADD DELIVERY_ORDER_ID NVARCHAR(50) NULL;

CREATE UNIQUE INDEX UX_SLS_SALES_ORDER_DELIVERY_ORDER
    ON SLS_SALES_ORDER (DELIVERY_ORDER_ID) WHERE DELIVERY_ORDER_ID IS NOT NULL;
