-- Purchase-order lines become the source for scheduled material receipts.
-- Existing MRP-created single-product headers are materialized once on upgrade.
CREATE TABLE PRC_PURCHASE_ITEM (
    PURCHASE_ORDER_ID NVARCHAR(50) NOT NULL,
    PRODUCT_ID        NVARCHAR(50) NOT NULL,
    ORDER_QTY         DECIMAL(18,4) NOT NULL,
    INCOMING_QTY      DECIMAL(18,4) NOT NULL DEFAULT 0,
    CREATED_BY        NVARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
    CREATED_AT        DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UPDATED_BY        NVARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
    UPDATED_AT        DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_PRC_PURCHASE_ITEM PRIMARY KEY (PURCHASE_ORDER_ID, PRODUCT_ID),
    CONSTRAINT FK_PRC_PURCHASE_ITEM_ORDER FOREIGN KEY (PURCHASE_ORDER_ID)
        REFERENCES PRC_PURCHASE_ORDER (PURCHASE_ORDER_ID) ON DELETE CASCADE,
    CONSTRAINT CK_PRC_PURCHASE_ITEM_QTY CHECK (ORDER_QTY > 0 AND INCOMING_QTY >= 0)
);

CREATE INDEX IX_PRC_PURCHASE_ITEM_PRODUCT ON PRC_PURCHASE_ITEM (PRODUCT_ID);

INSERT INTO PRC_PURCHASE_ITEM
    (PURCHASE_ORDER_ID, PRODUCT_ID, ORDER_QTY, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT)
SELECT PURCHASE_ORDER_ID, PRODUCT_ID, ORDER_QTY, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT
  FROM PRC_PURCHASE_ORDER
 WHERE PRODUCT_ID IS NOT NULL AND LTRIM(RTRIM(PRODUCT_ID)) <> '' AND ORDER_QTY > 0;
