-- IVT owns the durable split decision, its two LOT ledger entries, and the parent-to-child
-- genealogy. A retry reads this row instead of applying the stock movement again.
CREATE TABLE IVT_MATERIAL_LOT_SPLIT (
    SPLIT_ID              NVARCHAR(50)  NOT NULL,
    IDEMPOTENCY_KEY       NVARCHAR(100) NOT NULL,
    SOURCE_SYSTEM         NVARCHAR(50)  NOT NULL,
    SOURCE_EVENT_ID       NVARCHAR(100) NOT NULL,
    REQUEST_HASH          NVARCHAR(64)  NOT NULL,
    PARENT_LOT_ID         NVARCHAR(50)  NOT NULL,
    CHILD_LOT_ID          NVARCHAR(50)  NOT NULL,
    CHILD_LOT_NO          NVARCHAR(100) NOT NULL,
    QUANTITY              DECIMAL(22,6) NOT NULL,
    PARENT_BALANCE_BEFORE DECIMAL(22,6) NOT NULL,
    PARENT_BALANCE_AFTER  DECIMAL(22,6) NOT NULL,
    PARENT_VERSION        INT           NOT NULL,
    PARENT_STATUS         NVARCHAR(20)  NOT NULL,
    PARENT_TX_ID          NVARCHAR(50)  NOT NULL,
    CHILD_TX_ID           NVARCHAR(50)  NOT NULL,
    OCCURRED_AT           DATETIME2     NOT NULL,
    ACTOR_ID              NVARCHAR(50)  NOT NULL,
    CREATED_AT            DATETIME2     NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_IVT_MATERIAL_LOT_SPLIT PRIMARY KEY (SPLIT_ID),
    CONSTRAINT UX_IVT_SPLIT_KEY UNIQUE (IDEMPOTENCY_KEY),
    CONSTRAINT UX_IVT_SPLIT_SOURCE UNIQUE (SOURCE_SYSTEM, SOURCE_EVENT_ID),
    CONSTRAINT UX_IVT_SPLIT_CHILD UNIQUE (CHILD_LOT_ID),
    CONSTRAINT CK_IVT_SPLIT_QTY CHECK (QUANTITY > 0 AND PARENT_BALANCE_BEFORE = PARENT_BALANCE_AFTER + QUANTITY),
    CONSTRAINT FK_IVT_SPLIT_PARENT FOREIGN KEY (PARENT_LOT_ID) REFERENCES IVT_MATERIAL_LOT (LOT_ID),
    CONSTRAINT FK_IVT_SPLIT_CHILD FOREIGN KEY (CHILD_LOT_ID) REFERENCES IVT_MATERIAL_LOT (LOT_ID),
    CONSTRAINT FK_IVT_SPLIT_PARENT_TX FOREIGN KEY (PARENT_TX_ID) REFERENCES IVT_MATERIAL_TX (TX_ID),
    CONSTRAINT FK_IVT_SPLIT_CHILD_TX FOREIGN KEY (CHILD_TX_ID) REFERENCES IVT_MATERIAL_TX (TX_ID)
);

CREATE INDEX IX_IVT_SPLIT_PARENT ON IVT_MATERIAL_LOT_SPLIT (PARENT_LOT_ID, OCCURRED_AT);
